import type { WordPack } from '../game/types';

export const asiaPack: WordPack = {
  id: 'asia',
  name: 'Asia',
  entries: [
    // ── Original 40 ──
    { word: 'Naruto', category: 'Asia', hints: ['Ninja', 'Hokage', 'Ramen Lover', 'Sasuke', 'Rasengan'] },
    { word: 'One Piece', category: 'Asia', hints: ['Luffy', 'Pirate King', 'Straw Hat', 'Devil Fruit', 'Grand Line'] },
    { word: 'Attack on Titan', category: 'Asia', hints: ['Eren', 'Titan Shifter', 'Walls', 'Survey Corps', 'Mikasa'] },
    { word: 'Death Note', category: 'Asia', hints: ['Light Yagami', 'Ryuk', 'Shinigami', 'L Detective', 'Apple'] },
    { word: 'Dragon Ball Z', category: 'Asia', hints: ['Goku', 'Kamehameha', 'Super Saiyan', 'Frieza', 'Vegeta'] },
    { word: 'Studio Ghibli', category: 'Asia', hints: ['Miyazaki', 'Totoro', 'Animation', 'Japan', 'Fantasy'] },
    { word: 'Ramen', category: 'Asia', hints: ['Noodle Soup', 'Tonkotsu', 'Chopsticks', 'Broth', 'Naruto Fish Cake'] },
    { word: 'Sushi', category: 'Asia', hints: ['Raw Fish', 'Rice Roll', 'Wasabi', 'Soy Sauce', 'Nigiri'] },
    { word: 'Boba Tea', category: 'Asia', hints: ['Tapioca Pearls', 'Milk Tea', 'Taiwan', 'Straw', 'Chewy'] },
    { word: 'Kimchi', category: 'Asia', hints: ['Fermented', 'Cabbage', 'Korean Side', 'Spicy', 'Red Pepper'] },
    { word: 'K-Drama', category: 'Asia', hints: ['Korean Series', 'Romance', 'Subtitles', 'Netflix', 'Oppa'] },
    { word: 'Squid Game', category: 'Asia', hints: ['Red Light', 'Dalgona', 'Player 456', 'Netflix Hit', 'Masked Guards'] },
    { word: 'BTS', category: 'Asia', hints: ['Bangtan', 'Army Fandom', 'Dynamite', 'Seoul Group', 'Seven Members'] },
    { word: 'BLACKPINK', category: 'Asia', hints: ['Girl Group', 'Jennie', 'Pink Venom', 'YG Ent', 'Four Members'] },
    { word: 'K-Pop', category: 'Asia', hints: ['Korean Music', 'Idol Groups', 'Fan Chants', 'Choreography', 'Debut'] },
    { word: 'Manga', category: 'Asia', hints: ['Japanese Comic', 'Black White', 'Right to Left', 'Shonen', 'Panels'] },
    { word: 'Cosplay', category: 'Asia', hints: ['Costume Play', 'Convention', 'Character Dress', 'Wig', 'Props'] },
    { word: 'Cherry Blossom', category: 'Asia', hints: ['Sakura', 'Spring Japan', 'Pink Petals', 'Hanami', 'April'] },
    { word: 'Mount Fuji', category: 'Asia', hints: ['Japan Peak', 'Snow Cap', 'Sacred', 'Volcano', 'Iconic View'] },
    { word: 'Great Wall', category: 'Asia', hints: ['China', 'Ancient Defense', 'Ming Dynasty', 'Longest Structure', 'Beijing'] },
    { word: 'Thai Street Food', category: 'Asia', hints: ['Bangkok Stalls', 'Hawker', 'Spicy Cheap', 'Night Vendors', 'Wok Flame'] },
    { word: 'Pad Thai', category: 'Asia', hints: ['Noodle Stir Fry', 'Tamarind', 'Peanuts', 'Lime Squeeze', 'Bangkok'] },
    { word: 'Dim Sum', category: 'Asia', hints: ['Steamed Baskets', 'Dumplings', 'Cantonese', 'Yum Cha', 'Bamboo Tray'] },
    { word: 'Matcha', category: 'Asia', hints: ['Green Powder', 'Whisk', 'Japanese Tea', 'Latte', 'Bitter Sweet'] },
    { word: 'Tofu Stew', category: 'Asia', hints: ['Soybean Curd', 'Sundubu', 'Korean Pot', 'Soft Silken', 'Spicy Broth'] },
    { word: 'Anime Convention', category: 'Asia', hints: ['Cosplayers', 'Merch Booth', 'Panel Room', 'Badge', 'Fan Meet'] },
    { word: 'Bullet Train', category: 'Asia', hints: ['Shinkansen', 'High Speed', 'Tokyo Osaka', 'Punctual', 'Rail'] },
    { word: 'Night Market', category: 'Asia', hints: ['Street Stalls', 'Evening Bazaar', 'Taipei', 'Cheap Eats', 'Neon Lights'] },
    { word: 'Bali', category: 'Asia', hints: ['Indonesia', 'Temple Island', 'Rice Paddy', 'Surfing', 'Ubud'] },
    { word: 'Ha Long Bay', category: 'Asia', hints: ['Vietnam', 'Limestone Karsts', 'Emerald Water', 'Boat Cruise', 'UNESCO'] },
    { word: 'Angkor Wat', category: 'Asia', hints: ['Cambodia', 'Temple Complex', 'Khmer', 'Siem Reap', 'Sunrise'] },
    { word: 'Pho', category: 'Asia', hints: ['Vietnamese Soup', 'Beef Broth', 'Basil Sprouts', 'Rice Noodle', 'Hanoi'] },
    { word: 'Bibimbap', category: 'Asia', hints: ['Mixed Rice', 'Korean Bowl', 'Gochujang', 'Egg Top', 'Stone Pot'] },
    { word: 'Samurai', category: 'Asia', hints: ['Japanese Warrior', 'Sword', 'Bushido', 'Honor Code', 'Feudal'] },
    { word: 'Hanbok', category: 'Asia', hints: ['Korean Dress', 'Traditional', 'Colorful Silk', 'Lunar New Year', 'Palace'] },
    { word: 'Origami', category: 'Asia', hints: ['Paper Folding', 'Crane', 'Japanese Art', 'No Scissors', 'Square Sheet'] },
    { word: 'Jujutsu Kaisen', category: 'Asia', hints: ['Cursed Energy', 'Gojo', 'Yuji', 'Sorcerer', 'Domain Expansion'] },
    { word: 'Demon Slayer', category: 'Asia', hints: ['Tanjiro', 'Breathing Style', 'Nezuko', 'Hashira', 'Muzan'] },
    { word: 'Parasite', category: 'Asia', hints: ['Bong Joon-ho', 'Oscar Winner', 'Rich Poor', 'Basement', 'Korean Film'] },
    { word: 'Spirited Away', category: 'Asia', hints: ['Chihiro', 'No Face', 'Bathhouse', 'Ghibli', 'Oscar Anime'] },

    // ── Anime & Manga ──
    { word: 'My Hero Academia', category: 'Asia', hints: ['Deku', 'All Might', 'Quirk', 'UA School', 'One For All'] },
    { word: 'Fullmetal Alchemist', category: 'Asia', hints: ['Edward Elric', 'Equivalent Exchange', 'Automail', 'Philosopher Stone', 'Alphonse'] },
    { word: 'Sailor Moon', category: 'Asia', hints: ['Usagi', 'Moon Tiara', 'Tuxedo Mask', 'Crystal', 'Magical Girl'] },
    { word: 'Pokemon', category: 'Asia', hints: ['Pikachu', 'Pokeball', 'Ash Ketchum', 'Gym Badge', 'Gotta Catch'] },
    { word: 'Doraemon', category: 'Asia', hints: ['Robot Cat', 'Nobita', 'Pocket Gadget', 'Time Machine', 'Anywhere Door'] },
    { word: 'Shin Chan', category: 'Asia', hints: ['Naughty Boy', 'Butt Dance', 'Kasukabe', 'Himawari', 'Action Mask'] },
    { word: 'Hunter x Hunter', category: 'Asia', hints: ['Gon', 'Killua', 'Nen', 'Hunter Exam', 'Phantom Troupe'] },
    { word: 'Bleach', category: 'Asia', hints: ['Ichigo', 'Soul Reaper', 'Zanpakuto', 'Bankai', 'Hollow'] },
    { word: 'Spy x Family', category: 'Asia', hints: ['Anya', 'Loid Forger', 'Telepathy', 'Spy Mission', 'Yor'] },
    { word: 'Chainsaw Man', category: 'Asia', hints: ['Denji', 'Pochita', 'Devil Hunter', 'Makima', 'Power'] },
    { word: 'Tokyo Ghoul', category: 'Asia', hints: ['Kaneki', 'Ghoul Mask', 'Kagune', 'Red Eye', 'Coffee Shop'] },
    { word: 'Cowboy Bebop', category: 'Asia', hints: ['Spike', 'Space Bounty', 'Jazz', 'Ein Corgi', 'See You'] },
    { word: 'Neon Genesis', category: 'Asia', hints: ['Evangelion', 'Shinji', 'Mecha', 'Angel Attack', 'NERV'] },
    { word: 'Akira', category: 'Asia', hints: ['Neo Tokyo', 'Bike Chase', 'Tetsuo', 'Cyberpunk', 'Explosion'] },
    { word: 'Ghost in the Shell', category: 'Asia', hints: ['Major', 'Cyborg', 'Cyberbrain', 'Section Nine', 'Hacking'] },
    { word: 'Slam Dunk', category: 'Asia', hints: ['Basketball', 'Sakuragi', 'Shohoku', 'Rebound', 'Rukawa'] },
    { word: 'Haikyuu', category: 'Asia', hints: ['Volleyball', 'Hinata', 'Karasuno', 'Quick Attack', 'Kageyama'] },
    { word: 'Gintama', category: 'Asia', hints: ['Gintoki', 'Odd Jobs', 'Silver Hair', 'Edo Parody', 'Jump Manga'] },
    { word: 'One Punch Man', category: 'Asia', hints: ['Saitama', 'Bald Hero', 'Single Hit', 'Genos', 'Hero Rank'] },
    { word: 'Mob Psycho 100', category: 'Asia', hints: ['Psychic Power', 'Mob', 'Reigen', 'Exorcism', 'Explosion'] },
    { word: 'Vinland Saga', category: 'Asia', hints: ['Viking', 'Thorfinn', 'Revenge', 'Askeladd', 'Norse'] },
    { word: 'Totoro', category: 'Asia', hints: ['Forest Spirit', 'Catbus', 'Umbrella', 'Two Sisters', 'Ghibli'] },
    { word: 'Princess Mononoke', category: 'Asia', hints: ['San', 'Forest Gods', 'Ashitaka', 'Wolf Girl', 'Iron Town'] },
    { word: 'Howl Moving Castle', category: 'Asia', hints: ['Walking Castle', 'Sophie', 'Fire Demon', 'Calcifer', 'Wizard'] },
    { word: 'Ponyo', category: 'Asia', hints: ['Goldfish Girl', 'Ocean', 'Sosuke', 'Ghibli', 'Ham Ramen'] },
    { word: 'Violet Evergarden', category: 'Asia', hints: ['Letter Writer', 'Prosthetic Arms', 'War Veteran', 'Auto Memory', 'Beautiful Art'] },
    { word: 'Your Name', category: 'Asia', hints: ['Body Swap', 'Comet', 'Taki Mitsuha', 'Makoto Shinkai', 'Red String'] },
    { word: 'Weathering With You', category: 'Asia', hints: ['Rain Girl', 'Sunshine', 'Shinkai', 'Tokyo Rain', 'Hina'] },
    { word: 'Dragon Ball Super', category: 'Asia', hints: ['Goku', 'Ultra Instinct', 'Beerus', 'Tournament Power', 'Whis'] },
    { word: 'Yu-Gi-Oh', category: 'Asia', hints: ['Card Game', 'Duel Disk', 'Millennium Puzzle', 'Blue Eyes', 'Trap Card'] },
    { word: 'Beyblade', category: 'Asia', hints: ['Spinning Top', 'Let It Rip', 'Stadium', 'Bit Beast', 'Launcher'] },
    { word: 'Digimon', category: 'Asia', hints: ['Digital Monster', 'Agumon', 'Digivice', 'Evolve', 'Digital World'] },
    { word: 'Astro Boy', category: 'Asia', hints: ['Robot Boy', 'Osamu Tezuka', 'Flying', 'Classic Manga', 'Atom'] },
    { word: 'Speed Racer', category: 'Asia', hints: ['Mach Five', 'Racing', 'Helmet', 'Trixie', 'Go Go Go'] },
    { word: 'Kimetsu no Yaiba', category: 'Asia', hints: ['Tanjiro', 'Breathing Style', 'Demon', 'Nezuko', 'Hashira'] },
    { word: 'Solo Leveling', category: 'Asia', hints: ['Sung Jinwoo', 'Shadow Army', 'S Rank', 'Hunter Gate', 'Korean Manhwa'] },
    { word: 'Black Clover', category: 'Asia', hints: ['Asta', 'No Magic', 'Grimoire', 'Wizard King', 'Black Bulls'] },
    { word: 'Oshi no Ko', category: 'Asia', hints: ['Idol Mother', 'Aqua', 'Ruby', 'Reincarnation', 'Entertainment'] },

    // ── K-Pop & K-Drama ──
    { word: 'Crash Landing on You', category: 'Asia', hints: ['North South', 'Love Story', 'Paraglider', 'Captain Ri', 'Border Cross'] },
    { word: 'Goblin', category: 'Asia', hints: ['Grim Reaper', 'Immortal', 'Buckwheat Tea', 'Bride', 'Gong Yoo'] },
    { word: 'Itaewon Class', category: 'Asia', hints: ['Bar Owner', 'Revenge', 'Park Saeroyi', 'Seoul District', 'Webtoon'] },
    { word: 'Kingdom', category: 'Asia', hints: ['Joseon Zombie', 'Crown Prince', 'Plague', 'Netflix Korea', 'Period Horror'] },
    { word: 'All of Us Are Dead', category: 'Asia', hints: ['School Zombie', 'High School', 'Rooftop', 'Netflix', 'Survival'] },
    { word: 'Vincenzo', category: 'Asia', hints: ['Italian Mafia', 'Korean Lawyer', 'Song Joong-ki', 'Gold Heist', 'Dark Comedy'] },
    { word: 'Reply 1988', category: 'Asia', hints: ['Nostalgia', 'Ssangmun-dong', 'Five Families', 'Retro Seoul', 'Deok-sun'] },
    { word: 'Extraordinary You', category: 'Asia', hints: ['Manga World', 'Side Character', 'Self Aware', 'School Story', 'Fate'] },
    { word: 'True Beauty', category: 'Asia', hints: ['Makeup', 'Webtoon', 'School Romance', 'Secret Identity', 'Love Triangle'] },
    { word: 'Hospital Playlist', category: 'Asia', hints: ['Doctor Friends', 'Band Music', 'Friendship', 'Five Doctors', 'Warm Drama'] },
    { word: 'The Glory', category: 'Asia', hints: ['Revenge Drama', 'Bullying', 'Song Hye-kyo', 'Netflix', 'Dark'] },
    { word: 'Hometown Cha Cha', category: 'Asia', hints: ['Seaside Village', 'Dentist', 'Mr Hong', 'Romance', 'Small Town'] },
    { word: 'EXO', category: 'Asia', hints: ['Boy Group', 'Love Shot', 'SM Ent', 'Nine Members', 'Growl'] },
    { word: 'TWICE', category: 'Asia', hints: ['Girl Group', 'TT Dance', 'JYP Ent', 'Nine Members', 'Cheer Up'] },
    { word: 'Stray Kids', category: 'Asia', hints: ['Boy Group', 'God Menu', 'JYP', 'Self Produced', 'Eight Members'] },
    { word: 'Red Velvet', category: 'Asia', hints: ['Girl Group', 'SM Ent', 'Psycho', 'Five Members', 'Dual Concept'] },
    { word: 'NewJeans', category: 'Asia', hints: ['Girl Group', 'Hype Boy', 'Y2K Style', 'ADOR', 'Five Members'] },
    { word: 'SEVENTEEN', category: 'Asia', hints: ['Boy Group', 'Performance Unit', 'Pledis', 'Self Choreograph', 'Thirteen Members'] },
    { word: 'GOT7', category: 'Asia', hints: ['Boy Group', 'JYP', 'Just Right', 'Seven Members', 'Jackson Wang'] },
    { word: 'ITZY', category: 'Asia', hints: ['Girl Group', 'Dalla Dalla', 'JYP', 'Teen Crush', 'Five Members'] },
    { word: 'ENHYPEN', category: 'Asia', hints: ['Boy Group', 'I-Land', 'Bite Me', 'HYBE', 'Seven Members'] },
    { word: 'TXT', category: 'Asia', hints: ['Boy Group', 'HYBE', 'Blue Hour', 'Five Members', 'Tomorrow Together'] },
    { word: 'aespa', category: 'Asia', hints: ['Girl Group', 'SM Ent', 'Next Level', 'AI Avatar', 'Four Members'] },
    { word: 'IVE', category: 'Asia', hints: ['Girl Group', 'Eleven', 'Starship', 'Six Members', 'After Like'] },
    { word: 'LE SSERAFIM', category: 'Asia', hints: ['Girl Group', 'HYBE', 'Fearless', 'Five Members', 'Kazuha'] },
    { word: 'BigBang', category: 'Asia', hints: ['Boy Group', 'YG Ent', 'Fantastic Baby', 'GD', 'Legends'] },
    { word: 'PSY', category: 'Asia', hints: ['Korean Singer', 'Horse Dance', 'Gentleman', 'YG Ent', 'Viral Hit'] },
    { word: 'Gangnam Style', category: 'Asia', hints: ['Horse Dance', 'Viral Video', 'Billion Views', 'PSY Hit', 'Seoul District'] },
    { word: 'Hallyu Wave', category: 'Asia', hints: ['Korean Culture', 'Global Spread', 'Soft Power', 'Pop Export', 'Fan Culture'] },
    { word: 'Idol Trainee', category: 'Asia', hints: ['Debut Dream', 'Practice Room', 'Audition', 'Survival Show', 'Agency'] },
    { word: 'Mukbang', category: 'Asia', hints: ['Eating Show', 'Live Stream', 'Korean Trend', 'Food ASMR', 'Large Portions'] },
    { word: 'Soju', category: 'Asia', hints: ['Korean Alcohol', 'Green Bottle', 'Shot Glass', 'Rice Spirit', 'Drinking Culture'] },
    { word: 'Karaoke Room', category: 'Asia', hints: ['Singing Box', 'Noraebang', 'Microphone', 'Song List', 'Private Room'] },
    { word: 'Korean Skincare', category: 'Asia', hints: ['Ten Steps', 'Glass Skin', 'Essence', 'K-Beauty', 'Sheet Mask'] },
    { word: 'Sheet Mask', category: 'Asia', hints: ['Face Cover', 'Serum Soaked', 'K-Beauty', 'Selfie', 'Hydration'] },

    // ── Countries & Cities ──
    { word: 'Tokyo', category: 'Asia', hints: ['Japan Capital', 'Shibuya', 'Shinjuku', 'Metropolis', 'Akihabara'] },
    { word: 'Seoul', category: 'Asia', hints: ['Korea Capital', 'Gangnam', 'Han River', 'Myeongdong', 'Bukchon'] },
    { word: 'Bangkok', category: 'Asia', hints: ['Thailand Capital', 'Tuk Tuk', 'Grand Palace', 'Chatuchak', 'Khao San'] },
    { word: 'Singapore', category: 'Asia', hints: ['Lion City', 'Clean Streets', 'Marina Bay', 'Merlion', 'Hawker Centre'] },
    { word: 'Hong Kong', category: 'Asia', hints: ['Victoria Peak', 'Dim Sum', 'Harbour', 'Neon Signs', 'Star Ferry'] },
    { word: 'Shanghai', category: 'Asia', hints: ['China City', 'Bund', 'Pudong', 'Maglev Train', 'Neon Skyline'] },
    { word: 'Beijing', category: 'Asia', hints: ['China Capital', 'Forbidden City', 'Hutong', 'Peking Duck', 'Tiananmen'] },
    { word: 'Taipei', category: 'Asia', hints: ['Taiwan Capital', 'Night Market', 'Bubble Tea', 'Taipei 101', 'MRT'] },
    { word: 'Hanoi', category: 'Asia', hints: ['Vietnam Capital', 'Old Quarter', 'Pho Street', 'Hoan Kiem', 'Motorbike'] },
    { word: 'Manila', category: 'Asia', hints: ['Philippines Capital', 'Jeepney', 'Intramuros', 'Island Gateway', 'Traffic'] },
    { word: 'Jakarta', category: 'Asia', hints: ['Indonesia Capital', 'Java Island', 'Monas Tower', 'Batik', 'Megacity'] },
    { word: 'Kuala Lumpur', category: 'Asia', hints: ['Malaysia Capital', 'Twin Towers', 'Petronas', 'Batu Caves', 'KLCC'] },
    { word: 'Osaka', category: 'Asia', hints: ['Japan City', 'Dotonbori', 'Takoyaki', 'Universal Studios', 'Street Food'] },
    { word: 'Kyoto', category: 'Asia', hints: ['Japan City', 'Temples', 'Geisha', 'Bamboo Grove', 'Fushimi Inari'] },
    { word: 'Busan', category: 'Asia', hints: ['Korea City', 'Beach', 'Fish Market', 'Train Movie', 'Haeundae'] },
    { word: 'Phuket', category: 'Asia', hints: ['Thai Island', 'Beach', 'Phi Phi', 'Andaman Sea', 'Resort'] },
    { word: 'Kathmandu', category: 'Asia', hints: ['Nepal Capital', 'Trekking Base', 'Temple Square', 'Durbar', 'Himalaya Gate'] },
    { word: 'Colombo', category: 'Asia', hints: ['Sri Lanka Capital', 'Port City', 'Galle Face', 'Island Nation', 'Tea Country'] },
    { word: 'Dhaka', category: 'Asia', hints: ['Bangladesh Capital', 'Rickshaw City', 'Buriganga', 'Dense Population', 'Muslin'] },
    { word: 'Phnom Penh', category: 'Asia', hints: ['Cambodia Capital', 'Royal Palace', 'Mekong', 'Riverside', 'Khmer History'] },
    { word: 'Saigon', category: 'Asia', hints: ['Ho Chi Minh', 'Vietnam City', 'War Museum', 'Motorbike Chaos', 'French Quarter'] },
    { word: 'Lhasa', category: 'Asia', hints: ['Tibet Capital', 'Potala Palace', 'High Altitude', 'Buddhist', 'Roof of World'] },
    { word: 'Ulaanbaatar', category: 'Asia', hints: ['Mongolia Capital', 'Steppe', 'Nomadic', 'Genghis Khan', 'Cold City'] },
    { word: 'Maldives', category: 'Asia', hints: ['Island Nation', 'Overwater Villa', 'Crystal Water', 'Honeymoon', 'Coral Reef'] },
    { word: 'Sri Lanka', category: 'Asia', hints: ['Teardrop Island', 'Tea Plantation', 'Cricket', 'Sigiriya', 'Beaches'] },
    { word: 'Bhutan', category: 'Asia', hints: ['Happiness Index', 'Thunder Dragon', 'Buddhist Kingdom', 'Tiger Nest', 'Himalayan'] },
    { word: 'Nepal', category: 'Asia', hints: ['Everest Country', 'Himalaya', 'Trekking', 'Temple', 'Namaste'] },
    { word: 'Myanmar', category: 'Asia', hints: ['Golden Pagoda', 'Bagan Temples', 'Yangon', 'Irrawaddy', 'Buddhism'] },
    { word: 'Laos', category: 'Asia', hints: ['Mekong River', 'Luang Prabang', 'Monks', 'Quiet Country', 'Vientiane'] },
    { word: 'Cambodia', category: 'Asia', hints: ['Angkor Wat', 'Khmer', 'Temple Kingdom', 'Siem Reap', 'Mekong'] },
    { word: 'Vietnam', category: 'Asia', hints: ['Pho Country', 'Ao Dai', 'Halong', 'Motorbike', 'Rice Paddy'] },
    { word: 'Mongolia', category: 'Asia', hints: ['Steppe Land', 'Nomads', 'Yurt', 'Horse Riders', 'Genghis Khan'] },

    // ── Landmarks & Places ──
    { word: 'Forbidden City', category: 'Asia', hints: ['Beijing Palace', 'Emperor Home', 'Red Walls', 'Ming Dynasty', 'Golden Throne'] },
    { word: 'Terracotta Army', category: 'Asia', hints: ['Clay Soldiers', 'Xian', 'Emperor Tomb', 'Ancient China', 'Buried Army'] },
    { word: 'Petronas Towers', category: 'Asia', hints: ['Twin Towers', 'KL Skyline', 'Malaysia', 'Sky Bridge', 'Tallest Twins'] },
    { word: 'Marina Bay Sands', category: 'Asia', hints: ['Singapore Hotel', 'Infinity Pool', 'Rooftop Ship', 'Casino', 'Three Towers'] },
    { word: 'Merlion', category: 'Asia', hints: ['Lion Fish', 'Singapore Icon', 'Water Spout', 'Statue', 'Harbour'] },
    { word: 'Borobudur', category: 'Asia', hints: ['Java Temple', 'Buddhist', 'Indonesia', 'Stone Stupas', 'UNESCO'] },
    { word: 'Fushimi Inari', category: 'Asia', hints: ['Orange Gates', 'Kyoto Shrine', 'Fox Statues', 'Torii Path', 'Hillside'] },
    { word: 'Shinjuku', category: 'Asia', hints: ['Tokyo District', 'Neon Lights', 'Robot Cafe', 'Train Station', 'Nightlife'] },
    { word: 'Akihabara', category: 'Asia', hints: ['Electric Town', 'Anime Shops', 'Otaku', 'Maid Cafe', 'Tokyo'] },
    { word: 'Shibuya Crossing', category: 'Asia', hints: ['Busiest Crossing', 'Tokyo', 'Hachiko', 'Scramble', 'Pedestrian'] },
    { word: 'Jeju Island', category: 'Asia', hints: ['Korea Resort', 'Volcanic', 'Tangerines', 'Haenyeo Divers', 'Honeymoon'] },
    { word: 'Sentosa', category: 'Asia', hints: ['Singapore Island', 'Universal Studios', 'Beach Resort', 'Cable Car', 'Aquarium'] },
    { word: 'Phi Phi Islands', category: 'Asia', hints: ['Thai Islands', 'Maya Bay', 'Snorkeling', 'The Beach Film', 'Limestone'] },
    { word: 'Komodo Island', category: 'Asia', hints: ['Giant Lizard', 'Indonesia', 'Dragon', 'Flores Sea', 'National Park'] },
    { word: 'Sigiriya', category: 'Asia', hints: ['Lion Rock', 'Sri Lanka', 'Ancient Fortress', 'Rock Climb', 'Frescoes'] },
    { word: 'Meiji Shrine', category: 'Asia', hints: ['Tokyo Temple', 'Emperor Meiji', 'Forest Path', 'Torii Gate', 'Harajuku Near'] },
    { word: 'Sensoji Temple', category: 'Asia', hints: ['Asakusa', 'Thunder Gate', 'Oldest Tokyo', 'Red Lantern', 'Incense'] },
    { word: 'Tiananmen Square', category: 'Asia', hints: ['Beijing', 'Mao Portrait', 'Large Plaza', 'Forbidden City Near', 'China Icon'] },
    { word: 'Potala Palace', category: 'Asia', hints: ['Lhasa', 'Dalai Lama', 'Red White', 'Tibetan', 'Mountain Palace'] },
    { word: 'Mount Everest', category: 'Asia', hints: ['Highest Peak', 'Nepal Tibet', 'Summit', 'Base Camp', 'Sherpa'] },

    // ── Asian Food ──
    { word: 'Tom Yum', category: 'Asia', hints: ['Thai Soup', 'Sour Spicy', 'Lemongrass', 'Shrimp', 'Galangal'] },
    { word: 'Green Curry', category: 'Asia', hints: ['Thai Dish', 'Coconut Milk', 'Basil', 'Spicy Paste', 'Aromatic'] },
    { word: 'Spring Rolls', category: 'Asia', hints: ['Wrapped', 'Crispy Fried', 'Vietnamese', 'Rice Paper', 'Fresh Herbs'] },
    { word: 'Banh Mi', category: 'Asia', hints: ['Vietnamese Sandwich', 'Baguette', 'Pork Pate', 'Pickled Carrot', 'Cilantro'] },
    { word: 'Satay', category: 'Asia', hints: ['Grilled Skewer', 'Peanut Sauce', 'Southeast Asian', 'Charcoal', 'Chicken Stick'] },
    { word: 'Laksa', category: 'Asia', hints: ['Spicy Soup', 'Coconut Noodle', 'Malaysian', 'Curry Broth', 'Prawns'] },
    { word: 'Nasi Goreng', category: 'Asia', hints: ['Fried Rice', 'Indonesian', 'Sweet Soy', 'Egg Top', 'Kecap Manis'] },
    { word: 'Rendang', category: 'Asia', hints: ['Slow Cooked', 'Indonesian', 'Coconut Beef', 'Spice Paste', 'Padang'] },
    { word: 'Miso Soup', category: 'Asia', hints: ['Soybean Paste', 'Japanese', 'Tofu Seaweed', 'Dashi Broth', 'Warm Bowl'] },
    { word: 'Tempura', category: 'Asia', hints: ['Battered Fried', 'Japanese', 'Light Crispy', 'Shrimp Veggie', 'Dipping Sauce'] },
    { word: 'Takoyaki', category: 'Asia', hints: ['Octopus Ball', 'Osaka Street', 'Round Mold', 'Bonito Flakes', 'Mayo Drizzle'] },
    { word: 'Okonomiyaki', category: 'Asia', hints: ['Japanese Pancake', 'Osaka', 'Cabbage Mix', 'Savory Griddle', 'Brown Sauce'] },
    { word: 'Udon', category: 'Asia', hints: ['Thick Noodle', 'Japanese', 'Wheat Flour', 'Hot Broth', 'Chewy'] },
    { word: 'Soba', category: 'Asia', hints: ['Buckwheat Noodle', 'Japanese', 'Cold Dipping', 'Thin Brown', 'Zaru'] },
    { word: 'Teriyaki', category: 'Asia', hints: ['Glazed Sauce', 'Sweet Soy', 'Japanese Grill', 'Chicken Salmon', 'Shiny'] },
    { word: 'Gyoza', category: 'Asia', hints: ['Japanese Dumpling', 'Pan Fried', 'Pork Filling', 'Crispy Bottom', 'Dipping Sauce'] },
    { word: 'Tteokbokki', category: 'Asia', hints: ['Rice Cake', 'Korean Spicy', 'Gochujang', 'Street Snack', 'Chewy Red'] },
    { word: 'Japchae', category: 'Asia', hints: ['Glass Noodle', 'Korean Stir', 'Sweet Potato', 'Sesame Oil', 'Colorful Veggie'] },
    { word: 'Gimbap', category: 'Asia', hints: ['Korean Roll', 'Seaweed Rice', 'Packed Lunch', 'Sliced Round', 'Sesame'] },
    { word: 'Korean BBQ', category: 'Asia', hints: ['Grilled Meat', 'Tabletop Grill', 'Samgyeopsal', 'Lettuce Wrap', 'Ssamjang'] },
    { word: 'Hotpot', category: 'Asia', hints: ['Boiling Broth', 'Dip Cook', 'Shabu Shabu', 'Communal Pot', 'Chinese'] },
    { word: 'Peking Duck', category: 'Asia', hints: ['Beijing Roast', 'Crispy Skin', 'Pancake Wrap', 'Hoisin Sauce', 'Carved Table'] },
    { word: 'Xiao Long Bao', category: 'Asia', hints: ['Soup Dumpling', 'Shanghai', 'Thin Skin', 'Hot Broth', 'Ginger Vinegar'] },
    { word: 'Char Siu', category: 'Asia', hints: ['BBQ Pork', 'Cantonese', 'Red Glaze', 'Honey Roast', 'Sweet Savory'] },
    { word: 'Wonton', category: 'Asia', hints: ['Chinese Dumpling', 'Thin Wrapper', 'Soup Float', 'Pork Shrimp', 'Broth'] },
    { word: 'Congee', category: 'Asia', hints: ['Rice Porridge', 'Chinese Comfort', 'Ginger', 'Breakfast Bowl', 'Century Egg'] },
    { word: 'Mochi', category: 'Asia', hints: ['Rice Cake', 'Japanese Sweet', 'Sticky Chewy', 'Ice Cream', 'Soft Ball'] },
    { word: 'Taiyaki', category: 'Asia', hints: ['Fish Shaped', 'Japanese Waffle', 'Red Bean', 'Street Snack', 'Hot Fresh'] },
    { word: 'Dango', category: 'Asia', hints: ['Rice Ball', 'Skewered', 'Three Colors', 'Sweet Sauce', 'Japanese Treat'] },
    { word: 'Mango Sticky Rice', category: 'Asia', hints: ['Thai Dessert', 'Coconut Milk', 'Sweet', 'Bangkok', 'Golden'] },
    { word: 'Halo Halo', category: 'Asia', hints: ['Filipino Shaved Ice', 'Mixed Dessert', 'Ube', 'Colorful', 'Sweet Beans'] },
    { word: 'Naan', category: 'Asia', hints: ['Flatbread', 'Tandoor', 'Butter Garlic', 'Indian Bread', 'Fluffy'] },
    { word: 'Fried Rice', category: 'Asia', hints: ['Wok Tossed', 'Egg Rice', 'Leftover Rice', 'Soy Sauce', 'Quick Meal'] },
    { word: 'Chow Mein', category: 'Asia', hints: ['Stir Fried Noodle', 'Chinese', 'Crispy Soft', 'Vegetable Mix', 'Soy Sauce'] },
    { word: 'Bulgogi', category: 'Asia', hints: ['Korean Beef', 'Marinated', 'Sweet Soy', 'Grilled Thin', 'Pear Sauce'] },
    { word: 'Samgyeopsal', category: 'Asia', hints: ['Pork Belly', 'Korean BBQ', 'Grilled Thick', 'Lettuce Wrap', 'Garlic'] },
    { word: 'Onigiri', category: 'Asia', hints: ['Rice Ball', 'Japanese', 'Nori Wrap', 'Triangle', 'Convenience Store'] },
    { word: 'Bento Box', category: 'Asia', hints: ['Lunch Box', 'Japanese Packed', 'Compartments', 'Cute Arranged', 'Rice Side'] },
    { word: 'Wasabi', category: 'Asia', hints: ['Spicy Green', 'Japanese', 'Sushi Pair', 'Nose Burn', 'Root Paste'] },
    { word: 'Sashimi', category: 'Asia', hints: ['Raw Sliced', 'Japanese', 'Fresh Fish', 'No Rice', 'Soy Dip'] },

    // ── Martial Arts & Sports ──
    { word: 'Kung Fu', category: 'Asia', hints: ['Chinese Martial', 'Wushu', 'Shaolin', 'Flying Kick', 'Discipline'] },
    { word: 'Karate', category: 'Asia', hints: ['Japanese Martial', 'Black Belt', 'Kata', 'Okinawa', 'Strike Block'] },
    { word: 'Taekwondo', category: 'Asia', hints: ['Korean Martial', 'High Kick', 'Olympic', 'Belt System', 'Breaking Board'] },
    { word: 'Judo', category: 'Asia', hints: ['Throwing Art', 'Japanese', 'Olympic', 'Grapple', 'Ippon'] },
    { word: 'Sumo Wrestling', category: 'Asia', hints: ['Heavy Fighter', 'Japanese', 'Ring Push', 'Salt Throw', 'Loincloth'] },
    { word: 'Muay Thai', category: 'Asia', hints: ['Thai Boxing', 'Eight Limbs', 'Elbow Knee', 'Ring Fight', 'Bangkok'] },
    { word: 'Aikido', category: 'Asia', hints: ['Harmony Art', 'Japanese', 'Redirect', 'Defensive', 'Wrist Lock'] },
    { word: 'Wushu', category: 'Asia', hints: ['Chinese Martial', 'Performance', 'Acrobatic', 'Competition', 'Flexible'] },
    { word: 'Kendo', category: 'Asia', hints: ['Sword Way', 'Japanese', 'Bamboo Stick', 'Armor Mask', 'Shinai'] },
    { word: 'Tai Chi', category: 'Asia', hints: ['Slow Movement', 'Chinese', 'Morning Park', 'Balance', 'Meditation'] },
    { word: 'Ninja', category: 'Asia', hints: ['Shadow Warrior', 'Stealth', 'Japanese', 'Black Suit', 'Shuriken'] },
    { word: 'Shaolin Monk', category: 'Asia', hints: ['Kung Fu Temple', 'Bald Head', 'Orange Robe', 'Chinese', 'Iron Fist'] },
    { word: 'Black Belt', category: 'Asia', hints: ['Martial Rank', 'Master Level', 'Dan Grade', 'Achievement', 'Expert'] },
    { word: 'Nunchaku', category: 'Asia', hints: ['Swinging Weapon', 'Two Sticks', 'Bruce Lee', 'Chain Link', 'Martial Tool'] },
    { word: 'Katana', category: 'Asia', hints: ['Japanese Sword', 'Curved Blade', 'Samurai', 'Sharp Steel', 'Scabbard'] },
    { word: 'Shuriken', category: 'Asia', hints: ['Throwing Star', 'Ninja Weapon', 'Metal Points', 'Stealth', 'Hidden'] },
    { word: 'Bruce Lee', category: 'Asia', hints: ['Martial Legend', 'Enter Dragon', 'One Inch Punch', 'Hong Kong', 'Jeet Kune Do'] },
    { word: 'Jackie Chan', category: 'Asia', hints: ['Action Comedy', 'Stunt Master', 'Hong Kong', 'Rush Hour', 'Drunken Master'] },
    { word: 'Badminton', category: 'Asia', hints: ['Shuttlecock', 'Racket Sport', 'Asian Dominant', 'Singles Doubles', 'Smash'] },
    { word: 'Table Tennis', category: 'Asia', hints: ['Ping Pong', 'Small Ball', 'Paddle', 'China Sport', 'Fast Rally'] },
    { word: 'Kabaddi', category: 'Asia', hints: ['Tag Sport', 'Indian', 'Raid', 'Breath Hold', 'Pro League'] },
    { word: 'Sepak Takraw', category: 'Asia', hints: ['Kick Volleyball', 'Rattan Ball', 'Southeast Asian', 'Acrobatic', 'Net Sport'] },

    // ── Culture & Traditions ──
    { word: 'Tea Ceremony', category: 'Asia', hints: ['Japanese Ritual', 'Matcha Whisk', 'Zen', 'Host Guest', 'Bowl Pour'] },
    { word: 'Zen Garden', category: 'Asia', hints: ['Rock Sand', 'Japanese', 'Raked Pattern', 'Meditation', 'Minimalist'] },
    { word: 'Ikebana', category: 'Asia', hints: ['Flower Arranging', 'Japanese Art', 'Minimalist', 'Vase', 'Nature Beauty'] },
    { word: 'Calligraphy', category: 'Asia', hints: ['Brush Writing', 'Ink Art', 'Chinese Japanese', 'Beautiful Script', 'Scroll'] },
    { word: 'Silk Road', category: 'Asia', hints: ['Trade Route', 'Ancient', 'East West', 'Camel Caravan', 'Spice Path'] },
    { word: 'Chopsticks', category: 'Asia', hints: ['Eating Sticks', 'Two Piece', 'Asian Utensil', 'Bamboo Wood', 'Pinch Grip'] },
    { word: 'Kimono', category: 'Asia', hints: ['Japanese Robe', 'Obi Belt', 'Silk Pattern', 'Traditional', 'Formal Dress'] },
    { word: 'Yukata', category: 'Asia', hints: ['Summer Robe', 'Japanese', 'Cotton Light', 'Festival Wear', 'Onsen'] },
    { word: 'Sari', category: 'Asia', hints: ['Indian Drape', 'Six Meters', 'Silk Fabric', 'Pallu', 'Wedding'] },
    { word: 'Ao Dai', category: 'Asia', hints: ['Vietnamese Dress', 'Long Tunic', 'Silk', 'Elegant', 'Trousers'] },
    { word: 'Batik', category: 'Asia', hints: ['Wax Print', 'Indonesian', 'Hand Dyed', 'Fabric Art', 'Pattern'] },
    { word: 'Bonsai', category: 'Asia', hints: ['Miniature Tree', 'Japanese Art', 'Pruned', 'Pot Grown', 'Patience'] },
    { word: 'Feng Shui', category: 'Asia', hints: ['Energy Flow', 'Chinese', 'Home Arrange', 'Luck Balance', 'Harmony'] },
    { word: 'Zodiac Animal', category: 'Asia', hints: ['Twelve Year', 'Chinese', 'Rat to Pig', 'Birth Year', 'Horoscope'] },
    { word: 'Paper Lantern', category: 'Asia', hints: ['Glowing Light', 'Festival', 'Sky Release', 'Wish', 'Red Round'] },
    { word: 'Dragon Dance', category: 'Asia', hints: ['Chinese Festival', 'Long Body', 'New Year', 'Team Carry', 'Drumbeat'] },
    { word: 'Lion Dance', category: 'Asia', hints: ['Chinese New Year', 'Two Person', 'Red Gold', 'Drums', 'Good Luck'] },
    { word: 'Torii Gate', category: 'Asia', hints: ['Orange Red', 'Shrine Entrance', 'Japanese', 'Sacred Mark', 'Fushimi'] },
    { word: 'Pagoda', category: 'Asia', hints: ['Tiered Tower', 'Buddhist', 'East Asian', 'Temple Tower', 'Multi Story'] },
    { word: 'Geisha', category: 'Asia', hints: ['Japanese Artist', 'White Face', 'Kimono', 'Entertainment', 'Kyoto'] },
    { word: 'Rickshaw', category: 'Asia', hints: ['Pulled Cart', 'Human Power', 'Asian Transport', 'Two Wheels', 'Running'] },
    { word: 'Tuk Tuk', category: 'Asia', hints: ['Three Wheeler', 'Thai Transport', 'Auto Rickshaw', 'Buzzing', 'Open Air'] },
    { word: 'Lantern Festival', category: 'Asia', hints: ['Fifteenth Day', 'Lunar New Year', 'Sky Lantern', 'Tangyuan', 'Light Float'] },
    { word: 'Songkran', category: 'Asia', hints: ['Thai New Year', 'Water Festival', 'April', 'Splash', 'Street Fun'] },
    { word: 'Lunar New Year', category: 'Asia', hints: ['Chinese New Year', 'Red Envelope', 'Dragon Dance', 'Family Feast', 'Spring Festival'] },
    { word: 'Mid Autumn Fest', category: 'Asia', hints: ['Moon Cake', 'Harvest Moon', 'Lantern', 'Chinese', 'Family Reunion'] },
    { word: 'Chuseok', category: 'Asia', hints: ['Korean Harvest', 'Songpyeon', 'Ancestor Rite', 'Autumn Moon', 'Three Day'] },
    { word: 'Golden Week', category: 'Asia', hints: ['Japan Holiday', 'May Break', 'Travel Rush', 'National Days', 'Crowded'] },
    { word: 'Obon Festival', category: 'Asia', hints: ['Japanese Ancestor', 'Spirit Return', 'Bon Dance', 'Lantern Float', 'August'] },
    { word: 'Loy Krathong', category: 'Asia', hints: ['Thai Float', 'River Offering', 'Candle Flower', 'Full Moon', 'Wish'] },
    { word: 'Vesak', category: 'Asia', hints: ['Buddha Birthday', 'Full Moon', 'Lantern', 'Buddhist Holy', 'May'] },
    { word: 'Naadam', category: 'Asia', hints: ['Mongolian Festival', 'Three Games', 'Wrestling', 'Horse Racing', 'Archery'] },

    // ── Films & Directors ──
    { word: 'Crouching Tiger', category: 'Asia', hints: ['Hidden Dragon', 'Wuxia Film', 'Ang Lee', 'Flying Sword', 'Bamboo Fight'] },
    { word: 'Oldboy', category: 'Asia', hints: ['Korean Thriller', 'Hammer Scene', 'Revenge', 'Park Chan-wook', 'Twist'] },
    { word: 'Train to Busan', category: 'Asia', hints: ['Zombie Film', 'Korean', 'Fast Train', 'Survival', 'Father Daughter'] },
    { word: 'Battle Royale', category: 'Asia', hints: ['Japanese Film', 'Students Fight', 'Island', 'Survival', 'Class'] },
    { word: 'Ip Man', category: 'Asia', hints: ['Wing Chun', 'Donnie Yen', 'Martial Arts', 'Bruce Lee Teacher', 'Foshan'] },
    { word: 'Rashomon', category: 'Asia', hints: ['Kurosawa', 'Multiple Views', 'Japanese Classic', 'Truth Debate', 'Gate'] },
    { word: 'Seven Samurai', category: 'Asia', hints: ['Kurosawa', 'Village Defense', 'Ronin', 'Japanese Classic', 'Farmers'] },
    { word: 'In the Mood', category: 'Asia', hints: ['Wong Kar-wai', 'Hong Kong', 'Romance', 'Cheongsam', 'Unrequited'] },
    { word: 'Kung Fu Hustle', category: 'Asia', hints: ['Stephen Chow', 'Comedy Action', 'Axe Gang', 'Hong Kong', 'Landlady'] },
    { word: 'Infernal Affairs', category: 'Asia', hints: ['Undercover', 'Hong Kong', 'Mole', 'Police Triad', 'Departed Source'] },
    { word: 'Hero', category: 'Asia', hints: ['Zhang Yimou', 'Wuxia', 'Color Coded', 'Assassin', 'Qin Emperor'] },
    { word: 'House of Daggers', category: 'Asia', hints: ['Flying Daggers', 'Zhang Yimou', 'Wuxia', 'Bamboo Forest', 'Love Triangle'] },
    { word: 'Ringu', category: 'Asia', hints: ['Japanese Horror', 'Cursed Tape', 'Well Girl', 'Seven Days', 'Sadako'] },
    { word: 'The Grudge', category: 'Asia', hints: ['Ju-On', 'Japanese Horror', 'Haunted House', 'Kayako', 'Croaking'] },
    { word: 'Kurosawa', category: 'Asia', hints: ['Japanese Director', 'Samurai Films', 'Rashomon', 'Seven Samurai', 'Master'] },
    { word: 'Bong Joon-ho', category: 'Asia', hints: ['Korean Director', 'Parasite', 'Oscar Winner', 'Social Class', 'Snowpiercer'] },
    { word: 'Wong Kar-wai', category: 'Asia', hints: ['Hong Kong Director', 'Mood Love', 'Neon Light', 'Chungking', 'Visual'] },
    { word: 'Hayao Miyazaki', category: 'Asia', hints: ['Ghibli Founder', 'Animator', 'Spirited Away', 'Totoro', 'Japanese'] },
    { word: 'RRR', category: 'Asia', hints: ['Rajamouli', 'Telugu Epic', 'Naatu Naatu', 'Oscar Song', 'Freedom'] },
    { word: 'Baahubali', category: 'Asia', hints: ['Indian Epic', 'Rajamouli', 'Why Katappa', 'Telugu', 'Prabhas'] },

    // ── Brands & Tech ──
    { word: 'Toyota', category: 'Asia', hints: ['Japanese Cars', 'Camry', 'Reliable', 'Hybrid', 'Corolla'] },
    { word: 'Honda', category: 'Asia', hints: ['Japanese Motor', 'Civic', 'Motorcycle', 'Reliable', 'VTEC'] },
    { word: 'Samsung', category: 'Asia', hints: ['Korean Tech', 'Galaxy Phone', 'Seoul HQ', 'Electronics', 'Chaebol'] },
    { word: 'Sony', category: 'Asia', hints: ['Japanese Tech', 'PlayStation', 'Walkman', 'Camera', 'Entertainment'] },
    { word: 'Nintendo', category: 'Asia', hints: ['Game Company', 'Mario', 'Switch', 'Kyoto', 'Zelda'] },
    { word: 'Uniqlo', category: 'Asia', hints: ['Japanese Fashion', 'Basic Wear', 'Affordable', 'HeatTech', 'Simple'] },
    { word: 'Muji', category: 'Asia', hints: ['No Brand', 'Japanese', 'Minimalist', 'Simple Design', 'Stationery'] },
    { word: 'Hyundai', category: 'Asia', hints: ['Korean Cars', 'Creta', 'Seoul', 'Chaebol', 'i20'] },
    { word: 'Huawei', category: 'Asia', hints: ['Chinese Tech', 'Phone Brand', 'Shenzhen', '5G', 'Telecom'] },
    { word: 'Alibaba', category: 'Asia', hints: ['Chinese E-commerce', 'Jack Ma', 'Online Market', 'Hangzhou', 'Singles Day'] },
    { word: 'TikTok', category: 'Asia', hints: ['Short Video', 'ByteDance', 'Chinese App', 'Viral Dance', 'Algorithm'] },
    { word: 'WeChat', category: 'Asia', hints: ['Chinese Super App', 'Messaging', 'Payment', 'Tencent', 'QR Code'] },
    { word: 'Shein', category: 'Asia', hints: ['Fast Fashion', 'Chinese Brand', 'Cheap Clothes', 'Online Shop', 'Trendy'] },
    { word: 'Grab', category: 'Asia', hints: ['Ride Hailing', 'Southeast Asian', 'Green App', 'Food Delivery', 'Super App'] },
    { word: 'PlayStation', category: 'Asia', hints: ['Sony Console', 'Gaming', 'Controller', 'PS5', 'Japanese'] },

    // ── Gaming ──
    { word: 'Mario', category: 'Asia', hints: ['Nintendo Hero', 'Plumber', 'Mushroom', 'Princess Peach', 'Jump'] },
    { word: 'Zelda', category: 'Asia', hints: ['Nintendo Game', 'Link', 'Hyrule', 'Triforce', 'Sword Shield'] },
    { word: 'Final Fantasy', category: 'Asia', hints: ['JRPG', 'Square Enix', 'Cloud Strife', 'Chocobo', 'Epic Story'] },
    { word: 'Genshin Impact', category: 'Asia', hints: ['Open World', 'Gacha', 'miHoYo', 'Elemental', 'Teyvat'] },
    { word: 'Dark Souls', category: 'Asia', hints: ['Difficult Game', 'FromSoftware', 'You Died', 'Japanese', 'Boss Fight'] },
    { word: 'Street Fighter', category: 'Asia', hints: ['Fighting Game', 'Hadouken', 'Ryu', 'Capcom', 'Arcade'] },
    { word: 'Tekken', category: 'Asia', hints: ['Fighting Game', 'Bandai Namco', 'Iron Fist', 'Jin', 'Combo'] },
    { word: 'Pac-Man', category: 'Asia', hints: ['Arcade Classic', 'Yellow Circle', 'Ghosts', 'Dots', 'Namco'] },
    { word: 'Sonic', category: 'Asia', hints: ['Blue Hedgehog', 'SEGA', 'Fast Runner', 'Gold Rings', 'Tails'] },
    { word: 'Metal Gear Solid', category: 'Asia', hints: ['Stealth Game', 'Snake', 'Konami', 'Kojima', 'Tactical'] },
    { word: 'Resident Evil', category: 'Asia', hints: ['Horror Game', 'Zombies', 'Capcom', 'Raccoon City', 'Survival'] },
    { word: 'Elden Ring', category: 'Asia', hints: ['FromSoftware', 'Open World', 'George Martin', 'Tarnished', 'Hard Game'] },
    { word: 'Animal Crossing', category: 'Asia', hints: ['Nintendo', 'Island Life', 'Tom Nook', 'Villagers', 'Relaxing'] },
    { word: 'Persona 5', category: 'Asia', hints: ['JRPG', 'Phantom Thieves', 'Joker', 'Stylish', 'Tokyo School'] },
    { word: 'Fire Emblem', category: 'Asia', hints: ['Strategy RPG', 'Nintendo', 'Tactical', 'Permadeath', 'Sword Lord'] },

    // ── Nature & Geography ──
    { word: 'Bamboo Forest', category: 'Asia', hints: ['Green Tall', 'Arashiyama', 'Swaying', 'Kyoto', 'Path'] },
    { word: 'Himalaya', category: 'Asia', hints: ['Mountain Range', 'Tallest Peaks', 'Nepal India', 'Snow', 'Trekking'] },
    { word: 'Mekong River', category: 'Asia', hints: ['Southeast Asia', 'Long River', 'Vietnam Laos', 'Delta', 'Floating Market'] },
    { word: 'Yangtze River', category: 'Asia', hints: ['China Longest', 'Three Gorges', 'Cruise', 'Shanghai', 'Dragon'] },
    { word: 'Gobi Desert', category: 'Asia', hints: ['Mongolia China', 'Vast Dry', 'Sand Dunes', 'Dinosaur Fossil', 'Cold Desert'] },
    { word: 'Rice Terrace', category: 'Asia', hints: ['Stepped Fields', 'Philippines Bali', 'Green Paddy', 'Farming', 'Mountain'] },
    { word: 'Coral Triangle', category: 'Asia', hints: ['Marine Diversity', 'Southeast Asia', 'Reef', 'Diving', 'Fish'] },
    { word: 'Mount Kilimanjaro', category: 'Asia', hints: ['Africa Tallest', 'Tanzania', 'Snow Peak', 'Volcanic', 'Trek'] },
    { word: 'Dead Sea', category: 'Asia', hints: ['Salt Lake', 'Float', 'Lowest Point', 'Jordan Israel', 'Mineral'] },
    { word: 'Borneo Rainforest', category: 'Asia', hints: ['Oldest Forest', 'Orangutan', 'Malaysia Indonesia', 'Biodiversity', 'Tropical'] },
    { word: 'Lotus Pond', category: 'Asia', hints: ['Sacred Flower', 'Pink Bloom', 'Buddhist', 'Temple', 'Water Garden'] },
    { word: 'Koi Fish', category: 'Asia', hints: ['Ornamental', 'Japanese Pond', 'Colorful', 'Good Luck', 'Orange White'] },
    { word: 'Panda', category: 'Asia', hints: ['Black White Bear', 'Bamboo Eater', 'China', 'Endangered', 'Cute'] },
    { word: 'Snow Monkey', category: 'Asia', hints: ['Japanese Macaque', 'Hot Spring', 'Winter', 'Jigokudani', 'Bathing'] },
    { word: 'Red Panda', category: 'Asia', hints: ['Small Fluffy', 'Bamboo Eater', 'Himalaya', 'Cute', 'Firefox'] },
    { word: 'Komodo Dragon', category: 'Asia', hints: ['Giant Lizard', 'Indonesia', 'Venomous Bite', 'Island', 'Largest Reptile'] },
    { word: 'Bengal Tiger', category: 'Asia', hints: ['Indian', 'Orange Stripe', 'Jungle', 'Endangered', 'Sundarbans'] },
    { word: 'Asian Elephant', category: 'Asia', hints: ['Trunk', 'Temple', 'Smaller Ears', 'Sacred', 'Gentle Giant'] },
    { word: 'Orangutan', category: 'Asia', hints: ['Red Ape', 'Borneo', 'Smart Primate', 'Forest', 'Endangered'] },

    // ── Historical & Mythology ──
    { word: 'Genghis Khan', category: 'Asia', hints: ['Mongol Empire', 'Conqueror', 'Horse Archer', 'Steppe', 'Largest Empire'] },
    { word: 'Confucius', category: 'Asia', hints: ['Chinese Philosopher', 'Analects', 'Wisdom', 'Ethics', 'Teacher'] },
    { word: 'Sun Tzu', category: 'Asia', hints: ['Art of War', 'Chinese Strategist', 'Military', 'Ancient', 'Know Enemy'] },
    { word: 'Shogun', category: 'Asia', hints: ['Military Ruler', 'Japan', 'Feudal', 'Samurai Lord', 'Edo'] },
    { word: 'Emperor', category: 'Asia', hints: ['Ruler', 'Dynasty', 'Throne', 'Crown', 'Imperial'] },
    { word: 'Terracotta Warriors', category: 'Asia', hints: ['Clay Soldiers', 'Xian China', 'Emperor Tomb', 'Ancient Army', 'Underground'] },
    { word: 'Mughal Empire', category: 'Asia', hints: ['Indian Dynasty', 'Taj Mahal', 'Akbar', 'Delhi', 'Persian Influence'] },
    { word: 'Khmer Empire', category: 'Asia', hints: ['Angkor', 'Cambodia', 'Ancient', 'Temple Builder', 'Southeast Asian'] },
    { word: 'Silk Weaving', category: 'Asia', hints: ['Fine Fabric', 'Chinese Art', 'Loom', 'Thread', 'Luxury'] },
    { word: 'Jade Dragon', category: 'Asia', hints: ['Green Stone', 'Chinese Myth', 'Sacred', 'Carved', 'Lucky'] },
    { word: 'Phoenix', category: 'Asia', hints: ['Fire Bird', 'Rebirth', 'Mythical', 'Fenghuang', 'Immortal'] },
    { word: 'Yin Yang', category: 'Asia', hints: ['Balance', 'Black White', 'Duality', 'Chinese', 'Harmony'] },
    { word: 'Mandala', category: 'Asia', hints: ['Sacred Circle', 'Tibetan Sand', 'Meditation', 'Geometric', 'Spiritual'] },
    { word: 'Karma', category: 'Asia', hints: ['Action Result', 'What Goes Around', 'Hindu Buddhist', 'Deed', 'Cycle'] },
    { word: 'Nirvana', category: 'Asia', hints: ['Enlightenment', 'Buddhist Goal', 'Liberation', 'Peace', 'Suffering End'] },
    { word: 'Third Eye', category: 'Asia', hints: ['Inner Vision', 'Spiritual', 'Forehead', 'Awakening', 'Shiva'] },
    { word: 'Buddha', category: 'Asia', hints: ['Enlightened One', 'Siddhartha', 'Meditation', 'Bodhi Tree', 'Middle Path'] },
    { word: 'Lotus Flower', category: 'Asia', hints: ['Sacred Bloom', 'Mud Growth', 'Buddhist', 'Pink White', 'Purity'] },
    { word: 'Om Symbol', category: 'Asia', hints: ['Sacred Sound', 'Hindu Buddhist', 'Chanting', 'Meditation', 'Universal'] },

    // ── Language & Script ──
    { word: 'Mandarin', category: 'Asia', hints: ['Chinese Language', 'Tonal', 'Most Spoken', 'Beijing', 'Characters'] },
    { word: 'Hangul', category: 'Asia', hints: ['Korean Script', 'King Sejong', 'Alphabet', 'Blocks', 'Simple System'] },
    { word: 'Katakana', category: 'Asia', hints: ['Japanese Script', 'Foreign Words', 'Angular', 'Phonetic', 'Loan Words'] },
    { word: 'Hiragana', category: 'Asia', hints: ['Japanese Script', 'Curved', 'Basic Writing', 'Phonetic', 'Children Learn'] },
    { word: 'Kanji', category: 'Asia', hints: ['Chinese Characters', 'Japanese', 'Complex', 'Meaning Based', 'Thousands'] },
    { word: 'Thai Script', category: 'Asia', hints: ['Curvy Letters', 'No Spaces', 'Tonal Marks', 'Bangkok', 'Ancient'] },
    { word: 'Sanskrit', category: 'Asia', hints: ['Ancient Indian', 'Sacred Text', 'Devanagari', 'Vedas', 'Classical'] },
    { word: 'Haiku', category: 'Asia', hints: ['Three Lines', 'Five Seven Five', 'Japanese Poem', 'Nature', 'Short'] },
    { word: 'Manga Panel', category: 'Asia', hints: ['Comic Frame', 'Japanese', 'Sequential Art', 'Speech Bubble', 'Action Lines'] },
    { word: 'Webtoon', category: 'Asia', hints: ['Korean Comic', 'Scroll Format', 'Digital', 'NAVER', 'Color'] },

    // ── Miscellaneous ──
    { word: 'Onsen', category: 'Asia', hints: ['Hot Spring', 'Japanese', 'Natural Bath', 'Volcanic', 'Naked'] },
    { word: 'Capsule Hotel', category: 'Asia', hints: ['Tiny Room', 'Japanese', 'Pod Sleep', 'Budget', 'Stacked'] },
    { word: 'Robot Restaurant', category: 'Asia', hints: ['Shinjuku', 'Neon Show', 'Mechanical', 'Tokyo Tourist', 'Wild'] },
    { word: 'Cat Cafe', category: 'Asia', hints: ['Pet Cats', 'Coffee', 'Japanese Trend', 'Cuddle', 'Meow'] },
    { word: 'Vending Machine', category: 'Asia', hints: ['Japan Everywhere', 'Automatic', 'Hot Cold Drinks', 'Coin Insert', 'Convenient'] },
    { word: 'Kawaii', category: 'Asia', hints: ['Cute Culture', 'Japanese', 'Adorable', 'Pink Pastel', 'Hello Kitty'] },
    { word: 'Konbini', category: 'Asia', hints: ['Japanese Store', 'Seven Eleven', 'Always Open', 'Onigiri', 'Convenience'] },
    { word: 'Lucky Cat', category: 'Asia', hints: ['Maneki Neko', 'Waving Paw', 'Shop Front', 'Gold', 'Good Fortune'] },
    { word: 'Daruma Doll', category: 'Asia', hints: ['Red Round', 'Wish Maker', 'Japanese', 'One Eye', 'Goal Setting'] },
    { word: 'Tamagotchi', category: 'Asia', hints: ['Virtual Pet', 'Egg Shaped', 'Feed Play', 'Bandai', 'Nineties'] },
    { word: 'Hello Kitty', category: 'Asia', hints: ['Sanrio', 'White Cat', 'Red Bow', 'Kawaii Icon', 'No Mouth'] },
    { word: 'Gundam', category: 'Asia', hints: ['Giant Robot', 'Mecha Anime', 'Model Kit', 'Bandai', 'Mobile Suit'] },
    { word: 'Pachinko', category: 'Asia', hints: ['Japanese Arcade', 'Pinball', 'Gambling', 'Steel Ball', 'Loud'] },
    { word: 'Mahjong', category: 'Asia', hints: ['Tile Game', 'Chinese', 'Four Player', 'Clicking Sound', 'Strategy'] },
    { word: 'Go Board Game', category: 'Asia', hints: ['Black White Stones', 'Chinese Ancient', 'Territory', 'Grid', 'Deep Strategy'] },
    { word: 'Shogi', category: 'Asia', hints: ['Japanese Chess', 'Captured Reuse', 'Board Game', 'Strategy', 'Wooden Pieces'] },
    { word: 'Rickshaw Puller', category: 'Asia', hints: ['Human Cart', 'Kolkata', 'Running', 'Two Wheel', 'Old Transport'] },
    { word: 'Floating Market', category: 'Asia', hints: ['Boat Vendor', 'Thai Canal', 'Bangkok', 'Fruit Seller', 'Water Trade'] },
    { word: 'Lantern Street', category: 'Asia', hints: ['Hanging Lights', 'Hoi An', 'Colorful', 'Vietnam', 'Night Glow'] },
    { word: 'Dragon Boat', category: 'Asia', hints: ['Paddling Race', 'Chinese Festival', 'Long Canoe', 'Drum Beat', 'Zongzi'] },
    { word: 'Sake', category: 'Asia', hints: ['Japanese Rice Wine', 'Warm Cold', 'Brewery', 'Tokkuri', 'Kampai'] },
    { word: 'Oolong Tea', category: 'Asia', hints: ['Chinese Tea', 'Semi Oxidized', 'Fragrant', 'Taiwan', 'Between Green Black'] },
    { word: 'Jasmine Tea', category: 'Asia', hints: ['Flower Scented', 'Chinese', 'Fragrant', 'Green Base', 'Relaxing'] },
    { word: 'Green Tea', category: 'Asia', hints: ['Unoxidized', 'Japanese Chinese', 'Healthy', 'Antioxidant', 'Light'] },
    { word: 'Chai', category: 'Asia', hints: ['Indian Tea', 'Spiced Milk', 'Cardamom', 'Street Stall', 'Cutting'] },
    { word: 'Turmeric Latte', category: 'Asia', hints: ['Golden Milk', 'Haldi', 'Yellow', 'Wellness', 'Warm'] },
    { word: 'Pandan', category: 'Asia', hints: ['Green Leaf', 'Southeast Asian', 'Sweet Fragrant', 'Cake Color', 'Vanilla East'] },
    { word: 'Lychee', category: 'Asia', hints: ['Sweet Fruit', 'Red Shell', 'White Flesh', 'Chinese', 'Summer'] },
    { word: 'Durian', category: 'Asia', hints: ['Smelly Fruit', 'King Fruit', 'Southeast Asian', 'Banned Hotel', 'Thorny'] },
    { word: 'Rambutan', category: 'Asia', hints: ['Hairy Fruit', 'Red Spiky', 'Sweet White', 'Tropical', 'Southeast Asian'] },
    { word: 'Jackfruit', category: 'Asia', hints: ['Large Fruit', 'Yellow Pods', 'Tropical', 'Meat Substitute', 'Sweet Sticky'] },
    { word: 'Mangosteen', category: 'Asia', hints: ['Queen Fruit', 'Purple Shell', 'White Sweet', 'Southeast Asian', 'Tropical'] },
    { word: 'Starfruit', category: 'Asia', hints: ['Five Pointed', 'Cross Section', 'Tropical', 'Sour Sweet', 'Yellow Green'] },
    { word: 'Longan', category: 'Asia', hints: ['Dragon Eye', 'Small Sweet', 'Chinese Fruit', 'Translucent', 'Lychee Cousin'] },
    { word: 'Persimmon', category: 'Asia', hints: ['Orange Fruit', 'Autumn', 'Sweet Astringent', 'Japanese', 'Hachiya'] },
  ],
};
