import type { WordPack } from '../game/types';

export const asiaPack: WordPack = {
  id: 'asia',
  name: 'Asia',
  entries: [
    { word: 'Naruto', category: 'Asia' },
    { word: 'One Piece', category: 'Asia' },
    { word: 'Attack on Titan', category: 'Asia' },
    { word: 'Death Note', category: 'Asia' },
    { word: 'Dragon Ball Z', category: 'Asia' },
    { word: 'Studio Ghibli', category: 'Asia' },
    { word: 'Ramen', category: 'Asia' },
    { word: 'Sushi', category: 'Asia' },
    { word: 'Boba Tea', category: 'Asia' },
    { word: 'Kimchi', category: 'Asia' },
    { word: 'K-Drama', category: 'Asia' },
    { word: 'Squid Game', category: 'Asia' },
    { word: 'BTS', category: 'Asia' },
    { word: 'BLACKPINK', category: 'Asia' },
    { word: 'K-Pop', category: 'Asia' },
    { word: 'Manga', category: 'Asia' },
    { word: 'Cosplay', category: 'Asia' },
    { word: 'Cherry Blossom', category: 'Asia' },
    { word: 'Mount Fuji', category: 'Asia' },
    { word: 'Great Wall', category: 'Asia' },
    { word: 'Thai Street Food', category: 'Asia' },
    { word: 'Pad Thai', category: 'Asia' },
    { word: 'Dim Sum', category: 'Asia' },
    { word: 'Matcha', category: 'Asia' },
    { word: 'Tofu Stew', category: 'Asia' },
    { word: 'Anime Convention', category: 'Asia' },
    { word: 'Bullet Train', category: 'Asia' },
    { word: 'Night Market', category: 'Asia' },
    { word: 'Bali', category: 'Asia' },
    { word: 'Ha Long Bay', category: 'Asia' },
    { word: 'Angkor Wat', category: 'Asia' },
    { word: 'Pho', category: 'Asia' },
    { word: 'Bibimbap', category: 'Asia' },
    { word: 'Samurai', category: 'Asia' },
    { word: 'Hanbok', category: 'Asia' },
    { word: 'Origami', category: 'Asia' },
    { word: 'Jujutsu Kaisen', category: 'Asia' },
    { word: 'Demon Slayer', category: 'Asia' },
    { word: 'Parasite', category: 'Asia' },
    { word: 'Spirited Away', category: 'Asia' },
  ],
};
