import type { WordPack } from '../game/types';

export const bollywoodPack: WordPack = {
  id: 'bollywood',
  name: 'Bollywood',
  entries: [
    // ── Original 40 ─────────────────────────────────────────────
    { word: 'Mughal-e-Azam', category: 'Bollywood', hints: ['Anarkali', 'Salim', 'Pyar Kiya To Darna Kya', 'Sheesh Mahal', 'K Asif'] },
    { word: 'Sholay', category: 'Bollywood', hints: ['Gabbar', 'Thakur', 'Basanti', 'Kitne Aadmi The', 'Ramgarh'] },
    { word: 'DDLJ', category: 'Bollywood', hints: ['Simran', 'Raj', 'Mustard Fields', 'Palat', 'Europe Trip'] },
    { word: 'Lagaan', category: 'Bollywood', hints: ['Cricket Match', 'Bhuvan', 'British', 'Champaner', 'Oscar Nominated'] },
    { word: 'Dil Chahta Hai', category: 'Bollywood', hints: ['Goa Trip', 'Three Friends', 'Akash', 'Painting', 'Farhan Akhtar'] },
    { word: 'Gully Boy', category: 'Bollywood', hints: ['Rapper', 'Dharavi', 'Apna Time', 'Murad', 'Street Hip Hop'] },
    { word: 'Gangs of Wasseypur', category: 'Bollywood', hints: ['Coal Mafia', 'Sardar Khan', 'Faizal', 'Dhanbad', 'Revenge Saga'] },
    { word: 'Zindagi Na Milegi Dobara', category: 'Bollywood', hints: ['Spain Road Trip', 'Skydiving', 'Tomato Festival', 'Three Friends', 'Scuba Diving'] },
    { word: '3 Idiots', category: 'Bollywood', hints: ['Rancho', 'All Izz Well', 'Engineering College', 'Virus', 'Ladakh'] },
    { word: 'Andaz Apna Apna', category: 'Bollywood', hints: ['Amar Prem', 'Crime Master Gogo', 'Teja', 'Comedy Duo', 'Karisma'] },
    { word: 'Shah Rukh Khan', category: 'Bollywood', hints: ['King Khan', 'Mannat', 'Arms Spread', 'Baazigar', 'Raees'] },
    { word: 'Amitabh Bachchan', category: 'Bollywood', hints: ['Big B', 'Angry Young Man', 'KBC Host', 'Jumma Chumma', 'Natwarlal'] },
    { word: 'Alia Bhatt', category: 'Bollywood', hints: ['Highway', 'Gangubai', 'Raazi', 'Udta Punjab', 'Kapoor Wife'] },
    { word: 'Irrfan Khan', category: 'Bollywood', hints: ['Paan Singh', 'Hindi Medium', 'Life Of Pi', 'Maqbool', 'Subtle Acting'] },
    { word: 'Ranveer Singh', category: 'Bollywood', hints: ['Energy', 'Bajirao', 'Khilji', 'Deepika Husband', 'Band Baaja'] },
    { word: 'Item Number', category: 'Bollywood', hints: ['Dance', 'Special Appearance', 'Munni', 'Sheila', 'Club Song'] },
    { word: 'Interval Break', category: 'Bollywood', hints: ['Samosa', 'Cliffhanger', 'Popcorn', 'Theatre', 'Fifteen Minutes'] },
    { word: 'Slow Motion Walk', category: 'Bollywood', hints: ['Hero Entry', 'Wind Blowing', 'Background Music', 'Sunglasses', 'Action Star'] },
    { word: 'Wet Sari Scene', category: 'Bollywood', hints: ['Waterfall', 'Raveena', 'Tip Tip Barsa', 'Rain Song', 'Controversy'] },
    { word: 'Dishoom Dishoom', category: 'Bollywood', hints: ['Fight Scene', 'Punch Sound', 'Stunt', 'Action', 'Villain Beaten'] },
    { word: 'Mehendi Scene', category: 'Bollywood', hints: ['Wedding Prep', 'Bride Hands', 'Sangeet', 'Dulhan', 'Green Paste'] },
    { word: 'Airport Climax', category: 'Bollywood', hints: ['Last Minute', 'Stop The Plane', 'Running', 'Love Confession', 'Departure Gate'] },
    { word: 'Double Role', category: 'Bollywood', hints: ['Twins', 'Seeta Aur Geeta', 'Judwaa', 'Lost And Found', 'Mirror Scene'] },
    { word: 'Filmy Dialogue', category: 'Bollywood', hints: ['Punchline', 'Iconic Line', 'Whistle Moment', 'Mass Scene', 'Clap Worthy'] },
    { word: 'Train Chase', category: 'Bollywood', hints: ['Platform', 'Running', 'Hand Grab', 'Departure', 'Climax Scene'] },
    { word: 'Yash Raj Films', category: 'Bollywood', hints: ['YRF', 'Aditya Chopra', 'Romance', 'Chandni Chowk', 'Banner'] },
    { word: 'Karan Johar', category: 'Bollywood', hints: ['K3G', 'Koffee With', 'Family Drama', 'Poo', 'Toodles'] },
    { word: 'Rohit Shetty', category: 'Bollywood', hints: ['Car Flying', 'Cop Universe', 'Singham', 'Golmaal', 'Explosions'] },
    { word: 'Sanjay Leela Bhansali', category: 'Bollywood', hints: ['Grand Sets', 'Devdas', 'Padmaavat', 'Opera Style', 'Visual Spectacle'] },
    { word: 'Anurag Kashyap', category: 'Bollywood', hints: ['Dark Cinema', 'Wasseypur', 'Dev D', 'Ugly', 'Indie Filmmaker'] },
    { word: 'Hera Pheri', category: 'Bollywood', hints: ['Babu Rao', 'Raju Shyam', 'Scheme', 'Paresh Rawal', 'Utha Le Re'] },
    { word: 'Tumbbad', category: 'Bollywood', hints: ['Hastar', 'Gold Coins', 'Horror', 'Rain', 'Ancestral Curse'] },
    { word: 'Barfi', category: 'Bollywood', hints: ['Mute Deaf', 'Ranbir', 'Jhilmil', 'Darjeeling', 'Charlie Chaplin'] },
    { word: 'Queen', category: 'Bollywood', hints: ['Kangana', 'Solo Honeymoon', 'Paris', 'Independence', 'Rajouri Garden'] },
    { word: 'Sangeet Night', category: 'Bollywood', hints: ['Wedding Function', 'Dance', 'Choreography', 'DJ', 'Bride Groom'] },
    { word: 'Trailer Launch', category: 'Bollywood', hints: ['First Look', 'Promotion', 'Stage', 'Release Date', 'Teaser'] },
    { word: 'First Day First Show', category: 'Bollywood', hints: ['Opening Day', 'Fans', 'Morning Show', 'Theatre Rush', 'Tickets'] },
    { word: 'Cabaret Song', category: 'Bollywood', hints: ['Helen', 'Bar Dance', 'Retro', 'Nightclub', 'Shimmy'] },
    { word: 'Stunt Double', category: 'Bollywood', hints: ['Body Double', 'Action Scene', 'Behind Camera', 'Risk', 'Stand In'] },
    { word: 'Madhuri Dixit', category: 'Bollywood', hints: ['Dhak Dhak', 'Ek Do Teen', 'Nene', 'Devdas Chandramukhi', 'Graceful Dancer'] },
    // ── Movies: Classics ────────────────────────────────────────
    { word: 'Mother India', category: 'Bollywood', hints: ['Nargis', 'Village', 'Flood', 'Son Sacrifice', 'Sunil Dutt'] },
    { word: 'Pyaasa', category: 'Bollywood', hints: ['Guru Dutt', 'Poet', 'Jinhe Naaz Hai', 'Waheeda', 'Tragedy'] },
    { word: 'Guide', category: 'Bollywood', hints: ['Dev Anand', 'Rosie', 'Snake Dance', 'Waheeda Rehman', 'R K Narayan'] },
    { word: 'Pakeezah', category: 'Bollywood', hints: ['Meena Kumari', 'Courtesan', 'Train Letter', 'Kamal Amrohi', 'Inhi Logon Ne'] },
    { word: 'Anand', category: 'Bollywood', hints: ['Rajesh Khanna', 'Babu Moshai', 'Cancer', 'Zindagi Badi Honi', 'Hrishikesh'] },
    { word: 'Deewar', category: 'Bollywood', hints: ['Mere Paas Maa Hai', 'Brothers', 'Badge Number', 'Smuggler', 'Yash Chopra'] },
    { word: 'Amar Akbar Anthony', category: 'Bollywood', hints: ['Three Brothers', 'Lost And Found', 'My Name Is Anthony', 'Manmohan Desai', 'Multi Starrer'] },
    { word: 'Don', category: 'Bollywood', hints: ['Don Ko Pakadna', 'Mushkil Hi Nahi', 'Underworld', 'Amitabh', 'Smuggler'] },
    { word: 'Coolie', category: 'Bollywood', hints: ['Railway Porter', 'Amitabh Injury', 'Real Accident', 'Manmohan Desai', 'Iqbal'] },
    { word: 'Mr India', category: 'Bollywood', hints: ['Mogambo', 'Invisible', 'Sridevi', 'Hawa Hawaii', 'Shekhar Kapur'] },
    { word: 'Tezaab', category: 'Bollywood', hints: ['Ek Do Teen', 'Anil Kapoor', 'Madhuri', 'Dance', 'N Chandra'] },
    { word: 'Maine Pyar Kiya', category: 'Bollywood', hints: ['Salman Debut', 'Friendship', 'Pigeon', 'Bhagyashree', 'Dosti'] },
    { word: 'Hum Aapke Hain Koun', category: 'Bollywood', hints: ['Wedding Film', 'Tuffy Dog', 'Salman Madhuri', 'Fourteen Songs', 'Family'] },
    { word: 'Kuch Kuch Hota Hai', category: 'Bollywood', hints: ['Cool Nahi', 'Summer Camp', 'Friendship Band', 'Tina Rahul', 'Basketball'] },
    { word: 'Rangeela', category: 'Bollywood', hints: ['Aamir', 'Urmila', 'Bollywood Dream', 'Ram Gopal Varma', 'Tapori'] },
    { word: 'Satya', category: 'Bollywood', hints: ['Mumbai Underworld', 'Bhiku Mhatre', 'Manoj Bajpayee', 'Gang War', 'Ram Gopal Varma'] },
    { word: 'Baazigar', category: 'Bollywood', hints: ['Haar Ke Jeetne', 'Terrace Push', 'SRK Villain', 'Kajol', 'Abbas Mustan'] },
    { word: 'Darr', category: 'Bollywood', hints: ['K K K Kiran', 'Stalker', 'SRK Villain', 'Tu Haan Kar', 'Yash Chopra'] },
    { word: 'Kabhi Khushi Kabhie Gham', category: 'Bollywood', hints: ['K3G', 'Poo', 'Family Reunion', 'London', 'Bole Chudiyan'] },
    { word: 'Devdas', category: 'Bollywood', hints: ['Chandramukhi', 'Paro', 'Maar Daala', 'Alcohol', 'Bhansali'] },
    { word: 'Black', category: 'Bollywood', hints: ['Deaf Blind', 'Teacher Student', 'Rani Amitabh', 'Graduation', 'Helen Keller'] },
    { word: 'Swades', category: 'Bollywood', hints: ['NRI Returns', 'Village', 'Electricity', 'NASA', 'Yun Hi Chala'] },
    { word: 'Rang De Basanti', category: 'Bollywood', hints: ['Bhagat Singh', 'College Friends', 'Documentary', 'Aamir', 'Revolution'] },
    { word: 'Lage Raho Munna Bhai', category: 'Bollywood', hints: ['Gandhigiri', 'Chemical Locha', 'Radio Jockey', 'Sanjay Dutt', 'Jaadu Ki Jhappi'] },
    { word: 'Chak De India', category: 'Bollywood', hints: ['Hockey', 'Women Team', 'Coach', 'Sattar Minute', 'SRK Turban'] },
    { word: 'Om Shanti Om', category: 'Bollywood', hints: ['Reincarnation', 'Shantipriya', 'Film Within Film', 'Dard E Disco', 'Awards Night'] },
    { word: 'Jab We Met', category: 'Bollywood', hints: ['Geet', 'Train', 'Main Apni Favourite', 'Shahid Kareena', 'Shimla'] },
    { word: 'Taare Zameen Par', category: 'Bollywood', hints: ['Dyslexia', 'Art Teacher', 'Child Actor', 'Ishaan', 'Painting Competition'] },
    { word: 'Ghajini', category: 'Bollywood', hints: ['Memory Loss', 'Polaroid Photos', 'Body Tattoos', 'Aamir Bald', 'Revenge'] },
    { word: 'PK', category: 'Bollywood', hints: ['Alien', 'Remote Control', 'God Question', 'Aamir Nude Poster', 'Transistor'] },
    { word: 'Dangal', category: 'Bollywood', hints: ['Wrestling', 'Phogat Sisters', 'Aamir Fat', 'Haryana', 'Gold Medal'] },
    { word: 'Bajrangi Bhaijaan', category: 'Bollywood', hints: ['Pakistan Girl', 'Munni', 'Salman', 'Border Cross', 'Hanuman Bhakt'] },
    { word: 'Baahubali', category: 'Bollywood', hints: ['Katappa', 'Why Did He Kill', 'Waterfall', 'Rajamouli', 'Mahishmati'] },
    { word: 'Padmaavat', category: 'Bollywood', hints: ['Jauhar', 'Khilji', 'Rajput Queen', 'Ghoomar', 'Bhansali'] },
    { word: 'Sanju', category: 'Bollywood', hints: ['Biopic', 'Dutt', 'Drugs', 'Ranbir', 'Hirani'] },
    { word: 'War', category: 'Bollywood', hints: ['Hrithik Tiger', 'Chase', 'Ghungroo Song', 'Spy', 'Action'] },
    { word: 'Kabir Singh', category: 'Bollywood', hints: ['Arjun Reddy Remake', 'Shahid', 'Surgeon', 'Anger Issues', 'Preeti'] },
    { word: 'Stree', category: 'Bollywood', hints: ['O Stree Kal Aana', 'Chanderi', 'Horror Comedy', 'Rajkummar', 'Ghost Woman'] },
    { word: 'Andhadhun', category: 'Bollywood', hints: ['Blind Pianist', 'Murder Witness', 'Twist Ending', 'Ayushmann', 'Sriram Raghavan'] },
    { word: 'Article 15', category: 'Bollywood', hints: ['Caste System', 'IPS Officer', 'Constitution', 'Ayushmann', 'Lalgaon'] },
    { word: 'Tanhaji', category: 'Bollywood', hints: ['Maratha Warrior', 'Kondhana Fort', 'Ajay Devgn', 'Shivaji', 'Night Attack'] },
    { word: 'Drishyam', category: 'Bollywood', hints: ['Murder Cover Up', 'Cable Operator', 'Ajay Devgn', 'Family Alibi', 'Missing Body'] },
    { word: 'Pathaan', category: 'Bollywood', hints: ['Spy Thriller', 'Besharam Rang', 'SRK Comeback', 'Jim', 'YRF Spy Universe'] },
    { word: 'Jawan', category: 'Bollywood', hints: ['Bald SRK', 'Metro Train', 'Atlee', 'Social Issues', 'Double Role'] },
    { word: 'Rocky Aur Rani', category: 'Bollywood', hints: ['Joint Family', 'KJo', 'Ranveer Alia', 'Dharmendra Shabana', 'Tum Kya Ho'] },
    { word: 'Animal', category: 'Bollywood', hints: ['Ranbir', 'Father Son', 'Dark', 'Sandeep Vanga', 'Bobby Deol Villain'] },
    { word: 'Gadar', category: 'Bollywood', hints: ['Hand Pump', 'Sunny Deol', 'Partition', 'Pakistan', 'Tara Singh'] },
    { word: '12th Fail', category: 'Bollywood', hints: ['UPSC', 'IPS', 'Vikrant Massey', 'True Story', 'Manoj Sharma'] },
    { word: 'Dhoom', category: 'Bollywood', hints: ['Bike Chase', 'John Abraham', 'Heist', 'Uday Chopra', 'YRF Action'] },
    { word: 'Race', category: 'Bollywood', hints: ['Saif Ali Khan', 'Twist', 'Abbas Mustan', 'Bipasha', 'Cars'] },
    { word: 'Golmaal', category: 'Bollywood', hints: ['Ajay Devgn', 'Comedy Gang', 'Rohit Shetty', 'Gopal Madhav', 'Ghost House'] },
    { word: 'Singham', category: 'Bollywood', hints: ['Aata Majhi Satakli', 'Cop', 'Ajay Devgn', 'Rohit Shetty', 'Goa Police'] },
    { word: 'Dabangg', category: 'Bollywood', hints: ['Chulbul Pandey', 'Salman', 'Belt', 'Sonakshi', 'Hud Hud'] },
    { word: 'Kick', category: 'Bollywood', hints: ['Salman', 'Devil', 'Jacqueline', 'Devi Lal', 'Jumme Ki Raat'] },
    { word: 'Sultan', category: 'Bollywood', hints: ['Wrestling', 'Salman', 'Haryana', 'Anushka', 'Sultan Ali Khan'] },
    { word: 'Tiger Zinda Hai', category: 'Bollywood', hints: ['Spy', 'Salman Katrina', 'RAW', 'ISI', 'Iraq Hostage'] },
    { word: 'Bajirao Mastani', category: 'Bollywood', hints: ['Peshwa', 'Maratha', 'Ranveer Deepika', 'Kashibai', 'Bhansali'] },
    { word: 'Raees', category: 'Bollywood', hints: ['Baniye Ka Dimaag', 'Bootlegger', 'Gujarat', 'SRK Pathani', 'Nawazuddin Cop'] },
    { word: 'Kahaani', category: 'Bollywood', hints: ['Pregnant Woman', 'Kolkata', 'Vidya Balan', 'Metro Gas', 'Bob Biswas'] },
    { word: 'Neerja', category: 'Bollywood', hints: ['Pan Am', 'Hijack', 'Sonam Kapoor', 'Brave Hostess', 'Karachi'] },
    { word: 'Toilet Ek Prem Katha', category: 'Bollywood', hints: ['Swachh Bharat', 'Open Defecation', 'Akshay', 'Village', 'Bathroom'] },
    { word: 'Bhool Bhulaiyaa', category: 'Bollywood', hints: ['Ami Je Tomar', 'Haveli Ghost', 'Akshay Dance', 'Manjulika', 'Psychiatrist'] },
    { word: 'Fukrey', category: 'Bollywood', hints: ['Jugaad', 'Delhi Boys', 'Choocha', 'Bholi Punjaban', 'Lottery'] },
    { word: 'Badhaai Ho', category: 'Bollywood', hints: ['Pregnant Mother', 'Ayushmann', 'Late Pregnancy', 'Embarrassment', 'Family'] },
    { word: 'Chhichhore', category: 'Bollywood', hints: ['College Flashback', 'Sushant', 'Losers', 'Engineering', 'Suicide Message'] },
    { word: 'Piku', category: 'Bollywood', hints: ['Deepika', 'Constipation', 'Road Trip', 'Kolkata', 'Amitabh Father'] },
    { word: 'Tamasha', category: 'Bollywood', hints: ['Corsica', 'Ranbir Deepika', 'Split Personality', 'Imtiaz Ali', 'Storyteller'] },
    { word: 'Ae Dil Hai Mushkil', category: 'Bollywood', hints: ['Unrequited Love', 'Ranbir Anushka', 'London', 'Karan Johar', 'Bulleya'] },
    { word: 'Dear Zindagi', category: 'Bollywood', hints: ['Therapy', 'Alia SRK', 'Goa', 'Mental Health', 'Gauri Shinde'] },
    { word: 'Raazi', category: 'Bollywood', hints: ['Spy Wife', 'Pakistan', 'Alia Vicky', 'Ae Watan', 'Meghna Gulzar'] },
    { word: 'Uri', category: 'Bollywood', hints: ['Surgical Strike', 'How Is The Josh', 'Vicky Kaushal', 'Army', 'Pakistan Border'] },
    { word: 'Bala', category: 'Bollywood', hints: ['Baldness', 'Ayushmann', 'Wig', 'Tik Tok', 'Bhumi'] },
    { word: 'Dream Girl', category: 'Bollywood', hints: ['Pooja Voice', 'Female Voice', 'Ayushmann', 'Helpline', 'Nushrratt'] },
    { word: 'Shershaah', category: 'Bollywood', hints: ['Captain Vikram', 'Kargil', 'Sidharth', 'Yeh Dil Maange', 'Dimple Cheema'] },
    { word: 'Sooryavanshi', category: 'Bollywood', hints: ['ATS', 'Akshay Cop', 'Rohit Shetty', 'Cop Universe', 'Mumbai Terror'] },
    { word: 'The Kashmir Files', category: 'Bollywood', hints: ['Pandit Exodus', 'Vivek Agnihotri', 'Anupam Kher', 'Genocide', 'Nineteen Ninety'] },
    { word: 'Gangubai Kathiawadi', category: 'Bollywood', hints: ['Alia', 'Kamathipura', 'Mafia Queen', 'Bhansali', 'White Sari'] },
    { word: 'Brahmastra', category: 'Bollywood', hints: ['Astraverse', 'Ranbir Alia', 'Shiva Fire', 'Ayan', 'Amitabh Guru'] },
    { word: 'Kantara', category: 'Bollywood', hints: ['Bhoota Kola', 'Karnataka', 'Rishab Shetty', 'Demigod', 'Forest Rights'] },
    { word: 'RRR', category: 'Bollywood', hints: ['Naatu Naatu', 'Ram Bheem', 'British Raj', 'Rajamouli', 'Oscar Song'] },
    { word: 'Pushpa', category: 'Bollywood', hints: ['Allu Arjun', 'Smuggling', 'Thaggede Le', 'Red Sandalwood', 'Srivalli'] },
    { word: 'KGF', category: 'Bollywood', hints: ['Yash', 'Gold Mine', 'Rocky Bhai', 'Karnataka', 'Mother Promise'] },
    { word: 'Munna Bhai MBBS', category: 'Bollywood', hints: ['Sanjay Dutt', 'Circuit', 'Jaadu Ki Jhappi', 'Fake Doctor', 'Medical College'] },
    { word: 'Dil To Pagal Hai', category: 'Bollywood', hints: ['Dance Troupe', 'SRK Madhuri', 'Someone Somewhere', 'Yash Chopra', 'Karisma'] },
    { word: 'Mohabbatein', category: 'Bollywood', hints: ['Gurukul', 'Violin', 'SRK Amitabh', 'Three Couples', 'Aditya Chopra'] },
    { word: 'Veer-Zaara', category: 'Bollywood', hints: ['India Pakistan', 'SRK Preity', 'Jail', 'Tere Liye', 'Yash Chopra'] },
    { word: 'Kal Ho Naa Ho', category: 'Bollywood', hints: ['New York', 'SRK Dying', 'Preity Saif', 'Diary', 'Pretty Woman'] },
    { word: 'My Name Is Khan', category: 'Bollywood', hints: ['Autism', 'SRK Kajol', 'America', 'Not Terrorist', 'San Francisco'] },
    { word: 'Dilwale', category: 'Bollywood', hints: ['SRK Kajol', 'Gerua Song', 'Bulgaria', 'Rohit Shetty', 'Car Action'] },
    { word: 'Happy New Year', category: 'Bollywood', hints: ['Heist Dance', 'Dubai', 'SRK Deepika', 'World Dance', 'Farah Khan'] },
    { word: 'Chennai Express', category: 'Bollywood', hints: ['SRK Deepika', 'South Indian', 'Train Comedy', 'Rohit Shetty', 'Lungi Dance'] },
    { word: 'Yeh Jawaani Hai Deewani', category: 'Bollywood', hints: ['Ranbir Deepika', 'Manali Trek', 'Naina', 'Badtameez Dil', 'Wedding'] },
    { word: 'Goliyon Ki Raasleela', category: 'Bollywood', hints: ['Ram Leela', 'Ranveer Deepika', 'Gujarat', 'Romeo Juliet', 'Bhansali'] },
    { word: 'Lootera', category: 'Bollywood', hints: ['Ranveer Sonakshi', 'Period Drama', 'Art Theft', 'Dalhousie', 'Vikramaditya'] },
    { word: 'Rockstar', category: 'Bollywood', hints: ['Ranbir', 'Sadda Haq', 'Jordan', 'Prague', 'Imtiaz Ali'] },
    { word: 'Maqbool', category: 'Bollywood', hints: ['Macbeth', 'Irrfan', 'Mumbai Underworld', 'Tabu', 'Vishal Bhardwaj'] },
    { word: 'Omkara', category: 'Bollywood', hints: ['Othello', 'Ajay Devgn', 'UP Politics', 'Langda Tyagi', 'Vishal Bhardwaj'] },
    { word: 'Haider', category: 'Bollywood', hints: ['Hamlet', 'Kashmir', 'Shahid', 'Bisma', 'Vishal Bhardwaj'] },
    { word: 'Gulaal', category: 'Bollywood', hints: ['Rajasthan Politics', 'Anurag Kashyap', 'Student', 'Ranaji', 'Dark Thriller'] },
    { word: 'Dev D', category: 'Bollywood', hints: ['Modern Devdas', 'Abhay Deol', 'Anurag Kashyap', 'Paro Chanda', 'Emotional Attyachar'] },
    { word: 'Oye Lucky Lucky Oye', category: 'Bollywood', hints: ['Abhay Deol', 'Con Man', 'Delhi', 'True Story', 'Dibakar'] },
    { word: 'Udaan', category: 'Bollywood', hints: ['Strict Father', 'Jamshedpur', 'Rajat Barmecha', 'Vikramaditya', 'Teen Runaway'] },
    { word: 'Gangs of Wasseypur 2', category: 'Bollywood', hints: ['Faizal', 'Perpendicular', 'Definite', 'Nawazuddin', 'Finale'] },
    { word: 'Masaan', category: 'Bollywood', hints: ['Varanasi', 'Cremation Ghat', 'Vicky Kaushal', 'Caste Love', 'Neeraj Ghaywan'] },
    { word: 'Newton', category: 'Bollywood', hints: ['Election Duty', 'Rajkummar', 'Naxal Area', 'Democracy', 'Chhattisgarh'] },
    { word: 'Mukkabaaz', category: 'Bollywood', hints: ['Boxing', 'Anurag Kashyap', 'UP', 'Caste', 'Bareilly'] },
    { word: 'Super 30', category: 'Bollywood', hints: ['Anand Kumar', 'IIT Coaching', 'Hrithik', 'Patna', 'Free Classes'] },
    { word: 'Thappad', category: 'Bollywood', hints: ['Slap', 'Taapsee', 'Divorce', 'Marriage', 'One Slap Enough'] },
    { word: 'Ludo', category: 'Bollywood', hints: ['Multi Story', 'Anurag Basu', 'Pankaj Tripathi', 'Interconnected', 'Dark Comedy'] },
    { word: 'Raat Akeli Hai', category: 'Bollywood', hints: ['Murder Mystery', 'Nawazuddin', 'Radhika Apte', 'Haveli', 'Kanpur'] },
    { word: 'Mimi', category: 'Bollywood', hints: ['Surrogacy', 'Kriti Sanon', 'Rajasthan', 'American Couple', 'Pankaj Tripathi'] },
    { word: 'Sardar Udham', category: 'Bollywood', hints: ['Jallianwala Bagh', 'Vicky Kaushal', 'Freedom Fighter', 'London Assassination', 'Shoojit Sircar'] },
    { word: 'Gehraiyaan', category: 'Bollywood', hints: ['Deepika', 'Affair', 'Alibaug', 'Shakun Batra', 'Relationship Drama'] },
    { word: 'Darlings', category: 'Bollywood', hints: ['Alia', 'Domestic Violence', 'Dark Comedy', 'Vijay Varma', 'Mumbai Basti'] },
    { word: 'Monica O My Darling', category: 'Bollywood', hints: ['Rajkummar', 'Robot', 'Murder Plan', 'Noir Comedy', 'Vasan Bala'] },
    { word: 'An Action Hero', category: 'Bollywood', hints: ['Ayushmann', 'London Chase', 'Actor On Run', 'Jaideep Ahlawat', 'Satire'] },
    { word: 'Ek Villain', category: 'Bollywood', hints: ['Sidharth Shraddha', 'Serial Killer', 'Galliyan Song', 'Riteish', 'Mohit Suri'] },
    { word: 'Badlapur', category: 'Bollywood', hints: ['Varun Dhawan', 'Revenge', 'Dark Role', 'Sriram Raghavan', 'Nawazuddin'] },
    { word: 'Raanjhanaa', category: 'Bollywood', hints: ['Dhanush', 'Varanasi', 'Sonam Kapoor', 'One Sided Love', 'Aanand Rai'] },
    // ── Actors / Actresses ──────────────────────────────────────
    { word: 'Salman Khan', category: 'Bollywood', hints: ['Bhai', 'Being Human', 'Dabangg', 'Bodyguard', 'Tiger'] },
    { word: 'Aamir Khan', category: 'Bollywood', hints: ['Mr Perfectionist', 'Dangal', 'PK', 'Ghajini', 'Satyamev Jayate'] },
    { word: 'Akshay Kumar', category: 'Bollywood', hints: ['Khiladi', 'Canadian', 'Patriotic Films', 'Martial Arts', 'Toilet'] },
    { word: 'Hrithik Roshan', category: 'Bollywood', hints: ['Greek God', 'Krrish', 'Extra Thumb', 'War', 'Jadoo'] },
    { word: 'Ranbir Kapoor', category: 'Bollywood', hints: ['Kapoor Dynasty', 'Saawariya', 'Alia Husband', 'Rockstar Jordan', 'Animal'] },
    { word: 'Deepika Padukone', category: 'Bollywood', hints: ['Padmaavat', 'Ranveer Wife', 'Piku', 'Om Shanti Om', 'Mastani'] },
    { word: 'Priyanka Chopra', category: 'Bollywood', hints: ['Desi Girl', 'Miss World', 'Quantico', 'Nick Jonas', 'Baywatch'] },
    { word: 'Katrina Kaif', category: 'Bollywood', hints: ['Sheila', 'Vicky Wife', 'Tiger Zinda', 'Chikni Chameli', 'British Born'] },
    { word: 'Kareena Kapoor', category: 'Bollywood', hints: ['Bebo', 'Poo', 'Size Zero', 'Jab We Met Geet', 'Saif Wife'] },
    { word: 'Aishwarya Rai', category: 'Bollywood', hints: ['Miss World', 'Green Eyes', 'Devdas Paro', 'Cannes', 'Bachchan Bahu'] },
    { word: 'Kajol', category: 'Bollywood', hints: ['Simran', 'Unibrow', 'DDLJ', 'Ajay Wife', 'Fanaa'] },
    { word: 'Vidya Balan', category: 'Bollywood', hints: ['Kahaani', 'Dirty Picture', 'Silk Smitha', 'Shakuntala Devi', 'Saree'] },
    { word: 'Anushka Sharma', category: 'Bollywood', hints: ['Band Baaja', 'Virat Wife', 'NH10', 'Sui Dhaaga', 'Clean Slate'] },
    { word: 'Varun Dhawan', category: 'Bollywood', hints: ['David Dhawan Son', 'Student Of Year', 'Judwaa 2', 'Badlapur', 'Coolie No 1'] },
    { word: 'Ayushmann Khurrana', category: 'Bollywood', hints: ['Vicky Donor', 'Andhadhun', 'Bala', 'Dream Girl', 'Social Films'] },
    { word: 'Rajkummar Rao', category: 'Bollywood', hints: ['Stree', 'Newton', 'Trapped', 'Bareilly Ki Barfi', 'Method Actor'] },
    { word: 'Vicky Kaushal', category: 'Bollywood', hints: ['Uri Josh', 'Masaan', 'Katrina Husband', 'Sardar Udham', 'Sam Bahadur'] },
    { word: 'Kartik Aaryan', category: 'Bollywood', hints: ['Monologue', 'Bhool Bhulaiyaa 2', 'Sonu Ke Titu', 'Dhamaka', 'Love Aaj Kal'] },
    { word: 'Tiger Shroff', category: 'Bollywood', hints: ['Baaghi', 'Flying Kick', 'Jackie Son', 'Heropanti', 'Flexible'] },
    { word: 'Shahid Kapoor', category: 'Bollywood', hints: ['Kabir Singh', 'Haider', 'Jab We Met', 'Kaminey', 'Mira Wife'] },
    { word: 'Ajay Devgn', category: 'Bollywood', hints: ['Split Bikes', 'Singham', 'Phool Aur Kaante', 'Golmaal', 'Pan Masala'] },
    { word: 'Govinda', category: 'Bollywood', hints: ['Chi Chi', 'Hero No 1', 'Partner', 'Meri Pant Bhi Sexy', 'David Dhawan'] },
    { word: 'Sridevi', category: 'Bollywood', hints: ['Hawa Hawaii', 'English Vinglish', 'Chandni', 'Naagin', 'Boney Wife'] },
    { word: 'Rekha', category: 'Bollywood', hints: ['Umrao Jaan', 'Silsila', 'Sindoor', 'Khoobsurat', 'Kangana'] },
    { word: 'Hema Malini', category: 'Bollywood', hints: ['Dream Girl', 'Basanti', 'Sholay', 'Dharmendra Wife', 'Mathura MP'] },
    { word: 'Dharmendra', category: 'Bollywood', hints: ['He Man', 'Veeru', 'Sholay', 'Hema Husband', 'Sunny Father'] },
    { word: 'Rajesh Khanna', category: 'Bollywood', hints: ['First Superstar', 'Kaka', 'Anand', 'Mere Sapno Ki', 'Aradhana'] },
    { word: 'Dev Anand', category: 'Bollywood', hints: ['Evergreen', 'Guide', 'Puffed Hair', 'Navketan', 'Gregory Peck'] },
    { word: 'Dilip Kumar', category: 'Bollywood', hints: ['Tragedy King', 'Mughal-e-Azam', 'Yusuf Khan', 'Method Acting', 'Nargis Pair'] },
    { word: 'Raj Kapoor', category: 'Bollywood', hints: ['Showman', 'Tramp', 'RK Studios', 'Awaara', 'Mera Naam Joker'] },
    { word: 'Shammi Kapoor', category: 'Bollywood', hints: ['Yahoo', 'Elvis Of India', 'Kashmir Ki Kali', 'Junglee', 'Kapoor Family'] },
    { word: 'Meena Kumari', category: 'Bollywood', hints: ['Tragedy Queen', 'Pakeezah', 'Sahib Bibi Aur Ghulam', 'Poet', 'Kamal Amrohi'] },
    { word: 'Nargis', category: 'Bollywood', hints: ['Mother India', 'Sunil Dutt Wife', 'Sanjay Mother', 'Raj Kapoor Pair', 'Awaara'] },
    { word: 'Waheeda Rehman', category: 'Bollywood', hints: ['Guide Rosie', 'Pyaasa', 'Graceful', 'CID', 'Guru Dutt'] },
    { word: 'Naseeruddin Shah', category: 'Bollywood', hints: ['Parallel Cinema', 'Sparsh', 'Albert Pinto', 'Ratna Pathak', 'Iqbal'] },
    { word: 'Om Puri', category: 'Bollywood', hints: ['Ardh Satya', 'East Is East', 'City Of Joy', 'Jaane Bhi Do', 'Parallel Cinema'] },
    { word: 'Nawazuddin Siddiqui', category: 'Bollywood', hints: ['Faizal Khan', 'Sacred Games', 'Manto', 'Ganesh Gaitonde', 'Budhana'] },
    { word: 'Manoj Bajpayee', category: 'Bollywood', hints: ['Satya Bhiku', 'Family Man', 'Gangs', 'Bihar', 'Bandit Queen'] },
    { word: 'Pankaj Tripathi', category: 'Bollywood', hints: ['Mirzapur Kaleen', 'Stree', 'Mimi', 'Bihar', 'Scene Stealer'] },
    { word: 'Tabu', category: 'Bollywood', hints: ['Drishyam', 'Andhadhun', 'Maqbool', 'Haider', 'Ageless Beauty'] },
    { word: 'Rani Mukerji', category: 'Bollywood', hints: ['Mardaani', 'Black', 'Hichki', 'Aditya Chopra Wife', 'Bunty Babli'] },
    { word: 'Preity Zinta', category: 'Bollywood', hints: ['Dimples', 'Kal Ho Naa Ho', 'Veer-Zaara', 'KXIP', 'Dil Se'] },
    { word: 'Juhi Chawla', category: 'Bollywood', hints: ['Qayamat Se', 'Miss India', 'Darr', 'SRK Pair', 'KKR Co-Owner'] },
    { word: 'Karisma Kapoor', category: 'Bollywood', hints: ['Lolo', 'Dil To Pagal', 'Raja Hindustani', 'Kapoor Sisters', 'Fiza'] },
    { word: 'Sushmita Sen', category: 'Bollywood', hints: ['Miss Universe', 'Aarya', 'Main Hoon Na', 'Adoption', 'Bengali Beauty'] },
    { word: 'Kangana Ranaut', category: 'Bollywood', hints: ['Queen Rani', 'Tanu Weds Manu', 'Controversy', 'Manikarnika', 'Fashion'] },
    { word: 'Shraddha Kapoor', category: 'Bollywood', hints: ['Aashiqui 2', 'Stree', 'Ek Villain', 'Half Girlfriend', 'Shakti Kapoor'] },
    { word: 'Kriti Sanon', category: 'Bollywood', hints: ['Mimi', 'Luka Chuppi', 'Bareilly Ki Barfi', 'Heropanti', 'Adipurush'] },
    { word: 'Janhvi Kapoor', category: 'Bollywood', hints: ['Sridevi Daughter', 'Dhadak', 'Gunjan Saxena', 'Boney Daughter', 'Mili'] },
    { word: 'Sara Ali Khan', category: 'Bollywood', hints: ['Namaste Darshako', 'Kedarnath', 'Atrangi Re', 'Saif Daughter', 'Columbia'] },
    { word: 'Kiara Advani', category: 'Bollywood', hints: ['Kabir Singh Preeti', 'Shershaah', 'Good Newwz', 'Sidharth Wife', 'Lust Stories'] },
    { word: 'Sidharth Malhotra', category: 'Bollywood', hints: ['Student Of Year', 'Shershaah', 'Kiara Husband', 'Captain Vikram', 'Mission Majnu'] },
    { word: 'Sanjay Dutt', category: 'Bollywood', hints: ['Munna Bhai', 'Khalnayak', 'Nargis Son', 'Jail Time', 'Drugs'] },
    { word: 'Jackie Shroff', category: 'Bollywood', hints: ['Bhidu', 'Hero', 'Tiger Father', 'Rangeela', 'Pardes'] },
    { word: 'Anil Kapoor', category: 'Bollywood', hints: ['Jhakaas', 'Mr India', 'Slumdog', 'Forever Young', 'Sonam Father'] },
    { word: 'Sunny Deol', category: 'Bollywood', hints: ['Dhai Kilo Haath', 'Gadar', 'Damini', 'Border', 'Dharmendra Son'] },
    { word: 'Bobby Deol', category: 'Bollywood', hints: ['Barsaat', 'Animal Villain', 'Comeback', 'Soldier', 'Dharmendra Son'] },
    { word: 'Rishi Kapoor', category: 'Bollywood', hints: ['Bobby', 'Kapoor And Sons', 'Chocolate Hero', 'Neetu Husband', 'Om Tera Naam'] },
    { word: 'Saif Ali Khan', category: 'Bollywood', hints: ['Nawab', 'Dil Chahta Hai', 'Taimur Father', 'Omkara Langda', 'Sacred Games'] },
    { word: 'John Abraham', category: 'Bollywood', hints: ['Dhoom Bike', 'Fitness', 'Batla House', 'Force', 'Bipasha Ex'] },
    { word: 'Abhishek Bachchan', category: 'Bollywood', hints: ['Junior B', 'Guru', 'Dhoom', 'Aishwarya Husband', 'Manmarziyaan'] },
    { word: 'Emraan Hashmi', category: 'Bollywood', hints: ['Serial Kisser', 'Aashiqui 2', 'Murder', 'Jannat', 'Hashmi Clan'] },
    // ── Directors / Producers ───────────────────────────────────
    { word: 'Rajkumar Hirani', category: 'Bollywood', hints: ['Three Idiots', 'Munna Bhai', 'PK', 'Sanju', 'Feel Good'] },
    { word: 'Zoya Akhtar', category: 'Bollywood', hints: ['Gully Boy', 'Dil Dhadakne Do', 'ZNMD', 'Archie Comics', 'Akhtar Family'] },
    { word: 'Imtiaz Ali', category: 'Bollywood', hints: ['Jab We Met', 'Rockstar', 'Highway', 'Love Aaj Kal', 'Tamasha'] },
    { word: 'Vishal Bhardwaj', category: 'Bollywood', hints: ['Shakespeare', 'Haider', 'Omkara', 'Maqbool', 'Dark Films'] },
    { word: 'Ashutosh Gowariker', category: 'Bollywood', hints: ['Lagaan', 'Jodhaa Akbar', 'Swades', 'Period Drama', 'Epic'] },
    { word: 'Ram Gopal Varma', category: 'Bollywood', hints: ['Satya', 'Rangeela', 'Sarkar', 'Underworld', 'Controversy'] },
    { word: 'Mani Ratnam', category: 'Bollywood', hints: ['Bombay', 'Roja', 'Dil Se', 'Tamil Cinema', 'Ponniyin Selvan'] },
    { word: 'Farah Khan', category: 'Bollywood', hints: ['Om Shanti Om', 'Main Hoon Na', 'Choreographer', 'Happy New Year', 'SRK Films'] },
    { word: 'Aditya Chopra', category: 'Bollywood', hints: ['DDLJ', 'Yash Raj', 'Rani Husband', 'Reclusive', 'Rab Ne'] },
    { word: 'Subhash Ghai', category: 'Bollywood', hints: ['Showman', 'Taal', 'Pardes', 'Khalnayak', 'Mukta Arts'] },
    { word: 'Vidhu Vinod Chopra', category: 'Bollywood', hints: ['Three Idiots Producer', 'Parinda', 'Mission Kashmir', 'Lage Raho', 'Shikara'] },
    { word: 'Prakash Jha', category: 'Bollywood', hints: ['Gangaajal', 'Raajneeti', 'Apharan', 'Bihar Politics', 'Aarakshan'] },
    { word: 'Shoojit Sircar', category: 'Bollywood', hints: ['Piku', 'Vicky Donor', 'October', 'Gulabo Sitabo', 'Slice Of Life'] },
    { word: 'Aanand L Rai', category: 'Bollywood', hints: ['Tanu Weds Manu', 'Raanjhanaa', 'Atrangi Re', 'Zero', 'Small Town'] },
    { word: 'Sriram Raghavan', category: 'Bollywood', hints: ['Andhadhun', 'Badlapur', 'Agent Vinod', 'Thriller', 'Johnny Gaddar'] },
    { word: 'Neeraj Pandey', category: 'Bollywood', hints: ['A Wednesday', 'Baby', 'Special 26', 'MS Dhoni Biopic', 'Thriller'] },
    { word: 'Tigmanshu Dhulia', category: 'Bollywood', hints: ['Paan Singh Tomar', 'Saheb Biwi Gangster', 'Haasil', 'Dacoit', 'Rustic'] },
    { word: 'Dibakar Banerjee', category: 'Bollywood', hints: ['Oye Lucky', 'Khosla Ka Ghosla', 'Shanghai', 'Love Sex Dhokha', 'Indie'] },
    { word: 'Vikramaditya Motwane', category: 'Bollywood', hints: ['Udaan', 'Lootera', 'Sacred Games', 'Trapped', 'Phantom'] },
    { word: 'S S Rajamouli', category: 'Bollywood', hints: ['Baahubali', 'RRR', 'Telugu Epic', 'Visual Effects', 'Eega'] },
    // ── Iconic Songs ────────────────────────────────────────────
    { word: 'Chaiyya Chaiyya', category: 'Bollywood', hints: ['Train Roof', 'Dil Se', 'SRK Dance', 'Sukhwinder', 'Rahman'] },
    { word: 'Jai Ho', category: 'Bollywood', hints: ['Slumdog', 'Oscar Winner', 'Rahman', 'Anthem', 'Pussycat Dolls'] },
    { word: 'Tujhe Dekha Toh', category: 'Bollywood', hints: ['DDLJ', 'Mustard Fields', 'SRK Kajol', 'Kumar Sanu', 'Romantic'] },
    { word: 'Munni Badnaam', category: 'Bollywood', hints: ['Dabangg', 'Malaika', 'Item Song', 'Salman', 'Dance Floor'] },
    { word: 'Sheila Ki Jawani', category: 'Bollywood', hints: ['Tees Maar Khan', 'Katrina', 'Item Number', 'Party Song', 'Sunidhi'] },
    { word: 'Kajra Re', category: 'Bollywood', hints: ['Bunty Babli', 'Aishwarya', 'Amitabh Dance', 'Alisha Chinai', 'Shankar Ehsaan'] },
    { word: 'Choli Ke Peeche', category: 'Bollywood', hints: ['Khalnayak', 'Madhuri', 'Controversial', 'Ila Arun', 'Nineties'] },
    { word: 'Dil Se Re', category: 'Bollywood', hints: ['Dil Se', 'Rahman', 'Patriotic', 'Train', 'SRK Manisha'] },
    { word: 'Rang Barse', category: 'Bollywood', hints: ['Silsila', 'Holi Song', 'Amitabh', 'Festival', 'Classic'] },
    { word: 'Mere Sapno Ki Rani', category: 'Bollywood', hints: ['Aradhana', 'Jeep Song', 'Rajesh Khanna', 'Kishore Kumar', 'Sixties'] },
    { word: 'Aaj Ki Raat', category: 'Bollywood', hints: ['Don', 'Helen', 'Cabaret', 'Amitabh', 'Nightclub'] },
    { word: 'Badtameez Dil', category: 'Bollywood', hints: ['Yeh Jawaani', 'Ranbir', 'Party', 'Benny Dayal', 'Dance'] },
    { word: 'Lungi Dance', category: 'Bollywood', hints: ['Chennai Express', 'Rajinikanth Tribute', 'SRK Deepika', 'Honey Singh', 'South'] },
    { word: 'Balam Pichkari', category: 'Bollywood', hints: ['Yeh Jawaani', 'Holi', 'Ranbir Deepika', 'Vishal Dadlani', 'Colors'] },
    { word: 'Gallan Goodiyaan', category: 'Bollywood', hints: ['Dil Dhadakne Do', 'Family Dance', 'Ship', 'Shankar Mahadevan', 'Ensemble'] },
    { word: 'Kar Gayi Chull', category: 'Bollywood', hints: ['Kapoor And Sons', 'Alia', 'Party Hit', 'Badshah', 'Rooftop'] },
    { word: 'London Thumakda', category: 'Bollywood', hints: ['Queen', 'Kangana', 'Wedding Song', 'Labh Janjua', 'Dance Floor'] },
    { word: 'Baby Doll', category: 'Bollywood', hints: ['Ragini MMS', 'Sunny Leone', 'Meet Bros', 'Kanika Kapoor', 'Club Hit'] },
    { word: 'Cheap Thrills Remix', category: 'Bollywood', hints: ['Sia', 'Bollywood Mix', 'DJ', 'Viral', 'Indo Western'] },
    { word: 'Desi Girl', category: 'Bollywood', hints: ['Dostana', 'Priyanka', 'Vishal Shekhar', 'Beach', 'John Abhishek'] },
    { word: 'Chammak Challo', category: 'Bollywood', hints: ['Ra One', 'SRK', 'Akon Feature', 'Kareena', 'Party'] },
    { word: 'Gerua', category: 'Bollywood', hints: ['Dilwale', 'SRK Kajol', 'Iceland Shot', 'Arijit', 'Romantic Ballad'] },
    { word: 'Tera Ban Jaunga', category: 'Bollywood', hints: ['Kabir Singh', 'Akhil Tulsi', 'Love Ballad', 'Shahid Kiara', 'Slow Dance'] },
    { word: 'Makhna', category: 'Bollywood', hints: ['Drive', 'Tanishk', 'Sushant', 'Jacqueline', 'Catchy Hook'] },
    { word: 'Ghungroo', category: 'Bollywood', hints: ['War', 'Hrithik Vaani', 'Arijit Shilpa', 'Beach Dance', 'Party Banger'] },
    { word: 'Apna Time Aayega', category: 'Bollywood', hints: ['Gully Boy', 'Ranveer Rap', 'Divine', 'Mumbai Slums', 'Anthem'] },
    { word: 'Ek Ladki Ko Dekha', category: 'Bollywood', hints: ['1942 Love Story', 'Kumar Sanu', 'Anil Kapoor', 'Romantic', 'Nineties Classic'] },
    { word: 'Maahi Ve', category: 'Bollywood', hints: ['Kal Ho Naa Ho', 'SRK Preity', 'Wedding Anthem', 'Udit Narayan', 'Dance'] },
    { word: 'Koi Mil Gaya Title Song', category: 'Bollywood', hints: ['Hrithik', 'Alien Jadoo', 'Preity', 'Idhar Chala', 'Koi Mil Gaya'] },
    { word: 'Ek Pal Ka Jeena', category: 'Bollywood', hints: ['Kaho Naa Pyaar Hai', 'Hrithik Debut', 'Lucky Ali', 'Party Number', 'Two Thousand'] },
    // ── Bollywood Tropes / Terms ────────────────────────────────
    { word: 'Hero Entry', category: 'Bollywood', hints: ['Slow Motion', 'Whistle', 'Background Music', 'Dramatic', 'Mass Scene'] },
    { word: 'Rain Dance', category: 'Bollywood', hints: ['Wet Saree', 'Romance', 'Monsoon', 'White Shirt', 'Tip Tip Barsa'] },
    { word: 'Swiss Alps Song', category: 'Bollywood', hints: ['DDLJ', 'Yash Chopra', 'Snow Mountains', 'Europe Trip', 'Saree In Cold'] },
    { word: 'Villain Laugh', category: 'Bollywood', hints: ['Evil Plan', 'Muahahaha', 'Shakaal', 'Mogambo', 'Den Scene'] },
    { word: 'Six Pack Reveal', category: 'Bollywood', hints: ['Shirt Off', 'Transformation', 'Training Montage', 'Hrithik', 'Beach Scene'] },
    { word: 'Filmi Maa', category: 'Bollywood', hints: ['Nirupa Roy', 'Sacrifice', 'Temple Prayers', 'Crying', 'Mere Bete'] },
    { word: 'Gaana Bajao', category: 'Bollywood', hints: ['Dance Break', 'Sangeet', 'DJ Drop', 'Party Start', 'Mehfil'] },
    { word: 'Censor Board', category: 'Bollywood', hints: ['Cuts', 'Certification', 'Pahlaj', 'UA Rating', 'Beep Sound'] },
    { word: 'Masala Film', category: 'Bollywood', hints: ['Action Comedy Romance', 'Everything Mixed', 'Entertainer', 'Rohit Shetty', 'Mass'] },
    { word: 'Comeback Film', category: 'Bollywood', hints: ['Second Innings', 'Reinvention', 'After Flops', 'Career Revival', 'Surprise Hit'] },
    { word: 'Remake', category: 'Bollywood', hints: ['South Copy', 'Korean Adaptation', 'Same Story', 'Rights Bought', 'Drishyam'] },
    { word: 'Sequel', category: 'Bollywood', hints: ['Part Two', 'Franchise', 'Returns', 'Dhoom', 'Golmaal Again'] },
    { word: 'Box Office Flop', category: 'Bollywood', hints: ['Disaster', 'No Audience', 'Budget Lost', 'Empty Theatres', 'Bombed'] },
    { word: 'Blockbuster', category: 'Bollywood', hints: ['Superhit', 'Houseful', 'Record Breaking', 'Collection', 'Mass Appeal'] },
    { word: 'Hundred Crore Club', category: 'Bollywood', hints: ['Milestone', 'Box Office', 'Collection Race', 'Trade Analysts', 'Opening Weekend'] },
    { word: 'Nepotism Debate', category: 'Bollywood', hints: ['Kangana', 'Koffee With Karan', 'Insider Outsider', 'Star Kids', 'Bollywood Mafia'] },
    { word: 'Star Kid', category: 'Bollywood', hints: ['Famous Parents', 'Launch', 'Nepo Baby', 'Debut Film', 'Legacy'] },
    { word: 'Film City', category: 'Bollywood', hints: ['Goregaon', 'Mumbai Sets', 'Shooting Location', 'Studio', 'Dadasaheb'] },
    { word: 'Filmfare Award', category: 'Bollywood', hints: ['Black Lady', 'Ceremony', 'Best Actor', 'Magazine', 'Annual'] },
    { word: 'National Award', category: 'Bollywood', hints: ['President Gives', 'Dadasaheb Phalke', 'Best Film', 'Government', 'Merit'] },
    { word: 'Red Carpet', category: 'Bollywood', hints: ['Premiere Night', 'Designer Outfit', 'Celebrity Arrival', 'Cameras', 'Fashion'] },
    { word: 'Screen Test', category: 'Bollywood', hints: ['Audition', 'Camera Presence', 'Acting Test', 'Casting', 'New Face'] },
    { word: 'Casting Couch', category: 'Bollywood', hints: ['Dark Side', 'MeToo', 'Exploitation', 'Industry Secret', 'Power Abuse'] },
    { word: 'Paparazzi', category: 'Bollywood', hints: ['Airport Look', 'Papped', 'Viral Pic', 'Stalking Stars', 'Shutterbugs'] },
    { word: 'Khan Wars', category: 'Bollywood', hints: ['SRK Salman Aamir', 'Rivalry', 'Clash Friday', 'Fan Fight', 'Three Khans'] },
    { word: 'Friday Release', category: 'Bollywood', hints: ['Opening Day', 'First Show', 'Collection Start', 'New Movie', 'Theatre Rush'] },
    { word: 'OTT Release', category: 'Bollywood', hints: ['Netflix', 'Hotstar', 'Skip Theatre', 'Digital Premiere', 'Streaming'] },
    { word: 'Pan-India Film', category: 'Bollywood', hints: ['All Languages', 'RRR Baahubali', 'Dubbed Release', 'Cross Border', 'National Appeal'] },
    { word: 'Dubbed Version', category: 'Bollywood', hints: ['South Film Hindi', 'Voice Over', 'Lip Sync', 'Regional Language', 'Translation'] },
    { word: 'Dream Sequence', category: 'Bollywood', hints: ['Fantasy Scene', 'Fog Machine', 'White Dress', 'Slow Motion', 'Garden Dancing'] },
    { word: 'Flashback Scene', category: 'Bollywood', hints: ['Blur Transition', 'Past Reveal', 'Memory', 'Young Version', 'Sepia Tone'] },
    { word: 'Love Triangle', category: 'Bollywood', hints: ['Three People', 'Confusion', 'Dil To Pagal', 'Who She Picks', 'Best Friend'] },
    { word: 'Rich Girl Poor Boy', category: 'Bollywood', hints: ['Class Divide', 'Father Objects', 'DDLJ', 'Love Conquers', 'Big Haveli'] },
    { word: 'NRI Return', category: 'Bollywood', hints: ['Foreign Return', 'Desi Values', 'Namaste India', 'Coming Home', 'Swades'] },
    { word: 'Family Drama', category: 'Bollywood', hints: ['Joint Family', 'Wedding', 'Emotions', 'Hum Saath Saath', 'Karan Johar'] },
    { word: 'Revenge Story', category: 'Bollywood', hints: ['Badla', 'Villain Payback', 'Eye For Eye', 'Father Killed', 'Justice'] },
    { word: 'Lost Twin', category: 'Bollywood', hints: ['Separated At Birth', 'Double Role', 'Mela Mein', 'Identical', 'Seeta Aur Geeta'] },
    { word: 'Maa Ka Aashirvaad', category: 'Bollywood', hints: ['Mother Blessing', 'Temple Scene', 'Emotional', 'Departure', 'Tilak'] },
    { word: 'Dushmani', category: 'Bollywood', hints: ['Rivalry', 'Family Feud', 'Badle Ki Aag', 'Enemy', 'Villain Origin'] },
    { word: 'Court Scene', category: 'Bollywood', hints: ['Tareekh Pe Tareekh', 'Lawyer Drama', 'Order Order', 'Witness', 'Jolly LLB'] },
    { word: 'Hospital Scene', category: 'Bollywood', hints: ['Operation Theatre', 'Life Support', 'Last Words', 'Doctor Save', 'Green Light'] },
    { word: 'Mandir Scene', category: 'Bollywood', hints: ['Temple Prayer', 'Aarti', 'Bhagwan Promise', 'Devotion', 'Diya Lighting'] },
    // ── Music Directors / Composers ─────────────────────────────
    { word: 'A R Rahman', category: 'Bollywood', hints: ['Oscar Winner', 'Jai Ho', 'Roja', 'Mozart Of Madras', 'Maa Tujhe Salaam'] },
    { word: 'R D Burman', category: 'Bollywood', hints: ['Pancham Da', 'Mouth Organ', 'Asha Bhosle', 'Sholay', 'Dum Maro Dum'] },
    { word: 'Lata Mangeshkar', category: 'Bollywood', hints: ['Nightingale', 'Ae Mere Watan', 'Didi', 'Thousand Songs', 'Bharat Ratna'] },
    { word: 'Kishore Kumar', category: 'Bollywood', hints: ['Yodeling', 'Roop Tera Mastana', 'Mere Sapno Ki Rani', 'Playful Voice', 'Golden Era'] },
    { word: 'Arijit Singh', category: 'Bollywood', hints: ['Tum Hi Ho', 'Sad Songs King', 'Channa Mereya', 'Soulful Voice', 'Bollywood Playback'] },
    { word: 'Shreya Ghoshal', category: 'Bollywood', hints: ['Devdas', 'Bairi Piya', 'Classical Trained', 'Sweet Voice', 'National Award'] },
    { word: 'Pritam', category: 'Bollywood', hints: ['Ae Dil Hai Mushkil', 'Barfi', 'Jab We Met', 'Hit Machine', 'Anurag Basu'] },
    { word: 'Vishal-Shekhar', category: 'Bollywood', hints: ['Om Shanti Om', 'Desi Girl', 'Duo', 'War', 'Chennai Express'] },
    { word: 'Shankar-Ehsaan-Loy', category: 'Bollywood', hints: ['Dil Chahta Hai', 'Trio', 'Kal Ho Naa Ho', 'Rock On', 'ZNMD'] },
    { word: 'Amit Trivedi', category: 'Bollywood', hints: ['Dev D', 'Udta Punjab', 'Queen', 'Lootera', 'Indie Sound'] },
    { word: 'Anu Malik', category: 'Bollywood', hints: ['Indian Idol Judge', 'Copied Tunes', 'Border', 'Baazigar', 'Nineties Hits'] },
    { word: 'Himesh Reshammiya', category: 'Bollywood', hints: ['Nasal Voice', 'Cap', 'Aashiq Banaya', 'Suroor', 'Tera Suroor'] },
    { word: 'Badshah', category: 'Bollywood', hints: ['Rapper', 'Kar Gayi Chull', 'Genda Phool', 'Party Songs', 'Paagal'] },
    { word: 'Honey Singh', category: 'Bollywood', hints: ['Lungi Dance', 'Brown Rang', 'Chaar Botal', 'Rapper Singer', 'Comeback'] },
    { word: 'Diljit Dosanjh', category: 'Bollywood', hints: ['Punjabi Star', 'Good Newwz', 'Coachella', 'Turban', 'Lover'] },
    { word: 'Neha Kakkar', category: 'Bollywood', hints: ['Party Songs', 'Indian Idol', 'Dilbar', 'O Saki Saki', 'Social Media'] },
    { word: 'Kumar Sanu', category: 'Bollywood', hints: ['Nineties Romance', 'Tujhe Dekha Toh', 'Golden Voice', 'Melody King', 'Sadabahar'] },
    { word: 'Udit Narayan', category: 'Bollywood', hints: ['Papa Kehte Hain', 'SRK Voice', 'Lagaan Song', 'Bihari', 'DDLJ'] },
    { word: 'Sonu Nigam', category: 'Bollywood', hints: ['Kal Ho Naa Ho', 'Versatile', 'Stage Performer', 'Suraj Hua Maddham', 'Ab Mujhe Raat Din'] },
    { word: 'Sunidhi Chauhan', category: 'Bollywood', hints: ['Sheila', 'Dhoom Machale', 'Powerful Voice', 'Crazy Kiya Re', 'Kamli'] },
    // ── Iconic Dialogues (short) ────────────────────────────────
    { word: 'Kitne Aadmi The', category: 'Bollywood', hints: ['Sholay', 'Gabbar Singh', 'Thakur', 'Dacoits', 'Opening Line'] },
    { word: 'Mogambo Khush Hua', category: 'Bollywood', hints: ['Mr India', 'Amrish Puri', 'Villain Dialogue', 'Happy Villain', 'Invisible Man'] },
    { word: 'Rishte Mein Hum Tumhare', category: 'Bollywood', hints: ['Hum Aapke Hain Koun', 'Salman', 'Baap Lage', 'Family Film', 'Sooraj Barjatya'] },
    { word: 'Ja Simran Ja', category: 'Bollywood', hints: ['DDLJ', 'Amrish Father', 'SRK Kajol', 'Train Platform', 'Climax'] },
    { word: 'Picture Abhi Baaki Hai', category: 'Bollywood', hints: ['Om Shanti Om', 'SRK', 'Life Circle', 'Filmy Dialogue', 'Mere Dost'] },
    { word: 'Mere Paas Maa Hai', category: 'Bollywood', hints: ['Deewar', 'Amitabh Shashi', 'Brothers', 'What You Have', 'Emotional'] },
    { word: 'Ek Chutki Sindoor', category: 'Bollywood', hints: ['Om Shanti Om', 'SRK', 'Marriage Reference', 'Dramatic', 'Keemat Tum Kya Jaano'] },
    { word: 'Thappad Se Darr', category: 'Bollywood', hints: ['Dabangg', 'Salman Khan', 'Police Wala', 'Pyaar Se', 'Chulbul Pandey'] },
    { word: 'Babuchak', category: 'Bollywood', hints: ['Hera Pheri', 'Paresh Rawal', 'Comedy', 'Babu Bhaiyya', 'Insult'] },
    { word: 'Kya Se Kya Ho Gaye', category: 'Bollywood', hints: ['Mughal-E-Azam', 'Madhubala', 'Dekhte Dekhte', 'Tragedy', 'Classic'] },
    { word: 'Tareekh Pe Tareekh', category: 'Bollywood', hints: ['Damini', 'Sunny Deol', 'Court Room', 'Justice Delayed', 'Famous Rant'] },
    { word: 'Pushpa Raj', category: 'Bollywood', hints: ['Allu Arjun', 'Flower Not Fire', 'Telugu', 'Smuggler', 'Jhukega Nahi'] },
    { word: 'How Is The Josh', category: 'Bollywood', hints: ['URI', 'Vicky Kaushal', 'Army', 'Surgical Strike', 'High Sir'] },
    { word: 'All Izz Well', category: 'Bollywood', hints: ['Three Idiots', 'Aamir', 'Rancho', 'Positive Thinking', 'Heart Trick'] },
    { word: 'Dosti Khatam', category: 'Bollywood', hints: ['Angry Breakup', 'Best Friends Fight', 'Emotional', 'Filmy Line', 'Betrayal'] },
    { word: 'Tumse Na Ho Payega', category: 'Bollywood', hints: ['Gangs Of Wasseypur', 'Challenge', 'Manoj Bajpayee', 'Insult', 'Motivation'] },
    { word: 'Don Ko Pakadna', category: 'Bollywood', hints: ['Don', 'Mushkil Hi Nahi', 'Amitabh SRK', 'Chase', 'Namumkin'] },
    { word: 'Tension Nahi Lene Ka', category: 'Bollywood', hints: ['Munna Bhai', 'Sanjay Dutt', 'Bhai Log', 'Comedy', 'Relax'] },
    { word: 'Jaa Mowgli', category: 'Bollywood', hints: ['Delhi Belly', 'Aamir Cameo', 'Funny Insult', 'Comedy', 'Wild Child'] },
    { word: 'Sharma Ji Ka Ladka', category: 'Bollywood', hints: ['Comparison', 'Indian Parents', 'Neighbor Kid', 'Topper', 'Pressure'] },
  ],
};
