import type { WordPack } from '../game/types';

export const bollywoodPack: WordPack = {
  id: 'bollywood',
  name: 'Bollywood',
  entries: [
    { word: 'Mughal-e-Azam', category: 'Bollywood' },
    { word: 'Sholay', category: 'Bollywood' },
    { word: 'DDLJ', category: 'Bollywood' },
    { word: 'Lagaan', category: 'Bollywood' },
    { word: 'Dil Chahta Hai', category: 'Bollywood' },
    { word: 'Gully Boy', category: 'Bollywood' },
    { word: 'Gangs of Wasseypur', category: 'Bollywood' },
    { word: 'Zindagi Na Milegi Dobara', category: 'Bollywood' },
    { word: '3 Idiots', category: 'Bollywood' },
    { word: 'Andaz Apna Apna', category: 'Bollywood' },
    { word: 'Shah Rukh Khan', category: 'Bollywood' },
    { word: 'Amitabh Bachchan', category: 'Bollywood' },
    { word: 'Alia Bhatt', category: 'Bollywood' },
    { word: 'Irrfan Khan', category: 'Bollywood' },
    { word: 'Ranveer Singh', category: 'Bollywood' },
    { word: 'Item Number', category: 'Bollywood' },
    { word: 'Interval Break', category: 'Bollywood' },
    { word: 'Slow Motion Walk', category: 'Bollywood' },
    { word: 'Wet Sari Scene', category: 'Bollywood' },
    { word: 'Dishoom Dishoom', category: 'Bollywood' },
    { word: 'Mehendi Scene', category: 'Bollywood' },
    { word: 'Airport Climax', category: 'Bollywood' },
    { word: 'Double Role', category: 'Bollywood' },
    { word: 'Filmy Dialogue', category: 'Bollywood' },
    { word: 'Train Chase', category: 'Bollywood' },
    { word: 'Yash Raj Films', category: 'Bollywood' },
    { word: 'Karan Johar', category: 'Bollywood' },
    { word: 'Rohit Shetty', category: 'Bollywood' },
    { word: 'Sanjay Leela Bhansali', category: 'Bollywood' },
    { word: 'Anurag Kashyap', category: 'Bollywood' },
    { word: 'Hera Pheri', category: 'Bollywood' },
    { word: 'Tumbbad', category: 'Bollywood' },
    { word: 'Barfi', category: 'Bollywood' },
    { word: 'Queen', category: 'Bollywood' },
    { word: 'Sangeet Night', category: 'Bollywood' },
    { word: 'Trailer Launch', category: 'Bollywood' },
    { word: 'First Day First Show', category: 'Bollywood' },
    { word: 'Cabaret Song', category: 'Bollywood' },
    { word: 'Stunt Double', category: 'Bollywood' },
    { word: 'Madhuri Dixit', category: 'Bollywood' },
  ],
};
