import type { WordPack } from '../game/types';

export const cricketPack: WordPack = {
  id: 'cricket',
  name: 'Cricket',
  entries: [
    // ── Indian Legends ──
    { word: 'Sachin Tendulkar', category: 'Cricket', hints: ['Master Blaster', 'Mumbai', '100 Centuries', 'Straight Drive', 'Desert Storm'] },
    { word: 'MS Dhoni', category: 'Cricket', hints: ['Captain Cool', 'Ranchi', 'Helicopter', 'Finisher', 'Stumping'] },
    { word: 'Virat Kohli', category: 'Cricket', hints: ['Run Machine', 'Delhi', 'Aggression', 'Chase Master', 'RCB'] },
    { word: 'Kapil Dev', category: 'Cricket', hints: ['Haryana Hurricane', '1983 Final', 'Natwest', 'Pace', 'All Rounder'] },
    { word: 'Rahul Dravid', category: 'Cricket', hints: ['The Wall', 'Bangalore', 'Test Specialist', 'Patience', 'Coach'] },
    { word: 'Rohit Sharma', category: 'Cricket', hints: ['Hitman', 'Mumbai', 'Double Century', 'Pull Shot', 'Opener'] },
    { word: 'Jasprit Bumrah', category: 'Cricket', hints: ['Yorker King', 'Gujarat', 'Unorthodox Action', 'Death Overs', 'No Ball'] },
    { word: 'Sunil Gavaskar', category: 'Cricket', hints: ['Little Master', 'Mumbai', 'Opening Bat', '10000 Runs', 'West Indies'] },
    { word: 'Anil Kumble', category: 'Cricket', hints: ['Jumbo', 'Leg Spin', '10 Wickets', 'Bangalore', 'Bandaged Jaw'] },
    { word: 'Harbhajan Singh', category: 'Cricket', hints: ['Bhajji', 'Turbanator', 'Off Spin', 'Doosra', 'Punjab'] },
    { word: 'Sourav Ganguly', category: 'Cricket', hints: ['Dada', 'Kolkata', 'Lords Shirt', 'Left Hand', 'Captain'] },
    { word: 'VVS Laxman', category: 'Cricket', hints: ['Very Very Special', 'Hyderabad', '281 Kolkata', 'Wrist Play', 'Elegance'] },
    { word: 'Yuvraj Singh', category: 'Cricket', hints: ['Six Sixes', 'Punjab', 'Left Hand', 'Cancer Survivor', 'T20 Hero'] },
    { word: 'Zaheer Khan', category: 'Cricket', hints: ['Zak', 'Left Arm Pace', 'Reverse Swing', 'Baroda', '2011 Final'] },
    { word: 'Ashwin', category: 'Cricket', hints: ['Off Spinner', 'Chennai', 'Carrom Ball', '500 Wickets', 'Mankad'] },
    { word: 'Jadeja', category: 'Cricket', hints: ['Sir', 'Sword Celebration', 'Saurashtra', 'Fielding', 'Left Arm Spin'] },
    { word: 'KL Rahul', category: 'Cricket', hints: ['Stylish', 'Karnataka', 'Wicketkeeper', 'Lucknow', 'Elegant Cover Drive'] },
    { word: 'Rishabh Pant', category: 'Cricket', hints: ['Gabba Hero', 'Delhi', 'Reverse Scoop', 'Keeper Bat', 'Car Accident'] },
    { word: 'Shubman Gill', category: 'Cricket', hints: ['Punjab', 'Young Star', 'Gujarat Titans', 'Elegant Drives', 'WTC Final'] },
    { word: 'Hardik Pandya', category: 'Cricket', hints: ['Baroda', 'Pace All Rounder', 'GT Captain', 'T20 Final', 'Big Hitter'] },
    { word: 'Shreyas Iyer', category: 'Cricket', hints: ['Mumbai', 'KKR Captain', 'Spin Hitter', 'Middle Order', 'Back Injury'] },
    { word: 'Mohammed Shami', category: 'Cricket', hints: ['Bengal', 'Seam Position', 'World Cup 2023', 'Outswing', 'Reverse'] },
    { word: 'Mohammed Siraj', category: 'Cricket', hints: ['Hyderabad', 'Father Tribute', 'Gabba Spell', 'RCB', 'Pace'] },
    { word: 'Kuldeep Yadav', category: 'Cricket', hints: ['Chinaman', 'UP', 'Left Arm Wrist', 'Hat Trick', 'Googly'] },
    { word: 'Yashasvi Jaiswal', category: 'Cricket', hints: ['Mumbai', 'Homeless Story', 'Double Century', 'Left Hand', 'U19'] },
    { word: 'Sanju Samson', category: 'Cricket', hints: ['Kerala', 'Rajasthan Royals', 'Keeper Bat', 'Timing', 'IPL Star'] },
    { word: 'Ishan Kishan', category: 'Cricket', hints: ['Jharkhand', 'Mumbai Indians', 'Left Hand', 'Keeper', 'Auction Record'] },
    { word: 'Surya Kumar Yadav', category: 'Cricket', hints: ['SKY', '360 Player', 'Mumbai', 'T20 Number One', 'Scoop Master'] },
    { word: 'Navdeep Saini', category: 'Cricket', hints: ['Delhi', 'Express Pace', 'RCB', 'Bouncer', '150 Kmph'] },
    { word: 'Cheteshwar Pujara', category: 'Cricket', hints: ['Saurashtra', 'Test Specialist', 'Patience', 'Australia Hero', 'Rock Solid'] },
    { word: 'Ajinkya Rahane', category: 'Cricket', hints: ['Mumbai', 'Gabba Captain', 'Slip Fielder', 'Quiet Leader', 'Test Bat'] },
    { word: 'Irfan Pathan', category: 'Cricket', hints: ['Baroda', 'Swing', 'Hat Trick Karachi', 'All Rounder', 'Left Arm'] },
    { word: 'Sehwag', category: 'Cricket', hints: ['Nawab of Najafgarh', 'Triple Century', 'Multan', 'Opening Blast', 'Delhi'] },
    { word: 'Ishant Sharma', category: 'Cricket', hints: ['Delhi', 'Tall Pacer', 'Ponting Spell', 'Bouncer', 'Lords Test'] },
    { word: 'Bhuvneshwar Kumar', category: 'Cricket', hints: ['Bhuvi', 'Meerut', 'Swing King', 'Purple Cap', 'Injury Prone'] },
    { word: 'Venkatesh Prasad', category: 'Cricket', hints: ['Bangalore', 'Aamir Sohail', '1996 World Cup', 'Medium Pace', 'Stumps Flying'] },
    { word: 'Javagal Srinath', category: 'Cricket', hints: ['Mysore Express', 'Karnataka', 'Fast Bowling', '300 Wickets', 'ICC Referee'] },
    { word: 'Ajit Agarkar', category: 'Cricket', hints: ['Bombay Duck', 'Mumbai', 'Fast Bowling', 'Six ODI Ducks', 'Lords Century'] },
    { word: 'Vinoo Mankad', category: 'Cricket', hints: ['All Rounder', 'Gujarat', 'Mankading', 'Opening Bat', 'Spin Legend'] },
    { word: 'Bishan Bedi', category: 'Cricket', hints: ['Patka', 'Left Arm Spin', 'Punjab', 'Artful Flight', 'Spin Quartet'] },
    { word: 'Chandrasekhar', category: 'Cricket', hints: ['Chandra', 'Leg Spin', 'Bangalore', 'Polio Arm', 'Spin Quartet'] },
    { word: 'Dilip Vengsarkar', category: 'Cricket', hints: ['Colonel', 'Mumbai', 'Lords Specialist', 'Middle Order', 'Tall Batsman'] },
    { word: 'Mohammad Azharuddin', category: 'Cricket', hints: ['Azhar', 'Hyderabad', 'Wrist Flick', 'Match Fixing', 'Three Debut Centuries'] },
    { word: 'Navjot Sidhu', category: 'Cricket', hints: ['Sixer Sidhu', 'Punjab', 'Commentary', 'One Liners', 'Opening Bat'] },
    { word: 'Gautam Gambhir', category: 'Cricket', hints: ['Delhi', '2011 Final 97', 'Gutsy', 'KKR Owner', 'Coach'] },
    { word: 'Umesh Yadav', category: 'Cricket', hints: ['Vidarbha', 'Pace', 'Red Ball', 'Bouncer', 'Seam Up'] },
    { word: 'Ravindra Jadeja', category: 'Cricket', hints: ['Sir', 'Sword Dance', 'Saurashtra', 'Run Outs', 'Triple Threat'] },
    { word: 'Axar Patel', category: 'Cricket', hints: ['Gujarat', 'Left Arm Spin', 'DC Star', 'England Series', 'Arm Ball'] },
    { word: 'Prithvi Shaw', category: 'Cricket', hints: ['Mumbai', 'U19 Captain', 'Debut Century', 'Young Prodigy', 'Fearless'] },
    { word: 'Devdutt Padikkal', category: 'Cricket', hints: ['Karnataka', 'Left Hand', 'RCB Debut', 'Elegant', 'Young Opener'] },
    // ── International Stars ──
    { word: 'Don Bradman', category: 'Cricket', hints: ['99.94 Average', 'Australia', 'Invincible', 'Greatest Ever', 'Bowral'] },
    { word: 'Viv Richards', category: 'Cricket', hints: ['Swagger', 'Antigua', 'No Helmet', 'West Indies', 'Power Hitting'] },
    { word: 'Brian Lara', category: 'Cricket', hints: ['Trinidad', '400 Not Out', 'Left Hand', 'Stylish', '501 Not Out'] },
    { word: 'Shane Warne', category: 'Cricket', hints: ['Leg Spin King', 'Gatting Ball', 'Australia', 'Blonde Hair', '700 Wickets'] },
    { word: 'Glenn McGrath', category: 'Cricket', hints: ['Pigeon', 'Line Length', 'Australia', 'Pace', 'McGrath Foundation'] },
    { word: 'Ricky Ponting', category: 'Cricket', hints: ['Punter', 'Australia Captain', 'Tasmania', 'Pull Shot', 'World Cups'] },
    { word: 'Adam Gilchrist', category: 'Cricket', hints: ['Gilly', 'Keeper Bat', 'Left Hand', 'Australia', 'Squash Ball'] },
    { word: 'Steve Waugh', category: 'Cricket', hints: ['Tugga', 'Mental Disintegration', 'Twin', 'Australia Captain', 'Tough'] },
    { word: 'AB de Villiers', category: 'Cricket', hints: ['Mr 360', 'South Africa', 'RCB', 'Innovation', 'Fastest Century'] },
    { word: 'Dale Steyn', category: 'Cricket', hints: ['South Africa', 'Express Pace', 'Best Test Bowler', 'Aggressive', 'Reverse'] },
    { word: 'Jacques Kallis', category: 'Cricket', hints: ['South Africa', 'All Rounder', 'Quiet Giant', 'Consistency', 'Slip Catches'] },
    { word: 'Wasim Akram', category: 'Cricket', hints: ['Sultan of Swing', 'Pakistan', 'Left Arm', 'Reverse', 'Lahore'] },
    { word: 'Waqar Younis', category: 'Cricket', hints: ['Toe Crusher', 'Pakistan', 'Yorker', 'Reverse Swing', 'Pace Partner'] },
    { word: 'Shoaib Akhtar', category: 'Cricket', hints: ['Rawalpindi Express', '161 Kmph', 'Pakistan', 'Pace', 'Bouncer'] },
    { word: 'Babar Azam', category: 'Cricket', hints: ['Pakistan Captain', 'Cover Drive', 'Fab Four', 'Lahore', 'Elegant'] },
    { word: 'Shaheen Afridi', category: 'Cricket', hints: ['Pakistan', 'Left Arm Pace', 'Young Gun', 'Tall', 'T20 Final Spell'] },
    { word: 'Imran Khan', category: 'Cricket', hints: ['Pakistan Captain', '1992 World Cup', 'All Rounder', 'Oxford', 'Tiger'] },
    { word: 'Kumar Sangakkara', category: 'Cricket', hints: ['Sri Lanka', 'Left Hand', 'Elegant', 'Lawyer', 'MCC President'] },
    { word: 'Muttiah Muralitharan', category: 'Cricket', hints: ['800 Wickets', 'Sri Lanka', 'Off Spin', 'Doosra', 'Action Controversy'] },
    { word: 'Lasith Malinga', category: 'Cricket', hints: ['Slinger', 'Sri Lanka', 'Yorker King', 'Curly Hair', 'Mumbai Indians'] },
    { word: 'Chris Gayle', category: 'Cricket', hints: ['Universe Boss', 'Jamaica', 'T20 King', 'Left Hand', 'RCB 175'] },
    { word: 'Curtly Ambrose', category: 'Cricket', hints: ['West Indies', 'Tall', 'Bounce', 'Stare Down', 'Antigua'] },
    { word: 'Malcolm Marshall', category: 'Cricket', hints: ['West Indies', 'Barbados', 'Fastest', 'Broken Thumb', 'Legend'] },
    { word: 'Kane Williamson', category: 'Cricket', hints: ['New Zealand', 'Nice Guy', 'Captain', 'Anchor', 'Technique'] },
    { word: 'Trent Boult', category: 'Cricket', hints: ['New Zealand', 'Left Arm', 'Swing', 'Mumbai Indians', 'Outswing'] },
    { word: 'Tim Southee', category: 'Cricket', hints: ['New Zealand', 'Swing Bowling', 'Red Ball', 'Senior Pro', 'Right Arm'] },
    { word: 'Ben Stokes', category: 'Cricket', hints: ['England', 'Headingley Miracle', 'All Rounder', 'Durham', 'Bazball'] },
    { word: 'Joe Root', category: 'Cricket', hints: ['England', 'Yorkshire', 'Fab Four', 'Test Runs', 'Sweep Shot'] },
    { word: 'James Anderson', category: 'Cricket', hints: ['England', 'Swing Master', '700 Wickets', 'Lancashire', 'Oldest Pacer'] },
    { word: 'Stuart Broad', category: 'Cricket', hints: ['England', 'Ashes Hero', 'Tall Pacer', 'Yuvraj Six Sixes', 'Wicket Celebration'] },
    { word: 'Pat Cummins', category: 'Cricket', hints: ['Australia Captain', 'Pace', 'NSW', 'WTC Winner', 'Consistent'] },
    { word: 'Mitchell Starc', category: 'Cricket', hints: ['Australia', 'Left Arm', 'Yorker', 'World Cup Star', 'Express'] },
    { word: 'Steve Smith', category: 'Cricket', hints: ['Australia', 'Fidgety', 'Ashes King', 'Sandpaper', 'Unorthodox'] },
    { word: 'David Warner', category: 'Cricket', hints: ['Australia', 'Bull', 'Opening Bat', 'Sandpaper', 'T20 Specialist'] },
    { word: 'Rashid Khan', category: 'Cricket', hints: ['Afghanistan', 'Leg Spin', 'Young Prodigy', 'GT Star', 'Googly'] },
    { word: 'Shakib Al Hasan', category: 'Cricket', hints: ['Bangladesh', 'All Rounder', 'Left Hand', 'Best All Rounder', 'Spin'] },
    { word: 'Mushfiqur Rahim', category: 'Cricket', hints: ['Bangladesh', 'Keeper Bat', 'Small Frame', 'Celebration', 'Veteran'] },
    { word: 'Brendon McCullum', category: 'Cricket', hints: ['New Zealand', 'Bazball', 'Aggressive', '302 Test', 'Coach England'] },
    { word: 'Ross Taylor', category: 'Cricket', hints: ['New Zealand', 'Middle Order', 'Experience', 'Tears Farewell', 'Samoan Heritage'] },
    { word: 'Quinton de Kock', category: 'Cricket', hints: ['South Africa', 'Left Hand', 'Keeper Bat', 'Explosive', 'LSG'] },
    { word: 'Kagiso Rabada', category: 'Cricket', hints: ['South Africa', 'Young Pace', 'KG', 'Aggressive', 'Purple Cap'] },
    { word: 'Hashim Amla', category: 'Cricket', hints: ['South Africa', 'Beard', 'Calm', 'Triple Century', 'Elegant'] },
    { word: 'Graeme Smith', category: 'Cricket', hints: ['South Africa', 'Left Hand', 'Captain', 'Broken Hand', 'Opener'] },
    { word: 'Ian Botham', category: 'Cricket', hints: ['Beefy', 'England', 'Headingley 1981', 'All Rounder', 'Charity Walk'] },
    { word: 'Michael Holding', category: 'Cricket', hints: ['Whispering Death', 'Jamaica', 'Smooth Run Up', 'Fast', 'Commentary'] },
    { word: 'Courtney Walsh', category: 'Cricket', hints: ['West Indies', 'Jamaica', '500 Wickets', 'Sportsmanship', 'Tall'] },
    { word: 'Allan Border', category: 'Cricket', hints: ['AB Medal', 'Australia Captain', 'Tough', 'Left Hand', 'Queensland'] },
    { word: 'Dennis Lillee', category: 'Cricket', hints: ['Australia', 'Moustache', 'Fast', 'Aluminium Bat', 'WACA'] },
    { word: 'Jeff Thomson', category: 'Cricket', hints: ['Thommo', 'Australia', 'Slingshot', 'Fastest Ever', 'Fearsome'] },
    { word: 'Garfield Sobers', category: 'Cricket', hints: ['Sir Gary', 'Barbados', 'Six Sixes Over', 'Greatest All Rounder', 'Left Hand'] },
    { word: 'Clive Lloyd', category: 'Cricket', hints: ['Supercat', 'Guyana', 'West Indies Captain', 'Glasses', 'World Cups'] },
    { word: 'Inzamam ul Haq', category: 'Cricket', hints: ['Inzi', 'Pakistan', 'Big Frame', 'Run Out', 'Lahore'] },
    { word: 'Saeed Anwar', category: 'Cricket', hints: ['Pakistan', 'Left Hand', '194 Runs', 'Elegant', 'Chennai Innings'] },
    { word: 'Javed Miandad', category: 'Cricket', hints: ['Pakistan', 'Last Ball Six', 'Sharjah', 'Fighter', 'Run Machine'] },
    // ── Shots & Deliveries ──
    { word: 'Helicopter Shot', category: 'Cricket', hints: ['Dhoni Signature', 'Wrist Rotation', 'Bottom Hand', 'Six', 'T20'] },
    { word: 'Reverse Sweep', category: 'Cricket', hints: ['Switch Hands', 'Behind Square', 'Spin Counter', 'Risky', 'ABD'] },
    { word: 'Cover Drive', category: 'Cricket', hints: ['Textbook', 'Through Covers', 'Front Foot', 'Elegant', 'Timing'] },
    { word: 'Pull Shot', category: 'Cricket', hints: ['Short Ball', 'Cross Bat', 'Midwicket', 'Back Foot', 'Power'] },
    { word: 'Yorker', category: 'Cricket', hints: ['At Toes', 'Death Overs', 'Bumrah', 'Block Hole', 'Hard to Hit'] },
    { word: 'Googly', category: 'Cricket', hints: ['Wrong One', 'Leg Spinner', 'Deception', 'Surprise', 'Turning Away'] },
    { word: 'Doosra', category: 'Cricket', hints: ['Other One', 'Off Spin', 'Away Turn', 'Murali', 'Controversial'] },
    { word: 'Sixer', category: 'Cricket', hints: ['Over Boundary', 'Maximum', 'Big Hit', 'Crowd Roar', 'Stadium Roof'] },
    { word: 'Square Cut', category: 'Cricket', hints: ['Wide Ball', 'Behind Point', 'Flat Bat', 'Short Wide', 'Power'] },
    { word: 'Flick Shot', category: 'Cricket', hints: ['Wrist Work', 'Leg Side', 'On Pads', 'Rohit Special', 'Midwicket'] },
    { word: 'Late Cut', category: 'Cricket', hints: ['Behind Wicket', 'Timing', 'Third Man', 'Delicate', 'Wrist'] },
    { word: 'Uppercut', category: 'Cricket', hints: ['Over Slips', 'Short Ball', 'Third Man', 'Sehwag Style', 'Intentional'] },
    { word: 'Scoop Shot', category: 'Cricket', hints: ['Over Keeper', 'Fine Leg', 'T20 Innovation', 'Audacious', 'Ramp'] },
    { word: 'Paddle Sweep', category: 'Cricket', hints: ['Fine Leg', 'Spin Counter', 'Controlled', 'Down On Knee', 'Placement'] },
    { word: 'Switch Hit', category: 'Cricket', hints: ['Change Stance', 'KP Innovation', 'Ambidextrous', 'Confuse Bowler', 'Both Sides'] },
    { word: 'Ramp Shot', category: 'Cricket', hints: ['Over Keeper', 'Pace Redirect', 'T20', 'Third Man', 'Open Face'] },
    { word: 'Dilscoop', category: 'Cricket', hints: ['Dilshan Invention', 'Over Keeper', 'Sri Lanka', 'Audacious', 'Full Ball'] },
    { word: 'Straight Drive', category: 'Cricket', hints: ['Down Ground', 'Sachin Special', 'Textbook', 'Past Bowler', 'Front Foot'] },
    { word: 'On Drive', category: 'Cricket', hints: ['Midwicket Side', 'Front Foot', 'Timing', 'Mid On Gap', 'Elegant'] },
    { word: 'Off Drive', category: 'Cricket', hints: ['Through Covers', 'Front Foot', 'Classic', 'Off Side', 'Textbook'] },
    { word: 'Leg Glance', category: 'Cricket', hints: ['Fine Leg', 'Wrist Flick', 'On Pads', 'Delicate', 'Touch Shot'] },
    { word: 'Hook Shot', category: 'Cricket', hints: ['Short Ball', 'Square Leg', 'Top Edge Risk', 'Brave', 'Pulling High'] },
    { word: 'Lofted Drive', category: 'Cricket', hints: ['Over Fielder', 'Aerial', 'Big Shot', 'Down Ground', 'Risky'] },
    { word: 'Inside Out Shot', category: 'Cricket', hints: ['Against Spin', 'Over Covers', 'Wrist Work', 'Off Side', 'Modern'] },
    { word: 'Bouncer', category: 'Cricket', hints: ['Short Pitch', 'Head Height', 'Intimidation', 'Fast Bowler', 'Helmet'] },
    { word: 'Slower Ball', category: 'Cricket', hints: ['Change of Pace', 'Death Overs', 'Deception', 'Mistimed', 'Caught'] },
    { word: 'Outswinger', category: 'Cricket', hints: ['Away Movement', 'New Ball', 'Seam Position', 'Edge', 'Slip Catch'] },
    { word: 'Inswinger', category: 'Cricket', hints: ['Into Batsman', 'LBW Trap', 'Seam', 'New Ball', 'Wasim Akram'] },
    { word: 'Leg Cutter', category: 'Cricket', hints: ['Off Seam', 'Away From Right', 'Pace Variation', 'Finger Cut', 'Deviate'] },
    { word: 'Off Cutter', category: 'Cricket', hints: ['Into Right Hand', 'Finger Roll', 'Slow Pitch', 'Death Overs', 'Variation'] },
    { word: 'Knuckleball', category: 'Cricket', hints: ['No Spin', 'Dip', 'Slow', 'Baseball Origin', 'Death Variation'] },
    { word: 'Carrom Ball', category: 'Cricket', hints: ['Finger Flick', 'Ashwin Weapon', 'Surprise', 'Off Spin', 'Dip'] },
    { word: 'Flipper', category: 'Cricket', hints: ['Warne Special', 'Skids On', 'Low Bounce', 'Leg Spin', 'Back Spin'] },
    { word: 'Top Spinner', category: 'Cricket', hints: ['Over Spin', 'Extra Bounce', 'Leg Spinner', 'Dips', 'Loop'] },
    { word: 'Arm Ball', category: 'Cricket', hints: ['No Turn', 'Goes Straight', 'Left Arm', 'Surprise', 'LBW'] },
    { word: 'Beamer', category: 'Cricket', hints: ['Full Toss Head', 'Dangerous', 'No Ball', 'Warning', 'Illegal'] },
    { word: 'Full Toss', category: 'Cricket', hints: ['No Bounce', 'Waist Height', 'Easy Hit', 'Bad Ball', 'Gift'] },
    { word: 'Good Length Ball', category: 'Cricket', hints: ['Ideal Spot', 'Doubt', 'Play or Leave', 'Nagging', 'Disciplined'] },
    { word: 'Short Pitch', category: 'Cricket', hints: ['Halfway', 'Bounce', 'Pull or Duck', 'Intimidation', 'Body Line'] },
    { word: 'Reverse Swing', category: 'Cricket', hints: ['Old Ball', 'Rough Side', 'Pakistan Art', 'Late Movement', 'Wasim Waqar'] },
    { word: 'Seam Movement', category: 'Cricket', hints: ['Off Pitch', 'Upright Seam', 'Green Track', 'Nibble', 'English Conditions'] },
    // ── Terms & Rules ──
    { word: 'LBW', category: 'Cricket', hints: ['Leg Before', 'Umpire Finger', 'Pad First', 'Plumb', 'DRS Review'] },
    { word: 'Duck', category: 'Cricket', hints: ['Zero Runs', 'Out Cheaply', 'Walk Back', 'Embarrassing', 'Agarkar'] },
    { word: 'Hat Trick', category: 'Cricket', hints: ['Three in Three', 'Rare Feat', 'Consecutive', 'Irfan Pathan', 'Celebration'] },
    { word: 'Mankad', category: 'Cricket', hints: ['Non Striker Out', 'Backing Up', 'Ashwin', 'Controversial', 'Spirit Debate'] },
    { word: 'Run Out', category: 'Cricket', hints: ['Direct Hit', 'Stumps Broken', 'Short Run', 'Miscommunication', 'Jadeja Throw'] },
    { word: 'Super Over', category: 'Cricket', hints: ['Tiebreaker', 'Six Balls Each', 'World Cup 2019', 'Dramatic', 'Eliminator'] },
    { word: 'Third Umpire', category: 'Cricket', hints: ['TV Review', 'Upstairs', 'Replays', 'Technology', 'Decision Aid'] },
    { word: 'DRS Review', category: 'Cricket', hints: ['T Shape Signal', 'Challenge', 'Hawk Eye', 'Umpires Call', 'Retention'] },
    { word: 'Powerplay', category: 'Cricket', hints: ['Field Restrictions', 'First Six', 'Attacking', 'Two Fielders', 'ODI Overs'] },
    { word: 'Maiden Over', category: 'Cricket', hints: ['Zero Runs', 'Dot Balls', 'Six Dots', 'Pressure', 'Economy'] },
    { word: 'Spin Bowling', category: 'Cricket', hints: ['Turning Ball', 'Flight', 'Finger Wrist', 'Slow', 'Pitch Assist'] },
    { word: 'Boundary Line', category: 'Cricket', hints: ['Rope', 'Four or Six', 'Edge Line', 'Outfield', 'Diving Save'] },
    { word: 'Night Watchman', category: 'Cricket', hints: ['Protect Batsman', 'End of Day', 'Lower Order', 'Test Match', 'Jason Gillespie'] },
    { word: 'Sledging', category: 'Cricket', hints: ['Verbal Abuse', 'Mind Games', 'Australian Way', 'Provocation', 'Mental Battle'] },
    { word: 'Follow On', category: 'Cricket', hints: ['200 Run Lead', 'Bat Again', 'Test Match', 'Enforce', 'Rare Escape'] },
    { word: 'Declaration', category: 'Cricket', hints: ['Set Target', 'Captain Choice', 'Close Innings', 'Test Only', 'Sporting'] },
    { word: 'Duckworth Lewis', category: 'Cricket', hints: ['Rain Rule', 'Target Adjust', 'Complicated', 'Par Score', 'DLS Method'] },
    { word: 'Net Run Rate', category: 'Cricket', hints: ['Tiebreaker', 'Tournament', 'Scoring Rate', 'Difference', 'Group Stage'] },
    { word: 'Golden Duck', category: 'Cricket', hints: ['First Ball Out', 'Zero Score', 'Opening Ball', 'Worst Start', 'Walk Back'] },
    { word: 'Diamond Duck', category: 'Cricket', hints: ['Without Facing', 'Run Out', 'Non Striker', 'Rarest', 'Zero Balls'] },
    { word: 'King Pair', category: 'Cricket', hints: ['Two Golden Ducks', 'Both Innings', 'First Ball Both', 'Nightmare', 'Test Match'] },
    { word: 'Century', category: 'Cricket', hints: ['100 Runs', 'Bat Raise', 'Milestone', 'Helmet Off', 'Celebration'] },
    { word: 'Double Century', category: 'Cricket', hints: ['200 Runs', 'Rare', 'Sehwag', 'Marathon', 'Test Innings'] },
    { word: 'Half Century', category: 'Cricket', hints: ['50 Runs', 'Bat Raise', 'Good Start', 'Foundation', 'Milestone'] },
    { word: 'Five Wicket Haul', category: 'Cricket', hints: ['Fifer', 'Bowler Glory', 'Match Ball', 'Rare Feat', 'Test Honor'] },
    { word: 'Ten Wicket Match', category: 'Cricket', hints: ['Both Innings', 'Kumble 10 For', 'Legendary', 'Rare', 'Bowler Dream'] },
    { word: 'Free Hit', category: 'Cricket', hints: ['After No Ball', 'Cannot Out', 'Big Swing', 'Gift', 'Batsman Loves'] },
    { word: 'No Ball', category: 'Cricket', hints: ['Overstepping', 'Extra Run', 'Front Foot', 'Illegal', 'Bumrah WC'] },
    { word: 'Wide Ball', category: 'Cricket', hints: ['Outside Reach', 'Extra Run', 'Umpire Arms', 'Down Leg', 'Bowling Error'] },
    { word: 'Dead Ball', category: 'Cricket', hints: ['Play Stops', 'No Runs', 'Umpire Call', 'Interference', 'Ball Lodged'] },
    { word: 'Bye Run', category: 'Cricket', hints: ['Missed by All', 'Keeper Miss', 'Extra', 'No Bat Contact', 'Scoreboard'] },
    { word: 'Leg Bye', category: 'Cricket', hints: ['Off Body', 'No Bat', 'Pad Deflection', 'Extra', 'Playing Shot'] },
    { word: 'Retired Hurt', category: 'Cricket', hints: ['Injury', 'Leave Field', 'Can Return', 'Not Out', 'Medical'] },
    { word: 'Timed Out', category: 'Cricket', hints: ['Three Minutes', 'Rare Dismissal', 'Late Arrival', 'Clock', 'New Batsman'] },
    { word: 'Obstructing Field', category: 'Cricket', hints: ['Block Fielder', 'Rare Dismissal', 'In The Way', 'Deliberate', 'Controversial'] },
    { word: 'Hit Wicket', category: 'Cricket', hints: ['Own Stumps', 'Dislodge Bails', 'Unlucky', 'Back Foot', 'Embarrassing'] },
    { word: 'Handled Ball', category: 'Cricket', hints: ['Touch Ball', 'Without Permission', 'Rare', 'Deliberate', 'Out'] },
    { word: 'Caught Behind', category: 'Cricket', hints: ['Keeper Catch', 'Edge', 'Thin Nick', 'Gloves', 'Walking'] },
    { word: 'Stumped', category: 'Cricket', hints: ['Keeper Quick', 'Out of Crease', 'Spin Bowling', 'Dhoni Lightning', 'Bails Off'] },
    { word: 'Bowled', category: 'Cricket', hints: ['Castle Hit', 'Through Gate', 'Stumps Flying', 'Clean Bowled', 'Most Satisfying'] },
    { word: 'Caught and Bowled', category: 'Cricket', hints: ['Return Catch', 'Bowler Grabs', 'Reflex', 'Follow Through', 'Sharp'] },
    { word: 'Impact Player', category: 'Cricket', hints: ['IPL Rule', 'Substitute', 'Tactical', 'Extra Player', '12th Man'] },
    { word: 'Concussion Sub', category: 'Cricket', hints: ['Head Injury', 'Replacement', 'Safety Rule', 'Like for Like', 'New'] },
    { word: 'Batting Collapse', category: 'Cricket', hints: ['Wickets Falling', 'All Out Cheap', 'Panic', '36 All Out', 'Disaster'] },
    { word: 'Tail Ender', category: 'Cricket', hints: ['Lower Order', 'Number 11', 'Rabbit', 'Cannot Bat', 'Bowling First'] },
    { word: 'All Rounder', category: 'Cricket', hints: ['Bat and Bowl', 'Dual Skill', 'Stokes Kapil', 'Valuable', 'Balance Team'] },
    { word: 'Pinch Hitter', category: 'Cricket', hints: ['Promote Order', 'Quick Runs', 'Aggressive', 'Lower Bat Up', 'Surprise'] },
    { word: 'Death Bowling', category: 'Cricket', hints: ['Last Overs', 'Yorkers', 'Bumrah', 'High Pressure', 'Slog Overs'] },
    { word: 'Batting Average', category: 'Cricket', hints: ['Runs Per Dismissal', 'Statistic', 'Bradman 99', 'Measure', 'Consistency'] },
    { word: 'Strike Rate', category: 'Cricket', hints: ['Runs Per Ball', 'Speed', 'T20 Key', 'Aggressive', 'Percentage'] },
    { word: 'Economy Rate', category: 'Cricket', hints: ['Runs Per Over', 'Bowler Stat', 'Tight Bowling', 'Pressure', 'Low Better'] },
    { word: 'Wagon Wheel', category: 'Cricket', hints: ['Scoring Map', 'Shot Direction', 'Graphics', 'Broadcast', 'Run Chart'] },
    { word: 'Snickometer', category: 'Cricket', hints: ['Sound Wave', 'Edge Detection', 'Technology', 'DRS Tool', 'Audio Spike'] },
    { word: 'Hawk Eye', category: 'Cricket', hints: ['Ball Tracking', 'LBW Prediction', 'Trajectory', 'DRS', 'Green Red'] },
    { word: 'Ultra Edge', category: 'Cricket', hints: ['Edge Detection', 'Sound Spike', 'Bat Contact', 'DRS Tool', 'Fine Edge'] },
    { word: 'Hot Spot', category: 'Cricket', hints: ['Thermal Camera', 'Bat Edge', 'Heat Mark', 'Contact Point', 'DRS'] },
    { word: 'Spider Cam', category: 'Cricket', hints: ['Aerial Camera', 'Wire Mounted', 'Bird Eye View', 'Broadcast', 'Above Pitch'] },
    // ── Fielding Positions ──
    { word: 'Silly Point', category: 'Cricket', hints: ['Close In', 'Brave Fielder', 'Bat Pad', 'Dangerous', 'Helmet On'] },
    { word: 'Gully', category: 'Cricket', hints: ['Between Slips', 'Off Side', 'Angled Cut', 'Close Catcher', 'Street Name'] },
    { word: 'Slip Cordon', category: 'Cricket', hints: ['Behind Bat', 'Catching Line', 'Edge Catcher', 'First Second Third', 'Hands Ready'] },
    { word: 'Short Leg', category: 'Cricket', hints: ['Close Bat Pad', 'Leg Side', 'Brave Position', 'Helmet', 'Spin Trap'] },
    { word: 'Long On', category: 'Cricket', hints: ['Deep Bowler Side', 'Lofted Catch', 'Boundary', 'Straight Hit', 'Leg Side Deep'] },
    { word: 'Long Off', category: 'Cricket', hints: ['Deep Off Side', 'Straight Hit', 'Boundary Save', 'Lofted Drive', 'Deep'] },
    { word: 'Deep Midwicket', category: 'Cricket', hints: ['Leg Side Deep', 'Big Hit Zone', 'Boundary', 'Pull Shot', 'Slog Area'] },
    { word: 'Fine Leg', category: 'Cricket', hints: ['Behind Square', 'Leg Side', 'Glance Area', 'Deep Back', 'Tickle Shot'] },
    { word: 'Third Man', category: 'Cricket', hints: ['Behind Keeper', 'Off Side', 'Late Cut', 'Edge Area', 'Deep Backward'] },
    { word: 'Square Leg', category: 'Cricket', hints: ['Ninety Degrees', 'Leg Side', 'Umpire Position', 'Pull Area', 'Level Bat'] },
    { word: 'Point', category: 'Cricket', hints: ['Off Side', 'Cut Shot', 'Ninety Degrees', 'Agile Fielder', 'Diving Stop'] },
    { word: 'Mid Off', category: 'Cricket', hints: ['Off Side', 'Bowler End', 'Straight Drive', 'Close In', 'Captains Position'] },
    { word: 'Mid On', category: 'Cricket', hints: ['Leg Side', 'Bowler End', 'On Drive', 'Close In', 'Straight'] },
    { word: 'Cow Corner', category: 'Cricket', hints: ['Deep Midwicket', 'Slog Zone', 'Big Hit', 'Unorthodox', 'No Fielder'] },
    { word: 'Sweeper', category: 'Cricket', hints: ['Boundary Patrol', 'Deep Position', 'Save Fours', 'Cover Drive', 'Sliding'] },
    { word: 'Leg Slip', category: 'Cricket', hints: ['Behind Bat', 'Leg Side', 'Spin Catch', 'Close In', 'Rare Position'] },
    { word: 'Fly Slip', category: 'Cricket', hints: ['Deeper Slip', 'Upper Edge', 'Fast Bowlers', 'Standing Back', 'Top Edge'] },
    { word: 'Backward Point', category: 'Cricket', hints: ['Behind Square', 'Off Side', 'Cut Shot', 'Angled', 'Saving Runs'] },
    // ── Stadiums & Grounds ──
    { word: 'Wankhede Stadium', category: 'Cricket', hints: ['Mumbai', '2011 Final', 'Sea Breeze', 'Sachin Farewell', 'MI Home'] },
    { word: 'Eden Gardens', category: 'Cricket', hints: ['Kolkata', '100000 Capacity', '2001 Test', 'Bengal', 'KKR Home'] },
    { word: 'Chinnaswamy', category: 'Cricket', hints: ['Bangalore', 'Flat Pitch', 'RCB Home', 'High Scoring', 'Small Ground'] },
    { word: 'Feroz Shah Kotla', category: 'Cricket', hints: ['Delhi', 'Arun Jaitley Now', 'Spin Pitch', 'DC Home', 'Old Ground'] },
    { word: 'Chepauk', category: 'Cricket', hints: ['Chennai', 'CSK Home', 'Spin Friendly', 'MA Chidambaram', 'Hot Weather'] },
    { word: 'Mohali Stadium', category: 'Cricket', hints: ['Chandigarh', 'Punjab', 'Semi Final 2011', 'PCA', 'North India'] },
    { word: 'Rajiv Gandhi Stadium', category: 'Cricket', hints: ['Hyderabad', 'SRH Home', 'Uppal', 'Large Capacity', 'Deccan'] },
    { word: 'Narendra Modi Stadium', category: 'Cricket', hints: ['Ahmedabad', 'Largest Stadium', '132000 Seats', 'Motera', 'WC Final'] },
    { word: 'Brabourne Stadium', category: 'Cricket', hints: ['Mumbai', 'CCI Ground', 'Historic', 'Marine Drive', 'Small Capacity'] },
    { word: 'Green Park Kanpur', category: 'Cricket', hints: ['UP', 'Historic Ground', 'Day Night Test', 'Flat Track', 'November Test'] },
    { word: 'Holkar Stadium', category: 'Cricket', hints: ['Indore', 'Flat Pitch', 'High Scoring', 'MP', 'Clean Ground'] },
    { word: 'Dharamsala Stadium', category: 'Cricket', hints: ['Mountains', 'Himachal', 'Scenic', 'HPCA', 'Snow Backdrop'] },
    { word: 'Lords', category: 'Cricket', hints: ['Home of Cricket', 'London', 'Slope', 'MCC', 'Honors Board'] },
    { word: 'The Oval', category: 'Cricket', hints: ['London', 'England', 'Historic', 'Gas Holder', 'Ashes Ground'] },
    { word: 'MCG', category: 'Cricket', hints: ['Melbourne', '100000 Seats', 'Boxing Day', 'Australia', 'Iconic'] },
    { word: 'SCG', category: 'Cricket', hints: ['Sydney', 'New Year Test', 'Australia', 'Spin Friendly', 'Pink Test'] },
    { word: 'Gabba', category: 'Cricket', hints: ['Brisbane', 'Fortress', 'India 2021', 'Pace Track', 'Queensland'] },
    { word: 'Wanderers', category: 'Cricket', hints: ['Johannesburg', 'Bullring', 'Pace Track', 'South Africa', 'High Altitude'] },
    { word: 'Newlands', category: 'Cricket', hints: ['Cape Town', 'Table Mountain', 'Beautiful', 'South Africa', 'Green'] },
    { word: 'Dubai Stadium', category: 'Cricket', hints: ['UAE', 'Neutral Venue', 'IPL Bubble', 'Slow Pitch', 'Desert'] },
    { word: 'Sharjah Cricket', category: 'Cricket', hints: ['Desert Storm', 'UAE', 'Sachin', 'Small Ground', 'India Pakistan'] },
    { word: 'Galle Fort Ground', category: 'Cricket', hints: ['Sri Lanka', 'Fort Backdrop', 'Spin Paradise', 'Scenic', 'Murali'] },
    { word: 'Basin Reserve', category: 'Cricket', hints: ['Wellington', 'New Zealand', 'Windy', 'Cake Tin Nearby', 'Test Ground'] },
    { word: 'Headingley', category: 'Cricket', hints: ['Leeds', 'England', 'Stokes 2019', 'Botham 1981', 'Miracle Wins'] },
    { word: 'Old Trafford', category: 'Cricket', hints: ['Manchester', 'England', 'Rain', 'Red Rose', 'Ashes'] },
    { word: 'Edgbaston', category: 'Cricket', hints: ['Birmingham', 'England', 'Fortress', 'ICC Events', 'Bear Pit'] },
    // ── Tournaments ──
    { word: 'World Cup', category: 'Cricket', hints: ['50 Over', 'ICC Trophy', 'Every Four Years', 'India 2023', 'ODI'] },
    { word: 'IPL', category: 'Cricket', hints: ['Indian Premier', 'T20 Franchise', 'Auction', 'Two Months', 'Spring'] },
    { word: 'T20 World Cup', category: 'Cricket', hints: ['Short Format', 'ICC Event', 'India 2024', 'Twenty Overs', 'Global'] },
    { word: 'Champions Trophy', category: 'Cricket', hints: ['ICC Mini Cup', 'Eight Teams', 'Knockout', 'Pakistan 2025', 'Top Nations'] },
    { word: 'Asia Cup', category: 'Cricket', hints: ['Continental', 'India Pakistan', 'Subcontinent', 'Rotating Host', 'Asian Teams'] },
    { word: 'Border Gavaskar Trophy', category: 'Cricket', hints: ['India Australia', 'Test Series', 'Bilateral', 'Named After', 'Fierce'] },
    { word: 'The Ashes', category: 'Cricket', hints: ['England Australia', 'Oldest Rivalry', 'Tiny Urn', 'Test Series', 'Biennial'] },
    { word: 'Ranji Trophy', category: 'Cricket', hints: ['Domestic First Class', 'State Teams', 'India', 'Red Ball', 'Longest Running'] },
    { word: 'Duleep Trophy', category: 'Cricket', hints: ['Zonal Teams', 'Domestic India', 'Pink Ball', 'Multi Day', 'First Class'] },
    { word: 'Irani Cup', category: 'Cricket', hints: ['Ranji Champion', 'Rest of India', 'One Match', 'Domestic', 'Season Opener'] },
    { word: 'Vijay Hazare Trophy', category: 'Cricket', hints: ['Domestic ODI', 'India', 'State Teams', 'One Day', 'White Ball'] },
    { word: 'Syed Mushtaq Ali', category: 'Cricket', hints: ['Domestic T20', 'India', 'State Teams', 'Short Format', 'IPL Audition'] },
    { word: 'WTC Final', category: 'Cricket', hints: ['Test Championship', 'ICC', 'Lords Final', 'Two Year Cycle', 'Top Teams'] },
    { word: 'Big Bash League', category: 'Cricket', hints: ['Australia T20', 'BBL', 'Summer', 'Franchise', 'December'] },
    { word: 'Hundred Ball', category: 'Cricket', hints: ['England', '100 Balls', 'New Format', 'ECB', 'Men Women'] },
    { word: 'Caribbean Premier League', category: 'Cricket', hints: ['West Indies T20', 'CPL', 'Island Vibes', 'Franchise', 'Carnival'] },
    { word: 'PSL', category: 'Cricket', hints: ['Pakistan Super', 'T20 League', 'Franchise', 'Lahore Karachi', 'Spring'] },
    { word: 'Womens Premier League', category: 'Cricket', hints: ['WPL', 'India Women', 'T20 Franchise', 'Five Teams', 'BCCI'] },
    // ── IPL Teams ──
    { word: 'Mumbai Indians', category: 'Cricket', hints: ['MI', 'Five Titles', 'Blue', 'Ambani', 'Wankhede'] },
    { word: 'Chennai Super Kings', category: 'Cricket', hints: ['CSK', 'Whistle Podu', 'Yellow', 'Dhoni', 'Chepauk'] },
    { word: 'Royal Challengers', category: 'Cricket', hints: ['RCB', 'Bangalore', 'Red Gold', 'Kohli', 'Ee Sala'] },
    { word: 'Kolkata Knight Riders', category: 'Cricket', hints: ['KKR', 'Korbo Lorbo', 'Purple Gold', 'SRK', 'Eden Gardens'] },
    { word: 'Sunrisers Hyderabad', category: 'Cricket', hints: ['SRH', 'Orange Army', 'Bowling Attack', 'Kavya Maran', 'Deccan'] },
    { word: 'Rajasthan Royals', category: 'Cricket', hints: ['RR', 'Pink', 'First Winners', 'Jaipur', 'Warne Legacy'] },
    { word: 'Delhi Capitals', category: 'Cricket', hints: ['DC', 'Daredevils Before', 'Blue Red', 'Kotla', 'Young Team'] },
    { word: 'Punjab Kings', category: 'Cricket', hints: ['PBKS', 'Mohali', 'Red', 'Preity Zinta', 'No Title'] },
    { word: 'Gujarat Titans', category: 'Cricket', hints: ['GT', 'Ahmedabad', 'Navy Blue', 'Won First Year', 'Hardik'] },
    { word: 'Lucknow Super Giants', category: 'Cricket', hints: ['LSG', 'RPSG', 'Teal', 'New Franchise', 'UP'] },
    // ── IPL Culture ──
    { word: 'IPL Auction', category: 'Cricket', hints: ['Bidding War', 'Paddle Raise', 'Purse', 'TV Drama', 'Crores'] },
    { word: 'Orange Cap', category: 'Cricket', hints: ['Top Scorer', 'Batting Award', 'Season Best', 'Most Runs', 'Worn During'] },
    { word: 'Purple Cap', category: 'Cricket', hints: ['Top Wicket Taker', 'Bowling Award', 'Season Best', 'Most Wickets', 'Worn During'] },
    { word: 'Mega Auction', category: 'Cricket', hints: ['Full Reset', 'All Released', 'New Squads', 'Every Few Years', 'Big Day'] },
    { word: 'Retention', category: 'Cricket', hints: ['Keep Player', 'Before Auction', 'Core Players', 'Max Five', 'Loyalty'] },
    { word: 'RTM Card', category: 'Cricket', hints: ['Right to Match', 'Auction Power', 'Match Bid', 'Old Team', 'Strategy'] },
    { word: 'Salary Cap', category: 'Cricket', hints: ['Budget Limit', 'Purse Size', 'Crore Limit', 'Fair Play', 'Equalizer'] },
    { word: 'Strategic Timeout', category: 'Cricket', hints: ['Mandatory Break', 'Two Per Innings', 'Ad Break', 'Team Talk', 'Planning'] },
    { word: 'Cheerleaders', category: 'Cricket', hints: ['Dance Squad', 'Boundary Show', 'Entertainment', 'Stadium Hype', 'Cheer Team'] },
    { word: 'Opening Ceremony', category: 'Cricket', hints: ['Season Launch', 'Bollywood', 'Grand Show', 'First Night', 'Star Studded'] },
    { word: 'Franchise Owner', category: 'Cricket', hints: ['Team Boss', 'Billionaire', 'Business Tycoon', 'Bidder', 'Cricket Investment'] },
    // ── Iconic Moments ──
    { word: '2011 World Cup Final', category: 'Cricket', hints: ['Wankhede', 'Dhoni Finish', 'India Won', 'Mumbai Night', 'April Second'] },
    { word: 'Gabba Breach', category: 'Cricket', hints: ['Brisbane', 'India 2021', 'Fortress Broken', 'Pant Chase', 'Australia Stunned'] },
    { word: 'Natwest Final', category: 'Cricket', hints: ['Lords 2002', 'Kaif Yuvraj', 'India Chase', 'Shirt Off', 'Ganguly Balcony'] },
    { word: 'Sachin 200', category: 'Cricket', hints: ['First Double', 'ODI Record', 'Gwalior', 'South Africa', 'February 2010'] },
    { word: 'Dhoni Six', category: 'Cricket', hints: ['Finishing Style', 'World Cup', 'Over Long On', 'Helicopter', 'India Captain'] },
    { word: 'Kumble 10 Wickets', category: 'Cricket', hints: ['All Ten', 'Pakistan', 'Delhi Test', 'Spin Legend', 'February 1999'] },
    { word: 'Dravid The Wall', category: 'Cricket', hints: ['Solid Defence', 'Test Specialist', 'Patience', 'Bangalore', 'Jammy'] },
    { word: '1983 World Cup', category: 'Cricket', hints: ['Kapil Dev', 'Lords Final', 'West Indies Beat', 'Indian Cricket Changed', 'June 25'] },
    { word: 'Sehwag 319', category: 'Cricket', hints: ['Triple Century', 'Chennai Test', 'South Africa', 'Attacking', 'Test Record'] },
    { word: 'Yuvraj Six Sixes', category: 'Cricket', hints: ['Stuart Broad', 'T20 World Cup', 'One Over', 'Durban', 'Flintoff Sledge'] },
    { word: 'Kapil 175', category: 'Cricket', hints: ['Zimbabwe Match', 'World Cup 1983', 'No Telecast', 'Rescue Innings', 'Tunbridge Wells'] },
    { word: 'Kolkata 2001 Test', category: 'Cricket', hints: ['Laxman 281', 'Follow On Won', 'Australia Beat', 'Eden Gardens', 'Dravid Partnership'] },
    { word: 'Tied Test 1986', category: 'Cricket', hints: ['Madras', 'India Australia', 'First Ever Tie', 'Chepauk', 'Historic Draw'] },
    { word: 'Headingley 2019', category: 'Cricket', hints: ['Stokes', 'England Ashes', 'One Wicket Win', 'Leach Glasses', 'Leeds'] },
    { word: 'Stokes Ashes Knock', category: 'Cricket', hints: ['Headingley', 'Unbeaten', 'England Saved', '135 Runs', 'Greatest Innings'] },
    { word: '438 Game', category: 'Cricket', hints: ['South Africa Australia', 'Highest Chase', 'Johannesburg', 'ODI Record', '2006'] },
    { word: 'Lara 400', category: 'Cricket', hints: ['Test Record', 'Antigua', 'West Indies', 'Brian', 'Not Out'] },
    { word: 'Warne Ball of Century', category: 'Cricket', hints: ['Gatting', 'Ashes 1993', 'Leg Spin', 'First Ball', 'Old Trafford'] },
    { word: 'Underarm Incident', category: 'Cricket', hints: ['Australia NZ', 'Chappell Brothers', 'Rolled Along Ground', '1981', 'Unsportsmanlike'] },
    { word: 'Monkeygate', category: 'Cricket', hints: ['Sydney Test', 'Harbhajan', 'Symonds', 'Controversy', '2008'] },
    { word: 'Bodyline Series', category: 'Cricket', hints: ['Leg Theory', 'Jardine Larwood', 'Australia 1932', 'Short Pitched', 'Bradman Target'] },
    { word: 'Sandpaper Gate', category: 'Cricket', hints: ['Bancroft', 'Ball Tampering', 'Cape Town', 'Smith Warner Ban', '2018'] },
    // ── Cricket Culture ──
    { word: 'Gully Cricket', category: 'Cricket', hints: ['Street Game', 'Mohalla', 'Kids Playing', 'Informal', 'Rooftop'] },
    { word: 'Tape Ball', category: 'Cricket', hints: ['Electric Tape', 'Pakistan Street', 'Tennis Ball Wrapped', 'Swing', 'Gully'] },
    { word: 'Book Cricket', category: 'Cricket', hints: ['Pages Score', 'Classroom Game', 'Even Odd', 'School Time', 'Textbook'] },
    { word: 'Pitch Report', category: 'Cricket', hints: ['Before Match', 'Curator Chat', 'Grass Cover', 'Cracks', 'Sunny Gavaskar'] },
    { word: 'Last Over Finish', category: 'Cricket', hints: ['Nail Biter', 'Thriller', 'Heart Rate', 'Edge of Seat', 'Six Needed'] },
    { word: 'Commentary Box', category: 'Cricket', hints: ['Broadcast', 'Mic On', 'Expert Panel', 'Voice Over', 'Studio'] },
    { word: 'Dressing Room', category: 'Cricket', hints: ['Team Space', 'Padded Up', 'Locker', 'Before Batting', 'Private'] },
    { word: 'Team Huddle', category: 'Cricket', hints: ['Circle', 'Before Play', 'Strategy Talk', 'Captain Leads', 'Motivate'] },
    { word: 'Victory Lap', category: 'Cricket', hints: ['After Winning', 'Trophy Hold', 'Celebration', 'Stadium Round', 'Flag Wave'] },
    { word: 'Coin Toss', category: 'Cricket', hints: ['Before Match', 'Heads Tails', 'Captain Call', 'Bat or Bowl', 'Center Pitch'] },
    { word: 'Drinks Break', category: 'Cricket', hints: ['Hydration', 'Mid Session', 'Twelfth Man', 'Towel Water', 'Hot Day'] },
    { word: 'Tea Interval', category: 'Cricket', hints: ['Test Match', 'Twenty Minutes', 'Between Sessions', 'Traditional', 'English'] },
    { word: 'Lunch Break', category: 'Cricket', hints: ['Test Match', 'Forty Minutes', 'Mid Day', 'Session Gap', 'First Half'] },
    { word: 'Rain Delay', category: 'Cricket', hints: ['Covers On', 'Duckworth Lewis', 'Waiting', 'England Weather', 'Play Stopped'] },
    { word: 'Bad Light', category: 'Cricket', hints: ['Umpire Offer', 'Players Walk Off', 'Light Meter', 'Evening', 'Test Match'] },
    { word: 'Pitch Invasion', category: 'Cricket', hints: ['Fan Runs On', 'Security Chase', 'After Victory', 'Crowd Rush', 'Banned'] },
    { word: 'Barmy Army', category: 'Cricket', hints: ['England Fans', 'Singing Group', 'Travel Away', 'Trumpeter', 'Passionate'] },
    { word: 'Bharat Army', category: 'Cricket', hints: ['India Fans', 'Away Support', 'Blue Jersey', 'Dhol Beats', 'Travel Group'] },
    { word: 'Mexican Wave', category: 'Cricket', hints: ['Stadium Crowd', 'Stand Up Sit', 'Boring Match', 'Full House', 'Wave Around'] },
    { word: 'Dhol at Stadium', category: 'Cricket', hints: ['Drum Beats', 'Indian Crowd', 'Atmosphere', 'Cheer', 'Boundary Six'] },
    { word: 'Trumpet Guy', category: 'Cricket', hints: ['Barmy Army', 'Music Crowd', 'England Matches', 'Horn Sound', 'Stadium'] },
    { word: 'Cricket ka Mecca', category: 'Cricket', hints: ['Lords', 'Home of Cricket', 'Holy Ground', 'London', 'Pilgrimage'] },
    { word: 'Beach Cricket', category: 'Cricket', hints: ['Sand', 'Holiday Game', 'Goa', 'Casual', 'Waves Nearby'] },
    { word: 'Tennis Ball Cricket', category: 'Cricket', hints: ['Green Ball', 'Local Matches', 'Night Cricket', 'Tournaments', 'Rubber'] },
    { word: 'Box Cricket', category: 'Cricket', hints: ['Indoor', 'Small Ground', 'Corporate', 'Net Walls', 'Five a Side'] },
    { word: 'Cosco Ball', category: 'Cricket', hints: ['Rubber', 'Practice Ball', 'Cheap', 'Local Brand', 'Green Yellow'] },
    { word: 'Season Ball', category: 'Cricket', hints: ['Leather', 'Real Cricket', 'Cork Inside', 'Seam', 'Red Shine'] },
    { word: 'SG Ball', category: 'Cricket', hints: ['Indian Made', 'Test Match', 'Sanspareils Greenlands', 'Red Leather', 'Domestic'] },
    { word: 'Kookaburra', category: 'Cricket', hints: ['Australian Ball', 'White Ball ODI', 'Less Seam', 'Bird Name', 'International'] },
    { word: 'Dukes Ball', category: 'Cricket', hints: ['England Ball', 'Prominent Seam', 'Swing Friendly', 'Red', 'County Cricket'] },
    { word: 'MRF Bat', category: 'Cricket', hints: ['Tyre Brand', 'Sachin Used', 'Indian Make', 'Kohli Sticker', 'Sponsor'] },
    { word: 'Gray Nicolls', category: 'Cricket', hints: ['Bat Brand', 'English Make', 'Scoop Design', 'Premium', 'Classic'] },
    { word: 'SS Bat', category: 'Cricket', hints: ['Sareen Sports', 'Indian Brand', 'Dhoni Used', 'Meerut', 'Willow'] },
    { word: 'Thigh Pad', category: 'Cricket', hints: ['Leg Protection', 'Under Pad', 'Fast Bowling', 'Inner Thigh', 'Safety'] },
    { word: 'Box Guard', category: 'Cricket', hints: ['Groin Protection', 'Essential', 'Hard Plastic', 'Safety First', 'Painful Without'] },
    { word: 'Batting Gloves', category: 'Cricket', hints: ['Hand Protection', 'Grip', 'Padded Fingers', 'White', 'Essential Gear'] },
    { word: 'Helmet Grill', category: 'Cricket', hints: ['Face Guard', 'Metal Bars', 'Head Protection', 'Titanium', 'Visor'] },
    { word: 'Arm Guard', category: 'Cricket', hints: ['Forearm Protection', 'Fast Bowling', 'Plastic Shield', 'Strapped On', 'Inner Arm'] },
    { word: 'Sight Screen', category: 'Cricket', hints: ['White Board', 'Behind Bowler', 'Batsman View', 'Moved for Angle', 'Background'] },
    { word: 'Heavy Roller', category: 'Cricket', hints: ['Pitch Press', 'Before Play', 'Flatten Surface', 'Ground Staff', 'Between Innings'] },
    { word: 'Pitch Curator', category: 'Cricket', hints: ['Ground Keeper', 'Surface Expert', 'Prepare Wicket', 'Water Roll', 'Specialist'] },
    { word: 'Green Top', category: 'Cricket', hints: ['Pace Wicket', 'Grass Cover', 'Seam Movement', 'Bowler Friendly', 'Moist'] },
    { word: 'Dustbowl', category: 'Cricket', hints: ['Dry Pitch', 'Spin Paradise', 'Day Five', 'Crumbling', 'Subcontinent'] },
    { word: 'Flat Track', category: 'Cricket', hints: ['Batting Paradise', 'No Help Bowler', 'Highway', 'High Score', 'Dead Pitch'] },
    { word: 'Rank Turner', category: 'Cricket', hints: ['Spin Wicket', 'Day One Turn', 'Controversial', 'Subcontinent', 'Square Turn'] },
    { word: 'Sticky Wicket', category: 'Cricket', hints: ['Rain Affected', 'Difficult Bat', 'Old Term', 'Uncovered', 'Tricky Surface'] },
    { word: 'Seaming Track', category: 'Cricket', hints: ['Movement Off Pitch', 'Green Tinge', 'Fast Bowler', 'Nip Around', 'England'] },
    { word: 'Day Night Test', category: 'Cricket', hints: ['Pink Ball', 'Floodlights', 'Evening Session', 'Modern Format', 'Twilight'] },
    { word: 'Pink Ball', category: 'Cricket', hints: ['Day Night', 'Visibility', 'SG Make', 'Lacquer Coating', 'Floodlight'] },
    { word: 'Red Ball', category: 'Cricket', hints: ['Test Cricket', 'Traditional', 'First Class', 'Day Game', 'Classic'] },
    { word: 'White Ball', category: 'Cricket', hints: ['Limited Overs', 'ODI T20', 'Kookaburra', 'Floodlight', 'Two New Balls'] },
    // ── Commentary & Media ──
    { word: 'Harsha Bhogle', category: 'Cricket', hints: ['Voice of Cricket', 'Indian Commentator', 'Hyderabad', 'Never Played', 'Storyteller'] },
    { word: 'Ravi Shastri', category: 'Cricket', hints: ['Tracer Bullet', 'Former Coach', 'Deep Voice', 'Champion of Champions', 'All Rounder'] },
    { word: 'Sanjay Manjrekar', category: 'Cricket', hints: ['Bits and Pieces', 'Mumbai', 'Controversial Takes', 'Former Batsman', 'Hindi Comms'] },
    { word: 'Tony Greig', category: 'Cricket', hints: ['South African English', 'Pitch Report Key', 'Tall', 'Channel Nine', 'WSC'] },
    { word: 'Richie Benaud', category: 'Cricket', hints: ['Marvellous', 'Australia Captain', 'Cream Jacket', 'Leg Spin', 'Broadcasting Legend'] },
    { word: 'Ian Bishop', category: 'Cricket', hints: ['West Indian', 'Remember the Name', 'Fast Bowler', 'Carlos Brathwaite Call', 'Trinidad'] },
    { word: 'Danny Morrison', category: 'Cricket', hints: ['New Zealand', 'Energetic', 'IPL Voice', 'Loud', 'Fast Bowler'] },
    { word: 'Cricbuzz', category: 'Cricket', hints: ['Live Score', 'App', 'Ball by Ball', 'Indian Platform', 'Commentary Text'] },
    { word: 'ESPNcricinfo', category: 'Cricket', hints: ['Stats Database', 'Statsguru', 'Cricket Bible', 'Records', 'Articles'] },
    { word: 'Star Sports', category: 'Cricket', hints: ['TV Channel', 'Indian Broadcast', 'Hindi English', 'IPL Rights', 'Disney'] },
    { word: 'Hotstar', category: 'Cricket', hints: ['Streaming', 'Disney Plus', 'Live Cricket', 'App', 'Indian Platform'] },
    { word: 'Willow TV', category: 'Cricket', hints: ['USA Streaming', 'Cricket Abroad', 'NRI Watching', 'Subscription', 'International'] },
    { word: 'Jio Cinema', category: 'Cricket', hints: ['IPL Streaming', 'Free Cricket', 'Reliance', 'App Watch', 'Digital'] },
    // ── Records & Numbers ──
    { word: 'Sachin 100 Hundreds', category: 'Cricket', hints: ['Century of Centuries', 'International Record', 'Test ODI Combined', 'March 2012', 'Asia Cup'] },
    { word: 'Murali 800 Wickets', category: 'Cricket', hints: ['Test Record', 'Sri Lanka', 'Spin Legend', 'Most Ever', 'Doosra'] },
    { word: 'Bradman 99.94', category: 'Cricket', hints: ['Test Average', 'Australia', 'Best Ever', 'Duck Last Innings', 'The Don'] },
    { word: 'Lara 501', category: 'Cricket', hints: ['First Class', 'Warwickshire', 'Not Out', 'Durham Bowlers', 'County Record'] },
    { word: 'Rohit 264', category: 'Cricket', hints: ['ODI Record', 'Sri Lanka', 'Kolkata', 'Hitman Best', 'Double Century'] },
    { word: 'Gayle 175', category: 'Cricket', hints: ['IPL Record', 'RCB', 'Pune Destroyed', 'Fastest', 'Sixes Galore'] },
    { word: 'Fastest Fifty', category: 'Cricket', hints: ['12 Balls', 'Yuvraj', 'Speed Record', 'Quick Scoring', 'T20'] },
    { word: 'Fastest Century', category: 'Cricket', hints: ['AB de Villiers', '31 Balls', 'ODI Record', 'Speed', 'Destructive'] },
    { word: 'Most Sixes', category: 'Cricket', hints: ['Power Hitting', 'Gayle', 'Career Record', 'Over Boundary', 'Big Hitter'] },
    { word: 'Most Ducks', category: 'Cricket', hints: ['Zero Runs', 'Shameful Record', 'Courtney Walsh', 'Out First Ball', 'Unwanted'] },
    { word: 'Highest Chase', category: 'Cricket', hints: ['Fourth Innings', 'Record Target', 'Test Cricket', 'Historic Win', 'Impossible Made Possible'] },
    { word: 'Lowest All Out', category: 'Cricket', hints: ['36 All Out', 'India Adelaide', 'Embarrassing', 'Collapsed', 'Pink Ball'] },
    { word: 'Perfect 10', category: 'Cricket', hints: ['All Wickets', 'One Bowler', 'Kumble', 'Innings Record', 'Clean Sweep'] },
  ],
};
