import type { WordPack } from '../game/types';

export const cricketPack: WordPack = {
  id: 'cricket',
  name: 'Cricket',
  entries: [
    { word: 'Sachin Tendulkar', category: 'Cricket' },
    { word: 'MS Dhoni', category: 'Cricket' },
    { word: 'Virat Kohli', category: 'Cricket' },
    { word: 'Jasprit Bumrah', category: 'Cricket' },
    { word: 'Rohit Sharma', category: 'Cricket' },
    { word: 'Gully Cricket', category: 'Cricket' },
    { word: 'Helicopter Shot', category: 'Cricket' },
    { word: 'Reverse Sweep', category: 'Cricket' },
    { word: 'Yorker', category: 'Cricket' },
    { word: 'Googly', category: 'Cricket' },
    { word: 'LBW', category: 'Cricket' },
    { word: 'Sixer', category: 'Cricket' },
    { word: 'Duck', category: 'Cricket' },
    { word: 'Hat Trick', category: 'Cricket' },
    { word: 'Wankhede Stadium', category: 'Cricket' },
    { word: 'Eden Gardens', category: 'Cricket' },
    { word: 'Chinnaswamy', category: 'Cricket' },
    { word: 'IPL Auction', category: 'Cricket' },
    { word: 'Super Over', category: 'Cricket' },
    { word: 'Third Umpire', category: 'Cricket' },
    { word: 'DRS Review', category: 'Cricket' },
    { word: 'Powerplay', category: 'Cricket' },
    { word: 'Maiden Over', category: 'Cricket' },
    { word: 'Spin Bowling', category: 'Cricket' },
    { word: 'Doosra', category: 'Cricket' },
    { word: 'Boundary Line', category: 'Cricket' },
    { word: 'Night Watchman', category: 'Cricket' },
    { word: 'Pitch Report', category: 'Cricket' },
    { word: 'Tape Ball', category: 'Cricket' },
    { word: 'Last Over Finish', category: 'Cricket' },
    { word: 'Sledging', category: 'Cricket' },
    { word: 'Cover Drive', category: 'Cricket' },
    { word: 'Pull Shot', category: 'Cricket' },
    { word: 'Mankad', category: 'Cricket' },
    { word: 'Run Out', category: 'Cricket' },
    { word: 'Kapil Dev', category: 'Cricket' },
    { word: 'Rahul Dravid', category: 'Cricket' },
    { word: 'Orange Cap', category: 'Cricket' },
    { word: 'Purple Cap', category: 'Cricket' },
    { word: 'Book Cricket', category: 'Cricket' },
  ],
};
