import type { WordPack } from '../game/types';

export const desiPack: WordPack = {
  id: 'desi',
  name: 'Desi Life',
  entries: [
    // ── Original 40 ──
    { word: 'Auto Rickshaw', category: 'Desi Life', hints: ['Three Wheeler','Meter Down','Yellow Green','Jugaad Ride','Tuk Tuk'] },
    { word: 'Power Cut', category: 'Desi Life', hints: ['Darkness','Candle Light','Inverter On','Load Shedding','Generator Start'] },
    { word: 'Family Group Chat', category: 'Desi Life', hints: ['WhatsApp','Good Morning','Forward Message','Emoji Spam','Uncle Post'] },
    { word: 'Jugaad', category: 'Desi Life', hints: ['Hack','Desi Innovation','Shortcut','Makeshift','Creativity'] },
    { word: 'Rishta Aunty', category: 'Desi Life', hints: ['Matchmaker','Marriage Broker','Beta Settled','Biodata','Suitable Boy'] },
    { word: 'Dabbawala', category: 'Desi Life', hints: ['Mumbai Lunch','Tiffin Delivery','Train Network','Lunchbox','Six Sigma'] },
    { word: 'Tiffin Box', category: 'Desi Life', hints: ['Lunch Carrier','Steel Container','Four Tier','Roti Sabzi','Office Lunch'] },
    { word: 'Good Morning Message', category: 'Desi Life', hints: ['WhatsApp Forward','Flower Image','Blessing Text','Uncle Message','Daily Greeting'] },
    { word: 'Joint Family', category: 'Desi Life', hints: ['Big Household','Together Living','Elders Respect','Shared Kitchen','Multiple Generation'] },
    { word: 'Sharma Ji Ka Beta', category: 'Desi Life', hints: ['Comparison','Topper Kid','Ideal Son','Neighbour Boy','IIT Rank'] },
    { word: 'Tuition Class', category: 'Desi Life', hints: ['Extra Coaching','After School','Batch Study','Private Teacher','Homework Help'] },
    { word: 'Board Exams', category: 'Desi Life', hints: ['Tenth Twelfth','CBSE ICSE','Result Day','Percentage','Study Pressure'] },
    { word: 'Inverter', category: 'Desi Life', hints: ['Battery Backup','Power Bank','Luminous','Emergency Light','UPS System'] },
    { word: 'Cooler', category: 'Desi Life', hints: ['Desert Cooler','Water Pad','Summer Relief','Symphony','Khas Grass'] },
    { word: 'Pressure Cooker', category: 'Desi Life', hints: ['Whistle Sound','Three Seethi','Hawkins','Dal Rice','Steam Release'] },
    { word: 'Doorbell Camera', category: 'Desi Life', hints: ['Security','Video Ring','Visitor Alert','Smart Home','CCTV Entry'] },
    { word: 'Water Tanker', category: 'Desi Life', hints: ['Supply Truck','Blue Tank','Summer Crisis','Municipal','Boring Water'] },
    { word: 'Chappal Threat', category: 'Desi Life', hints: ['Mom Weapon','Flying Slipper','Discipline Tool','Hawai Warning','Aim Perfect'] },
    { word: 'Guest Room', category: 'Desi Life', hints: ['Spare Bedroom','Visitor Stay','Extra Mattress','Mehman Space','Sofa Bed'] },
    { word: 'Mehman', category: 'Desi Life', hints: ['Guest Visit','Unexpected Arrival','Chai Nashta','Relative Drop','Welcome Mat'] },
    { word: 'Train Reservation', category: 'Desi Life', hints: ['IRCTC Booking','Tatkal Queue','Wait List','Confirmed Seat','PNR Status'] },
    { word: 'General Dabba', category: 'Desi Life', hints: ['Unreserved Coach','Crowded Train','Standing Room','Cheap Ticket','Rush Hour'] },
    { word: 'Sabzi Wala', category: 'Desi Life', hints: ['Vegetable Vendor','Cart Push','Fresh Greens','Morning Market','Bargain Price'] },
    { word: 'Newspaper Boy', category: 'Desi Life', hints: ['Morning Delivery','Cycle Throw','Paper Route','Headlines Early','Subscription'] },
    { word: 'Colony Park', category: 'Desi Life', hints: ['Evening Walk','Kids Play','Bench Sitting','Morning Yoga','Aunty Gang'] },
    { word: 'Balcony Gossip', category: 'Desi Life', hints: ['Neighbour Chat','Tea Sipping','Overheard Talk','Drying Clothes','Evening View'] },
    { word: 'UPI Payment', category: 'Desi Life', hints: ['QR Scan','Digital Transfer','Cashless','Phone Banking','GPay Sound'] },
    { word: 'Chai Tapri', category: 'Desi Life', hints: ['Roadside Tea','Cutting Chai','Biscuit Dip','Adrak Elaichi','Standing Sip'] },
    { word: 'Morning Walk', category: 'Desi Life', hints: ['Park Rounds','Health Routine','Uncle Group','Track Suit','Early Rise'] },
    { word: 'Society Uncle', category: 'Desi Life', hints: ['Building Elder','Nosy Neighbor','Free Advice','Committee Head','Gate Watch'] },
    { word: 'Diwan Sofa', category: 'Desi Life', hints: ['Multipurpose Bed','Guest Seating','Living Room','Gadda Cover','Day Nap'] },
    { word: 'Steel Tumbler', category: 'Desi Life', hints: ['Silver Glass','Chai Cup','South Indian','Unbreakable','Metal Drink'] },
    { word: 'Plastic Chair', category: 'Desi Life', hints: ['Nilkamal','Garden Seat','Party Furniture','Stackable','White Red'] },
    { word: 'Ceiling Fan', category: 'Desi Life', hints: ['Three Blade','Regulator Speed','Summer Must','Usha Crompton','Wobble Sound'] },
    { word: 'School Assembly', category: 'Desi Life', hints: ['Prayer Morning','National Anthem','Line Up','News Reading','Principal Speech'] },
    { word: 'Tuck Shop', category: 'Desi Life', hints: ['Canteen Counter','Samosa Break','Recess Rush','Pocket Money','Chips Cola'] },
    { word: 'Rickshaw Ride', category: 'Desi Life', hints: ['Shared Seat','Meter Tamper','Bargain Fare','Short Distance','Three Seater'] },
    { word: 'Horn Please', category: 'Desi Life', hints: ['Truck Back','Road Sign','Loud Honk','Overtake Signal','Highway Paint'] },
    { word: 'Dhobi Ghat', category: 'Desi Life', hints: ['Washing Place','Clothes Cleaning','Ironing Service','Laundry Spot','Open Air Wash'] },
    { word: 'Aam Papad', category: 'Desi Life', hints: ['Mango Leather','Sweet Sour','Flat Sheet','Summer Snack','Dried Fruit'] },

    // ── Household & Home ──
    { word: 'Matka', category: 'Desi Life', hints: ['Clay Pot','Cool Water','Earthen Vessel','Kulhad Type','Natural Filter'] },
    { word: 'Atta Chakki', category: 'Desi Life', hints: ['Flour Mill','Wheat Grind','Neighbourhood Mill','Fresh Ground','Gehu Peesna'] },
    { word: 'Belan', category: 'Desi Life', hints: ['Rolling Pin','Roti Making','Wood Cylinder','Dough Flatten','Chapati Tool'] },
    { word: 'Chimta', category: 'Desi Life', hints: ['Tongs Metal','Roti Flip','Fire Pick','Kitchen Grip','Hot Handle'] },
    { word: 'Tawa', category: 'Desi Life', hints: ['Flat Pan','Roti Surface','Iron Griddle','Paratha Cook','Round Plate'] },
    { word: 'Kadhai', category: 'Desi Life', hints: ['Deep Pan','Frying Wok','Sabzi Pot','Iron Round','Tadka Vessel'] },
    { word: 'Jhadu', category: 'Desi Life', hints: ['Broom Sweep','Floor Clean','Grass Bundle','Daily Chore','Dust Clear'] },
    { word: 'Pocha', category: 'Desi Life', hints: ['Mop Floor','Wet Cloth','Cleaning Rag','Wipe Surface','Bucket Squeeze'] },
    { word: 'Bucket Bath', category: 'Desi Life', hints: ['Mug Pour','Water Save','Morning Wash','No Shower','Balti Mugga'] },
    { word: 'Geyser', category: 'Desi Life', hints: ['Water Heater','Hot Bath','Winter Must','Wall Mount','Electric Warm'] },
    { word: 'Mosquito Coil', category: 'Desi Life', hints: ['Green Spiral','Night Burn','Smoke Repel','Good Knight','Insect Guard'] },
    { word: 'All Out', category: 'Desi Life', hints: ['Liquid Repellent','Plugin Device','Mosquito Free','Night Protection','Electric Mat'] },
    { word: 'Godrej Almirah', category: 'Desi Life', hints: ['Steel Wardrobe','Lock Cupboard','Heavy Metal','Clothes Store','Locker Safe'] },
    { word: 'Bajaj Mixer', category: 'Desi Life', hints: ['Grinder Blend','Kitchen Appliance','Chutney Make','Motor Sound','Three Jar'] },
    { word: 'Aquaguard', category: 'Desi Life', hints: ['Water Purifier','RO Filter','Clean Drink','UV Treat','Eureka Forbes'] },
    { word: 'Sintex Tank', category: 'Desi Life', hints: ['Overhead Storage','Black Plastic','Roof Water','Supply Reserve','Building Top'] },
    { word: 'Washing Machine', category: 'Desi Life', hints: ['Laundry Spin','Auto Clean','LG Samsung','Top Load','Rinse Cycle'] },
    { word: 'Clothes Line', category: 'Desi Life', hints: ['Drying Wire','Terrace Rope','Peg Hang','Sunlight Dry','Wind Blow'] },
    { word: 'Naphthalene Balls', category: 'Desi Life', hints: ['Moth Repel','White Round','Camphor Smell','Cupboard Keep','Insect Away'] },
    { word: 'Agarbatti', category: 'Desi Life', hints: ['Incense Stick','Fragrance Smoke','Puja Burn','Sandalwood Scent','Temple Aroma'] },
    { word: 'Pooja Room', category: 'Desi Life', hints: ['Prayer Corner','Mandir Home','Diya Lit','Idol Shelf','Aarti Space'] },
    { word: 'Tulsi Plant', category: 'Desi Life', hints: ['Holy Basil','Courtyard Green','Sacred Leaf','Morning Water','Medicinal Herb'] },
    { word: 'Rangoli', category: 'Desi Life', hints: ['Floor Art','Colorful Pattern','Entrance Design','Festival Decor','Powder Draw'] },
    { word: 'Diya', category: 'Desi Life', hints: ['Oil Lamp','Clay Light','Diwali Glow','Cotton Wick','Evening Flame'] },
    { word: 'Lota', category: 'Desi Life', hints: ['Small Vessel','Water Pot','Brass Round','Temple Use','Pour Spout'] },
    { word: 'Spice Box', category: 'Desi Life', hints: ['Masala Dabba','Seven Section','Round Steel','Kitchen Essential','Haldi Mirch'] },
    { word: 'Pickle Jar', category: 'Desi Life', hints: ['Achaar Bottle','Glass Container','Oil Preserve','Mango Lime','Grandmother Recipe'] },
    { word: 'Papad Drying', category: 'Desi Life', hints: ['Rooftop Spread','Sun Bake','Urad Dal','Flat Disc','Season Stock'] },
    { word: 'Terrace Garden', category: 'Desi Life', hints: ['Rooftop Green','Pot Plants','Urban Farm','Balcony Extend','Herb Grow'] },
    { word: 'Charpai', category: 'Desi Life', hints: ['String Cot','Village Bed','Woven Frame','Outdoor Sleep','Afternoon Nap'] },
    { word: 'Durrie', category: 'Desi Life', hints: ['Floor Rug','Cotton Weave','Flat Carpet','Handmade Spread','Sitting Mat'] },
    { word: 'Sofa Cover', category: 'Desi Life', hints: ['Fabric Shield','Furniture Protect','Wash Replace','Pattern Print','Elastic Fit'] },
    { word: 'Table Cloth', category: 'Desi Life', hints: ['Dining Spread','Plastic Sheet','Food Cover','Print Floral','Wipe Clean'] },
    { word: 'Wall Clock', category: 'Desi Life', hints: ['Time Display','Pendulum Swing','Living Room','Battery Change','Tick Sound'] },
    { word: 'Calendar Photo', category: 'Desi Life', hints: ['God Image','Kitchen Wall','Date Tracker','New Year Gift','Monthly Flip'] },
    { word: 'Shoe Rack', category: 'Desi Life', hints: ['Entrance Stand','Chappal Shelf','Door Side','Footwear Organize','Bottom Tier'] },
    { word: 'Doorstopper', category: 'Desi Life', hints: ['Rubber Wedge','Door Hold','Wind Block','Floor Grip','Heavy Weight'] },
    { word: 'Voltage Stabilizer', category: 'Desi Life', hints: ['Power Guard','AC Protector','Fluctuation Fix','V-Guard Box','Surge Shield'] },
    { word: 'Extension Board', category: 'Desi Life', hints: ['Multi Plug','Power Strip','Socket Extra','Wire Length','Overload Risk'] },
    { word: 'Generator', category: 'Desi Life', hints: ['Backup Power','Diesel Run','Colony Shared','Noise Machine','DG Set'] },
    { word: 'Rooftop Antenna', category: 'Desi Life', hints: ['TV Signal','Cable Free','Dish Setup','Channel Catch','Direction Adjust'] },

    // ── Family & Relationships ──
    { word: 'Nani Ka Ghar', category: 'Desi Life', hints: ['Grandma House','Summer Holiday','Mango Tree','Cousin Fun','Village Visit'] },
    { word: 'Chacha', category: 'Desi Life', hints: ['Father Brother','Uncle Paternal','Family Elder','Same Surname','Nearby House'] },
    { word: 'Bua', category: 'Desi Life', hints: ['Father Sister','Paternal Aunt','Festival Visit','Gift Giver','Marriage Invite'] },
    { word: 'Mausi', category: 'Desi Life', hints: ['Mother Sister','Maternal Aunt','Close Bond','Second Mom','Holiday Stay'] },
    { word: 'Mama', category: 'Desi Life', hints: ['Mother Brother','Maternal Uncle','Wedding Role','Family Support','Nanaji Son'] },
    { word: 'Bhabhi', category: 'Desi Life', hints: ['Brother Wife','Sister In Law','Elder Respect','Family Bond','Rakhi Partner'] },
    { word: 'Saas Bahu Drama', category: 'Desi Life', hints: ['Mother Daughter Law','TV Serial','Kitchen Fight','Family Tension','Daily Soap'] },
    { word: 'Family Function', category: 'Desi Life', hints: ['Gathering Fest','Relative Meet','Big Dinner','Dance Floor','Photo Session'] },
    { word: 'Cousin Marriage', category: 'Desi Life', hints: ['Family Wedding','Known Since Birth','Relative Match','Community Custom','Close Kin'] },
    { word: 'Log Kya Kahenge', category: 'Desi Life', hints: ['Society Pressure','People Talk','Reputation Fear','Sharam Factor','Public Opinion'] },
    { word: 'Padosi Ki Ladki', category: 'Desi Life', hints: ['Next Door Girl','Comparison Target','Marriage Talk','Aunty Gossip','Rishta Topic'] },
    { word: 'Emotional Blackmail', category: 'Desi Life', hints: ['Guilt Trip','Tears Weapon','Heart Attack Threat','Silent Treatment','Drama Queen'] },
    { word: 'Kundli Matching', category: 'Desi Life', hints: ['Horoscope Check','Star Align','Pandit Reading','Guna Milan','Marriage Approve'] },
    { word: 'Arranged Marriage', category: 'Desi Life', hints: ['Family Choose','Biodata Exchange','First Meeting','Parent Approve','Matchmaking'] },
    { word: 'Tilak Ceremony', category: 'Desi Life', hints: ['Forehead Mark','Engagement Ritual','Groom Accept','Family Bless','Shagun Give'] },
    { word: 'Roka', category: 'Desi Life', hints: ['Engagement Fix','Pre Wedding','Family Agreement','Ring Exchange','Date Set'] },
    { word: 'Shagun Ka Lifafa', category: 'Desi Life', hints: ['Cash Envelope','Gift Money','Wedding Blessing','Lucky Amount','Odd Number'] },
    { word: 'Pehla Pyaar', category: 'Desi Life', hints: ['First Love','School Crush','Butterflies','Secret Letter','Heart Flutter'] },
    { word: 'Love Marriage', category: 'Desi Life', hints: ['Self Choose','Family Oppose','Court Wedding','Running Away','Own Decision'] },
    { word: 'Ghar Ka Khana', category: 'Desi Life', hints: ['Home Food','Mom Cooking','Roti Dal','No Outside','Tiffin Pack'] },
    { word: 'Beta Engineer Banega', category: 'Desi Life', hints: ['Career Pressure','IIT Dream','Parent Vision','Science Stream','Coaching Class'] },
    { word: 'Doctor Ya Lawyer', category: 'Desi Life', hints: ['Two Options','Safe Career','Parent Choice','Professional Dream','Secure Future'] },

    // ── School & College ──
    { word: 'PT Period', category: 'Desi Life', hints: ['Physical Training','Ground Play','Free Period','Sports Class','Running Laps'] },
    { word: 'Bunk Marna', category: 'Desi Life', hints: ['Skip Class','Absent Secret','Proxy Mark','Outside Roam','Teacher Dodge'] },
    { word: 'Back Bencher', category: 'Desi Life', hints: ['Last Row','Mischief Maker','Sleep Spot','Funny Guy','Teacher Radar'] },
    { word: 'First Bencher', category: 'Desi Life', hints: ['Front Row','Teacher Pet','Note Taker','Question Asker','Topper Seat'] },
    { word: 'Class Monitor', category: 'Desi Life', hints: ['Discipline Duty','Name List','Teacher Helper','Board Cleaner','Badge Wear'] },
    { word: 'Report Card Day', category: 'Desi Life', hints: ['Marks Reveal','Parent Sign','Rank Check','Red Ink','Result Fear'] },
    { word: 'Parent Teacher Meeting', category: 'Desi Life', hints: ['Complaint Session','Progress Report','Mom Visit','Behaviour Discuss','Marks Explain'] },
    { word: 'Homework Diary', category: 'Desi Life', hints: ['Assignment Book','Daily Task','Teacher Sign','Forget Excuse','Subject List'] },
    { word: 'Compass Box', category: 'Desi Life', hints: ['Geometry Set','Pencil Case','Eraser Sharpener','Scale Divider','School Pouch'] },
    { word: 'Cello Pen', category: 'Desi Life', hints: ['Blue Ink','Gel Write','Exam Favourite','Gripper Dot','Smooth Flow'] },
    { word: 'Camlin Colors', category: 'Desi Life', hints: ['Paint Box','Art Class','Watercolor Set','Drawing Period','Brush Palette'] },
    { word: 'Natraj Pencil', category: 'Desi Life', hints: ['Yellow Black','HB Grade','Eraser Tip','Sharpener Need','Writing Stick'] },
    { word: 'School Bus', category: 'Desi Life', hints: ['Yellow Vehicle','Morning Pickup','Driver Conductor','Route Number','Window Seat'] },
    { word: 'Canteen Samosa', category: 'Desi Life', hints: ['Break Snack','Hot Crispy','Recess Treat','Potato Fill','Green Chutney'] },
    { word: 'Annual Day', category: 'Desi Life', hints: ['Stage Show','Dance Drama','Parent Audience','Costume Wear','Certificate Prize'] },
    { word: 'Sports Day', category: 'Desi Life', hints: ['Track Race','House Competition','Medal Ceremony','March Past','Relay Sprint'] },
    { word: 'Republic Day Parade', category: 'Desi Life', hints: ['Flag Hoist','January 26','National Holiday','Cultural Show','Sweet Distribution'] },
    { word: 'Farewell Party', category: 'Desi Life', hints: ['Senior Goodbye','Saree Suit Day','Title Awards','Last Day School','Emotional Speech'] },
    { word: 'Ragging', category: 'Desi Life', hints: ['Senior Bully','First Year Fear','Introduction Round','Campus Terror','Anti Committee'] },
    { word: 'Hostel Room', category: 'Desi Life', hints: ['Shared Space','Bunk Bed','Night Study','Roommate Life','Warden Round'] },
    { word: 'Mess Food', category: 'Desi Life', hints: ['Canteen Meal','Bland Taste','Rice Dal Daily','Complaint Book','Sunday Special'] },
    { word: 'Study Leave', category: 'Desi Life', hints: ['Exam Prep','Home Revision','Last Minute','All Nighter','Syllabus Finish'] },
    { word: 'Xerox Shop', category: 'Desi Life', hints: ['Photocopy Centre','Print Station','Notes Copy','Spiral Bind','Lamination Service'] },
    { word: 'Last Bench Gang', category: 'Desi Life', hints: ['Back Row Squad','Mischief Group','Paper Throw','Gossip Circle','Fun Zone'] },
    { word: 'Proxy Attendance', category: 'Desi Life', hints: ['Fake Present','Friend Favour','Roll Call Cheat','Sign For Me','Voice Mimic'] },
    { word: 'Viva Exam', category: 'Desi Life', hints: ['Oral Test','Face To Face','Professor Question','Nervous Answer','Lab Practical'] },
    { word: 'Lab Manual', category: 'Desi Life', hints: ['Experiment Record','Observation Write','Graph Draw','Procedure Copy','Practical File'] },
    { word: 'Library Fine', category: 'Desi Life', hints: ['Late Return','Overdue Book','Penalty Slip','Renewal Forget','Card Stamp'] },
    { word: 'College Fest', category: 'Desi Life', hints: ['Cultural Event','Band Perform','Food Stall','Dance Battle','Sponsor Banner'] },
    { word: 'Campus Placement', category: 'Desi Life', hints: ['Job Interview','Company Visit','Package Offer','Dream Recruit','Final Year'] },

    // ── Childhood Games ──
    { word: 'Gilli Danda', category: 'Desi Life', hints: ['Stick Flip','Village Game','Street Play','Hit Fly','Wooden Bat'] },
    { word: 'Kho Kho', category: 'Desi Life', hints: ['Chase Tag','Sitting Line','Running Touch','Team Game','Ground Play'] },
    { word: 'Langdi', category: 'Desi Life', hints: ['One Leg Hop','Tag Game','Balance Chase','Playground Fun','Leg Lift'] },
    { word: 'Stapoo', category: 'Desi Life', hints: ['Hopscotch','Number Jump','Stone Throw','Grid Draw','One Foot'] },
    { word: 'Chhupan Chhupai', category: 'Desi Life', hints: ['Hide Seek','Count Hundred','Behind Tree','Found You','Den Safe'] },
    { word: 'Pittu Garam', category: 'Desi Life', hints: ['Stone Stack','Ball Throw','Seven Stones','Team Hit','Rebuild Tower'] },
    { word: 'Kancha', category: 'Desi Life', hints: ['Glass Marble','Aim Shoot','Round Ball','Collection Bag','Goti Game'] },
    { word: 'Lattu', category: 'Desi Life', hints: ['Spinning Top','String Wind','Wooden Toy','Balance Spin','Ground Trick'] },
    { word: 'Pithoo', category: 'Desi Life', hints: ['Stone Pile','Ball Break','Seven Stack','Team Chase','Rebuild Race'] },
    { word: 'Chain Chain', category: 'Desi Life', hints: ['Link Tag','Hold Hands','Growing Line','Catch Join','Group Chase'] },
    { word: 'Raja Mantri Chor', category: 'Desi Life', hints: ['Paper Chit','Role Pick','Point Score','Guess Who','Four Player'] },
    { word: 'Antakshari', category: 'Desi Life', hints: ['Song Game','Last Letter','Music Round','Team Sing','Bollywood Tune'] },
    { word: 'Ludo Board', category: 'Desi Life', hints: ['Dice Roll','Four Color','Home Safe','Star Space','Kill Piece'] },
    { word: 'Carrom Board', category: 'Desi Life', hints: ['Striker Flick','Queen Pocket','Powder Smooth','Corner Hole','Wood Board'] },
    { word: 'Trump Cards', category: 'Desi Life', hints: ['Top Trumps','Compare Stats','Card Deck','Cricket Player','Best Wins'] },
    { word: 'Cricket Gully', category: 'Desi Life', hints: ['Street Match','Tennis Ball','Boundary Wall','Out Rules','Six Roof'] },
    { word: 'Book Cricket', category: 'Desi Life', hints: ['Page Turn','Run Score','Even Odd','Classroom Game','Textbook Play'] },
    { word: 'Lock And Key', category: 'Desi Life', hints: ['Chase Catch','Freeze Free','Tag Variant','Touch Release','Running Game'] },
    { word: 'Poshampa', category: 'Desi Life', hints: ['Circle Song','Trap Game','Kids Ring','Fall Down','Choose Side'] },
    { word: 'Dog And The Bone', category: 'Desi Life', hints: ['Centre Grab','Team Rush','Hanky Pick','Sprint Back','Two Side'] },

    // ── Vehicles & Transport ──
    { word: 'Maruti 800', category: 'Desi Life', hints: ['First Car','White Small','Family Drive','Cheap Petrol','Iconic Hatch'] },
    { word: 'Splendor Bike', category: 'Desi Life', hints: ['Hero Honda','Mileage King','Common Two Wheeler','Black Silver','Daily Commute'] },
    { word: 'Activa Scooty', category: 'Desi Life', hints: ['Honda Scooter','Gearless Ride','Mom Vehicle','City Travel','Easy Balance'] },
    { word: 'Jugaad Vehicle', category: 'Desi Life', hints: ['Makeshift Transport','Diesel Engine','Village Truck','Desi Innovation','Tractor Mod'] },
    { word: 'Cycle Rickshaw', category: 'Desi Life', hints: ['Pedal Power','Old City','Slow Ride','Man Pull','Tourist Spot'] },
    { word: 'State Bus', category: 'Desi Life', hints: ['Government Route','Red Orange','Crowded Travel','Roadways','Long Distance'] },
    { word: 'Volvo Bus', category: 'Desi Life', hints: ['AC Luxury','Highway Travel','Sleeper Seat','Private Operator','Night Journey'] },
    { word: 'Tempo Traveller', category: 'Desi Life', hints: ['Group Van','Twelve Seater','Trip Vehicle','Pushback Seat','Family Tour'] },
    { word: 'Shared Auto', category: 'Desi Life', hints: ['Pool Ride','Fixed Route','Squeeze Seat','Ten Rupee','Stop Anywhere'] },
    { word: 'DTC Bus', category: 'Desi Life', hints: ['Delhi Transport','Red Bus','Metro Feeder','Bus Pass','Rush Hour'] },
    { word: 'Metro Train', category: 'Desi Life', hints: ['Underground Rail','Smart Card','Station Platform','Yellow Blue Line','AC Coach'] },
    { word: 'Local Train', category: 'Desi Life', hints: ['Mumbai Lifeline','First Class','Platform Jump','Season Pass','Rush Crowd'] },
    { word: 'Rajdhani Express', category: 'Desi Life', hints: ['Delhi Train','Premium Fast','Meal Included','Capital Connect','Night Journey'] },
    { word: 'Shatabdi Express', category: 'Desi Life', hints: ['Day Travel','Chair Car','Fast Express','Morning Departure','Business Route'] },
    { word: 'Sleeper Coach', category: 'Desi Life', hints: ['Bunk Bed Train','Night Travel','Chain Lock','Blue Sheet','TTE Check'] },
    { word: 'Upper Berth', category: 'Desi Life', hints: ['Top Bunk','Climb Up','No Window','Luggage Space','Sleep High'] },
    { word: 'Chai Wala Train', category: 'Desi Life', hints: ['Platform Seller','Garam Cup','Window Serve','Running Vendor','Kulhad Offer'] },
    { word: 'Platform Ticket', category: 'Desi Life', hints: ['Station Entry','Two Rupee','See Off','No Travel','Gate Pass'] },
    { word: 'Ola Cab', category: 'Desi Life', hints: ['App Ride','Book Online','Driver Cancel','Surge Price','Wait Time'] },
    { word: 'Tractor', category: 'Desi Life', hints: ['Farm Vehicle','Rural Transport','Green Machine','Field Plough','Diesel Engine'] },
    { word: 'Bullock Cart', category: 'Desi Life', hints: ['Ox Pull','Village Transport','Wooden Wheel','Slow Move','Hay Load'] },
    { word: 'Thela', category: 'Desi Life', hints: ['Hand Cart','Push Vendor','Street Stall','Wheel Platform','Fruit Sell'] },
    { word: 'Helicopter Taxi', category: 'Desi Life', hints: ['Air Travel','Short Hop','VIP Ride','Helipad Land','Premium Commute'] },
    { word: 'Two Wheeler', category: 'Desi Life', hints: ['Bike Scooter','Road Ride','Helmet Must','Petrol Fill','Daily Drive'] },
    { word: 'Triple Riding', category: 'Desi Life', hints: ['Three Seat','Traffic Fine','Family Squeeze','Balance Risk','Challan Worry'] },

    // ── Clothes & Fashion ──
    { word: 'Kurta Pajama', category: 'Desi Life', hints: ['Cotton Comfort','Festival Wear','Loose Fit','White Classic','Home Dress'] },
    { word: 'Salwar Kameez', category: 'Desi Life', hints: ['Suit Set','Dupatta Match','Daily Wear','Tailored Fit','Cotton Print'] },
    { word: 'Dupatta', category: 'Desi Life', hints: ['Scarf Drape','Shoulder Cover','Suit Match','Chiffon Silk','Pin Adjust'] },
    { word: 'Lungi', category: 'Desi Life', hints: ['Wrap Around','South Comfort','Check Pattern','Casual Home','Tied Knot'] },
    { word: 'Dhoti', category: 'Desi Life', hints: ['White Drape','Traditional Wrap','Cotton Long','Kurta Pair','Formal Ethnic'] },
    { word: 'Saree', category: 'Desi Life', hints: ['Six Yard','Drape Style','Pallu Pleat','Silk Cotton','Wedding Wear'] },
    { word: 'Bindi', category: 'Desi Life', hints: ['Forehead Dot','Red Round','Sticker Sheet','Matching Outfit','Married Sign'] },
    { word: 'Juttis', category: 'Desi Life', hints: ['Embroidered Shoe','Punjabi Footwear','Flat Slip On','Mirror Work','Rajasthani Craft'] },
    { word: 'Kolhapuri Chappal', category: 'Desi Life', hints: ['Leather Sandal','Maharashtrian Craft','Flat Sole','Brown Tan','Handmade Footwear'] },
    { word: 'Sherwani', category: 'Desi Life', hints: ['Groom Outfit','Long Coat','Wedding Formal','Embroidered Silk','Churidar Pair'] },
    { word: 'Lehenga', category: 'Desi Life', hints: ['Bridal Skirt','Heavy Work','Wedding Outfit','Choli Match','Red Gold'] },
    { word: 'Churidar', category: 'Desi Life', hints: ['Tight Bottom','Gathered Ankle','Kurta Pair','Slim Fit','Cotton Stretch'] },
    { word: 'Patiala Suit', category: 'Desi Life', hints: ['Pleated Salwar','Punjabi Style','Loose Drape','Phulkari Top','Broad Fold'] },
    { word: 'Nehru Jacket', category: 'Desi Life', hints: ['Sleeveless Coat','Formal Layer','Mandarin Collar','Modi Style','Ethnic Blazer'] },
    { word: 'Pagdi', category: 'Desi Life', hints: ['Turban Wrap','Head Cover','Rajasthani Style','Wedding Groom','Honor Symbol'] },
    { word: 'Mojri', category: 'Desi Life', hints: ['Pointed Shoe','Ethnic Footwear','Thread Work','Rajasthani Pair','Curled Toe'] },
    { word: 'Bandhani Fabric', category: 'Desi Life', hints: ['Tie Dye','Dot Pattern','Gujarati Craft','Colorful Cloth','Festival Material'] },
    { word: 'Phulkari', category: 'Desi Life', hints: ['Flower Embroidery','Punjabi Craft','Bright Thread','Dupatta Design','Hand Stitch'] },
    { word: 'Chikan Embroidery', category: 'Desi Life', hints: ['Lucknow Craft','White Thread','Delicate Stitch','Cotton Fabric','Mughal Style'] },
    { word: 'Mehndi Design', category: 'Desi Life', hints: ['Henna Art','Hand Pattern','Wedding Ritual','Bride Palm','Dark Stain'] },

    // ── Wedding ──
    { word: 'Baraat', category: 'Desi Life', hints: ['Groom Procession','Band Baja','Horse Ride','Dance Walk','Wedding Entry'] },
    { word: 'Ghodi', category: 'Desi Life', hints: ['White Horse','Groom Mount','Wedding Ride','Decorated Animal','Procession Lead'] },
    { word: 'DJ Wala', category: 'Desi Life', hints: ['Music System','Loud Speaker','Wedding Beats','Dance Floor','Bass Drop'] },
    { word: 'Dulhan Entry', category: 'Desi Life', hints: ['Bride Walk','Flower Shower','Slow Motion','Emotional Moment','Phoolon Ki'] },
    { word: 'Mandap', category: 'Desi Life', hints: ['Wedding Stage','Fire Altar','Four Pillar','Flower Decor','Sacred Space'] },
    { word: 'Phera', category: 'Desi Life', hints: ['Seven Round','Fire Circle','Vow Take','Bride Groom','Sacred Walk'] },
    { word: 'Vidaai', category: 'Desi Life', hints: ['Bride Farewell','Emotional Goodbye','Rice Throw','Car Departure','Crying Moment'] },
    { word: 'Haldi Ceremony', category: 'Desi Life', hints: ['Turmeric Paste','Yellow Smear','Pre Wedding','Skin Glow','Fun Ritual'] },
    { word: 'Sangeet Night', category: 'Desi Life', hints: ['Dance Party','Family Perform','Choreography','Music Night','Bollywood Song'] },
    { word: 'Joota Churai', category: 'Desi Life', hints: ['Shoe Steal','Bride Side','Ransom Demand','Groom Search','Fun Tradition'] },
    { word: 'Wedding Card', category: 'Desi Life', hints: ['Invitation Print','Gold Foil','Sweet Box','Guest List','Date Venue'] },
    { word: 'Pandit Ji', category: 'Desi Life', hints: ['Priest','Mantra Chant','Sacred Ritual','Hindu Ceremony','Puja Lead'] },
    { word: 'Varmala', category: 'Desi Life', hints: ['Garland Exchange','Flower Necklace','Bride Groom','Lift Up','First Ritual'] },
    { word: 'Sindoor', category: 'Desi Life', hints: ['Vermillion Red','Parting Fill','Married Symbol','Groom Apply','Sacred Mark'] },
    { word: 'Mangalsutra', category: 'Desi Life', hints: ['Gold Necklace','Black Bead','Marriage Symbol','Wife Wear','Sacred Thread'] },
    { word: 'Dahej', category: 'Desi Life', hints: ['Dowry Give','Marriage Gift','Family Demand','Social Evil','Cash Kind'] },
    { word: 'Reception Party', category: 'Desi Life', hints: ['Post Wedding','Guest Dinner','Stage Photo','Couple Entry','Buffet Hall'] },
    { word: 'Wedding Photographer', category: 'Desi Life', hints: ['Candid Shot','Pre Wedding Shoot','Album Make','Drone Fly','Couple Pose'] },
    { word: 'Tent House', category: 'Desi Life', hints: ['Shamiana Setup','Event Decor','Chair Table','Flower Stage','Light String'] },
    { word: 'Catering Wala', category: 'Desi Life', hints: ['Food Service','Bulk Cook','Paneer Dish','Buffet Line','Sweet Counter'] },

    // ── Street & Market ──
    { word: 'Paan Wala', category: 'Desi Life', hints: ['Betel Leaf','Red Mouth','Corner Shop','Supari Mix','Meetha Plain'] },
    { word: 'Golgappa Stall', category: 'Desi Life', hints: ['Pani Puri','Water Shot','Crispy Shell','Tangy Fill','Street Corner'] },
    { word: 'Chaat Counter', category: 'Desi Life', hints: ['Tangy Snack','Papdi Mix','Sweet Sour','Curd Topping','Evening Bite'] },
    { word: 'Juice Wala', category: 'Desi Life', hints: ['Fresh Squeeze','Sugarcane Cart','Orange Mosambi','Blender Mix','Glass Serve'] },
    { word: 'Kulfi Wala', category: 'Desi Life', hints: ['Frozen Cream','Matka Shape','Malai Pista','Stick Lick','Summer Treat'] },
    { word: 'Ice Gola', category: 'Desi Life', hints: ['Shaved Ice','Color Syrup','Stick Hold','Rainbow Cup','Brain Freeze'] },
    { word: 'Kirana Store', category: 'Desi Life', hints: ['Grocery Shop','Monthly Ration','Small Store','Udhaar Book','Daily Need'] },
    { word: 'Medical Store', category: 'Desi Life', hints: ['Pharmacy Counter','OTC Medicine','Prescription Fill','Chemist Shop','Night Open'] },
    { word: 'STD Booth', category: 'Desi Life', hints: ['Phone Call','Yellow Sign','Coin Insert','ISD Rate','Old Days'] },
    { word: 'Cyber Cafe', category: 'Desi Life', hints: ['Internet Shop','Hourly Rate','Gaming Zone','Print Scan','Browse Email'] },
    { word: 'Chor Bazaar', category: 'Desi Life', hints: ['Thief Market','Cheap Deal','Second Hand','Bargain Hunt','Stolen Goods'] },
    { word: 'Sunday Market', category: 'Desi Life', hints: ['Weekly Bazaar','Cheap Clothes','Street Setup','Temporary Stall','Bargain Day'] },
    { word: 'Mandi', category: 'Desi Life', hints: ['Wholesale Market','Vegetable Fruit','Bulk Buy','Early Morning','Truck Load'] },
    { word: 'Rehri Wala', category: 'Desi Life', hints: ['Cart Vendor','Street Seller','Push Mobile','Roadside Shop','Walking Store'] },
    { word: 'Nukkad', category: 'Desi Life', hints: ['Street Corner','Gathering Spot','Tea Stall','Chat Point','Meeting Place'] },
    { word: 'Barber Shop', category: 'Desi Life', hints: ['Hair Cut','Shave Trim','Mirror Chair','Powder Brush','Saloon Board'] },
    { word: 'Tailoring Shop', category: 'Desi Life', hints: ['Stitch Master','Measure Tape','Fitting Trial','Alter Hem','Sewing Machine'] },
    { word: 'Photostat', category: 'Desi Life', hints: ['Copy Machine','Document Print','ID Proof','Both Side','Reduced Size'] },
    { word: 'Redi Wala', category: 'Desi Life', hints: ['Cart Push','Street Food','Mobile Stall','Evening Snack','Roadside Sell'] },
    { word: 'Kabadiwala', category: 'Desi Life', hints: ['Scrap Dealer','Old Paper','Recycle Buy','Weight Scale','Sunday Visit'] },

    // ── Office & Work ──
    { word: 'Chai Break', category: 'Desi Life', hints: ['Tea Time','Office Pause','Gossip Session','Cutting Order','Biscuit Dip'] },
    { word: 'Pantry Gossip', category: 'Desi Life', hints: ['Office Kitchen','Water Cooler','Colleague Chat','Break Room','Whisper Talk'] },
    { word: 'Half Day Leave', category: 'Desi Life', hints: ['Short Absence','Afternoon Off','Manager Approve','Personal Work','Early Exit'] },
    { word: 'Casual Leave', category: 'Desi Life', hints: ['Day Off','CL Balance','Leave Apply','HR Portal','Reason Sick'] },
    { word: 'Notice Period', category: 'Desi Life', hints: ['Exit Time','Two Month','Serving Days','Buy Out','Handover Work'] },
    { word: 'Appraisal Cycle', category: 'Desi Life', hints: ['Review Season','Rating Star','Salary Hike','Self Assess','Manager Feedback'] },
    { word: 'TCS Offer Letter', category: 'Desi Life', hints: ['First Job','IT Company','Mass Recruit','Package CTC','Joining Date'] },
    { word: 'Infosys Training', category: 'Desi Life', hints: ['Mysore Campus','Foundation Program','Batch Mates','Six Month','Hostel Stay'] },
    { word: 'Wipro Campus', category: 'Desi Life', hints: ['IT Park','Sarjapur Road','Green Building','Tech Giant','Badge Entry'] },
    { word: 'Startup Culture', category: 'Desi Life', hints: ['Funding Round','Hustle Grind','Flat Hierarchy','Free Lunch','Equity Offer'] },
    { word: 'LinkedIn Post', category: 'Desi Life', hints: ['Professional Network','Humble Brag','Career Update','Agree Comment','Connection Add'] },
    { word: 'Resume Update', category: 'Desi Life', hints: ['CV Polish','Job Hunt','Experience Add','Skill List','Format Change'] },
    { word: 'Naukri Dot Com', category: 'Desi Life', hints: ['Job Portal','Profile Upload','Recruiter Call','Apply Now','Salary Filter'] },
    { word: 'Reference Check', category: 'Desi Life', hints: ['Background Verify','Past Manager','Character Vouch','Company Call','Employment History'] },
    { word: 'Cab Pickup', category: 'Desi Life', hints: ['Morning Ride','Office Transport','Driver Call','Drop Location','Carpool Share'] },
    { word: 'ID Card Lanyard', category: 'Desi Life', hints: ['Neck Badge','Employee Tag','Access Swipe','Photo Print','Building Entry'] },
    { word: 'Team Lunch', category: 'Desi Life', hints: ['Group Outing','Restaurant Bill','Manager Treat','Birthday Celebrate','Order Together'] },
    { word: 'Slack Message', category: 'Desi Life', hints: ['Work Chat','Channel Post','Thread Reply','Emoji React','DM Ping'] },
    { word: 'Standup Meeting', category: 'Desi Life', hints: ['Morning Sync','Quick Update','Yesterday Today','Blocker Share','Sprint Check'] },
    { word: 'Work From Home', category: 'Desi Life', hints: ['Remote Day','Laptop Bed','Video Call','Mute Mic','Background Blur'] },

    // ── Desi Parenting ──
    { word: 'Mummy Ki Daant', category: 'Desi Life', hints: ['Mother Scold','Lecture Session','Loud Voice','Guilt Trip','Ear Pull'] },
    { word: 'Papa Ka Gussa', category: 'Desi Life', hints: ['Father Angry','Silent Treatment','Belt Threat','Stern Look','Discipline Mode'] },
    { word: 'Pocket Money', category: 'Desi Life', hints: ['Weekly Cash','Allowance Give','Save Spend','Small Amount','Piggy Bank'] },
    { word: 'Curfew Time', category: 'Desi Life', hints: ['Home Before Dark','Night Limit','Parent Rule','Door Lock','Phone Check'] },
    { word: 'Mobile Phone Ban', category: 'Desi Life', hints: ['Screen Restrict','Study First','Confiscate Device','WiFi Cut','Exam Time'] },
    { word: 'WiFi Password', category: 'Desi Life', hints: ['Internet Access','Router Connect','Network Name','Family Share','Speed Slow'] },
    { word: 'Screen Time Limit', category: 'Desi Life', hints: ['Hour Restrict','App Timer','Digital Detox','Parent Control','Eye Strain'] },
    { word: 'Padhle Beta', category: 'Desi Life', hints: ['Study Now','Parent Pressure','Book Open','Exam Close','Career Focus'] },
    { word: 'IIT Coaching', category: 'Desi Life', hints: ['Kota Centre','Allen Fiitjee','Entrance Prep','Physics Chemistry','Rank Chase'] },
    { word: 'Kota Factory', category: 'Desi Life', hints: ['Coaching Hub','Student Town','Rajasthan City','JEE NEET','Hostel Life'] },
    { word: 'Olympiad Exam', category: 'Desi Life', hints: ['Competition Test','Extra Smart','Medal Certificate','School Level','Science Math'] },
    { word: 'Summer Vacation', category: 'Desi Life', hints: ['Long Holiday','May June','Mango Eat','Grandma House','No Homework'] },
    { word: 'Nani Ka Ghar Trip', category: 'Desi Life', hints: ['Grandma Visit','Train Journey','Cousin Meet','Village Stay','Summer Holiday'] },
    { word: 'Cartoon Network', category: 'Desi Life', hints: ['TV Channel','Kids Show','After School','Animation Watch','Remote Fight'] },
    { word: 'Shaka Laka Boom Boom', category: 'Desi Life', hints: ['Magic Pencil','DD Show','Sanju Character','Draw Real','Childhood Memory'] },
    { word: 'Malgudi Days', category: 'Desi Life', hints: ['Swami Friends','RK Narayan','Small Town','Doordarshan Classic','Simple Story'] },

    // ── Superstitions & Traditions ──
    { word: 'Nazar Ka Tika', category: 'Desi Life', hints: ['Evil Eye','Black Dot','Baby Forehead','Protection Mark','Kajal Apply'] },
    { word: 'Nimbu Mirchi', category: 'Desi Life', hints: ['Lemon Chilli','Door Hang','Evil Ward','Saturday Thread','Bad Luck Away'] },
    { word: 'Kala Billi', category: 'Desi Life', hints: ['Black Cat','Bad Omen','Cross Path','Superstition Fear','Wait Stop'] },
    { word: 'Shubh Muhurat', category: 'Desi Life', hints: ['Auspicious Time','Pandit Suggest','Calendar Check','Good Hour','Start Begin'] },
    { word: 'Puja Thali', category: 'Desi Life', hints: ['Worship Plate','Diya Flower','Roli Akshat','Steel Decorate','Ritual Set'] },
    { word: 'Aarti', category: 'Desi Life', hints: ['Lamp Circle','Song Prayer','Evening Ritual','Temple Routine','Flame Wave'] },
    { word: 'Prasad', category: 'Desi Life', hints: ['Holy Offering','Sweet Distribute','Temple Return','God Blessed','Fruit Sweet'] },
    { word: 'Mannat', category: 'Desi Life', hints: ['Wish Prayer','Vow Promise','Temple Ask','Thread Tie','Faith Request'] },
    { word: 'Tuesday Fast', category: 'Desi Life', hints: ['Hanuman Day','No Meat','Vrat Keep','Orange Wear','Temple Visit'] },
    { word: 'Satyanarayan Katha', category: 'Desi Life', hints: ['Puja Story','Family Gathering','Banana Leaf','Prasad Sweet','Monthly Ritual'] },
    { word: 'Griha Pravesh', category: 'Desi Life', hints: ['House Entry','New Home Puja','Milk Boil','Coconut Break','Havan Fire'] },
    { word: 'Vastu Shastra', category: 'Desi Life', hints: ['Direction Science','North East','Home Design','Energy Flow','Placement Rule'] },
    { word: 'Horoscope Check', category: 'Desi Life', hints: ['Star Sign','Daily Prediction','Rashi Read','Paper Column','Match Compare'] },
    { word: 'Pandit Consultation', category: 'Desi Life', hints: ['Priest Advice','Star Reading','Problem Solution','Gem Stone','Remedy Suggest'] },
    { word: 'Temple Visit', category: 'Desi Life', hints: ['Darshan Queue','Bell Ring','Shoe Remove','Prasad Take','Mandir Trip'] },

    // ── Food & Kitchen Habits ──
    { word: 'Dabba Party', category: 'Desi Life', hints: ['Tiffin Swap','Lunch Share','Office Group','Taste Try','Home Cook'] },
    { word: 'Leftover Roti', category: 'Desi Life', hints: ['Yesterday Bread','Morning Fry','Not Waste','Paratha Reheat','Desi Recycle'] },
    { word: 'Fridge Ka Dahi', category: 'Desi Life', hints: ['Cold Curd','Morning Bowl','Set Overnight','White Thick','Rice Mix'] },
    { word: 'Chai Ki Chuski', category: 'Desi Life', hints: ['Tea Sip','Hot Cup','Slow Drink','Morning Ritual','Adrak Flavor'] },
    { word: 'Nashta', category: 'Desi Life', hints: ['Breakfast Meal','Morning Bite','Poha Paratha','Before Work','Energy Start'] },
    { word: 'Lunch Ka Dabba', category: 'Desi Life', hints: ['Midday Box','Office Tiffin','Home Pack','Steel Container','Roti Sabzi'] },
    { word: 'Sunday Brunch', category: 'Desi Life', hints: ['Late Breakfast','Family Meal','Aloo Puri','Lazy Morning','Chole Bhature'] },
    { word: 'Maggi At Night', category: 'Desi Life', hints: ['Late Snack','Two Minute','Hostel Food','Quick Cook','Yellow Noodle'] },
    { word: 'Thali', category: 'Desi Life', hints: ['Full Plate','Multiple Bowl','Complete Meal','Roti Rice Dal','Round Steel'] },
    { word: 'Papad Fry', category: 'Desi Life', hints: ['Crispy Side','Roast Flame','Oil Deep','Meal Accompany','Urad Moong'] },
    { word: 'Mango Season', category: 'Desi Life', hints: ['Summer Fruit','Alphonso Hapus','Aam Ras','Yellow Sweet','Dozen Box'] },
    { word: 'Achaar Making', category: 'Desi Life', hints: ['Pickle Prepare','Oil Spice','Sun Dry','Glass Jar','Year Stock'] },
    { word: 'Mithai Box', category: 'Desi Life', hints: ['Sweet Package','Festival Gift','Ladoo Barfi','Halwai Shop','Celebration Treat'] },
    { word: 'Steel Plate', category: 'Desi Life', hints: ['Dinner Thali','Round Metal','Partition Section','Unbreakable Dish','Desi Dining'] },
    { word: 'Water Jug', category: 'Desi Life', hints: ['Surahi Shape','Table Pitcher','Cold Serve','Glass Fill','Steel Copper'] },

    // ── Brands & Products ──
    { word: 'Parle-G Biscuit', category: 'Desi Life', hints: ['Chai Dip','Yellow Pack','Baby Photo','Glucose Energy','Cheapest Treat'] },
    { word: 'Frooti', category: 'Desi Life', hints: ['Mango Drink','Tetra Pack','Fresh Juicy','Yellow Straw','School Canteen'] },
    { word: 'Rooh Afza', category: 'Desi Life', hints: ['Rose Syrup','Pink Drink','Ramadan Iftar','Summer Cool','Milk Mix'] },
    { word: 'Hajmola', category: 'Desi Life', hints: ['Digestive Tablet','Tangy Sour','After Meal','Imli Flavor','Small Round'] },
    { word: 'Bournvita', category: 'Desi Life', hints: ['Chocolate Milk','Health Drink','Brown Powder','Cadbury Make','Night Glass'] },
    { word: 'Amul Butter', category: 'Desi Life', hints: ['Utterly Butterly','Yellow Block','Bread Spread','Girl Logo','Morning Toast'] },
    { word: 'Nirma Washing Powder', category: 'Desi Life', hints: ['White White','Detergent Powder','Jingle Famous','Doodh Si','Bucket Wash'] },
    { word: 'Lifebuoy Soap', category: 'Desi Life', hints: ['Red Bar','Germ Kill','Handwash Brand','Health Clean','Tangy Smell'] },
    { word: 'Fevicol', category: 'Desi Life', hints: ['Strong Glue','Mazboot Jod','White Sticky','Pidilite Brand','Craft Stick'] },
    { word: 'Cello Tape', category: 'Desi Life', hints: ['Sticky Strip','Transparent Roll','Seal Pack','Tear Stick','Gift Wrap'] },
    { word: 'Britannia Cake', category: 'Desi Life', hints: ['Soft Sponge','Small Pack','Tea Time','Fruit Flavor','School Snack'] },
    { word: 'Kurkure', category: 'Desi Life', hints: ['Crispy Snack','Masala Crunch','Twisted Shape','Finger Food','PepsiCo Brand'] },
    { word: 'Haldiram Namkeen', category: 'Desi Life', hints: ['Bhujia Packet','Mixture Snack','Festival Munch','Yellow Green Pack','Bikaner Style'] },
    { word: 'MDH Masala', category: 'Desi Life', hints: ['Spice King','Deggi Mirch','Uncle Photo','Red Box','Asli Masale'] },
    { word: 'Patanjali', category: 'Desi Life', hints: ['Baba Ramdev','Ayurvedic Brand','Desi Product','Natural Herbal','Swadeshi'] },
    { word: 'Titan Watch', category: 'Desi Life', hints: ['Tata Brand','Wrist Time','Gift Classic','Raga Fastrack','Indian Make'] },
    { word: 'Bata Shoes', category: 'Desi Life', hints: ['School Shoe','Black White','Budget Footwear','Every Town','Canvas Tennis'] },
    { word: 'Raymond Suit', category: 'Desi Life', hints: ['Complete Man','Fabric Brand','Tailored Fit','Suiting Shirting','Premium Cloth'] },
    { word: 'Jio SIM', category: 'Desi Life', hints: ['Ambani Network','Free Data','4G Revolution','Reliance Telecom','Cheap Plan'] },
    { word: 'Paytm Wallet', category: 'Desi Life', hints: ['Digital Money','Scan Pay','Vijay Sharma','Cashback Offer','QR Code'] },

    // ── Slang & Social ──
    { word: 'Jugaad Fix', category: 'Desi Life', hints: ['Quick Patch','Temporary Solution','Desi Repair','Wire Tape','Make Do'] },
    { word: 'Time Pass', category: 'Desi Life', hints: ['Doing Nothing','Waste Hours','Bore Kill','Just Chilling','Scroll Phone'] },
    { word: 'Bakchodi', category: 'Desi Life', hints: ['Nonsense Talk','Useless Chat','Fun Banter','Friend Circle','Gupshup'] },
    { word: 'Chill Maar', category: 'Desi Life', hints: ['Relax Bro','Take Easy','No Tension','Cool Down','Laid Back'] },
    { word: 'Scene On Hai', category: 'Desi Life', hints: ['Plan Ready','Something Brewing','Its Happening','Good News','Confirmed'] },
    { word: 'Bindaas', category: 'Desi Life', hints: ['Carefree','Bold Move','No Worry','Fearless Style','Cool Attitude'] },
    { word: 'Desi Swag', category: 'Desi Life', hints: ['Indian Style','Attitude Walk','Confident Look','Street Cool','Local Vibes'] },
    { word: 'Fokat Ka Gyaan', category: 'Desi Life', hints: ['Free Advice','Unsolicited Wisdom','Know It All','Lecture Give','Opinion Force'] },
    { word: 'Saste Nashe', category: 'Desi Life', hints: ['Cheap Thrills','Bad Influence','Weird Idea','Crazy Plan','Funny Trip'] },
    { word: 'Wahiyat', category: 'Desi Life', hints: ['Terrible Bad','Useless Thing','No Standard','Low Quality','Rubbish Work'] },
    { word: 'Setting Lagana', category: 'Desi Life', hints: ['Arrange Fix','Connection Build','Romance Start','Contact Use','Network Play'] },
    { word: 'Panga', category: 'Desi Life', hints: ['Fight Pick','Trouble Start','Mess With','Challenge Take','Dare Confront'] },
    { word: 'Dhakkan', category: 'Desi Life', hints: ['Dim Person','Slow Thinker','Clueless One','Not Sharp','Lid Head'] },
    { word: 'Chamcha', category: 'Desi Life', hints: ['Sycophant Yes Man','Boss Flatter','Follow Blindly','Apple Polish','Favour Seeker'] },
    { word: 'Kanjoos', category: 'Desi Life', hints: ['Miser Cheap','Penny Pinch','Never Spend','Tight Fist','Budget Always'] },

    // ── Festivals Prep ──
    { word: 'Safai Drive', category: 'Desi Life', hints: ['Clean Campaign','Dust Sweep','Pre Festival','House Wash','Declutter Day'] },
    { word: 'Whitewash', category: 'Desi Life', hints: ['Wall Paint','Fresh Coat','Lime White','Annual Refresh','Festival Prep'] },
    { word: 'New Curtains', category: 'Desi Life', hints: ['Window Drape','Fresh Fabric','Room Makeover','Pattern Change','Festival Buy'] },
    { word: 'Bonus Month', category: 'Desi Life', hints: ['Extra Salary','Festival Gift','Company Reward','Diwali Special','Year End'] },
    { word: 'Diwali Shopping', category: 'Desi Life', hints: ['Festival Buy','New Clothes','Gift List','Market Rush','Discount Hunt'] },
    { word: 'Cracker Ban', category: 'Desi Life', hints: ['Firecracker Rule','Pollution Control','Court Order','Green Diwali','Noise Limit'] },
    { word: 'Kite Flying', category: 'Desi Life', hints: ['Makar Sankranti','String Cut','Rooftop Fun','Paper Colorful','Wind Catch'] },
    { word: 'Holi Colors', category: 'Desi Life', hints: ['Gulaal Throw','Water Balloon','Pink Green','Festival Play','Rang Barse'] },
    { word: 'Pichkari', category: 'Desi Life', hints: ['Water Gun','Holi Spray','Color Shoot','Plastic Pump','Festival Toy'] },
    { word: 'Thandai', category: 'Desi Life', hints: ['Cold Drink','Holi Special','Almond Milk','Bhang Mix','Spiced Sweet'] },
    { word: 'Ganesh Chaturthi', category: 'Desi Life', hints: ['Elephant God','Modak Offer','Visarjan Procession','Mumbai Pandal','Eco Friendly'] },
    { word: 'Durga Pandal', category: 'Desi Life', hints: ['Goddess Idol','Kolkata Style','Navratri Nights','Dhak Sound','Sindoor Play'] },
    { word: 'Navratri Garba', category: 'Desi Life', hints: ['Dance Night','Dandiya Stick','Nine Days','Gujarat Style','Circle Move'] },
    { word: 'Onam Sadya', category: 'Desi Life', hints: ['Kerala Feast','Banana Leaf','Payasam Sweet','Harvest Festival','Flower Carpet'] },
    { word: 'Lohri Bonfire', category: 'Desi Life', hints: ['Winter Fire','Punjab Festival','Popcorn Peanut','January Night','Bhangra Dance'] },

    // ── Digital & Modern ──
    { word: 'Instagram Reel', category: 'Desi Life', hints: ['Short Video','Trending Audio','Scroll Feed','Like Share','Content Create'] },
    { word: 'YouTube Tutorial', category: 'Desi Life', hints: ['How To Video','DIY Watch','Subscribe Bell','Step Guide','Learn Online'] },
    { word: 'WhatsApp Forward', category: 'Desi Life', hints: ['Chain Message','Fake News','Uncle Send','Morning Text','Viral Share'] },
    { word: 'Zomato Order', category: 'Desi Life', hints: ['Food Delivery','App Order','Restaurant Menu','Rider Track','Coupon Apply'] },
    { word: 'Swiggy Delivery', category: 'Desi Life', hints: ['Quick Food','Instamart Order','Delivery Boy','Online Meal','Late Night'] },
    { word: 'Amazon Sale', category: 'Desi Life', hints: ['Great Indian','Prime Deal','Cart Add','Lightning Offer','EMI Option'] },
    { word: 'Flipkart Big Day', category: 'Desi Life', hints: ['Big Billion','Online Shopping','Phone Deal','Flash Sale','Discount Fest'] },
    { word: 'Cred Points', category: 'Desi Life', hints: ['Credit Card Pay','Reward Earn','Cashback App','Premium Club','Member Perk'] },
    { word: 'PhonePe Sound Box', category: 'Desi Life', hints: ['Payment Alert','Audio Confirm','Merchant Device','Transaction Sound','Money Received'] },
    { word: 'Google Pay', category: 'Desi Life', hints: ['Tez Transfer','UPI Send','Scratch Card','Reward Earn','Bank Direct'] },
    { word: 'Aadhaar Card', category: 'Desi Life', hints: ['Twelve Digit','Biometric ID','Thumb Scan','UIDAI Issue','Identity Proof'] },
    { word: 'PAN Card', category: 'Desi Life', hints: ['Tax ID','Ten Character','Income Proof','Blue Laminate','Financial Link'] },
    { word: 'Passport Office', category: 'Desi Life', hints: ['Travel Document','Long Queue','Tatkal Apply','Blue Book','Police Verify'] },
    { word: 'Voter ID', category: 'Desi Life', hints: ['Election Card','Photo ID','Ink Finger','Booth Slip','EPIC Number'] },
    { word: 'IRCTC Tatkal', category: 'Desi Life', hints: ['Quick Book','Ten AM Rush','Premium Charge','Train Ticket','Instant Reserve'] },
    { word: 'DigiLocker', category: 'Desi Life', hints: ['Digital Document','Cloud Store','Government App','Paperless ID','Link Aadhaar'] },
    { word: 'Online Tuition', category: 'Desi Life', hints: ['Video Class','Home Study','Zoom Lecture','Digital Learn','Screen Teacher'] },
    { word: 'Unacademy Class', category: 'Desi Life', hints: ['EdTech Platform','Live Lesson','Educator Follow','Subscription Plan','Exam Prep'] },
    { word: 'ShareChat', category: 'Desi Life', hints: ['Regional App','Local Language','Meme Share','Indian Social','Vernacular Post'] },
    { word: 'Josh App', category: 'Desi Life', hints: ['Short Video','Desi TikTok','Trend Follow','Creator Hub','Viral Clip'] },

    // ── Miscellaneous Desi Life ──
    { word: 'Traffic Jam', category: 'Desi Life', hints: ['Road Block','Bumper Touch','Horn Noise','Late Office','Signal Wait'] },
    { word: 'Speed Breaker', category: 'Desi Life', hints: ['Road Hump','Slow Down','Car Bump','Unmarked Danger','Back Pain'] },
    { word: 'Pothole', category: 'Desi Life', hints: ['Road Hole','Monsoon Damage','Tire Burst','Swerve Avoid','Complaint File'] },
    { word: 'Toll Booth', category: 'Desi Life', hints: ['Highway Pay','FASTag Scan','Cash Lane','Barrier Lift','Receipt Print'] },
    { word: 'Chai Sutta Break', category: 'Desi Life', hints: ['Tea Cigarette','Office Escape','Staircase Spot','Quick Puff','Colleague Bond'] },
    { word: 'Jugaad Repair', category: 'Desi Life', hints: ['Quick Fix','Wire Tape','Temporary Patch','Desi Engineering','Make Work'] },
    { word: 'Load Shedding', category: 'Desi Life', hints: ['Power Cut Schedule','Dark Hours','Grid Failure','Area Wise','Summer Problem'] },
    { word: 'Water Shortage', category: 'Desi Life', hints: ['Dry Tap','Tanker Call','Summer Crisis','Bore Well','Ration Supply'] },
    { word: 'RO Filter', category: 'Desi Life', hints: ['Water Purify','TDS Check','UV Treat','Kent Aqua','Clean Drink'] },
    { word: 'Borewell', category: 'Desi Life', hints: ['Deep Drill','Ground Water','Motor Pump','Farm Supply','Underground Source'] },
    { word: 'Sarkari Naukri', category: 'Desi Life', hints: ['Government Job','Secure Career','Pension Life','UPSC SSC','Parent Dream'] },
    { word: 'Bank Queue', category: 'Desi Life', hints: ['Long Line','Token Number','Cash Deposit','Counter Window','Wait Patient'] },
    { word: 'Ration Card', category: 'Desi Life', hints: ['Subsidy Benefit','BPL APL','Fair Price','Government Issue','Family List'] },
    { word: 'Gas Cylinder', category: 'Desi Life', hints: ['LPG Booking','Blue Red','HP Indane','Kitchen Fuel','Delivery Day'] },
    { word: 'Milk Packet', category: 'Desi Life', hints: ['Morning Delivery','Amul Mother','Half Full','Boil Pour','White Pouch'] },
    { word: 'Newspaper Raddiwala', category: 'Desi Life', hints: ['Old Paper Sell','Weight Kilo','Monthly Collection','Recycle Cash','Scrap Buy'] },
    { word: 'Watchman', category: 'Desi Life', hints: ['Security Guard','Night Duty','Gate Open','Whistle Blow','Colony Patrol'] },
    { word: 'Society Meeting', category: 'Desi Life', hints: ['Resident Gather','AGM Annual','Complaint Discuss','Committee Vote','Maintenance Talk'] },
    { word: 'Maintenance Bill', category: 'Desi Life', hints: ['Monthly Fee','Society Charge','Flat Owner','Due Date','Penalty Late'] },
    { word: 'Electricity Bill', category: 'Desi Life', hints: ['BSES NDPL','Unit Charge','Meter Read','High Summer','Online Pay'] },
    { word: 'Rent Agreement', category: 'Desi Life', hints: ['Lease Sign','Eleven Month','Stamp Paper','Landlord Tenant','Deposit Advance'] },
    { word: 'PG Accommodation', category: 'Desi Life', hints: ['Paying Guest','Shared Room','Monthly Rent','Single Double','Meal Include'] },
    { word: 'Flat Hunting', category: 'Desi Life', hints: ['House Search','Property Site','Broker Visit','Budget Area','Shift Move'] },
    { word: 'Broker Fee', category: 'Desi Life', hints: ['Agent Commission','One Month Rent','Middle Man','Deal Negotiate','Property Show'] },
    { word: 'House Warming', category: 'Desi Life', hints: ['New Home Party','Griha Pravesh','Gift Bring','Guest Invite','Sweet Distribute'] },
  ],
};
