import type { WordPack } from '../game/types';

export const desiPack: WordPack = {
  id: 'desi',
  name: 'Desi Life',
  entries: [
    { word: 'Auto Rickshaw', category: 'Desi Life' },
    { word: 'Power Cut', category: 'Desi Life' },
    { word: 'Family Group Chat', category: 'Desi Life' },
    { word: 'Jugaad', category: 'Desi Life' },
    { word: 'Rishta Aunty', category: 'Desi Life' },
    { word: 'Dabbawala', category: 'Desi Life' },
    { word: 'Tiffin Box', category: 'Desi Life' },
    { word: 'Good Morning Message', category: 'Desi Life' },
    { word: 'Joint Family', category: 'Desi Life' },
    { word: 'Sharma Ji Ka Beta', category: 'Desi Life' },
    { word: 'Tuition Class', category: 'Desi Life' },
    { word: 'Board Exams', category: 'Desi Life' },
    { word: 'Inverter', category: 'Desi Life' },
    { word: 'Cooler', category: 'Desi Life' },
    { word: 'Pressure Cooker', category: 'Desi Life' },
    { word: 'Doorbell Camera', category: 'Desi Life' },
    { word: 'Water Tanker', category: 'Desi Life' },
    { word: 'Chappal Threat', category: 'Desi Life' },
    { word: 'Guest Room', category: 'Desi Life' },
    { word: 'Mehman', category: 'Desi Life' },
    { word: 'Train Reservation', category: 'Desi Life' },
    { word: 'General Dabba', category: 'Desi Life' },
    { word: 'Sabzi Wala', category: 'Desi Life' },
    { word: 'Newspaper Boy', category: 'Desi Life' },
    { word: 'Colony Park', category: 'Desi Life' },
    { word: 'Balcony Gossip', category: 'Desi Life' },
    { word: 'UPI Payment', category: 'Desi Life' },
    { word: 'Chai Tapri', category: 'Desi Life' },
    { word: 'Morning Walk', category: 'Desi Life' },
    { word: 'Society Uncle', category: 'Desi Life' },
    { word: 'Diwan Sofa', category: 'Desi Life' },
    { word: 'Steel Tumbler', category: 'Desi Life' },
    { word: 'Plastic Chair', category: 'Desi Life' },
    { word: 'Ceiling Fan', category: 'Desi Life' },
    { word: 'School Assembly', category: 'Desi Life' },
    { word: 'Tuck Shop', category: 'Desi Life' },
    { word: 'Rickshaw Ride', category: 'Desi Life' },
    { word: 'Horn Please', category: 'Desi Life' },
    { word: 'Dhobi Ghat', category: 'Desi Life' },
    { word: 'Aam Papad', category: 'Desi Life' },
  ],
};
