import type { WordPack } from '../game/types';

export const festivalsPack: WordPack = {
  id: 'festivals',
  name: 'Festivals',
  entries: [
    // ── Original 40 ──
    { word: 'Diwali', category: 'Festivals', hints: ['Lights', 'Crackers', 'Lakshmi Puja', 'Rangoli', 'Sweets'] },
    { word: 'Holi', category: 'Festivals', hints: ['Colors', 'Water Balloons', 'Thandai', 'Spring', 'Gulal'] },
    { word: 'Eid', category: 'Festivals', hints: ['Namaz', 'Sewaiyan', 'Moon Sighting', 'New Clothes', 'Charity'] },
    { word: 'Christmas', category: 'Festivals', hints: ['Santa Claus', 'Gifts', 'Carols', 'December', 'Plum Cake'] },
    { word: 'Pongal', category: 'Festivals', hints: ['Harvest', 'Tamil Nadu', 'January', 'Rice Pot', 'Sun God'] },
    { word: 'Onam', category: 'Festivals', hints: ['Kerala', 'Boat Race', 'Sadhya', 'Mahabali', 'Flower Carpet'] },
    { word: 'Baisakhi', category: 'Festivals', hints: ['Punjab', 'Wheat Harvest', 'April', 'Bhangra', 'Khalsa'] },
    { word: 'Navratri', category: 'Festivals', hints: ['Nine Nights', 'Garba', 'Dandiya', 'Durga', 'Fasting'] },
    { word: 'Durga Puja', category: 'Festivals', hints: ['Kolkata', 'Pandal', 'Sindoor Khela', 'Dashami', 'Dhunuchi'] },
    { word: 'Ganesh Chaturthi', category: 'Festivals', hints: ['Modak', 'Visarjan', 'Mumbai', 'Elephant God', 'Clay Idol'] },
    { word: 'Bihu', category: 'Festivals', hints: ['Assam', 'Dance', 'April', 'Gamosa', 'Jolpan'] },
    { word: 'Lohri', category: 'Festivals', hints: ['Bonfire', 'Punjab', 'January', 'Rewri', 'Popcorn'] },
    { word: 'Makar Sankranti', category: 'Festivals', hints: ['Kites', 'Til Gul', 'January', 'Harvest', 'Sun'] },
    { word: 'Raksha Bandhan', category: 'Festivals', hints: ['Brother Sister', 'Thread', 'August', 'Promise', 'Sweets'] },
    { word: 'Janmashtami', category: 'Festivals', hints: ['Krishna Birth', 'Midnight', 'Dahi Handi', 'Mathura', 'Flute'] },
    { word: 'Guru Purab', category: 'Festivals', hints: ['Sikh', 'Langar', 'Procession', 'Gurudwara', 'Prayer'] },
    { word: 'Nowruz', category: 'Festivals', hints: ['Persian New Year', 'Spring', 'March', 'Parsi', 'Feast'] },
    { word: 'Vishu', category: 'Festivals', hints: ['Kerala New Year', 'Kani', 'April', 'Gold Coins', 'Sadhya'] },
    { word: 'Ugadi', category: 'Festivals', hints: ['Telugu New Year', 'Pachadi', 'Spring', 'Neem', 'Jaggery'] },
    { word: 'Chhath Puja', category: 'Festivals', hints: ['Sun Worship', 'Bihar', 'River Bank', 'Thekua', 'Arghya'] },
    { word: 'Karva Chauth', category: 'Festivals', hints: ['Moon', 'Fasting', 'Husband', 'Sieve', 'Married Women'] },
    { word: 'Muharram', category: 'Festivals', hints: ['Tazia', 'Mourning', 'Procession', 'Karbala', 'First Month'] },
    { word: 'Good Friday', category: 'Festivals', hints: ['Cross', 'Jesus', 'Church', 'April', 'Crucifixion'] },
    { word: 'Buddha Purnima', category: 'Festivals', hints: ['Enlightenment', 'Bodh Gaya', 'May', 'Meditation', 'Peace'] },
    { word: 'Mahavir Jayanti', category: 'Festivals', hints: ['Jain', 'Non Violence', 'April', 'Procession', 'Temple'] },
    { word: 'Rangoli', category: 'Festivals', hints: ['Floor Art', 'Colors', 'Patterns', 'Doorstep', 'Powder'] },
    { word: 'Diyas', category: 'Festivals', hints: ['Oil Lamp', 'Clay', 'Wick', 'Row of Lights', 'Evening'] },
    { word: 'Fireworks', category: 'Festivals', hints: ['Sky', 'Crackers', 'Sparks', 'Night', 'Celebration'] },
    { word: 'Garba Raas', category: 'Festivals', hints: ['Circle Dance', 'Gujarat', 'Sticks', 'Music', 'Spinning'] },
    { word: 'Pandal Hopping', category: 'Festivals', hints: ['Kolkata', 'Durga Idols', 'Walking Tour', 'Crowds', 'Night Out'] },
    { word: 'Thaipusam', category: 'Festivals', hints: ['Tamil', 'Murugan', 'Kavadi', 'Piercing', 'Penance'] },
    { word: 'Puthandu', category: 'Festivals', hints: ['Tamil New Year', 'April', 'Mango', 'Neem', 'Kolam'] },
    { word: 'Mela', category: 'Festivals', hints: ['Fair', 'Stalls', 'Rides', 'Crowds', 'Fun'] },
    { word: 'Ladoo Distribution', category: 'Festivals', hints: ['Sweets', 'Celebration', 'Sharing', 'Box', 'Neighbors'] },
    { word: 'Kite Flying', category: 'Festivals', hints: ['String', 'Sky', 'Wind', 'Paper', 'Competition'] },
    { word: 'Dhol', category: 'Festivals', hints: ['Drum', 'Beats', 'Punjab', 'Dancing', 'Loud'] },
    { word: 'Langar', category: 'Festivals', hints: ['Free Kitchen', 'Gurudwara', 'Community', 'Serving', 'Equality'] },
    { word: 'Iftaar', category: 'Festivals', hints: ['Breaking Fast', 'Dates', 'Evening', 'Mosque', 'Ramadan'] },
    { word: 'Midnight Mass', category: 'Festivals', hints: ['Church', 'December', 'Carols', 'Candles', 'Prayer'] },
    { word: 'Visarjan', category: 'Festivals', hints: ['Immersion', 'Water', 'Procession', 'Goodbye', 'River'] },

    // ── Hindu festivals ──
    { word: 'Ram Navami', category: 'Festivals', hints: ['Lord Rama', 'April', 'Ayodhya', 'Bhajan', 'Fasting'] },
    { word: 'Hanuman Jayanti', category: 'Festivals', hints: ['Monkey God', 'Strength', 'April', 'Sindoor', 'Bajrang'] },
    { word: 'Maha Shivaratri', category: 'Festivals', hints: ['Shiva', 'Night Vigil', 'Fasting', 'Bel Patra', 'Milk'] },
    { word: 'Vasant Panchami', category: 'Festivals', hints: ['Saraswati', 'Yellow', 'Spring', 'Knowledge', 'February'] },
    { word: 'Govardhan Puja', category: 'Festivals', hints: ['Krishna', 'Mountain', 'Annakut', 'Food Offering', 'Cattle'] },
    { word: 'Bhai Dooj', category: 'Festivals', hints: ['Brother Sister', 'Tilak', 'Yamuna', 'November', 'Sweets'] },
    { word: 'Dhanteras', category: 'Festivals', hints: ['Gold Buying', 'Dhanvantari', 'Prosperity', 'Shopping', 'Utensils'] },
    { word: 'Narak Chaturdashi', category: 'Festivals', hints: ['Pre-Diwali', 'Oil Bath', 'Evil Defeat', 'Krishna', 'Dawn'] },
    { word: 'Tulsi Vivah', category: 'Festivals', hints: ['Holy Basil', 'Marriage', 'Vishnu', 'November', 'Plant'] },
    { word: 'Akshaya Tritiya', category: 'Festivals', hints: ['Gold', 'Auspicious', 'Never Ending', 'May', 'Charity'] },
    { word: 'Guru Purnima', category: 'Festivals', hints: ['Teacher', 'Full Moon', 'July', 'Respect', 'Vyasa'] },
    { word: 'Ganga Dussehra', category: 'Festivals', hints: ['River Ganges', 'Descent', 'June', 'Holy Dip', 'Varanasi'] },
    { word: 'Dussehra', category: 'Festivals', hints: ['Ravan Effigy', 'Victory', 'October', 'Ram', 'Burning'] },
    { word: 'Holika Dahan', category: 'Festivals', hints: ['Bonfire', 'Night Before', 'Evil Burns', 'Prahlad', 'Wood Pile'] },
    { word: 'Sharad Purnima', category: 'Festivals', hints: ['Autumn Moon', 'Kheer', 'Moonlight', 'October', 'Radha'] },
    { word: 'Kartik Purnima', category: 'Festivals', hints: ['Full Moon', 'November', 'Dev Diwali', 'Holy Dip', 'Lamp Float'] },
    { word: 'Vat Savitri', category: 'Festivals', hints: ['Banyan Tree', 'Married Women', 'Thread', 'Husband', 'Fasting'] },
    { word: 'Hartalika Teej', category: 'Festivals', hints: ['Parvati', 'Fasting', 'Shiva', 'Monsoon', 'Green'] },
    { word: 'Kajari Teej', category: 'Festivals', hints: ['Monsoon', 'Swings', 'Songs', 'Neem Tree', 'Women'] },
    { word: 'Ahoi Ashtami', category: 'Festivals', hints: ['Son', 'Mother', 'Fasting', 'Stars', 'Kartik'] },
    { word: 'Devshayani Ekadashi', category: 'Festivals', hints: ['Vishnu Sleeps', 'Monsoon', 'No Weddings', 'July', 'Fasting'] },
    { word: 'Prabodhini Ekadashi', category: 'Festivals', hints: ['Vishnu Wakes', 'November', 'Wedding Season', 'Kartik', 'Tulsi'] },
    { word: 'Vivah Panchami', category: 'Festivals', hints: ['Ram Sita', 'Marriage', 'December', 'Janakpur', 'Ceremony'] },
    { word: 'Putrada Ekadashi', category: 'Festivals', hints: ['Son Blessing', 'Fasting', 'Vishnu', 'Shravan', 'Prayers'] },
    { word: 'Narsingh Jayanti', category: 'Festivals', hints: ['Half Lion', 'Vishnu Avatar', 'May', 'Prahlad', 'Pillar'] },
    { word: 'Parshurama Jayanti', category: 'Festivals', hints: ['Axe Warrior', 'Vishnu Avatar', 'May', 'Brahmin', 'Renuka'] },
    { word: 'Anant Chaturdashi', category: 'Festivals', hints: ['Infinite', 'Thread', 'Vishnu', 'September', 'Last Day'] },
    { word: 'Sheetala Ashtami', category: 'Festivals', hints: ['Cooling', 'Goddess', 'Stale Food', 'No Cooking', 'Spring'] },
    { word: 'Kamada Ekadashi', category: 'Festivals', hints: ['Desire Fulfilling', 'April', 'Fasting', 'Vishnu', 'Love'] },
    { word: 'Vaikuntha Ekadashi', category: 'Festivals', hints: ['Heaven Gate', 'December', 'Vishnu Temple', 'Fasting', 'Queue'] },

    // ── Muslim festivals ──
    { word: 'Eid al-Fitr', category: 'Festivals', hints: ['End of Ramadan', 'Sewai', 'New Clothes', 'Namaz', 'Hugs'] },
    { word: 'Eid al-Adha', category: 'Festivals', hints: ['Sacrifice', 'Bakra', 'Abraham', 'Meat Sharing', 'Prayer'] },
    { word: 'Shab-e-Barat', category: 'Festivals', hints: ['Night Forgiveness', 'Halwa Puri', 'Graves Visit', 'Prayers', 'Fifteenth Night'] },
    { word: 'Milad-un-Nabi', category: 'Festivals', hints: ['Prophet Birthday', 'Procession', 'Green Flags', 'Naat', 'Sweets'] },
    { word: 'Shab-e-Qadr', category: 'Festivals', hints: ['Night of Power', 'Quran', 'Last Ten Nights', 'Prayer', 'Angels'] },
    { word: 'Ramadan', category: 'Festivals', hints: ['Fasting Month', 'Sehri', 'Taraweeh', 'Quran', 'Crescent'] },
    { word: 'Bakrid', category: 'Festivals', hints: ['Goat', 'Sacrifice', 'Abraham', 'Sharing Meat', 'Eid Prayer'] },
    { word: 'Shab-e-Meraj', category: 'Festivals', hints: ['Night Journey', 'Prophet', 'Ascension', 'Prayer', 'Heaven'] },
    { word: 'Jumma-tul-Vida', category: 'Festivals', hints: ['Last Friday', 'Ramadan', 'Mosque', 'Special Prayer', 'Crowded'] },
    { word: 'Alvida Namaz', category: 'Festivals', hints: ['Farewell Prayer', 'Ramadan End', 'Mosque', 'Tears', 'Dua'] },

    // ── Sikh festivals ──
    { word: 'Guru Nanak Jayanti', category: 'Festivals', hints: ['Sikh Founder', 'Langar', 'November', 'Prabhat Pheri', 'Gurudwara'] },
    { word: 'Guru Gobind Singh Jayanti', category: 'Festivals', hints: ['Tenth Guru', 'Khalsa', 'January', 'Martial Arts', 'Anandpur'] },
    { word: 'Hola Mohalla', category: 'Festivals', hints: ['Sikh Warriors', 'Anandpur', 'March', 'Mock Battles', 'Horse Riding'] },
    { word: 'Maghi', category: 'Festivals', hints: ['January', 'Sikh', 'Muktsar', 'Forty Martyrs', 'Holy Dip'] },
    { word: 'Nagar Kirtan', category: 'Festivals', hints: ['Procession', 'Holy Book', 'Streets', 'Singing', 'Sword Display'] },
    { word: 'Akhand Path', category: 'Festivals', hints: ['Continuous Reading', 'Guru Granth', 'Forty Eight Hours', 'Gurudwara', 'Devotion'] },
    { word: 'Khalsa Day', category: 'Festivals', hints: ['Sikh Identity', 'Five Ks', 'April', 'Turban', 'Sword'] },
    { word: 'Band Chhor Diwas', category: 'Festivals', hints: ['Sikh Freedom', 'Guru Hargobind', 'Gwalior Fort', 'Prisoners', 'Lights'] },

    // ── Christian festivals ──
    { word: 'Easter', category: 'Festivals', hints: ['Resurrection', 'Eggs', 'Bunny', 'Spring', 'Sunday'] },
    { word: 'Palm Sunday', category: 'Festivals', hints: ['Jesus Entry', 'Leaves', 'Donkey', 'Jerusalem', 'Week Before'] },
    { word: 'Ash Wednesday', category: 'Festivals', hints: ['Forehead Cross', 'Lent Start', 'Fasting', 'Repentance', 'Forty Days'] },
    { word: 'Lent', category: 'Festivals', hints: ['Fasting Period', 'Forty Days', 'Sacrifice', 'Before Easter', 'Prayer'] },
    { word: 'Advent', category: 'Festivals', hints: ['Four Weeks', 'Before Christmas', 'Wreath', 'Candles', 'Calendar'] },
    { word: 'Epiphany', category: 'Festivals', hints: ['Three Kings', 'January Sixth', 'Star', 'Gifts', 'Magi'] },
    { word: 'Pentecost', category: 'Festivals', hints: ['Holy Spirit', 'Tongues of Fire', 'Fifty Days', 'After Easter', 'Church'] },
    { word: 'All Saints Day', category: 'Festivals', hints: ['November', 'Departed Souls', 'Candles', 'Cemetery', 'Prayer'] },
    { word: 'Christmas Carol', category: 'Festivals', hints: ['Singing', 'Door to Door', 'December', 'Joy', 'Groups'] },
    { word: 'Nativity Scene', category: 'Festivals', hints: ['Manger', 'Baby Jesus', 'Stable', 'Shepherds', 'Star'] },

    // ── Buddhist / Jain ──
    { word: 'Paryushana', category: 'Festivals', hints: ['Jain', 'Eight Days', 'Forgiveness', 'Fasting', 'Monsoon'] },
    { word: 'Samvatsari', category: 'Festivals', hints: ['Forgiveness Day', 'Jain', 'Micchami Dukkadam', 'Last Day', 'Apology'] },
    { word: 'Vesak', category: 'Festivals', hints: ['Buddha Birthday', 'Full Moon', 'May', 'Lanterns', 'Bodhi Tree'] },
    { word: 'Ambedkar Jayanti', category: 'Festivals', hints: ['April Fourteenth', 'Constitution', 'Equality', 'Dalit Rights', 'Blue Flag'] },
    { word: 'Losar', category: 'Festivals', hints: ['Tibetan New Year', 'February', 'Monastery', 'Butter Tea', 'Dance'] },
    { word: 'Hemis Festival', category: 'Festivals', hints: ['Ladakh', 'Monastery', 'Mask Dance', 'June', 'Buddhist'] },
    { word: 'Saga Dawa', category: 'Festivals', hints: ['Buddha Enlightenment', 'Tibetan', 'June', 'Pilgrimage', 'Prayer Flags'] },

    // ── Regional festivals ──
    { word: 'Rath Yatra', category: 'Festivals', hints: ['Chariot', 'Puri', 'Jagannath', 'July', 'Rope Pulling'] },
    { word: 'Thrissur Pooram', category: 'Festivals', hints: ['Elephants', 'Kerala', 'April', 'Drums', 'Umbrellas'] },
    { word: 'Hampi Utsav', category: 'Festivals', hints: ['Ruins', 'Karnataka', 'November', 'Dance', 'Heritage'] },
    { word: 'Pushkar Fair', category: 'Festivals', hints: ['Camels', 'Rajasthan', 'November', 'Desert', 'Trading'] },
    { word: 'Surajkund Mela', category: 'Festivals', hints: ['Crafts', 'Haryana', 'February', 'Handicrafts', 'Food Stalls'] },
    { word: 'Hornbill Festival', category: 'Festivals', hints: ['Nagaland', 'December', 'Tribal Dance', 'Kohima', 'Heritage'] },
    { word: 'Wangala Festival', category: 'Festivals', hints: ['Meghalaya', 'Garo Tribe', 'Drum', 'Harvest', 'November'] },
    { word: 'Chapchar Kut', category: 'Festivals', hints: ['Mizoram', 'March', 'Bamboo Dance', 'Spring', 'Cheraw'] },
    { word: 'Moatsu Mong', category: 'Festivals', hints: ['Nagaland', 'Ao Tribe', 'May', 'Sowing', 'Feast'] },
    { word: 'Ziro Music Festival', category: 'Festivals', hints: ['Arunachal', 'Indie Music', 'September', 'Valley', 'Outdoor'] },
    { word: 'Losoong', category: 'Festivals', hints: ['Sikkim', 'December', 'New Year', 'Archery', 'Cham Dance'] },
    { word: 'Sangai Festival', category: 'Festivals', hints: ['Manipur', 'November', 'Dance', 'Deer', 'Cultural'] },
    { word: 'Me-Dam-Me-Phi', category: 'Festivals', hints: ['Assam', 'Ahom', 'Ancestors', 'January', 'Offerings'] },
    { word: 'Ambubachi Mela', category: 'Festivals', hints: ['Kamakhya', 'Assam', 'June', 'Tantric', 'Temple Closed'] },
    { word: 'Bonalu', category: 'Festivals', hints: ['Telangana', 'Goddess', 'Pot Offering', 'July', 'Procession'] },
    { word: 'Bathukamma', category: 'Festivals', hints: ['Flower Stack', 'Telangana', 'October', 'Women', 'Lake Immersion'] },
    { word: 'Sammakka Saralamma', category: 'Festivals', hints: ['Tribal Goddess', 'Telangana', 'Medaram', 'Jaggery', 'Biennial'] },
    { word: 'Mysore Dasara', category: 'Festivals', hints: ['Palace Lights', 'Karnataka', 'October', 'Elephant March', 'Jamboo Savari'] },
    { word: 'Navaratri Golu', category: 'Festivals', hints: ['Doll Display', 'Tamil Nadu', 'Steps', 'Nine Nights', 'Sundal'] },
    { word: 'Theyyam', category: 'Festivals', hints: ['Kerala', 'Ritual Dance', 'Face Paint', 'Trance', 'North Malabar'] },
    { word: 'Aranmula Boat Race', category: 'Festivals', hints: ['Kerala', 'Snake Boats', 'August', 'Oars', 'Pampa River'] },
    { word: 'Nehru Trophy', category: 'Festivals', hints: ['Boat Race', 'Kerala', 'Alleppey', 'August', 'Snake Boats'] },
    { word: 'Jallikattu', category: 'Festivals', hints: ['Bull Taming', 'Tamil Nadu', 'January', 'Pongal', 'Courage'] },
    { word: 'Thiruvathira', category: 'Festivals', hints: ['Kerala Women', 'Dance Circle', 'December', 'Shiva', 'Lamp'] },
    { word: 'Attukal Pongala', category: 'Festivals', hints: ['Women Gathering', 'Kerala', 'Open Fire', 'Rice Pot', 'Record'] },
    { word: 'Pooram Elephant', category: 'Festivals', hints: ['Kerala', 'Caparisoned', 'Umbrella Display', 'Drums', 'Temple'] },
    { word: 'Kullu Dussehra', category: 'Festivals', hints: ['Himachal', 'October', 'Raghunath', 'Seven Days', 'Valley'] },
    { word: 'Baisakhi Bhangra', category: 'Festivals', hints: ['Punjab Dance', 'April', 'Wheat', 'Drums', 'Turban'] },
    { word: 'Jat Jatra', category: 'Festivals', hints: ['Odisha', 'Tribal', 'Chariot', 'Procession', 'Harvest'] },
    { word: 'Hemis Tsechu', category: 'Festivals', hints: ['Ladakh', 'Mask Dance', 'Monastery', 'Padmasambhava', 'June'] },
    { word: 'Chhau Dance', category: 'Festivals', hints: ['Jharkhand', 'Mask', 'Martial Art', 'Storytelling', 'Tribal'] },
    { word: 'Jhulan Yatra', category: 'Festivals', hints: ['Swing', 'Radha Krishna', 'Monsoon', 'Flowers', 'Singing'] },
    { word: 'Dahi Handi', category: 'Festivals', hints: ['Human Pyramid', 'Mumbai', 'Pot Breaking', 'August', 'Krishna'] },
    { word: 'Nanda Devi Raj Jat', category: 'Festivals', hints: ['Uttarakhand', 'Pilgrimage', 'Himalayas', 'Twelve Years', 'Goddess'] },
    { word: 'Teej', category: 'Festivals', hints: ['Monsoon', 'Swings', 'Married Women', 'Green', 'Fasting'] },
    { word: 'Gangaur', category: 'Festivals', hints: ['Rajasthan', 'Gauri', 'Shiva Parvati', 'Procession', 'March'] },
    { word: 'Mewar Festival', category: 'Festivals', hints: ['Rajasthan', 'Udaipur', 'Spring', 'Lake', 'Cultural'] },
    { word: 'Desert Festival', category: 'Festivals', hints: ['Jaisalmer', 'Sand Dunes', 'Camel Race', 'February', 'Folk Music'] },
    { word: 'Marwar Festival', category: 'Festivals', hints: ['Jodhpur', 'October', 'Folk Music', 'Rajasthan', 'Heritage'] },
    { word: 'Camel Fair', category: 'Festivals', hints: ['Pushkar', 'Rajasthan', 'November', 'Trading', 'Desert'] },
    { word: 'Kambala', category: 'Festivals', hints: ['Buffalo Race', 'Karnataka', 'Paddy Field', 'Water', 'Tulunad'] },
    { word: 'Bisu Parba', category: 'Festivals', hints: ['Tulu New Year', 'Karnataka', 'April', 'Feast', 'New Clothes'] },
    { word: 'Yugadi Pachadi', category: 'Festivals', hints: ['Six Tastes', 'New Year', 'Neem', 'Jaggery', 'Telugu'] },
    { word: 'Gudhi Padwa', category: 'Festivals', hints: ['Maharashtra', 'New Year', 'March', 'Flag Pole', 'Shrikhand'] },
    { word: 'Gudi Raising', category: 'Festivals', hints: ['Pole', 'Cloth', 'Copper Pot', 'Morning', 'Maharashtra'] },
    { word: 'Poila Boishakh', category: 'Festivals', hints: ['Bengali New Year', 'April', 'Alpona', 'New Ledger', 'Ilish Fish'] },
    { word: 'Bohag Bihu', category: 'Festivals', hints: ['Assam New Year', 'April', 'Gamosa', 'Dance', 'Feast'] },
    { word: 'Magh Bihu', category: 'Festivals', hints: ['Harvest', 'Assam', 'January', 'Bonfire', 'Feast'] },
    { word: 'Kati Bihu', category: 'Festivals', hints: ['Assam', 'October', 'Lamp Lighting', 'Tulsi', 'Crop Prayer'] },
    { word: 'Nuakhai', category: 'Festivals', hints: ['Odisha', 'New Rice', 'September', 'Harvest', 'Family Meal'] },
    { word: 'Raja Festival', category: 'Festivals', hints: ['Odisha', 'Three Days', 'Swings', 'Earth Mother', 'Monsoon Start'] },
    { word: 'Manabasa Gurubara', category: 'Festivals', hints: ['Odisha', 'Lakshmi', 'Thursday', 'Rice Powder Art', 'November'] },
    { word: 'Sarhul', category: 'Festivals', hints: ['Jharkhand', 'Sal Tree', 'Spring', 'Tribal', 'Flowers'] },
    { word: 'Tusu Festival', category: 'Festivals', hints: ['Jharkhand', 'January', 'Harvest', 'Doll Making', 'Dam Immersion'] },
    { word: 'Karma Puja', category: 'Festivals', hints: ['Jharkhand', 'Karma Tree', 'August', 'Tribal Dance', 'Nature'] },
    { word: 'Sama Chakeva', category: 'Festivals', hints: ['Bihar', 'Bird Dolls', 'Brother Sister', 'November', 'Clay'] },
    { word: 'Chhath Ghaat', category: 'Festivals', hints: ['River Steps', 'Bihar', 'Sunrise', 'Standing Water', 'Offerings'] },

    // ── Rituals & traditions ──
    { word: 'Aarti', category: 'Festivals', hints: ['Lamp Waving', 'Temple', 'Evening', 'Bell', 'Devotion'] },
    { word: 'Puja Thali', category: 'Festivals', hints: ['Plate', 'Flowers', 'Kumkum', 'Rice', 'Incense'] },
    { word: 'Havan', category: 'Festivals', hints: ['Fire Ritual', 'Sacred Fire', 'Ghee', 'Mantras', 'Smoke'] },
    { word: 'Prasad', category: 'Festivals', hints: ['Blessed Food', 'Temple', 'Offering', 'Sweet', 'Sharing'] },
    { word: 'Kalash Sthapana', category: 'Festivals', hints: ['Pot Setup', 'Coconut', 'Mango Leaves', 'Water', 'First Day'] },
    { word: 'Toran Bandhan', category: 'Festivals', hints: ['Door Hanging', 'Mango Leaves', 'Welcome', 'Entrance', 'Auspicious'] },
    { word: 'Tilak Ceremony', category: 'Festivals', hints: ['Forehead Mark', 'Rice', 'Kumkum', 'Blessing', 'Vermillion'] },
    { word: 'Sindoor Khela', category: 'Festivals', hints: ['Red Powder Play', 'Married Women', 'Dashami', 'Durga', 'Bengal'] },
    { word: 'Dhunuchi Naach', category: 'Festivals', hints: ['Incense Dance', 'Bengal', 'Smoke', 'Durga Puja', 'Clay Pot'] },
    { word: 'Kumkum Archana', category: 'Festivals', hints: ['Vermillion Worship', 'Goddess', 'Red Powder', 'South India', 'Chanting'] },
    { word: 'Mangal Snaan', category: 'Festivals', hints: ['Holy Bath', 'Dawn', 'River', 'Auspicious', 'Kartik'] },
    { word: 'Bhoomi Pujan', category: 'Festivals', hints: ['Ground Breaking', 'New Building', 'Coconut', 'Foundation', 'Priest'] },
    { word: 'Griha Pravesh', category: 'Festivals', hints: ['House Warming', 'New Home', 'Milk Boil', 'Kalash', 'Coconut'] },
    { word: 'Satyanarayan Katha', category: 'Festivals', hints: ['Story Reading', 'Vishnu', 'Full Moon', 'Banana Leaf', 'Family'] },
    { word: 'Shankh Naad', category: 'Festivals', hints: ['Conch Blowing', 'Temple', 'Auspicious', 'Sound', 'Evening'] },
    { word: 'Ghatasthapana', category: 'Festivals', hints: ['Pot Setup', 'Navratri Start', 'Barley', 'Coconut', 'Nine Days'] },
    { word: 'Sandhi Puja', category: 'Festivals', hints: ['Junction Worship', 'Ashtami Navami', 'One Hundred Eight Lamps', 'Bengal', 'Midnight'] },
    { word: 'Kumari Puja', category: 'Festivals', hints: ['Girl Child Worship', 'Bengal', 'Navami', 'Feet Washing', 'Goddess Form'] },
    { word: 'Kanya Pujan', category: 'Festivals', hints: ['Nine Girls', 'Ashtami', 'Halwa Puri', 'Feet Washing', 'Gift'] },
    { word: 'Murti Sthapana', category: 'Festivals', hints: ['Idol Installation', 'Temple', 'Mantras', 'Flowers', 'Consecration'] },
    { word: 'Bhog Offering', category: 'Festivals', hints: ['Food to God', 'Temple Kitchen', 'Sweets', 'Fruits', 'Sharing'] },
    { word: 'Pushpanjali', category: 'Festivals', hints: ['Flower Offering', 'Morning', 'Mantras', 'Handful', 'Temple'] },
    { word: 'Chandan Yatra', category: 'Festivals', hints: ['Sandalwood', 'Summer', 'Puri', 'Boat Ride', 'Cooling'] },
    { word: 'Snan Yatra', category: 'Festivals', hints: ['Bathing Ritual', 'Full Moon', 'Puri', 'Jagannath', 'June'] },
    { word: 'Parikrama', category: 'Festivals', hints: ['Circumambulation', 'Temple', 'Clockwise', 'Barefoot', 'Devotion'] },
    { word: 'Jal Abhishek', category: 'Festivals', hints: ['Water Pouring', 'Shiva Linga', 'Milk', 'Temple', 'Chanting'] },
    { word: 'Durga Stuti', category: 'Festivals', hints: ['Goddess Hymn', 'Chanting', 'Navratri', 'Devotion', 'Power'] },
    { word: 'Gauri Pujan', category: 'Festivals', hints: ['Parvati Worship', 'Married Women', 'Turmeric', 'Green Bangles', 'Maharashtra'] },
    { word: 'Shanti Path', category: 'Festivals', hints: ['Peace Prayer', 'Vedic Chant', 'Havan', 'Mantras', 'Calm'] },
    { word: 'Pooja Vidhi', category: 'Festivals', hints: ['Worship Method', 'Steps', 'Mantras', 'Priest', 'Rituals'] },

    // ── Festival foods ──
    { word: 'Gujiya', category: 'Festivals', hints: ['Crescent Sweet', 'Holi', 'Fried', 'Stuffed', 'Khoya'] },
    { word: 'Modak', category: 'Festivals', hints: ['Ganesh Sweet', 'Coconut', 'Steamed', 'Dumpling', 'Maharashtra'] },
    { word: 'Puran Poli', category: 'Festivals', hints: ['Stuffed Flatbread', 'Jaggery', 'Lentil', 'Maharashtra', 'Festival Bread'] },
    { word: 'Malpua', category: 'Festivals', hints: ['Fried Pancake', 'Rabri', 'Sugar Syrup', 'Rajasthan', 'Dessert'] },
    { word: 'Sheer Khurma', category: 'Festivals', hints: ['Eid Sweet', 'Vermicelli', 'Milk', 'Dates', 'Nuts'] },
    { word: 'Sewai', category: 'Festivals', hints: ['Vermicelli', 'Eid', 'Milk', 'Sweet', 'Cardamom'] },
    { word: 'Thandai', category: 'Festivals', hints: ['Cold Drink', 'Holi', 'Almonds', 'Fennel', 'Milk'] },
    { word: 'Bhang Lassi', category: 'Festivals', hints: ['Cannabis Drink', 'Holi', 'Varanasi', 'Shiva', 'Intoxicating'] },
    { word: 'Undhiyu', category: 'Festivals', hints: ['Gujarat', 'Winter', 'Mixed Veggies', 'Earthen Pot', 'Uttarayan'] },
    { word: 'Sakkarai Pongal', category: 'Festivals', hints: ['Sweet Rice', 'Tamil', 'Jaggery', 'Ghee', 'Harvest'] },
    { word: 'Payasam', category: 'Festivals', hints: ['South Indian', 'Milk', 'Vermicelli', 'Temple', 'Sweet'] },
    { word: 'Til Gul', category: 'Festivals', hints: ['Sesame Jaggery', 'Sankranti', 'Maharashtra', 'Sweet Talk', 'January'] },
    { word: 'Revdi', category: 'Festivals', hints: ['Sesame Candy', 'Lohri', 'January', 'Punjab', 'Crunchy'] },
    { word: 'Gajak', category: 'Festivals', hints: ['Sesame Brittle', 'Winter', 'North India', 'Crunchy', 'Mathura'] },
    { word: 'Pitha', category: 'Festivals', hints: ['Rice Cake', 'Assam', 'Bihu', 'Steamed', 'Coconut'] },
    { word: 'Naaru', category: 'Festivals', hints: ['Bengal Sweet', 'Coconut Ball', 'Til', 'Winter', 'Homemade'] },
    { word: 'Chikki', category: 'Festivals', hints: ['Peanut Brittle', 'Jaggery', 'Lonavala', 'Winter', 'Crunchy'] },
    { word: 'Phirni', category: 'Festivals', hints: ['Rice Pudding', 'Clay Pot', 'Saffron', 'Eid', 'Cold'] },
    { word: 'Kheer', category: 'Festivals', hints: ['Milk Rice', 'Cardamom', 'Nuts', 'Festival', 'Sweet'] },
    { word: 'Ghevar', category: 'Festivals', hints: ['Rajasthan', 'Honeycomb', 'Teej', 'Sugar Syrup', 'Round'] },
    { word: 'Karanji', category: 'Festivals', hints: ['Fried Sweet', 'Coconut', 'Maharashtra', 'Crescent', 'Diwali'] },
    { word: 'Anarsa', category: 'Festivals', hints: ['Rice Flour', 'Maharashtra', 'Sesame', 'Fried', 'Diwali'] },
    { word: 'Chakli', category: 'Festivals', hints: ['Spiral Snack', 'Rice Flour', 'Fried', 'Crunchy', 'Diwali'] },
    { word: 'Fafda Jalebi', category: 'Festivals', hints: ['Gujarat', 'Dussehra', 'Crispy', 'Sweet Sour', 'Morning'] },
    { word: 'Plum Cake', category: 'Festivals', hints: ['Christmas', 'Rum', 'Dried Fruits', 'December', 'Kerala'] },
    { word: 'Biryani Feast', category: 'Festivals', hints: ['Eid', 'Rice', 'Meat', 'Family', 'Cooking Pot'] },
    { word: 'Kada Prasad', category: 'Festivals', hints: ['Gurudwara Sweet', 'Wheat Flour', 'Ghee', 'Sugar', 'Warm'] },
    { word: 'Thekua', category: 'Festivals', hints: ['Bihar Sweet', 'Chhath', 'Wheat', 'Fried', 'Sun Offering'] },
    { word: 'Laddoo Gopal', category: 'Festivals', hints: ['Krishna Idol', 'Sweets', 'Temple', 'Dress Up', 'Janmashtami'] },
    { word: 'Panchamrit', category: 'Festivals', hints: ['Five Nectars', 'Milk', 'Honey', 'Curd', 'Abhishek'] },

    // ── Decorations & objects ──
    { word: 'Toran', category: 'Festivals', hints: ['Door Hanging', 'Mango Leaf', 'Marigold', 'Welcome', 'Entrance'] },
    { word: 'Marigold Garland', category: 'Festivals', hints: ['Orange Flower', 'Temple', 'Neck', 'Deity', 'Welcome'] },
    { word: 'Banana Leaf Door', category: 'Festivals', hints: ['South India', 'Auspicious', 'Green', 'Entrance', 'Festival'] },
    { word: 'Akash Kandil', category: 'Festivals', hints: ['Sky Lantern', 'Paper', 'Diwali', 'Hanging', 'Balcony'] },
    { word: 'Paper Lantern', category: 'Festivals', hints: ['Light Inside', 'Hanging', 'Night', 'Colorful', 'Sky'] },
    { word: 'Mango Leaf', category: 'Festivals', hints: ['Door Hanging', 'Green', 'Auspicious', 'String', 'Fresh'] },
    { word: 'Kolam', category: 'Festivals', hints: ['Rice Powder', 'South India', 'Doorstep', 'Morning', 'Geometric'] },
    { word: 'Alpana', category: 'Festivals', hints: ['Bengal', 'Floor Art', 'White', 'Rice Paste', 'Doorstep'] },
    { word: 'Muggulu', category: 'Festivals', hints: ['Andhra', 'Floor Art', 'Chalk', 'Doorstep', 'Geometric'] },
    { word: 'Flower Carpet', category: 'Festivals', hints: ['Petals', 'Floor', 'Onam', 'Pattern', 'Colorful'] },
    { word: 'Pookalam', category: 'Festivals', hints: ['Onam', 'Flower', 'Kerala', 'Circular', 'Ten Days'] },
    { word: 'Fairy Lights', category: 'Festivals', hints: ['String', 'Diwali', 'Balcony', 'Twinkling', 'Electric'] },
    { word: 'Sky Lantern', category: 'Festivals', hints: ['Paper', 'Flying', 'Fire Inside', 'Night', 'Wish'] },
    { word: 'Pataka', category: 'Festivals', hints: ['Firecracker', 'Loud', 'String', 'Diwali', 'Night'] },
    { word: 'Anar Firework', category: 'Festivals', hints: ['Fountain', 'Sparks', 'Ground', 'Golden', 'Cone'] },
    { word: 'Sparkler', category: 'Festivals', hints: ['Hand Held', 'Glowing', 'Children', 'Iron', 'Night'] },
    { word: 'Chakri Firework', category: 'Festivals', hints: ['Spinning', 'Ground', 'Sparks', 'Circle', 'Night'] },
    { word: 'Gulal', category: 'Festivals', hints: ['Colored Powder', 'Holi', 'Red Pink', 'Face', 'Throwing'] },
    { word: 'Pichkari', category: 'Festivals', hints: ['Water Gun', 'Holi', 'Spray', 'Colorful', 'Children'] },
    { word: 'Colour Balloon', category: 'Festivals', hints: ['Water Filled', 'Holi', 'Throwing', 'Splash', 'Fun'] },
    { word: 'Sindoor Packet', category: 'Festivals', hints: ['Red Powder', 'Married Women', 'Parting', 'Blessing', 'Temple'] },
    { word: 'Camphor', category: 'Festivals', hints: ['Burning', 'Aarti', 'Flame', 'Fragrant', 'White'] },
    { word: 'Incense Stick', category: 'Festivals', hints: ['Agarbatti', 'Smoke', 'Fragrant', 'Temple', 'Morning'] },
    { word: 'Dhoop', category: 'Festivals', hints: ['Thick Smoke', 'Resin', 'Fragrant', 'Temple', 'Purifying'] },
    { word: 'Coconut Offering', category: 'Festivals', hints: ['Breaking', 'Temple', 'Auspicious', 'Hard Shell', 'Water Inside'] },
    { word: 'Christmas Tree', category: 'Festivals', hints: ['Pine', 'December', 'Star Top', 'Ornaments', 'Gifts Below'] },
    { word: 'Star Topper', category: 'Festivals', hints: ['Tree Top', 'December', 'Bethlehem', 'Shining', 'Point'] },
    { word: 'Crib Set', category: 'Festivals', hints: ['Nativity', 'Baby Jesus', 'Stable', 'Figures', 'December'] },
    { word: 'Stocking', category: 'Festivals', hints: ['Hanging', 'Fireplace', 'Gifts Inside', 'Red', 'December'] },
    { word: 'Mistletoe', category: 'Festivals', hints: ['Kiss Below', 'December', 'Green', 'Hanging', 'Western'] },

    // ── Clothing & accessories ──
    { word: 'Chaniya Choli', category: 'Festivals', hints: ['Gujarat', 'Navratri', 'Mirror Work', 'Colorful', 'Skirt Blouse'] },
    { word: 'Lehenga', category: 'Festivals', hints: ['Long Skirt', 'Wedding', 'Embroidered', 'Heavy', 'Dupatta'] },
    { word: 'Anarkali Suit', category: 'Festivals', hints: ['Long Frock', 'Mughal Style', 'Flared', 'Festival', 'Elegant'] },
    { word: 'Sherwani', category: 'Festivals', hints: ['Men Coat', 'Wedding', 'Embroidered', 'North India', 'Formal'] },
    { word: 'Kurta Pyjama', category: 'Festivals', hints: ['Men Cotton', 'Festival', 'Comfortable', 'White', 'Traditional'] },
    { word: 'Silk Saree', category: 'Festivals', hints: ['Six Yards', 'South India', 'Kanjivaram', 'Golden Border', 'Temple'] },
    { word: 'Kasavu Mundu', category: 'Festivals', hints: ['Kerala White', 'Gold Border', 'Onam', 'Cotton', 'Draping'] },
    { word: 'Dhoti Kurta', category: 'Festivals', hints: ['White Wrap', 'Traditional', 'Men', 'Temple', 'Bengal'] },
    { word: 'Pagdi', category: 'Festivals', hints: ['Turban', 'Rajasthan', 'Colorful', 'Men', 'Wedding'] },
    { word: 'Dastar', category: 'Festivals', hints: ['Sikh Turban', 'Respect', 'Tied', 'Identity', 'Cloth'] },
    { word: 'Juttis', category: 'Festivals', hints: ['Pointed Shoes', 'Embroidered', 'Flat', 'Punjab', 'Colorful'] },
    { word: 'Mojaris', category: 'Festivals', hints: ['Leather Shoes', 'Rajasthan', 'Handmade', 'Pointed', 'Traditional'] },
    { word: 'Glass Bangles', category: 'Festivals', hints: ['Wrist', 'Colorful', 'Clinking', 'Married', 'Breakable'] },
    { word: 'Mehndi Hands', category: 'Festivals', hints: ['Henna Design', 'Palms', 'Brown', 'Bride', 'Intricate'] },
    { word: 'Alta', category: 'Festivals', hints: ['Red Dye', 'Feet', 'Bengal', 'Bride', 'Cotton Swab'] },
    { word: 'Bindi', category: 'Festivals', hints: ['Forehead Dot', 'Red', 'Sticker', 'Women', 'Third Eye'] },
    { word: 'Nose Ring', category: 'Festivals', hints: ['Nath', 'Gold', 'Chain', 'Bride', 'Piercing'] },
    { word: 'Maang Tikka', category: 'Festivals', hints: ['Hair Parting', 'Forehead', 'Gold', 'Bride', 'Pendant'] },
    { word: 'Kamarband', category: 'Festivals', hints: ['Waist Belt', 'Gold', 'Bride', 'Saree', 'Ornament'] },
    { word: 'Payal', category: 'Festivals', hints: ['Ankle Bells', 'Silver', 'Jingling', 'Feet', 'Dance'] },

    // ── Music & dance ──
    { word: 'Dandiya Stick', category: 'Festivals', hints: ['Wooden', 'Decorated', 'Pair', 'Navratri', 'Hitting'] },
    { word: 'Garba Circle', category: 'Festivals', hints: ['Rotating', 'Gujarat', 'Women', 'Clapping', 'Night'] },
    { word: 'Bhangra Dhol', category: 'Festivals', hints: ['Punjab Drum', 'Loud', 'Shoulder', 'Dancing', 'Beats'] },
    { word: 'Gidda', category: 'Festivals', hints: ['Punjabi Women', 'Clapping', 'Singing', 'Circle', 'Boliyan'] },
    { word: 'Lavani', category: 'Festivals', hints: ['Maharashtra', 'Women Dance', 'Saree', 'Drum', 'Fast'] },
    { word: 'Bihu Dance', category: 'Festivals', hints: ['Assam', 'Hip Movement', 'Pepa', 'Group', 'April'] },
    { word: 'Kathakali', category: 'Festivals', hints: ['Kerala', 'Face Paint', 'Green', 'Story', 'Eyes'] },
    { word: 'Thiruvathira Kali', category: 'Festivals', hints: ['Kerala Women', 'Circle Dance', 'Lamp', 'Graceful', 'December'] },
    { word: 'Bharatanatyam', category: 'Festivals', hints: ['Tamil Nadu', 'Classical', 'Temple', 'Footwork', 'Expression'] },
    { word: 'Dhaak', category: 'Festivals', hints: ['Bengal Drum', 'Durga Puja', 'Loud', 'Rhythm', 'Pandal'] },
    { word: 'Shehnai', category: 'Festivals', hints: ['Wind Pipe', 'Wedding', 'Auspicious', 'Bismillah Khan', 'Nasal'] },
    { word: 'Nagara Drum', category: 'Festivals', hints: ['Temple Drum', 'Large', 'Sticks', 'Procession', 'Loud'] },
    { word: 'Conch Shell Blow', category: 'Festivals', hints: ['Temple', 'Morning', 'Aarti', 'Sound', 'White'] },
    { word: 'Bhajan Sandhya', category: 'Festivals', hints: ['Devotional Night', 'Singing', 'Temple', 'Group', 'Harmonium'] },
    { word: 'Qawwali Night', category: 'Festivals', hints: ['Sufi Singing', 'Dargah', 'Group', 'Clapping', 'Soulful'] },
    { word: 'Kirtan', category: 'Festivals', hints: ['Devotional Singing', 'Gurudwara', 'Harmonium', 'Community', 'Praise'] },
    { word: 'Jagrata', category: 'Festivals', hints: ['Night Vigil', 'Mata', 'Singing', 'No Sleep', 'Navratri'] },
    { word: 'Akhara', category: 'Festivals', hints: ['Wrestling Ring', 'Training', 'Sand Pit', 'Kumbh', 'Sadhus'] },
    { word: 'Ramlila Stage', category: 'Festivals', hints: ['Drama', 'Ram Story', 'Open Air', 'Dussehra', 'Costumes'] },

    // ── Mythology ──
    { word: 'Ravan Dahan', category: 'Festivals', hints: ['Effigy Burning', 'Dussehra', 'Ten Heads', 'Fireworks', 'Ground'] },
    { word: 'Lakshmi Pujan', category: 'Festivals', hints: ['Wealth Goddess', 'Diwali Night', 'Gold Coins', 'Red Saree', 'Lotus'] },
    { word: 'Krishna Leela', category: 'Festivals', hints: ['Childhood Plays', 'Butter Theft', 'Gopis', 'Vrindavan', 'Flute'] },
    { word: 'Radha Krishna', category: 'Festivals', hints: ['Divine Love', 'Vrindavan', 'Flute', 'Dance', 'Holi'] },
    { word: 'Sita Haran', category: 'Festivals', hints: ['Abduction', 'Golden Deer', 'Ravana', 'Lanka', 'Forest'] },
    { word: 'Ram Setu', category: 'Festivals', hints: ['Bridge', 'Stones', 'Monkey Army', 'Ocean', 'Lanka'] },
    { word: 'Sudarshan Chakra', category: 'Festivals', hints: ['Spinning Disc', 'Vishnu', 'Weapon', 'Finger', 'Divine'] },
    { word: 'Nandi Bull', category: 'Festivals', hints: ['Shiva Vehicle', 'Temple Gate', 'Stone', 'White', 'Devotee'] },
    { word: 'Makhan Chor', category: 'Festivals', hints: ['Butter Thief', 'Baby Krishna', 'Pot', 'Gopis', 'Naughty'] },
    { word: 'Govinda Aala Re', category: 'Festivals', hints: ['Song', 'Dahi Handi', 'Mumbai', 'Pyramid', 'Krishna'] },
    { word: 'Prahlad Story', category: 'Festivals', hints: ['Devotee Boy', 'Narasimha', 'Fire', 'Vishnu', 'Holika'] },
    { word: 'Holika Fire', category: 'Festivals', hints: ['Bonfire', 'Evil Aunt', 'Prahlad', 'Night Before', 'Wood Pile'] },
    { word: 'Lanka Dahan', category: 'Festivals', hints: ['Hanuman', 'Fire Tail', 'Golden City', 'Burning', 'Sita Search'] },
    { word: 'Sagar Manthan', category: 'Festivals', hints: ['Ocean Churning', 'Amrit', 'Snake Rope', 'Tortoise', 'Mountain'] },
    { word: 'Ganesh Vandana', category: 'Festivals', hints: ['Elephant Chant', 'First Prayer', 'Obstacle Remover', 'Opening', 'Auspicious'] },
    { word: 'Saraswati Pujan', category: 'Festivals', hints: ['Knowledge Goddess', 'White Sari', 'Veena', 'Books', 'February'] },
    { word: 'Durga Mahishasura', category: 'Festivals', hints: ['Buffalo Demon', 'Battle', 'Trident', 'Lion Mount', 'Victory'] },
    { word: 'Devi Mahabhagwat', category: 'Festivals', hints: ['Goddess Scripture', 'Stories', 'Nine Forms', 'Power', 'Reading'] },

    // ── Activities & experiences ──
    { word: 'Diya Lighting', category: 'Festivals', hints: ['Oil Lamp', 'Evening', 'Wick', 'Row', 'Doorstep'] },
    { word: 'Candle March', category: 'Festivals', hints: ['Walking', 'Night', 'Holding', 'Vigil', 'Tribute'] },
    { word: 'Sparkler Circle', category: 'Festivals', hints: ['Arm Swirl', 'Night', 'Glowing Ring', 'Children', 'Fun'] },
    { word: 'Balloon Shooting', category: 'Festivals', hints: ['Fair Game', 'Dart', 'Prize', 'Stall', 'Aim'] },
    { word: 'Ferris Wheel', category: 'Festivals', hints: ['Giant Wheel', 'Mela', 'Heights', 'Ride', 'Night View'] },
    { word: 'Merry Go Round', category: 'Festivals', hints: ['Carousel', 'Children', 'Horses', 'Spinning', 'Fair'] },
    { word: 'Card Exchange', category: 'Festivals', hints: ['Greeting', 'Wishes', 'Postal', 'Festival', 'Friends'] },
    { word: 'Gift Wrapping', category: 'Festivals', hints: ['Paper', 'Ribbon', 'Box', 'Surprise', 'Scissors'] },
    { word: 'Sweet Box', category: 'Festivals', hints: ['Mithai', 'Sharing', 'Neighbors', 'Celebration', 'Assorted'] },
    { word: 'Dry Fruit Box', category: 'Festivals', hints: ['Almonds', 'Cashews', 'Gift', 'Festive', 'Premium'] },
    { word: 'Shagun Envelope', category: 'Festivals', hints: ['Cash Gift', 'Auspicious', 'Red', 'Wedding', 'Odd Number'] },
    { word: 'Eidi Money', category: 'Festivals', hints: ['Eid Gift', 'Elders Give', 'Children', 'Cash', 'Envelope'] },
    { word: 'Secret Santa', category: 'Festivals', hints: ['Christmas', 'Anonymous', 'Gift', 'Office', 'Name Draw'] },
    { word: 'Bonfire Night', category: 'Festivals', hints: ['Flames', 'Winter', 'Gathering', 'Warmth', 'Outdoor'] },
    { word: 'Popcorn Stall', category: 'Festivals', hints: ['Mela', 'Snack', 'Corn', 'Hot', 'Paper Bag'] },
    { word: 'Cotton Candy', category: 'Festivals', hints: ['Spun Sugar', 'Pink', 'Fair', 'Stick', 'Fluffy'] },
    { word: 'Ferris Wheel Ride', category: 'Festivals', hints: ['Giant Wheel', 'Top View', 'Slow', 'Fair', 'Couple'] },
    { word: 'Puppet Show', category: 'Festivals', hints: ['String Dolls', 'Rajasthan', 'Kathputli', 'Stage', 'Story'] },
    { word: 'Magic Show', category: 'Festivals', hints: ['Tricks', 'Hat', 'Stage', 'Audience', 'Disappear'] },
    { word: 'Tambola Night', category: 'Festivals', hints: ['Number Game', 'Ticket', 'Colony', 'Prizes', 'Housie'] },

    // ── Greetings ──
    { word: 'Shubh Deepavali', category: 'Festivals', hints: ['Greeting', 'Diwali', 'Auspicious', 'Wish', 'Card'] },
    { word: 'Happy Holi', category: 'Festivals', hints: ['Greeting', 'Colors', 'Wish', 'Spring', 'Splashing'] },
    { word: 'Eid Mubarak', category: 'Festivals', hints: ['Greeting', 'Blessed', 'Wish', 'Hugging', 'Moon'] },
    { word: 'Merry Christmas', category: 'Festivals', hints: ['Greeting', 'December', 'Wish', 'Joy', 'Carols'] },
    { word: 'Happy Onam', category: 'Festivals', hints: ['Greeting', 'Kerala', 'Wish', 'Mahabali', 'Harvest'] },
    { word: 'Baisakhi Di Wadhai', category: 'Festivals', hints: ['Punjabi Greeting', 'April', 'Wish', 'Bhangra', 'Harvest'] },
    { word: 'Sat Sri Akal', category: 'Festivals', hints: ['Sikh Greeting', 'God Is Truth', 'Hello', 'Gurudwara', 'Respect'] },
    { word: 'Namaskar', category: 'Festivals', hints: ['Folded Hands', 'Greeting', 'Respect', 'Bow', 'Traditional'] },
    { word: 'Khushi Manaao', category: 'Festivals', hints: ['Celebrate Joy', 'Happy Occasion', 'Party', 'Together', 'Cheers'] },
    { word: 'Aap Ko Badhai', category: 'Festivals', hints: ['Congratulations', 'Formal Hindi', 'Good News', 'Respectful', 'Wish'] },

    // ── Places of worship ──
    { word: 'Temple Bell', category: 'Festivals', hints: ['Ringing', 'Brass', 'Entrance', 'Devotion', 'Loud'] },
    { word: 'Mosque Dome', category: 'Festivals', hints: ['Round Top', 'White', 'Crescent', 'Prayer Hall', 'Architecture'] },
    { word: 'Church Steeple', category: 'Festivals', hints: ['Tower', 'Bell', 'Cross Top', 'Tall', 'Stone'] },
    { word: 'Gurudwara Sahib', category: 'Festivals', hints: ['Sikh Temple', 'Langar', 'Golden', 'Prayer', 'Community'] },
    { word: 'Golden Temple', category: 'Festivals', hints: ['Amritsar', 'Sarovar', 'Gold Plated', 'Sikh', 'Langar'] },
    { word: 'Varanasi Ghat', category: 'Festivals', hints: ['Steps', 'Ganges', 'Aarti', 'Boats', 'Ancient'] },
    { word: 'Mathura Vrindavan', category: 'Festivals', hints: ['Krishna Birth', 'Temples', 'Holi', 'UP', 'Pilgrimage'] },
    { word: 'Tirupati', category: 'Festivals', hints: ['Balaji', 'Hair Offering', 'Queue', 'Andhra', 'Seven Hills'] },
    { word: 'Shirdi', category: 'Festivals', hints: ['Sai Baba', 'Temple', 'Maharashtra', 'Prasad', 'Pilgrimage'] },
    { word: 'Ajmer Dargah', category: 'Festivals', hints: ['Sufi Shrine', 'Rajasthan', 'Chaddar', 'Qawwali', 'Pilgrimage'] },

    // ── Modern celebrations ──
    { word: 'Dandiya Night DJ', category: 'Festivals', hints: ['Music', 'Navratri', 'Club', 'Modern', 'Neon Lights'] },
    { word: 'Holi Pool Party', category: 'Festivals', hints: ['Water', 'Colors', 'Music', 'Modern', 'Young'] },
    { word: 'Midnight Countdown', category: 'Festivals', hints: ['New Year', 'Ten Nine', 'Cheering', 'Party', 'Fireworks'] },
    { word: 'New Year Bash', category: 'Festivals', hints: ['January First', 'Party', 'Midnight', 'Dancing', 'Champagne'] },
    { word: 'Rain Dance Holi', category: 'Festivals', hints: ['Sprinklers', 'Music', 'Colors', 'Wet', 'Modern'] },
    { word: 'Eco Ganpati', category: 'Festivals', hints: ['Clay Idol', 'Seed', 'No Paint', 'Dissolves', 'Green'] },
    { word: 'Organic Colours', category: 'Festivals', hints: ['Natural', 'Holi', 'Flower Based', 'Safe', 'Turmeric'] },
    { word: 'Green Diwali', category: 'Festivals', hints: ['No Crackers', 'Less Pollution', 'Lamps Only', 'Eco', 'Quiet'] },
    { word: 'Terrace Party', category: 'Festivals', hints: ['Rooftop', 'Night', 'Friends', 'Music', 'City View'] },
    { word: 'Community Feast', category: 'Festivals', hints: ['Neighbors', 'Potluck', 'Colony', 'Together', 'Sharing'] },
    { word: 'Potluck Dinner', category: 'Festivals', hints: ['Bring Food', 'Friends', 'Variety', 'Sharing', 'Party'] },
    { word: 'Charity Drive', category: 'Festivals', hints: ['Donation', 'Clothes', 'Festival', 'NGO', 'Giving Back'] },
    { word: 'Blood Donation Camp', category: 'Festivals', hints: ['Festival', 'Volunteering', 'Red Cross', 'Camp', 'Life Saving'] },
    { word: 'Colony Rangoli', category: 'Festivals', hints: ['Neighborhood', 'Competition', 'Diwali', 'Floor Art', 'Judges'] },
    { word: 'Society Garba', category: 'Festivals', hints: ['Apartment', 'Navratri', 'Community', 'Night', 'DJ'] },
  ],
};
