import type { WordPack } from '../game/types';

export const festivalsPack: WordPack = {
  id: 'festivals',
  name: 'Festivals',
  entries: [
    { word: 'Diwali', category: 'Festivals' },
    { word: 'Holi', category: 'Festivals' },
    { word: 'Eid', category: 'Festivals' },
    { word: 'Christmas', category: 'Festivals' },
    { word: 'Pongal', category: 'Festivals' },
    { word: 'Onam', category: 'Festivals' },
    { word: 'Baisakhi', category: 'Festivals' },
    { word: 'Navratri', category: 'Festivals' },
    { word: 'Durga Puja', category: 'Festivals' },
    { word: 'Ganesh Chaturthi', category: 'Festivals' },
    { word: 'Bihu', category: 'Festivals' },
    { word: 'Lohri', category: 'Festivals' },
    { word: 'Makar Sankranti', category: 'Festivals' },
    { word: 'Raksha Bandhan', category: 'Festivals' },
    { word: 'Janmashtami', category: 'Festivals' },
    { word: 'Guru Purab', category: 'Festivals' },
    { word: 'Nowruz', category: 'Festivals' },
    { word: 'Vishu', category: 'Festivals' },
    { word: 'Ugadi', category: 'Festivals' },
    { word: 'Chhath Puja', category: 'Festivals' },
    { word: 'Karva Chauth', category: 'Festivals' },
    { word: 'Muharram', category: 'Festivals' },
    { word: 'Good Friday', category: 'Festivals' },
    { word: 'Buddha Purnima', category: 'Festivals' },
    { word: 'Mahavir Jayanti', category: 'Festivals' },
    { word: 'Rangoli', category: 'Festivals' },
    { word: 'Diyas', category: 'Festivals' },
    { word: 'Fireworks', category: 'Festivals' },
    { word: 'Garba Raas', category: 'Festivals' },
    { word: 'Pandal Hopping', category: 'Festivals' },
    { word: 'Thaipusam', category: 'Festivals' },
    { word: 'Puthandu', category: 'Festivals' },
    { word: 'Mela', category: 'Festivals' },
    { word: 'Ladoo Distribution', category: 'Festivals' },
    { word: 'Kite Flying', category: 'Festivals' },
    { word: 'Dhol', category: 'Festivals' },
    { word: 'Langar', category: 'Festivals' },
    { word: 'Iftaar', category: 'Festivals' },
    { word: 'Midnight Mass', category: 'Festivals' },
    { word: 'Visarjan', category: 'Festivals' },
  ],
};
