import type { WordPack } from '../game/types';

export const foodPack: WordPack = {
  id: 'food',
  name: 'Food',
  entries: [
    { word: 'Pani Puri', category: 'Food' },
    { word: 'Vada Pav', category: 'Food' },
    { word: 'Chole Bhature', category: 'Food' },
    { word: 'Biryani', category: 'Food' },
    { word: 'Butter Chicken', category: 'Food' },
    { word: 'Masala Dosa', category: 'Food' },
    { word: 'Cutting Chai', category: 'Food' },
    { word: 'Filter Coffee', category: 'Food' },
    { word: 'Pav Bhaji', category: 'Food' },
    { word: 'Samosa', category: 'Food' },
    { word: 'Jalebi', category: 'Food' },
    { word: 'Gulab Jamun', category: 'Food' },
    { word: 'Rasgulla', category: 'Food' },
    { word: 'Momos', category: 'Food' },
    { word: 'Kathi Roll', category: 'Food' },
    { word: 'Litti Chokha', category: 'Food' },
    { word: 'Idli Sambhar', category: 'Food' },
    { word: 'Thali', category: 'Food' },
    { word: 'Maggi', category: 'Food' },
    { word: 'Paratha', category: 'Food' },
    { word: 'Dal Makhani', category: 'Food' },
    { word: 'Paneer Tikka', category: 'Food' },
    { word: 'Kebab', category: 'Food' },
    { word: 'Bhel Puri', category: 'Food' },
    { word: 'Lassi', category: 'Food' },
    { word: 'Kulfi', category: 'Food' },
    { word: 'Rabri', category: 'Food' },
    { word: 'Chaat', category: 'Food' },
    { word: 'Dabeli', category: 'Food' },
    { word: 'Misal Pav', category: 'Food' },
    { word: 'Poha', category: 'Food' },
    { word: 'Khichdi', category: 'Food' },
    { word: 'Tandoori Roti', category: 'Food' },
    { word: 'Rasam', category: 'Food' },
    { word: 'Appam', category: 'Food' },
    { word: 'Paan', category: 'Food' },
    { word: 'Golgappa', category: 'Food' },
    { word: 'Falooda', category: 'Food' },
    { word: 'Kachori', category: 'Food' },
    { word: 'Egg Roll', category: 'Food' },
  ],
};
