import type { WordPack } from '../game/types';

export const foodPack: WordPack = {
  id: 'food',
  name: 'Food',
  entries: [
    // ── Original 40 ──
    { word: 'Pani Puri', category: 'Food', hints: ['Spicy Water', 'Crispy Shell', 'Chutney', 'Street Stall', 'Tamarind'] },
    { word: 'Vada Pav', category: 'Food', hints: ['Mumbai', 'Bun', 'Potato Patty', 'Chutney', 'Street Food'] },
    { word: 'Chole Bhature', category: 'Food', hints: ['Chickpeas', 'Fried Bread', 'Delhi', 'Pickle', 'Onion'] },
    { word: 'Biryani', category: 'Food', hints: ['Rice', 'Dum', 'Hyderabad', 'Spices', 'Raita'] },
    { word: 'Butter Chicken', category: 'Food', hints: ['Creamy', 'Tomato', 'Tandoor', 'Punjab', 'Naan'] },
    { word: 'Masala Dosa', category: 'Food', hints: ['Crispy', 'Potato Filling', 'Sambhar', 'South Indian', 'Fermented'] },
    { word: 'Cutting Chai', category: 'Food', hints: ['Half Glass', 'Tapri', 'Mumbai', 'Ginger', 'Shared'] },
    { word: 'Filter Coffee', category: 'Food', hints: ['Tumbler', 'Decoction', 'South Indian', 'Frothy', 'Davara'] },
    { word: 'Pav Bhaji', category: 'Food', hints: ['Buttered Bun', 'Mashed Veggies', 'Mumbai', 'Tawa', 'Lemon'] },
    { word: 'Samosa', category: 'Food', hints: ['Triangle', 'Fried', 'Potato', 'Chai Time', 'Crispy'] },
    { word: 'Jalebi', category: 'Food', hints: ['Syrup', 'Spiral', 'Orange', 'Fried', 'Crispy'] },
    { word: 'Gulab Jamun', category: 'Food', hints: ['Syrup', 'Khoya', 'Deep Fried', 'Dessert', 'Round'] },
    { word: 'Rasgulla', category: 'Food', hints: ['Bengal', 'Spongy', 'Sugar Syrup', 'Chenna', 'White'] },
    { word: 'Momos', category: 'Food', hints: ['Steamed', 'Dumpling', 'Northeast', 'Chilli Sauce', 'Stuffed'] },
    { word: 'Kathi Roll', category: 'Food', hints: ['Kolkata', 'Paratha Wrap', 'Onion', 'Kebab', 'Street Food'] },
    { word: 'Litti Chokha', category: 'Food', hints: ['Bihar', 'Sattu', 'Roasted', 'Mashed Veggie', 'Desi Ghee'] },
    { word: 'Idli Sambhar', category: 'Food', hints: ['Steamed', 'Fermented', 'South Indian', 'Lentil Soup', 'Soft'] },
    { word: 'Thali', category: 'Food', hints: ['Plate', 'Katori', 'Assorted', 'Unlimited', 'Regional'] },
    { word: 'Maggi', category: 'Food', hints: ['Two Minutes', 'Noodles', 'Hostel', 'Masala', 'Late Night'] },
    { word: 'Paratha', category: 'Food', hints: ['Flatbread', 'Stuffed', 'Butter', 'Griddle', 'Breakfast'] },
    { word: 'Dal Makhani', category: 'Food', hints: ['Black Lentil', 'Creamy', 'Butter', 'Slow Cooked', 'Punjab'] },
    { word: 'Paneer Tikka', category: 'Food', hints: ['Grilled', 'Marinated', 'Skewer', 'Tandoor', 'Cottage Cheese'] },
    { word: 'Kebab', category: 'Food', hints: ['Skewer', 'Grilled', 'Minced', 'Mughlai', 'Charcoal'] },
    { word: 'Bhel Puri', category: 'Food', hints: ['Puffed Rice', 'Chutney', 'Mumbai Beach', 'Tangy', 'Sev'] },
    { word: 'Lassi', category: 'Food', hints: ['Yogurt', 'Punjab', 'Chilled', 'Sweet', 'Tall Glass'] },
    { word: 'Kulfi', category: 'Food', hints: ['Frozen', 'Malai', 'Matka', 'Pista', 'Stick'] },
    { word: 'Rabri', category: 'Food', hints: ['Thickened Milk', 'Sweet', 'Simmered', 'Creamy', 'Saffron'] },
    { word: 'Chaat', category: 'Food', hints: ['Tangy', 'Street Food', 'Sev', 'Curd', 'Chutney'] },
    { word: 'Dabeli', category: 'Food', hints: ['Kutch', 'Peanuts', 'Pomegranate', 'Bun', 'Spiced Potato'] },
    { word: 'Misal Pav', category: 'Food', hints: ['Spicy Sprouts', 'Pune', 'Farsan', 'Bun', 'Maharashtrian'] },
    { word: 'Poha', category: 'Food', hints: ['Flattened Rice', 'Breakfast', 'Peanuts', 'Turmeric', 'Indore'] },
    { word: 'Khichdi', category: 'Food', hints: ['Rice Lentil', 'Comfort Food', 'Ghee', 'One Pot', 'Light'] },
    { word: 'Tandoori Roti', category: 'Food', hints: ['Clay Oven', 'Wheat', 'Charred', 'Dhaba', 'Puffed'] },
    { word: 'Rasam', category: 'Food', hints: ['Tamarind', 'Pepper', 'South Indian', 'Soupy', 'Warm'] },
    { word: 'Appam', category: 'Food', hints: ['Kerala', 'Fermented', 'Lacy Edge', 'Coconut Milk', 'Bowl Shape'] },
    { word: 'Paan', category: 'Food', hints: ['Betel Leaf', 'Supari', 'Gulkand', 'After Meal', 'Banaras'] },
    { word: 'Golgappa', category: 'Food', hints: ['Spicy Water', 'Crispy Shell', 'Delhi', 'Tangy', 'Vendor'] },
    { word: 'Falooda', category: 'Food', hints: ['Rose Syrup', 'Vermicelli', 'Ice Cream', 'Basil Seeds', 'Chilled'] },
    { word: 'Kachori', category: 'Food', hints: ['Deep Fried', 'Stuffed', 'Moong Dal', 'Rajasthan', 'Crispy'] },
    { word: 'Egg Roll', category: 'Food', hints: ['Kolkata', 'Paratha Wrap', 'Onion', 'Street Food', 'Lime'] },
    // ── North Indian ──
    { word: 'Rajma Chawal', category: 'Food', hints: ['Kidney Beans', 'Rice', 'Delhi', 'Sunday', 'Comfort Food'] },
    { word: 'Sarson Ka Saag', category: 'Food', hints: ['Mustard Greens', 'Punjab', 'Winter', 'Makki Roti', 'Butter'] },
    { word: 'Makki Ki Roti', category: 'Food', hints: ['Cornmeal', 'Punjab', 'Saag', 'Winter', 'Griddle'] },
    { word: 'Kadhi Pakora', category: 'Food', hints: ['Yogurt Curry', 'Besan Fritter', 'Turmeric', 'Rice', 'Tangy'] },
    { word: 'Aloo Gobi', category: 'Food', hints: ['Potato', 'Cauliflower', 'Turmeric', 'Dry Sabzi', 'Homestyle'] },
    { word: 'Shahi Paneer', category: 'Food', hints: ['Royal', 'Cashew Gravy', 'Creamy', 'Mughlai', 'Rich'] },
    { word: 'Palak Paneer', category: 'Food', hints: ['Spinach', 'Cottage Cheese', 'Green', 'Creamy', 'Iron'] },
    { word: 'Baingan Bharta', category: 'Food', hints: ['Roasted Eggplant', 'Smoky', 'Mashed', 'Tandoor', 'Punjabi'] },
    { word: 'Dum Aloo', category: 'Food', hints: ['Baby Potato', 'Slow Cooked', 'Kashmiri', 'Gravy', 'Spiced'] },
    { word: 'Malai Kofta', category: 'Food', hints: ['Cream', 'Dumpling', 'Cashew', 'Rich Gravy', 'Paneer'] },
    { word: 'Naan', category: 'Food', hints: ['Tandoor', 'Leavened', 'Butter', 'Soft', 'Tear Drop'] },
    { word: 'Kulcha', category: 'Food', hints: ['Amritsar', 'Stuffed', 'Chole', 'Baked', 'Maida'] },
    { word: 'Amritsari Kulcha', category: 'Food', hints: ['Stuffed', 'Potato', 'Tandoor', 'Punjab', 'Chole'] },
    { word: 'Chole Kulche', category: 'Food', hints: ['Chickpea Curry', 'Bread', 'Delhi Street', 'Onion', 'Spicy'] },
    { word: 'Laccha Paratha', category: 'Food', hints: ['Layered', 'Flaky', 'Ghee', 'Tandoor', 'Crispy'] },
    { word: 'Stuffed Paratha', category: 'Food', hints: ['Filling', 'Griddle', 'Butter', 'Breakfast', 'Homemade'] },
    { word: 'Gobhi Paratha', category: 'Food', hints: ['Cauliflower', 'Stuffed', 'Butter', 'Pickle', 'Breakfast'] },
    { word: 'Aloo Paratha', category: 'Food', hints: ['Potato', 'Stuffed', 'Butter', 'Curd', 'Punjabi'] },
    { word: 'Methi Paratha', category: 'Food', hints: ['Fenugreek', 'Green', 'Stuffed', 'Healthy', 'Winter'] },
    { word: 'Paneer Paratha', category: 'Food', hints: ['Cottage Cheese', 'Stuffed', 'Butter', 'Griddle', 'Rich'] },
    { word: 'Dal Tadka', category: 'Food', hints: ['Tempering', 'Lentil', 'Cumin', 'Garlic', 'Ghee'] },
    { word: 'Yellow Dal', category: 'Food', hints: ['Toor', 'Turmeric', 'Everyday', 'Lentil', 'Simple'] },
    { word: 'Dal Fry', category: 'Food', hints: ['Tempered', 'Lentil', 'Onion Tomato', 'Dhaba', 'Tadka'] },
    { word: 'Kadai Paneer', category: 'Food', hints: ['Wok', 'Bell Pepper', 'Spicy', 'Cottage Cheese', 'Tomato'] },
    { word: 'Matar Paneer', category: 'Food', hints: ['Green Peas', 'Cottage Cheese', 'Gravy', 'North Indian', 'Homestyle'] },
    { word: 'Paneer Bhurji', category: 'Food', hints: ['Scrambled', 'Cottage Cheese', 'Onion', 'Spicy', 'Quick'] },
    { word: 'Chutneys', category: 'Food', hints: ['Condiment', 'Dipping', 'Green', 'Sweet', 'Accompaniment'] },
    { word: 'Mint Chutney', category: 'Food', hints: ['Pudina', 'Green', 'Spicy', 'Yogurt', 'Dip'] },
    { word: 'Tamarind Chutney', category: 'Food', hints: ['Imli', 'Sweet Sour', 'Brown', 'Chaat', 'Thick'] },
    { word: 'Aloo Tikki', category: 'Food', hints: ['Potato Patty', 'Crispy', 'Street Food', 'Chutney', 'Pan Fried'] },
    { word: 'Pakora', category: 'Food', hints: ['Batter Fried', 'Besan', 'Rainy Day', 'Chai Time', 'Crispy'] },
    { word: 'Bread Pakora', category: 'Food', hints: ['Stuffed Slice', 'Besan Batter', 'Deep Fried', 'Potato', 'Street Food'] },
    { word: 'Pyaaz Kachori', category: 'Food', hints: ['Onion Filled', 'Deep Fried', 'Jodhpur', 'Crispy', 'Spicy'] },
    { word: 'Bedmi Puri', category: 'Food', hints: ['Delhi', 'Urad Dal', 'Deep Fried', 'Sabzi', 'Breakfast'] },
    { word: 'Nagori Puri', category: 'Food', hints: ['Jodhpur', 'Crispy', 'Small', 'Deep Fried', 'Halwa'] },
    { word: 'Puri Sabzi', category: 'Food', hints: ['Fried Bread', 'Potato Curry', 'Puffed', 'Breakfast', 'Festive'] },
    { word: 'Aloo Puri', category: 'Food', hints: ['Potato Curry', 'Puffed Bread', 'Breakfast', 'Deep Fried', 'North Indian'] },
    { word: 'Raita', category: 'Food', hints: ['Yogurt', 'Cooling', 'Side Dish', 'Cucumber', 'Biryani'] },
    { word: 'Boondi Raita', category: 'Food', hints: ['Yogurt', 'Fried Drops', 'Cumin', 'Side Dish', 'Cool'] },
    { word: 'Jeera Rice', category: 'Food', hints: ['Cumin', 'Basmati', 'Tempered', 'Side Dish', 'Ghee'] },
    { word: 'Pulao', category: 'Food', hints: ['Fragrant Rice', 'One Pot', 'Whole Spices', 'Vegetables', 'Basmati'] },
    { word: 'Kashmiri Pulao', category: 'Food', hints: ['Saffron', 'Dry Fruits', 'Sweet', 'Fragrant', 'Kashmir'] },
    { word: 'Rogan Josh', category: 'Food', hints: ['Kashmir', 'Red Gravy', 'Mutton', 'Aromatic', 'Slow Cooked'] },
    { word: 'Nihari', category: 'Food', hints: ['Slow Cooked', 'Morning', 'Lucknow', 'Shank', 'Rich Gravy'] },
    { word: 'Haleem', category: 'Food', hints: ['Ramzan', 'Hyderabad', 'Wheat Meat', 'Slow Cooked', 'Thick'] },
    { word: 'Seekh Kebab', category: 'Food', hints: ['Skewer', 'Minced Meat', 'Grilled', 'Charcoal', 'Cylindrical'] },
    { word: 'Shammi Kebab', category: 'Food', hints: ['Lucknow', 'Chana Dal', 'Pan Fried', 'Minced', 'Flat Round'] },
    { word: 'Galouti Kebab', category: 'Food', hints: ['Lucknow', 'Melt Mouth', 'Minced', 'Mughlai', 'Tender'] },
    { word: 'Lucknowi Biryani', category: 'Food', hints: ['Awadhi', 'Pukki', 'Saffron', 'Dum', 'Fragrant'] },
    { word: 'Tunde Kebab', category: 'Food', hints: ['Lucknow', 'One Arm', 'Buffalo', 'Famous', 'Spiced'] },
    { word: 'Chicken Tikka', category: 'Food', hints: ['Marinated', 'Tandoor', 'Charred', 'Yogurt', 'Skewer'] },
    { word: 'Tandoori Chicken', category: 'Food', hints: ['Clay Oven', 'Red', 'Yogurt Marinate', 'Charred', 'Leg Piece'] },
    { word: 'Reshmi Kebab', category: 'Food', hints: ['Silky', 'Cream', 'Chicken', 'Tender', 'Grilled'] },
    { word: 'Keema', category: 'Food', hints: ['Minced Meat', 'Spiced', 'Peas', 'North Indian', 'Dry'] },
    { word: 'Keema Pav', category: 'Food', hints: ['Minced Meat', 'Bun', 'Mumbai', 'Spicy', 'Irani Cafe'] },
    { word: 'Mutton Korma', category: 'Food', hints: ['Mughlai', 'Cashew Paste', 'Rich', 'Slow Cooked', 'Aromatic'] },
    { word: 'Bhindi Masala', category: 'Food', hints: ['Okra', 'Spiced', 'Dry', 'Onion', 'Homestyle'] },
    { word: 'Lauki Ki Sabzi', category: 'Food', hints: ['Bottle Gourd', 'Light', 'Homestyle', 'Healthy', 'Simple'] },
    { word: 'Tinda Masala', category: 'Food', hints: ['Round Gourd', 'Summer', 'Spiced', 'North Indian', 'Homestyle'] },
    { word: 'Arhar Dal', category: 'Food', hints: ['Pigeon Pea', 'Turmeric', 'Everyday', 'Tempered', 'Staple'] },
    { word: 'Chana Dal', category: 'Food', hints: ['Split Gram', 'Yellow', 'Bengali', 'Protein', 'Ghee'] },
    // ── South Indian ──
    { word: 'Uttapam', category: 'Food', hints: ['Thick Pancake', 'Onion Topping', 'Fermented', 'South Indian', 'Griddle'] },
    { word: 'Rava Dosa', category: 'Food', hints: ['Semolina', 'Crispy', 'Lacy', 'Instant', 'South Indian'] },
    { word: 'Onion Dosa', category: 'Food', hints: ['Crispy', 'Chopped Onion', 'Tawa', 'Sambhar', 'Chutney'] },
    { word: 'Paper Dosa', category: 'Food', hints: ['Thin', 'Crispy', 'Huge', 'Golden', 'South Indian'] },
    { word: 'Set Dosa', category: 'Food', hints: ['Soft', 'Spongy', 'Stacked', 'Karnataka', 'Three Piece'] },
    { word: 'Medu Vada', category: 'Food', hints: ['Donut Shape', 'Urad Dal', 'Crispy', 'Sambhar', 'South Indian'] },
    { word: 'Bisi Bele Bath', category: 'Food', hints: ['Karnataka', 'Spicy Rice', 'Lentil', 'Masala', 'One Pot'] },
    { word: 'Pesarattu', category: 'Food', hints: ['Moong Dal', 'Andhra', 'Green Crepe', 'Ginger Chutney', 'Breakfast'] },
    { word: 'Upma', category: 'Food', hints: ['Semolina', 'Tempered', 'Breakfast', 'Vegetables', 'South Indian'] },
    { word: 'Pongal', category: 'Food', hints: ['Tamil Nadu', 'Pepper', 'Ghee', 'Cashew', 'Harvest'] },
    { word: 'Curd Rice', category: 'Food', hints: ['Yogurt', 'Comfort', 'Cool', 'Tempered', 'Last Course'] },
    { word: 'Lemon Rice', category: 'Food', hints: ['Turmeric', 'Tangy', 'Temple', 'Peanuts', 'South Indian'] },
    { word: 'Tamarind Rice', category: 'Food', hints: ['Puliyodarai', 'Tangy', 'Temple', 'Brown', 'Peanuts'] },
    { word: 'Coconut Rice', category: 'Food', hints: ['Grated', 'White', 'South Indian', 'Tempered', 'Mild'] },
    { word: 'Tomato Rice', category: 'Food', hints: ['Red', 'Tangy', 'Quick', 'South Indian', 'Spiced'] },
    { word: 'Avial', category: 'Food', hints: ['Mixed Veggie', 'Coconut', 'Kerala', 'Onam', 'Curry Leaf'] },
    { word: 'Sambar', category: 'Food', hints: ['Lentil Stew', 'Tamarind', 'Drumstick', 'South Indian', 'Tempered'] },
    { word: 'Kootu', category: 'Food', hints: ['Dal Veggie', 'Coconut', 'Tamil', 'Mild', 'Side Dish'] },
    { word: 'Puttu', category: 'Food', hints: ['Kerala', 'Steamed', 'Cylindrical', 'Rice Flour', 'Coconut'] },
    { word: 'Appam Stew', category: 'Food', hints: ['Kerala', 'Coconut Milk', 'Lacy Bread', 'Creamy', 'Breakfast'] },
    { word: 'Kerala Parotta', category: 'Food', hints: ['Flaky', 'Layered', 'Maida', 'Kerala', 'Egg Curry'] },
    { word: 'Malabar Biryani', category: 'Food', hints: ['Kerala', 'Fragrant', 'Khaima Rice', 'Fried Onion', 'Dum'] },
    { word: 'Fish Curry', category: 'Food', hints: ['Coastal', 'Coconut', 'Tamarind', 'Spicy', 'Rice'] },
    { word: 'Prawn Masala', category: 'Food', hints: ['Coastal', 'Spicy', 'Onion Tomato', 'Seafood', 'Goa'] },
    { word: 'Fish Fry', category: 'Food', hints: ['Masala Coated', 'Crispy', 'Coastal', 'Shallow Fried', 'Lemon'] },
    { word: 'Chettinad Chicken', category: 'Food', hints: ['Tamil Nadu', 'Pepper', 'Fiery', 'Star Anise', 'Aromatic'] },
    { word: 'Hyderabadi Biryani', category: 'Food', hints: ['Kacchi', 'Dum', 'Saffron', 'Raita', 'Mirchi Salan'] },
    { word: 'Gongura Mutton', category: 'Food', hints: ['Sorrel Leaf', 'Andhra', 'Tangy', 'Spicy', 'Red'] },
    { word: 'Mirchi Ka Salan', category: 'Food', hints: ['Green Chilli', 'Peanut', 'Hyderabad', 'Biryani Side', 'Tangy'] },
    { word: 'Mysore Pak', category: 'Food', hints: ['Ghee', 'Besan', 'Karnataka', 'Melt Mouth', 'Golden'] },
    { word: 'Payasam', category: 'Food', hints: ['Vermicelli', 'Milk', 'South Indian', 'Festive', 'Coconut Milk'] },
    { word: 'Kesari Bath', category: 'Food', hints: ['Semolina', 'Saffron', 'Karnataka', 'Ghee', 'Orange'] },
    { word: 'Coconut Chutney', category: 'Food', hints: ['White', 'Dosa Side', 'Tempered', 'South Indian', 'Fresh'] },
    { word: 'Gunpowder', category: 'Food', hints: ['Podi', 'Dry Chutney', 'Lentil', 'Idli', 'Spicy Powder'] },
    { word: 'Murukku', category: 'Food', hints: ['Spiral', 'Rice Flour', 'Crispy', 'Tamil Nadu', 'Snack'] },
    { word: 'Banana Chips', category: 'Food', hints: ['Kerala', 'Coconut Oil', 'Salted', 'Crispy', 'Plantain'] },
    { word: 'Bonda', category: 'Food', hints: ['Round', 'Deep Fried', 'Potato', 'Besan Coat', 'Snack'] },
    { word: 'Bajji', category: 'Food', hints: ['Batter Fried', 'Chilli', 'Evening Snack', 'South Indian', 'Crispy'] },
    { word: 'Paniyaram', category: 'Food', hints: ['Round', 'Fermented', 'Appe Pan', 'Tamil', 'Ball Shape'] },
    { word: 'Idiappam', category: 'Food', hints: ['String Hopper', 'Rice Flour', 'Steamed', 'Kerala', 'Coconut Milk'] },
    { word: 'Kanji', category: 'Food', hints: ['Rice Porridge', 'Kerala', 'Fermented', 'Watery', 'Simple'] },
    // ── West Indian ──
    { word: 'Dhokla', category: 'Food', hints: ['Gujarat', 'Steamed', 'Besan', 'Spongy', 'Mustard Temper'] },
    { word: 'Khandvi', category: 'Food', hints: ['Gujarat', 'Rolled', 'Besan', 'Thin Layer', 'Tempered'] },
    { word: 'Thepla', category: 'Food', hints: ['Gujarat', 'Fenugreek', 'Flatbread', 'Travel Food', 'Spiced'] },
    { word: 'Undhiyu', category: 'Food', hints: ['Gujarat', 'Winter', 'Mixed Veggie', 'Surti', 'Festive'] },
    { word: 'Handvo', category: 'Food', hints: ['Gujarat', 'Baked', 'Rice Lentil', 'Savoury Cake', 'Tempered'] },
    { word: 'Fafda Jalebi', category: 'Food', hints: ['Gujarat', 'Sunday', 'Crunchy', 'Sweet Salty', 'Breakfast'] },
    { word: 'Sev Khamani', category: 'Food', hints: ['Gujarat', 'Chana Dal', 'Sweet Spicy', 'Sev Topping', 'Steamed'] },
    { word: 'Sev Puri', category: 'Food', hints: ['Crispy Disc', 'Chutney', 'Sev', 'Mumbai', 'Chaat'] },
    { word: 'Ragda Pattice', category: 'Food', hints: ['Peas Curry', 'Potato Patty', 'Chutney', 'Mumbai', 'Street Food'] },
    { word: 'Bombay Sandwich', category: 'Food', hints: ['Chutney', 'Grilled', 'Cheese', 'Mumbai', 'Beetroot'] },
    { word: 'Batata Vada', category: 'Food', hints: ['Potato Ball', 'Besan Coat', 'Fried', 'Mumbai', 'Chutney'] },
    { word: 'Frankie', category: 'Food', hints: ['Mumbai', 'Wrap', 'Roti Roll', 'Street Food', 'Masala'] },
    { word: 'Thalipeeth', category: 'Food', hints: ['Multi Grain', 'Maharashtra', 'Griddle', 'Bhajani', 'Butter'] },
    { word: 'Puran Poli', category: 'Food', hints: ['Sweet Flatbread', 'Chana Dal', 'Maharashtra', 'Festive', 'Ghee'] },
    { word: 'Sabudana Khichdi', category: 'Food', hints: ['Sago', 'Fasting', 'Peanuts', 'Navratri', 'Maharashtra'] },
    { word: 'Zunka Bhakri', category: 'Food', hints: ['Besan', 'Millet Bread', 'Maharashtra', 'Rural', 'Dry'] },
    { word: 'Kolhapuri Chicken', category: 'Food', hints: ['Fiery', 'Red Masala', 'Maharashtra', 'Spicy', 'Kolhapur'] },
    { word: 'Sol Kadhi', category: 'Food', hints: ['Kokum', 'Coconut Milk', 'Pink', 'Konkan', 'Digestive'] },
    { word: 'Kokum Sharbat', category: 'Food', hints: ['Purple', 'Tangy', 'Cooling', 'Konkan', 'Summer'] },
    { word: 'Aamras', category: 'Food', hints: ['Mango Pulp', 'Sweet', 'Puri', 'Gujarat', 'Summer'] },
    { word: 'Shrikhand', category: 'Food', hints: ['Strained Curd', 'Saffron', 'Sweet', 'Gujarat', 'Cardamom'] },
    { word: 'Basundi', category: 'Food', hints: ['Thickened Milk', 'Sweet', 'Saffron', 'Maharashtra', 'Chilled'] },
    { word: 'Modak', category: 'Food', hints: ['Ganesh', 'Coconut Filling', 'Steamed', 'Sweet', 'Maharashtra'] },
    { word: 'Surti Locho', category: 'Food', hints: ['Surat', 'Steamed', 'Soft', 'Chana Dal', 'Sev Topping'] },
    { word: 'Gathiya', category: 'Food', hints: ['Gujarat', 'Besan', 'Crunchy', 'Fried', 'Tea Snack'] },
    { word: 'Dal Baati Churma', category: 'Food', hints: ['Rajasthan', 'Baked Ball', 'Ghee', 'Crushed Sweet', 'Five Dal'] },
    { word: 'Gatte Ki Sabzi', category: 'Food', hints: ['Rajasthan', 'Besan Roll', 'Yogurt Gravy', 'Desert', 'Spiced'] },
    { word: 'Ker Sangri', category: 'Food', hints: ['Rajasthan', 'Desert Bean', 'Dried', 'Pickle', 'Arid'] },
    { word: 'Laal Maas', category: 'Food', hints: ['Rajasthan', 'Red Chilli', 'Mutton', 'Fiery', 'Rajput'] },
    { word: 'Ghevar', category: 'Food', hints: ['Rajasthan', 'Honeycomb', 'Teej', 'Syrup', 'Disc Shape'] },
    { word: 'Mawa Kachori', category: 'Food', hints: ['Jodhpur', 'Sweet Filling', 'Khoya', 'Fried', 'Syrup'] },
    { word: 'Mirchi Vada', category: 'Food', hints: ['Jodhpur', 'Stuffed Chilli', 'Potato', 'Fried', 'Spicy'] },
    // ── East Indian & Northeast ──
    { word: 'Machher Jhol', category: 'Food', hints: ['Bengali Fish', 'Mustard', 'Curry', 'Rice Pair', 'Kolkata'] },
    { word: 'Shorshe Ilish', category: 'Food', hints: ['Hilsa', 'Mustard Paste', 'Bengali', 'Monsoon', 'Steamed'] },
    { word: 'Mishti Doi', category: 'Food', hints: ['Sweet Curd', 'Bengali', 'Clay Pot', 'Jaggery', 'Kolkata'] },
    { word: 'Sandesh', category: 'Food', hints: ['Bengal Sweet', 'Chenna', 'Milk', 'Kolkata', 'Light'] },
    { word: 'Chum Chum', category: 'Food', hints: ['Oval Shape', 'Bengali', 'Milk Sweet', 'Coconut', 'Soft'] },
    { word: 'Pitha', category: 'Food', hints: ['Rice Cake', 'Bengali', 'Assamese', 'Winter', 'Festival'] },
    { word: 'Luchi', category: 'Food', hints: ['Bengal Puri', 'Maida', 'Deep Fried', 'Fluffy', 'Aloo Pair'] },
    { word: 'Aloo Dum', category: 'Food', hints: ['Baby Potato', 'Spicy Gravy', 'Bengali Style', 'Fried', 'Luchi Pair'] },
    { word: 'Jhalmuri', category: 'Food', hints: ['Puffed Rice', 'Spicy Mix', 'Street Snack', 'Kolkata', 'Paper Cone'] },
    { word: 'Phuchka', category: 'Food', hints: ['Golgappa', 'Bengali', 'Tamarind Water', 'Street', 'Crispy Shell'] },
    { word: 'Ghugni', category: 'Food', hints: ['Chickpea Curry', 'Street Snack', 'Bengali', 'Evening', 'Spicy'] },
    { word: 'Muri', category: 'Food', hints: ['Puffed Rice', 'Snack', 'Bengali', 'Light', 'Crunchy'] },
    { word: 'Kosha Mangsho', category: 'Food', hints: ['Mutton', 'Bengali', 'Slow Cooked', 'Dark Gravy', 'Sunday'] },
    { word: 'Doi Maach', category: 'Food', hints: ['Yogurt Fish', 'Bengali', 'Mild', 'Creamy', 'Rohu'] },
    { word: 'Chingri Malaikari', category: 'Food', hints: ['Prawn Curry', 'Coconut', 'Bengali', 'Rich', 'Creamy'] },
    { word: 'Thukpa', category: 'Food', hints: ['Noodle Soup', 'Tibetan', 'Northeast', 'Hot Bowl', 'Winter'] },
    { word: 'Chowmein', category: 'Food', hints: ['Fried Noodles', 'Street', 'Indo Chinese', 'Wok', 'Vegetables'] },
    { word: 'Bamboo Shoot', category: 'Food', hints: ['Northeast', 'Fermented', 'Pickle', 'Forest', 'Nagaland'] },
    { word: 'Pork Ribs', category: 'Food', hints: ['Northeast', 'Smoked', 'Naga Style', 'Meat', 'Bone'] },
    { word: 'Smoked Meat', category: 'Food', hints: ['Northeast', 'Preserved', 'Naga', 'Fire Dried', 'Traditional'] },
    { word: 'Axone', category: 'Food', hints: ['Fermented Soybean', 'Nagaland', 'Strong Smell', 'Northeast', 'Paste'] },
    { word: 'Jadoh', category: 'Food', hints: ['Meghalaya', 'Rice Pork', 'Khasi', 'Mixed', 'Northeast'] },
    { word: 'Tungrymbai', category: 'Food', hints: ['Meghalaya', 'Fermented', 'Soybean', 'Khasi', 'Chutney'] },
    { word: 'Dalma', category: 'Food', hints: ['Odisha', 'Lentil Veggie', 'Temple Food', 'Jagannath', 'Mixed Dal'] },
    { word: 'Chhena Poda', category: 'Food', hints: ['Odisha', 'Baked Cheese', 'Caramelized', 'Sweet', 'Cottage'] },
    { word: 'Chha Gosht', category: 'Food', hints: ['Odisha', 'Mutton', 'Spicy', 'Mustard', 'Traditional'] },
    // ── Sweets & Mithai ──
    { word: 'Kaju Katli', category: 'Food', hints: ['Cashew', 'Silver Foil', 'Diwali', 'Diamond Shape', 'Gift Box'] },
    { word: 'Barfi', category: 'Food', hints: ['Milk Fudge', 'Sweet Shop', 'Silver Leaf', 'Festival', 'Square'] },
    { word: 'Ladoo', category: 'Food', hints: ['Round Sweet', 'Prasad', 'Festival', 'Besan', 'Tirupati'] },
    { word: 'Motichoor Ladoo', category: 'Food', hints: ['Tiny Drops', 'Orange', 'Wedding', 'Boondi', 'Round'] },
    { word: 'Besan Ladoo', category: 'Food', hints: ['Gram Flour', 'Ghee', 'Homemade', 'Yellow', 'Diwali'] },
    { word: 'Peda', category: 'Food', hints: ['Mathura', 'Milk Solid', 'Saffron', 'Temple Sweet', 'Round Flat'] },
    { word: 'Soan Papdi', category: 'Food', hints: ['Flaky', 'Diwali Gift', 'Nobody Wants', 'Layered', 'Sweet Box'] },
    { word: 'Halwa', category: 'Food', hints: ['Semolina', 'Ghee Heavy', 'Prasad', 'Sweet Pudding', 'Warm'] },
    { word: 'Gajar Halwa', category: 'Food', hints: ['Carrot', 'Winter', 'Khoya', 'North India', 'Dessert'] },
    { word: 'Moong Dal Halwa', category: 'Food', hints: ['Lentil', 'Rich', 'Ghee Loaded', 'Rajasthani', 'Winter'] },
    { word: 'Sooji Halwa', category: 'Food', hints: ['Semolina', 'Quick Make', 'Prasad', 'Ghee', 'Sweet'] },
    { word: 'Imarti', category: 'Food', hints: ['Flower Shape', 'Orange', 'Syrup Soaked', 'Urad Dal', 'Jalebi Cousin'] },
    { word: 'Balushahi', category: 'Food', hints: ['Flaky', 'Glazed', 'North Indian', 'Badusha', 'Sweet'] },
    { word: 'Malpua', category: 'Food', hints: ['Pancake', 'Rabri', 'Fried', 'Bengali', 'Festival'] },
    { word: 'Kheer', category: 'Food', hints: ['Rice Pudding', 'Milk', 'Cardamom', 'Saffron', 'Dessert'] },
    { word: 'Rice Kheer', category: 'Food', hints: ['Payasam', 'Milk', 'Sweet', 'Cardamom', 'Temple'] },
    { word: 'Rasmalai', category: 'Food', hints: ['Milk Balls', 'Saffron Cream', 'Bengali', 'Chilled', 'Soft'] },
    { word: 'Kalakand', category: 'Food', hints: ['Milk Cake', 'Alwar', 'Grainy', 'Sweet', 'Paneer'] },
    { word: 'Petha', category: 'Food', hints: ['Agra', 'Ash Gourd', 'Translucent', 'Taj City', 'Soft'] },
    { word: 'Gajak', category: 'Food', hints: ['Sesame', 'Winter', 'Crunchy', 'Jaggery', 'Makar Sankranti'] },
    { word: 'Chikki', category: 'Food', hints: ['Peanut', 'Jaggery', 'Lonavala', 'Brittle', 'Crunchy'] },
    { word: 'Rewri', category: 'Food', hints: ['Sesame Candy', 'Lohri', 'Winter', 'Small', 'Jaggery'] },
    { word: 'Til Ladoo', category: 'Food', hints: ['Sesame Ball', 'Sankranti', 'Jaggery', 'Winter', 'Round'] },
    { word: 'Rasgulla', category: 'Food', hints: ['Syrup Ball', 'Bengal Odisha', 'White', 'Spongy', 'Chenna'] },
    { word: 'Cham Cham', category: 'Food', hints: ['Oval Sweet', 'Bengali', 'Coconut', 'Milk', 'Soft'] },
    { word: 'Pantua', category: 'Food', hints: ['Bengali', 'Gulab Jamun Like', 'Darker', 'Syrup', 'Fried'] },
    { word: 'Double Ka Meetha', category: 'Food', hints: ['Hyderabadi', 'Bread Pudding', 'Saffron', 'Rabri', 'Eid'] },
    { word: 'Qubani Ka Meetha', category: 'Food', hints: ['Apricot', 'Hyderabadi', 'Cream Top', 'Stewed', 'Nizam'] },
    { word: 'Phirni', category: 'Food', hints: ['Rice Pudding', 'Clay Bowl', 'Saffron', 'Mughlai', 'Chilled'] },
    { word: 'Sheer Korma', category: 'Food', hints: ['Eid', 'Vermicelli', 'Milk', 'Dry Fruits', 'Muslim Festival'] },
    // ── Drinks ──
    { word: 'Masala Chai', category: 'Food', hints: ['Adrak', 'Tapri', 'Cutting', 'Ginger Cardamom', 'Morning'] },
    { word: 'Thandai', category: 'Food', hints: ['Holi', 'Almonds', 'Bhang', 'Milk', 'Cool Drink'] },
    { word: 'Aam Panna', category: 'Food', hints: ['Raw Mango', 'Summer', 'Green', 'Tangy', 'Cool'] },
    { word: 'Jaljeera', category: 'Food', hints: ['Cumin Water', 'Tangy', 'Street', 'Digestive', 'Summer'] },
    { word: 'Nimbu Pani', category: 'Food', hints: ['Lemonade', 'Salt Sugar', 'Summer', 'Refreshing', 'Lime'] },
    { word: 'Rooh Afza', category: 'Food', hints: ['Rose Syrup', 'Red', 'Hamdard', 'Ramadan', 'Milk Mix'] },
    { word: 'Shikanji', category: 'Food', hints: ['Lemon Drink', 'North India', 'Masala', 'Salt', 'Summer'] },
    { word: 'Chaas', category: 'Food', hints: ['Buttermilk', 'Gujarati', 'Summer', 'Cumin', 'Digestive'] },
    { word: 'Mango Lassi', category: 'Food', hints: ['Yogurt', 'Aam', 'Thick', 'Sweet', 'Punjabi'] },
    { word: 'Rose Lassi', category: 'Food', hints: ['Pink', 'Yogurt', 'Gulab', 'Sweet', 'Punjab'] },
    { word: 'Badam Milk', category: 'Food', hints: ['Almond', 'Saffron', 'Hot Cold', 'Winter', 'Bedtime'] },
    { word: 'Haldi Doodh', category: 'Food', hints: ['Turmeric Milk', 'Golden', 'Immunity', 'Nani Remedy', 'Night'] },
    { word: 'Sugarcane Juice', category: 'Food', hints: ['Ganne Ka Ras', 'Crusher', 'Summer', 'Street', 'Green'] },
    { word: 'Coconut Water', category: 'Food', hints: ['Nariyal', 'Beach', 'Natural', 'Hydrating', 'Green Shell'] },
    { word: 'Bel Sharbat', category: 'Food', hints: ['Wood Apple', 'Summer', 'Temple', 'Bilva', 'Cool'] },
    { word: 'Kahwa', category: 'Food', hints: ['Kashmiri', 'Green Tea', 'Saffron', 'Almonds', 'Winter'] },
    { word: 'Sulaimani Chai', category: 'Food', hints: ['Kerala', 'Black Tea', 'Lemon', 'No Milk', 'Malabar'] },
    { word: 'Sattu Drink', category: 'Food', hints: ['Bihar', 'Roasted Gram', 'Summer', 'Energy', 'Protein'] },
    { word: 'Jigarthanda', category: 'Food', hints: ['Madurai', 'Cold Drink', 'Almond Gum', 'Tamil Nadu', 'Ice Cream'] },
    { word: 'Paneer Soda', category: 'Food', hints: ['Tamil Nadu', 'Rose Flavour', 'Street', 'Pink', 'Fizzy'] },
    // ── Spices & Ingredients ──
    { word: 'Turmeric', category: 'Food', hints: ['Haldi', 'Yellow', 'Healing', 'Every Curry', 'Antiseptic'] },
    { word: 'Garam Masala', category: 'Food', hints: ['Spice Mix', 'Warm Blend', 'Finishing', 'Aromatic', 'Tadka'] },
    { word: 'Cumin', category: 'Food', hints: ['Jeera', 'Tadka First', 'Seed', 'Earthy', 'Chaunk'] },
    { word: 'Coriander', category: 'Food', hints: ['Dhaniya', 'Green Garnish', 'Seed Powder', 'Fresh Leaves', 'Every Dish'] },
    { word: 'Red Chilli', category: 'Food', hints: ['Lal Mirch', 'Heat', 'Powder', 'Kashmiri', 'Spicy'] },
    { word: 'Mustard Seeds', category: 'Food', hints: ['Rai', 'Tadka Pop', 'South Indian', 'Small Black', 'Crackle'] },
    { word: 'Curry Leaves', category: 'Food', hints: ['Kadipatta', 'South Indian', 'Aromatic', 'Tadka', 'Fresh'] },
    { word: 'Asafoetida', category: 'Food', hints: ['Hing', 'Strong Smell', 'Pinch Only', 'Digestive', 'Dal Essential'] },
    { word: 'Saffron', category: 'Food', hints: ['Kesar', 'Kashmir', 'Expensive', 'Orange Thread', 'Biryani'] },
    { word: 'Cardamom', category: 'Food', hints: ['Elaichi', 'Chai', 'Green Pod', 'Sweet Savory', 'Mouth Freshener'] },
    { word: 'Clove', category: 'Food', hints: ['Laung', 'Toothache', 'Biryani', 'Strong', 'Spice'] },
    { word: 'Cinnamon', category: 'Food', hints: ['Dalchini', 'Bark Roll', 'Sweet Spice', 'Biryani', 'Warm'] },
    { word: 'Bay Leaf', category: 'Food', hints: ['Tej Patta', 'Biryani', 'Remove Before Eat', 'Aromatic', 'Pulao'] },
    { word: 'Fenugreek', category: 'Food', hints: ['Methi', 'Bitter', 'Seeds Leaves', 'Paratha', 'Hair Oil'] },
    { word: 'Black Pepper', category: 'Food', hints: ['Kali Mirch', 'King Spice', 'Kerala', 'Sneeze', 'Grinder'] },
    { word: 'Star Anise', category: 'Food', hints: ['Chakra Phool', 'Biryani', 'Star Shape', 'Licorice', 'Aromatic'] },
    { word: 'Ghee', category: 'Food', hints: ['Clarified Butter', 'Desi', 'Pure', 'Dal Tadka', 'Rich'] },
    { word: 'Paneer', category: 'Food', hints: ['Cottage Cheese', 'Vegetarian', 'Tikka', 'North Indian', 'Protein'] },
    { word: 'Dahi', category: 'Food', hints: ['Curd', 'Homemade', 'Raita', 'Culture', 'White'] },
    { word: 'Atta', category: 'Food', hints: ['Wheat Flour', 'Roti', 'Chakki', 'Dough', 'Daily'] },
    { word: 'Besan', category: 'Food', hints: ['Gram Flour', 'Pakora', 'Yellow', 'Ladoo', 'Chilla'] },
    { word: 'Jaggery', category: 'Food', hints: ['Gur', 'Sugarcane', 'Brown', 'Winter', 'Healthy Sugar'] },
    { word: 'Tamarind', category: 'Food', hints: ['Imli', 'Sour', 'Chutney', 'Sambhar', 'Tangy'] },
    { word: 'Kokum', category: 'Food', hints: ['Konkan', 'Sour Berry', 'Sol Kadhi', 'Dark Purple', 'Goan'] },
    { word: 'Amchur', category: 'Food', hints: ['Mango Powder', 'Sour', 'Dry', 'Chaat Masala', 'Tangy'] },
    // ── Snacks ──
    { word: 'Mathri', category: 'Food', hints: ['Flaky', 'Tea Time', 'Diwali', 'Fried', 'North Indian'] },
    { word: 'Namak Pare', category: 'Food', hints: ['Salty', 'Diamond Shape', 'Diwali', 'Crispy', 'Fried'] },
    { word: 'Chakli', category: 'Food', hints: ['Spiral', 'Maharashtrian', 'Rice Flour', 'Crispy', 'Diwali'] },
    { word: 'Shakarpara', category: 'Food', hints: ['Sweet', 'Diamond', 'Fried', 'Festival', 'Maida'] },
    { word: 'Sev Mamra', category: 'Food', hints: ['Puffed Rice', 'Thin Noodles', 'Gujarati', 'Snack Mix', 'Crunchy'] },
    { word: 'Mixture', category: 'Food', hints: ['Snack Mix', 'Namkeen', 'Farsan', 'Haldiram', 'Tea Time'] },
    { word: 'Chivda', category: 'Food', hints: ['Flattened Rice', 'Poha Mix', 'Maharashtrian', 'Dry Snack', 'Crunchy'] },
    { word: 'Bhujia', category: 'Food', hints: ['Bikaneri', 'Thin Crispy', 'Besan', 'Spicy', 'Haldiram'] },
    { word: 'Papad', category: 'Food', hints: ['Thin Crisp', 'Lijjat', 'Roasted Fried', 'Side Dish', 'Urad'] },
    { word: 'Masala Papad', category: 'Food', hints: ['Onion Tomato', 'Starter', 'Crispy', 'Chaat Style', 'Restaurant'] },
    { word: 'Khakhra', category: 'Food', hints: ['Gujarati', 'Thin Crisp', 'Methi', 'Healthy Snack', 'Travel'] },
    { word: 'Makhana', category: 'Food', hints: ['Fox Nuts', 'Lotus Seed', 'Roasted', 'Healthy', 'Bihar'] },
    { word: 'Aloo Bhujia', category: 'Food', hints: ['Potato Sev', 'Crispy', 'Bikaneri', 'Thin', 'Namkeen'] },
    { word: 'Papdi Chaat', category: 'Food', hints: ['Crispy Wafer', 'Curd', 'Chutney', 'Street', 'Delhi'] },
    { word: 'Dahi Puri', category: 'Food', hints: ['Yogurt', 'Crispy Shell', 'Mumbai', 'Sweet Tangy', 'Chaat'] },
    { word: 'Corn Chaat', category: 'Food', hints: ['Sweet Corn', 'Masala', 'Lime', 'Street', 'Evening'] },
    // ── Breakfast ──
    { word: 'Aloo Poori', category: 'Food', hints: ['Fried Bread', 'Potato Curry', 'Sunday', 'North Indian', 'Puffed'] },
    { word: 'Choora Matar', category: 'Food', hints: ['Flattened Rice', 'Peas', 'UP Style', 'Dry', 'Morning'] },
    { word: 'Anda Bhurji', category: 'Food', hints: ['Scrambled Egg', 'Pav Pair', 'Street', 'Spicy', 'Mumbai'] },
    { word: 'Omelette', category: 'Food', hints: ['Egg', 'Fried', 'Morning', 'Bread Pair', 'Quick'] },
    { word: 'Boiled Eggs', category: 'Food', hints: ['Anda', 'Simple', 'Protein', 'Salt Pepper', 'Gym'] },
    { word: 'Bread Omelette', category: 'Food', hints: ['Street', 'Morning', 'Cart', 'Egg Bread', 'Quick'] },
    { word: 'Misal', category: 'Food', hints: ['Pune', 'Spicy Sprouts', 'Pav Pair', 'Maharashtrian', 'Tarri'] },
    { word: 'Sabudana Vada', category: 'Food', hints: ['Fasting', 'Tapioca', 'Fried', 'Maharashtrian', 'Crispy'] },
    { word: 'Kanda Poha', category: 'Food', hints: ['Onion', 'Flattened Rice', 'Maharashtrian', 'Morning', 'Indore'] },
    { word: 'Sheera', category: 'Food', hints: ['Semolina', 'Sweet', 'Maharashtrian', 'Ghee', 'Morning'] },
    // ── Breads ──
    { word: 'Bhakri', category: 'Food', hints: ['Jowar', 'Maharashtrian', 'Thick Roti', 'Bajra', 'Rural'] },
    { word: 'Rumali Roti', category: 'Food', hints: ['Thin Cloth', 'Handkerchief', 'Tossed', 'Soft', 'Mughlai'] },
    { word: 'Missi Roti', category: 'Food', hints: ['Besan Mix', 'Rajasthani', 'Spiced', 'Gram Flour', 'Thick'] },
    { word: 'Tandoori Naan', category: 'Food', hints: ['Clay Oven', 'Charred', 'Butter Top', 'Punjabi', 'Restaurant'] },
    { word: 'Garlic Naan', category: 'Food', hints: ['Lahsun', 'Butter', 'Tandoor', 'Popular', 'Restaurant'] },
    { word: 'Roomali Roti', category: 'Food', hints: ['Paper Thin', 'Inverted Wok', 'Folded', 'Soft', 'Kebab Pair'] },
    { word: 'Lachha Naan', category: 'Food', hints: ['Layered', 'Flaky', 'Tandoor', 'Butter', 'Striped'] },
    { word: 'Sheermal', category: 'Food', hints: ['Saffron Bread', 'Lucknow', 'Sweet Naan', 'Mughlai', 'Milk'] },
    { word: 'Bakarkhani', category: 'Food', hints: ['Hyderabad', 'Thick Biscuit', 'Mughlai', 'Layered', 'Sweet'] },
    // ── Rice Dishes ──
    { word: 'Tehri', category: 'Food', hints: ['Veg Pulao', 'UP Style', 'Yellow Rice', 'Turmeric', 'One Pot'] },
    { word: 'Veg Biryani', category: 'Food', hints: ['Vegetables', 'Layered Rice', 'Dum', 'Saffron', 'Handi'] },
    { word: 'Chicken Biryani', category: 'Food', hints: ['Hyderabad', 'Dum Style', 'Layered', 'Friday', 'Aromatic'] },
    { word: 'Egg Biryani', category: 'Food', hints: ['Anda', 'Layered Rice', 'Budget', 'Boiled', 'Masala'] },
    { word: 'Khichuri', category: 'Food', hints: ['Bengali', 'Rainy Day', 'Rice Lentil', 'Comfort', 'Ghee Top'] },
    { word: 'Bhuna Khichdi', category: 'Food', hints: ['Roasted', 'Dry Style', 'Rajasthani', 'Moong', 'Ghee'] },
    { word: 'Vangi Bath', category: 'Food', hints: ['Karnataka', 'Brinjal Rice', 'Spicy', 'South Indian', 'Masala'] },
    // ── Non-Veg Mains ──
    { word: 'Butter Naan', category: 'Food', hints: ['Makkhan', 'Tandoor', 'Fluffy', 'Restaurant', 'Golden'] },
    { word: 'Chicken 65', category: 'Food', hints: ['Hyderabad', 'Red Fried', 'Spicy', 'Starter', 'Bar Snack'] },
    { word: 'Chicken Lollipop', category: 'Food', hints: ['Drumstick', 'Fried', 'Indo Chinese', 'Starter', 'Party'] },
    { word: 'Mutton Biryani', category: 'Food', hints: ['Gosht', 'Hyderabadi', 'Dum', 'Bone', 'Rich'] },
    { word: 'Keema Naan', category: 'Food', hints: ['Stuffed', 'Mince', 'Tandoor', 'Mutton', 'Mughlai'] },
    { word: 'Egg Curry', category: 'Food', hints: ['Anda', 'Gravy', 'Boiled', 'Dhaba', 'Rice Pair'] },
    { word: 'Fish Tikka', category: 'Food', hints: ['Grilled', 'Tandoor', 'Marinade', 'Lemon', 'Starter'] },
    { word: 'Pomfret Fry', category: 'Food', hints: ['Coastal', 'Whole Fish', 'Crispy', 'Goan', 'Rava Coat'] },
    { word: 'Prawn Curry', category: 'Food', hints: ['Jhinga', 'Coconut', 'Coastal', 'Goan', 'Rice Pair'] },
    { word: 'Mutton Curry', category: 'Food', hints: ['Gosht', 'Sunday Special', 'Slow Cook', 'Bone', 'Rich'] },
    { word: 'Saag Meat', category: 'Food', hints: ['Spinach', 'Mutton', 'Punjabi', 'Green', 'Winter'] },
    { word: 'Bhuna Gosht', category: 'Food', hints: ['Dry Mutton', 'Slow Cooked', 'Spicy', 'Roasted', 'Rich'] },
    { word: 'Kadai Chicken', category: 'Food', hints: ['Wok', 'Bell Pepper', 'Spicy', 'Restaurant', 'North Indian'] },
    { word: 'Mughlai Chicken', category: 'Food', hints: ['Creamy', 'Royal', 'Rich Gravy', 'Cashew', 'Nawabi'] },
    { word: 'Achari Chicken', category: 'Food', hints: ['Pickle Spice', 'Tangy', 'Mustard Oil', 'North Indian', 'Masala'] },
    // ── Pickles & Condiments ──
    { word: 'Achar', category: 'Food', hints: ['Pickle', 'Oil', 'Sun Dried', 'Spicy', 'Grandma'] },
    { word: 'Mango Pickle', category: 'Food', hints: ['Aam', 'Raw', 'Summer', 'Oil Spice', 'Tangy'] },
    { word: 'Lime Pickle', category: 'Food', hints: ['Nimbu', 'Sour', 'Salt', 'Aged', 'Yellow'] },
    { word: 'Garlic Pickle', category: 'Food', hints: ['Lahsun', 'Spicy', 'Oil', 'Strong', 'Rajasthani'] },
    { word: 'Murabba', category: 'Food', hints: ['Preserve', 'Amla', 'Sweet', 'Syrup', 'Traditional'] },
    // ── Food Culture ──
    { word: 'Tiffin', category: 'Food', hints: ['Lunch Box', 'School', 'Steel', 'Packed', 'Compartment'] },
    { word: 'Dabba', category: 'Food', hints: ['Lunch Box', 'Mumbai', 'Office', 'Steel', 'Delivery'] },
    { word: 'Dabbawala', category: 'Food', hints: ['Mumbai', 'Lunch Delivery', 'Train', 'White Cap', 'Zero Error'] },
    { word: 'Dhaba', category: 'Food', hints: ['Highway', 'Truck Stop', 'Charpoy', 'Punjabi', 'Roadside'] },
    { word: 'Halwai', category: 'Food', hints: ['Sweet Maker', 'Shop', 'Mithai', 'Traditional', 'Festival'] },
    { word: 'Tandoor', category: 'Food', hints: ['Clay Oven', 'Charcoal', 'Naan', 'Hot', 'Cylinder'] },
    { word: 'Tawa', category: 'Food', hints: ['Flat Pan', 'Roti', 'Iron', 'Griddle', 'Dosa'] },
    { word: 'Kadhai', category: 'Food', hints: ['Wok', 'Deep Fry', 'Iron', 'Round Bottom', 'Cooking'] },
    { word: 'Handi', category: 'Food', hints: ['Clay Pot', 'Dum', 'Slow Cook', 'Traditional', 'Biryani'] },
    { word: 'Pressure Cooker', category: 'Food', hints: ['Whistle', 'Dal', 'Hawkins', 'Seethi', 'Every Kitchen'] },
    { word: 'Sil Batta', category: 'Food', hints: ['Stone Grinder', 'Chutney', 'Traditional', 'Flat Stone', 'Manual'] },
    { word: 'Masala Dabba', category: 'Food', hints: ['Spice Box', 'Steel Round', 'Seven Compartments', 'Kitchen', 'Essential'] },
    { word: 'Banana Leaf', category: 'Food', hints: ['South Indian', 'Sadhya', 'Plate', 'Green', 'Traditional'] },
    { word: 'Patta Plate', category: 'Food', hints: ['Leaf Plate', 'Eco', 'Langar', 'Disposable', 'Traditional'] },
  ],
};
