import type { WordPack } from '../game/types';

export const musicPack: WordPack = {
  id: 'music',
  name: 'Music',
  entries: [
    // Bollywood songs - classics
    { word: 'Chaiyya Chaiyya', category: 'Music', hints: ['Train Roof', 'Dil Se', 'Sukhwinder', 'Shah Rukh', 'Malaika'] },
    { word: 'Kal Ho Naa Ho', category: 'Music', hints: ['Heartbreak', 'Shankar Ehsaan', 'Sonu Nigam', 'New York', 'Shah Rukh'] },
    { word: 'Tujhe Dekha Toh', category: 'Music', hints: ['DDLJ', 'Mustard Fields', 'Kumar Sanu', 'Switzerland', 'Lata'] },
    { word: 'Mere Sapno Ki Rani', category: 'Music', hints: ['Aradhana', 'Jeep Chase', 'Rajesh Khanna', 'Kishore', 'Train'] },
    { word: 'Lag Ja Gale', category: 'Music', hints: ['Woh Kaun Thi', 'Melancholy', 'Lata', 'Madan Mohan', 'Embrace'] },
    { word: 'Dum Maro Dum', category: 'Music', hints: ['Hare Krishna', 'Asha Bhosle', 'RD Burman', 'Hippie', 'Zeenat'] },
    { word: 'Roop Tera Mastana', category: 'Music', hints: ['Aradhana', 'Kishore', 'Candlelight', 'Sharmila', 'RD Burman'] },
    { word: 'Chura Liya Hai', category: 'Music', hints: ['Yaadon Ki Baaraat', 'Asha Rafi', 'Stolen Heart', 'RD Burman', 'Retro'] },
    { word: 'Ek Ladki Bheegi Bhaagi', category: 'Music', hints: ['Chalti Ka Naam', 'Kishore', 'Rain', 'Comedy', 'Madhubala'] },
    { word: 'Pyar Kiya Toh Darna', category: 'Music', hints: ['Mughal-e-Azam', 'Lata', 'Anarkali', 'Sheesh Mahal', 'Naushad'] },
    { word: 'Yeh Dosti', category: 'Music', hints: ['Sholay', 'Friendship', 'Sidecar', 'Kishore Rafi', 'Jai Veeru'] },
    { word: 'Mehbooba Mehbooba', category: 'Music', hints: ['Sholay', 'RD Burman', 'Helen', 'Desert', 'Belly Dance'] },
    { word: 'Kabhi Kabhie', category: 'Music', hints: ['Amitabh', 'Poetry', 'Mukesh', 'Sahir', 'Romance'] },
    { word: 'Om Shanti Om', category: 'Music', hints: ['Karz', 'Rishi Kapoor', 'Stage', 'Reincarnation', 'Kishore'] },
    { word: 'Mundian To Bach Ke', category: 'Music', hints: ['Panjabi MC', 'Bhangra', 'Viral Global', 'Jay-Z Remix', 'Dhol'] },
    { word: 'Kajra Re', category: 'Music', hints: ['Bunty Aur Babli', 'Aishwarya', 'Amitabh', 'Alisha', 'Shankar Ehsaan'] },
    { word: 'Rang De Basanti', category: 'Music', hints: ['AR Rahman', 'Patriotic', 'Daler Mehndi', 'Aamir Khan', 'Revolution'] },
    { word: 'Jai Ho', category: 'Music', hints: ['Slumdog', 'Oscar Winner', 'AR Rahman', 'Victory', 'Global Hit'] },
    { word: 'Masakali', category: 'Music', hints: ['Delhi-6', 'Pigeon', 'AR Rahman', 'Mohit Chauhan', 'Rooftop'] },
    { word: 'Dil Se Re', category: 'Music', hints: ['Title Track', 'AR Rahman', 'Lata', 'Train', 'Intense'] },
    { word: 'Kun Faya Kun', category: 'Music', hints: ['Rockstar', 'AR Rahman', 'Sufi', 'Ranbir', 'Dargah'] },
    { word: 'Tum Hi Ho', category: 'Music', hints: ['Aashiqui 2', 'Arijit', 'Love Anthem', 'Mithoon', 'Shraddha'] },
    { word: 'Channa Mereya', category: 'Music', hints: ['Ae Dil', 'Arijit', 'Breakup', 'Ranbir', 'Pritam'] },
    { word: 'Gerua', category: 'Music', hints: ['Dilwale', 'Iceland', 'Arijit', 'Pritam', 'Shah Rukh Kajol'] },
    { word: 'Badtameez Dil', category: 'Music', hints: ['Yeh Jawaani', 'Ranbir', 'Party Song', 'Benny Dayal', 'Pritam'] },
    { word: 'Lungi Dance', category: 'Music', hints: ['Chennai Express', 'Honey Singh', 'Rajinikanth Tribute', 'Shah Rukh', 'South'] },
    { word: 'Balam Pichkari', category: 'Music', hints: ['Yeh Jawaani', 'Holi', 'Vishal Shekhar', 'Ranbir', 'Colors'] },
    { word: 'Gallan Goodiyaan', category: 'Music', hints: ['Dil Dhadakne Do', 'Family Dance', 'Ship', 'Shankar Ehsaan', 'Farhan'] },
    { word: 'Zingaat', category: 'Music', hints: ['Sairat', 'Marathi', 'Ajay Atul', 'Dhadak Remake', 'Wedding DJ'] },
    { word: 'Apna Time Aayega', category: 'Music', hints: ['Gully Boy', 'Ranveer', 'Rap', 'Mumbai Slum', 'Divine'] },
    { word: 'Ghoomar', category: 'Music', hints: ['Padmaavat', 'Deepika', 'Rajasthani', 'Twirl', 'Sanjay Leela'] },
    { word: 'Khalibali', category: 'Music', hints: ['Padmaavat', 'Ranveer', 'Wild Dance', 'Shivam Pathak', 'Khilji'] },
    { word: 'Aankh Marey', category: 'Music', hints: ['Simmba', 'Ranveer Sara', 'Mika', 'Remake', 'Neha Kakkar'] },
    { word: 'London Thumakda', category: 'Music', hints: ['Queen', 'Kangana', 'Wedding Song', 'Labh Janjua', 'Amit Trivedi'] },
    { word: 'Desi Girl', category: 'Music', hints: ['Dostana', 'Priyanka', 'Vishal Shekhar', 'Beach', 'John Abraham'] },
    { word: 'Nachde Ne Saare', category: 'Music', hints: ['Baar Baar Dekho', 'Wedding Dance', 'Jasleen Royal', 'Sidharth', 'Katrina'] },
    { word: 'Malhari', category: 'Music', hints: ['Bajirao Mastani', 'Ranveer', 'Victory Dance', 'Vishal Dadlani', 'Peshwa'] },
    { word: 'Tattad Tattad', category: 'Music', hints: ['Ram Leela', 'Ranveer', 'Garba Energy', 'Holi', 'Sanjay Leela'] },
    { word: 'Nagada Sang Dhol', category: 'Music', hints: ['Ram Leela', 'Deepika', 'Garba', 'Osman Mir', 'Navratri'] },
    { word: 'Dhoom Machale', category: 'Music', hints: ['Bike Chase', 'Sunidhi', 'Pritam', 'Title Track', 'Hrithik'] },
    { word: 'Sheila Ki Jawani', category: 'Music', hints: ['Tees Maar Khan', 'Katrina', 'Vishal Shekhar', 'Item Song', 'Dance Floor'] },
    { word: 'Munni Badnaam Hui', category: 'Music', hints: ['Dabangg', 'Malaika', 'Mamta Sharma', 'Salman', 'Item Song'] },
    { word: 'Fevicol Se', category: 'Music', hints: ['Dabangg 2', 'Kareena', 'Mamta Sharma', 'Salman', 'Adhesive'] },
    { word: 'Baby Doll', category: 'Music', hints: ['Ragini MMS 2', 'Kanika Kapoor', 'Meet Bros', 'Sunny Leone', 'Party Hit'] },
    { word: 'Suno Na Sangemarmar', category: 'Music', hints: ['Youngistaan', 'Arijit', 'Jackky Bhagnani', 'Romantic', 'Jeet Gannguli'] },
    { word: 'Tere Bina', category: 'Music', hints: ['Guru', 'AR Rahman', 'Chinmayi', 'Aishwarya', 'Abhishek'] },
    { word: 'Ae Dil Hai Mushkil', category: 'Music', hints: ['Title Track', 'Arijit', 'Pritam', 'Ranbir', 'Heartbreak'] },
    { word: 'Bulleya', category: 'Music', hints: ['Ae Dil', 'Amit Mishra', 'Pritam', 'Sufi', 'Ranbir Anushka'] },
    { word: 'Roke Na Ruke Naina', category: 'Music', hints: ['Badrinath', 'Arijit', 'Varun Alia', 'Amaal Mallik', 'Romantic'] },
    { word: 'Raabta Title Track', category: 'Music', hints: ['Arijit', 'Sushant Kriti', 'Pritam', 'Love Story', 'Past Life'] },
    { word: 'Kala Chashma', category: 'Music', hints: ['Baar Baar Dekho', 'Badshah', 'Sidharth Katrina', 'Sunglasses', 'Amar Arshi'] },
    { word: 'Kar Gayi Chull', category: 'Music', hints: ['Kapoor And Sons', 'Badshah', 'Alia', 'Fazilpuria', 'Party'] },
    { word: 'Cheap Thrills Remix', category: 'Music', hints: ['Sia', 'Vidya Vox', 'Mashup', 'Indian Twist', 'Viral'] },
    { word: 'High Heels', category: 'Music', hints: ['Ki And Ka', 'Honey Singh', 'Jaz Dhami', 'Arjun Kareena', 'Party'] },
    { word: 'Naach Meri Rani', category: 'Music', hints: ['Guru Randhawa', 'Nora Fatehi', 'Tanishk', 'Robot Dance', 'Party'] },
    { word: 'Bijlee Bijlee', category: 'Music', hints: ['Harrdy Sandhu', 'Palak Tiwari', 'Electric', 'Punjabi Pop', 'Jaani'] },
    { word: 'Pasoori', category: 'Music', hints: ['Coke Studio', 'Ali Sethi', 'Shae Gill', 'Pakistan', 'Viral Global'] },
    { word: 'Kesariya', category: 'Music', hints: ['Brahmastra', 'Arijit', 'Pritam', 'Ranbir Alia', 'Saffron'] },
    { word: 'Maan Meri Jaan', category: 'Music', hints: ['King', 'Indie Hit', 'Champagne Talk', 'Viral Reel', 'Romantic'] },
    { word: 'Tere Hawaale', category: 'Music', hints: ['Laal Singh Chaddha', 'Arijit', 'Pritam', 'Aamir Kareena', 'Emotional'] },

    // Bollywood songs - 90s/2000s
    { word: 'Suraj Hua Maddham', category: 'Music', hints: ['K3G', 'SRK Kajol', 'Egypt Shot', 'Sonu Nigam', 'Romantic'] },
    { word: 'Pehla Nasha', category: 'Music', hints: ['Jo Jeeta Wohi Sikandar', 'First Love', 'Aamir', 'Sadhana Sargam', 'College'] },
    { word: 'Kuch Kuch Hota Hai', category: 'Music', hints: ['SRK Kajol', 'Udit Alka', 'Summer Camp', 'Title Track', 'Jatin Lalit'] },
    { word: 'Dil To Pagal Hai', category: 'Music', hints: ['SRK Madhuri', 'Lata Udit', 'Dance Film', 'Yash Chopra', 'Title Track'] },
    { word: 'Tip Tip Barsa Paani', category: 'Music', hints: ['Mohra', 'Raveena Rain', 'Alka Yagnik', 'Sensuous', 'Nineties'] },
    { word: 'Tu Cheez Badi Hai', category: 'Music', hints: ['Mohra', 'Akshay Raveena', 'Udit Kavita', 'Party Song', 'Remake'] },
    { word: 'Choli Ke Peeche', category: 'Music', hints: ['Khalnayak', 'Madhuri', 'Controversial', 'Ila Arun', 'Nineties'] },
    { word: 'Humma Humma', category: 'Music', hints: ['Bombay', 'Rahman', 'Tamil Origin', 'Remo Fernandes', 'OK Jaanu Remake'] },
    { word: 'Mera Joota Hai Japani', category: 'Music', hints: ['Shree 420', 'Raj Kapoor', 'Patriotic', 'Mukesh', 'Evergreen'] },
    { word: 'Woh Lamhe', category: 'Music', hints: ['Zeher', 'Atif Aslam', 'Emraan', 'Sad Song', 'Two Thousands'] },
    { word: 'Tumse Milke', category: 'Music', hints: ['Parinda', 'Asha Bhosle', 'Suresh Wadkar', 'RD Burman', 'Emotional'] },
    { word: 'Dard-E-Disco', category: 'Music', hints: ['Om Shanti Om', 'SRK Shirtless', 'Club Song', 'Sukhwinder', 'Disco'] },
    { word: 'Koi Mil Gaya Title', category: 'Music', hints: ['Hrithik', 'Alien Jadoo', 'Udit Narayan', 'Alka Yagnik', 'Idhar Chala'] },
    { word: 'Saanson Ki Zaroorat', category: 'Music', hints: ['Aashiqui', 'Kumar Sanu', 'Romantic', 'Nineties', 'Rahul Roy'] },
    { word: 'Jaadu Teri Nazar', category: 'Music', hints: ['Darr', 'SRK Stalker', 'Udit Narayan', 'Obsession', 'Shiv Kumar'] },
    { word: 'Papa Kehte Hain', category: 'Music', hints: ['Qayamat Se', 'Aamir Khan', 'Udit Narayan', 'College Song', 'Debut'] },
    { word: 'Saawariya', category: 'Music', hints: ['Swades', 'AR Rahman', 'Udit Narayan', 'NRI Return', 'SRK'] },
    { word: 'Tu Jaane Na', category: 'Music', hints: ['Ajab Prem', 'Atif Aslam', 'Ranbir Katrina', 'Romantic', 'Pritam'] },
    { word: 'Kabhi Alvida Naa', category: 'Music', hints: ['Karan Johar', 'SRK Rani', 'Sonu Nigam', 'Farewell', 'SEL'] },
    { word: 'Mitwa', category: 'Music', hints: ['KKKG', 'Kabhi Khushi', 'Shaan', 'Friendship', 'SRK Hrithik'] },

    // Indian singers
    { word: 'Kishore Kumar', category: 'Music', hints: ['Yodeling', 'Mere Sapno Ki', 'Golden Voice', 'Bengali', 'Comedian Actor'] },
    { word: 'Lata Mangeshkar', category: 'Music', hints: ['Nightingale', 'Bharat Ratna', 'Aye Mere Watan', 'Highest Range', 'Didi'] },
    { word: 'Mohammed Rafi', category: 'Music', hints: ['Versatile Legend', 'Tere Mere Sapne', 'Golden Era', 'Naushad Duo', 'Gentle Voice'] },
    { word: 'Asha Bhosle', category: 'Music', hints: ['RD Partner', 'Cabaret Queen', 'Guinness Record', 'Piya Tu', 'Lata Sister'] },
    { word: 'Arijit Singh', category: 'Music', hints: ['Tum Hi Ho', 'Modern King', 'Bengali Origin', 'Pritam Duo', 'Soft Voice'] },
    { word: 'Shreya Ghoshal', category: 'Music', hints: ['Sa Re Ga Ma Pa Winner', 'Devdas', 'Sanjay Leela', 'Bairi Piya', 'Melody Queen'] },
    { word: 'Sonu Nigam', category: 'Music', hints: ['Kal Ho Naa Ho', 'Rafi Tribute', 'Child Star', 'Abhi Mujh Mein', 'Versatile'] },
    { word: 'Kumar Sanu', category: 'Music', hints: ['Nineties King', 'Bengali', 'Romantic Voice', 'Filmfare Five Times', 'Gulshan Kumar'] },
    { word: 'Udit Narayan', category: 'Music', hints: ['Pehla Nasha', 'Nepal Origin', 'Papa Kehte Hain', 'SRK Voice', 'Padma Bhushan'] },
    { word: 'Alka Yagnik', category: 'Music', hints: ['Nineties Queen', 'Most Streamed', 'Tip Tip', 'Kajol Songs', 'Jatin Lalit'] },
    { word: 'Sunidhi Chauhan', category: 'Music', hints: ['Dhoom Machale', 'Powerful Voice', 'Child Prodigy', 'Sheila', 'Kamli'] },
    { word: 'KK', category: 'Music', hints: ['Pal', 'Yaaron', 'Emraan Songs', 'Live Concert', 'Soulful Voice'] },
    { word: 'Atif Aslam', category: 'Music', hints: ['Pakistani', 'Woh Lamhe', 'Aadat', 'Jal Band', 'Cross Border'] },
    { word: 'Neha Kakkar', category: 'Music', hints: ['Instagram Queen', 'Aankh Marey', 'Indian Idol', 'Rohanpreet', 'Party Songs'] },
    { word: 'Honey Singh', category: 'Music', hints: ['Lungi Dance', 'Punjabi Rap', 'Brown Rang', 'Hirdesh', 'Comeback'] },
    { word: 'Badshah', category: 'Music', hints: ['DJ Waley Babu', 'Kala Chashma', 'Rapper', 'Paagal Views', 'Genda Phool'] },
    { word: 'Diljit Dosanjh', category: 'Music', hints: ['Punjabi Star', 'GOAT', 'Coachella', 'Actor Singer', 'Turban'] },
    { word: 'AP Dhillon', category: 'Music', hints: ['Brown Munde', 'Canada Punjabi', 'Excuses', 'With You', 'New Wave'] },
    { word: 'Karan Aujla', category: 'Music', hints: ['Softly', 'Punjabi Rapper', 'BTFU', 'Canada Based', 'Tauja'] },
    { word: 'Prateek Kuhad', category: 'Music', hints: ['Cold Mess', 'Obama Playlist', 'Indie Artist', 'Kasoor', 'Soft Voice'] },
    { word: 'Anuv Jain', category: 'Music', hints: ['Baarishein', 'Indie Pop', 'Gul', 'Alag Aasmaan', 'Soft Vocals'] },
    { word: 'Ritviz', category: 'Music', hints: ['Udd Gaye', 'Electronic', 'Indie Dance', 'Liggi', 'Bacardi Sessions'] },
    { word: 'Nucleya', category: 'Music', hints: ['Bass Rani', 'EDM India', 'Udyan Sagar', 'Laung Gawacha', 'Drop'] },
    { word: 'Divine', category: 'Music', hints: ['Gully Boy', 'Mere Gully Mein', 'Mumbai Rapper', 'Vivian Fernandes', 'Street'] },
    { word: 'Raftaar', category: 'Music', hints: ['Swag Mera Desi', 'Rapper', 'MTV Hustle', 'Dilin Nair', 'Kerala Origin'] },
    { word: 'Armaan Malik', category: 'Music', hints: ['Bol Do Na Zara', 'Young Singer', 'Sa Re Ga Ma Pa', 'Amaal Brother', 'Romantic Voice'] },
    { word: 'Jubin Nautiyal', category: 'Music', hints: ['Lut Gaye', 'Raataan Lambiyan', 'Uttarakhand', 'T-Series Hits', 'Tum Hi Aana'] },
    { word: 'Darshan Raval', category: 'Music', hints: ['Tera Zikr', 'Gujarat', 'Indie Pop', 'Dil Mera Blast', 'Raw Star'] },
    { word: 'Vishal Dadlani', category: 'Music', hints: ['Rock On', 'Vishal Shekhar', 'Pentagram', 'Indian Idol Judge', 'Bhaag DK Bose'] },
    { word: 'Shaan', category: 'Music', hints: ['Chand Sifarish', 'Tanha Dil', 'Jab Se Tere Naina', 'Smooth Voice', 'Bollywood Pop'] },
    { word: 'Mika Singh', category: 'Music', hints: ['Mauja Hi Mauja', 'Punjabi Party', 'Sawan Mein', 'Singh Is King', 'Daler Brother'] },
    { word: 'Sukhwinder Singh', category: 'Music', hints: ['Chaiyya Chaiyya', 'Jai Ho', 'Powerful Voice', 'Hairy Singh', 'Padmaavat'] },
    { word: 'Mohit Chauhan', category: 'Music', hints: ['Tum Se Hi', 'Masakali', 'Silk Route', 'Rockstar', 'Sadda Haq'] },
    { word: 'Shankar Mahadevan', category: 'Music', hints: ['Breathless', 'SEL Trio', 'Classical Trained', 'Mitwa', 'Marathi'] },
    { word: 'Hariharan', category: 'Music', hints: ['Ghazal Singer', 'Colonial Cousins', 'Tu Hi Re', 'Bombay Jayashri', 'Soulful'] },
    { word: 'SPB', category: 'Music', hints: ['South Legend', 'Ek Duuje Ke Liye', 'Balasubrahmanyam', 'Guinness', 'Telugu Tamil'] },
    { word: 'Sid Sriram', category: 'Music', hints: ['Maate Vinadhuga', 'South Sensation', 'Berkeley Trained', 'Srivalli', 'Telugu Hits'] },
    { word: 'Rahat Fateh Ali Khan', category: 'Music', hints: ['Tere Mast Mast', 'Pakistani', 'Nusrat Nephew', 'Jiya Dhadak', 'Sufi Voice'] },
    { word: 'Nusrat Fateh Ali Khan', category: 'Music', hints: ['Qawwali King', 'Pakistani Legend', 'Afreen Afreen', 'Dam Mast', 'World Music'] },
    { word: 'Jagjit Singh', category: 'Music', hints: ['Ghazal King', 'Tum Itna Jo', 'Chitra Duo', 'Hoshwalon Ko', 'Velvet Voice'] },
    { word: 'Gulzar', category: 'Music', hints: ['Lyricist Poet', 'Tere Bina', 'Oscar Speech', 'Sampooran Singh', 'Filmmaking'] },
    { word: 'Javed Akhtar', category: 'Music', hints: ['Lyricist', 'Salim Javed', 'Farhan Father', 'Sholay Writer', 'Padma Bhushan'] },
    { word: 'Irshad Kamil', category: 'Music', hints: ['Imtiaz Ali Films', 'Tum Se Hi', 'Love Aaj Kal', 'Rockstar Lyrics', 'Punjabi Poet'] },
    { word: 'Amitabh Bhattacharya', category: 'Music', hints: ['Channa Mereya', 'Pritam Partner', 'Gerua', 'Ilahi', 'Modern Lyricist'] },

    // Composers / Music directors
    { word: 'AR Rahman', category: 'Music', hints: ['Oscar Winner', 'Roja', 'Mozart Madras', 'Jai Ho', 'Tamil Genius'] },
    { word: 'RD Burman', category: 'Music', hints: ['Pancham Da', 'Asha Duo', 'Mouth Organ', 'Sholay', 'Dum Maro Dum'] },
    { word: 'SD Burman', category: 'Music', hints: ['Pancham Father', 'Bengali', 'Guide Film', 'Dev Anand', 'Wahan Kaun Hai'] },
    { word: 'Shankar Ehsaan Loy', category: 'Music', hints: ['Trio', 'Dil Chahta Hai', 'SEL', 'Rock On', 'Kal Ho Naa Ho'] },
    { word: 'Vishal Shekhar', category: 'Music', hints: ['Duo', 'War', 'Sheila', 'Chennai Express', 'Balam Pichkari'] },
    { word: 'Pritam', category: 'Music', hints: ['Ae Dil', 'Bollywood Hit Machine', 'Barfi', 'Gerua', 'Arijit Partner'] },
    { word: 'Amit Trivedi', category: 'Music', hints: ['Dev D', 'Udaan', 'Queen Film', 'Indie Sound', 'Manmarziyaan'] },
    { word: 'Mithoon', category: 'Music', hints: ['Tum Hi Ho', 'Aashiqui 2', 'Melody Master', 'Maahi Ve', 'Romantic Ballads'] },
    { word: 'Sachin Jigar', category: 'Music', hints: ['Duo', 'ABCD', 'Gujarati', 'Nachde Ne Saare', 'Dance Songs'] },
    { word: 'Tanishk Bagchi', category: 'Music', hints: ['Remix King', 'Remake Master', 'T-Series', 'Vaaste', 'Lut Gaye'] },
    { word: 'Anu Malik', category: 'Music', hints: ['Indian Idol Judge', 'Nineties', 'Border', 'Copied Tunes', 'Dil Hai Ke'] },
    { word: 'Himesh Reshammiya', category: 'Music', hints: ['Nasal Voice', 'Cap Singer', 'Aashiq Banaya', 'Tera Suroor', 'Actor Composer'] },
    { word: 'Nadeem Shravan', category: 'Music', hints: ['Aashiqui', 'Nineties Duo', 'Saajan', 'Dil Hai Ke', 'Melody Kings'] },
    { word: 'Jatin Lalit', category: 'Music', hints: ['DDLJ', 'Kuch Kuch', 'Brothers Duo', 'Nineties', 'SRK Films'] },
    { word: 'Laxmikant Pyarelal', category: 'Music', hints: ['Duo Legend', 'Bobby', 'Tezaab', 'Hum Aapke', 'Dosti'] },
    { word: 'Ilaiyaraaja', category: 'Music', hints: ['South Maestro', 'Tamil Legend', 'Roja Kaadhal', 'Isaignani', 'Symphony'] },

    // Classical music terms
    { word: 'Raag Yaman', category: 'Music', hints: ['Evening Raga', 'Kalyan Thaat', 'Tivra Ma', 'Romantic Mood', 'Beginner Raga'] },
    { word: 'Raag Bhairavi', category: 'Music', hints: ['Morning Raga', 'Komal Notes', 'Closing Piece', 'Devotional', 'All Flat'] },
    { word: 'Raag Malkauns', category: 'Music', hints: ['Midnight', 'Pentatonic', 'Serious Mood', 'Man Tadpat', 'Shiva'] },
    { word: 'Raag Darbari', category: 'Music', hints: ['Court Music', 'Tansen', 'Akbar', 'Grave Mood', 'Late Night'] },
    { word: 'Raag Bhimpalasi', category: 'Music', hints: ['Afternoon', 'Romantic', 'Komal Ni Ga', 'Popular Raga', 'Film Songs'] },
    { word: 'Taal Teentaal', category: 'Music', hints: ['16 Beats', 'Most Common', 'Four Vibhag', 'Clap Pattern', 'Hindustani'] },
    { word: 'Taal Ektaal', category: 'Music', hints: ['12 Beats', 'Slow Tempo', 'Khayal Singing', 'Six Vibhag', 'Classical'] },
    { word: 'Jhaptaal', category: 'Music', hints: ['10 Beats', 'Asymmetric', 'Classical Taal', 'Four Vibhag', 'Medium Tempo'] },
    { word: 'Alaap', category: 'Music', hints: ['Opening Section', 'No Rhythm', 'Slow Exploration', 'Raga Intro', 'Free Tempo'] },
    { word: 'Bandish', category: 'Music', hints: ['Composition', 'Fixed Melody', 'Khayal Form', 'Sthayi Antara', 'Set Piece'] },
    { word: 'Taan', category: 'Music', hints: ['Fast Notes', 'Melodic Run', 'Rapid Passage', 'Vocal Display', 'Sapat Koot'] },
    { word: 'Jugalbandi', category: 'Music', hints: ['Duet Duel', 'Two Artists', 'Instrumental', 'Friendly Battle', 'Zakir Shankar'] },
    { word: 'Sargam', category: 'Music', hints: ['Note Names', 'Sa Re Ga', 'Singing Notes', 'Solfa Indian', 'Seven Notes'] },
    { word: 'Saptak', category: 'Music', hints: ['Octave', 'Seven Notes', 'Mandra Madhya', 'Scale Range', 'Three Registers'] },
    { word: 'Shruti', category: 'Music', hints: ['Microtone', 'Twenty Two', 'Pitch Nuance', 'Fine Tuning', 'Subtle Note'] },
    { word: 'Thaat', category: 'Music', hints: ['Parent Scale', 'Ten Types', 'Bhatkhande System', 'Raga Family', 'Classification'] },
    { word: 'Dhrupad', category: 'Music', hints: ['Ancient Form', 'Temple Music', 'Dagars', 'Austere', 'Pakhawaj'] },
    { word: 'Khayal', category: 'Music', hints: ['Imagination', 'Main Vocal Form', 'Vilambit Drut', 'Bandish Based', 'Romantic'] },
    { word: 'Thumri', category: 'Music', hints: ['Light Classical', 'Romantic Form', 'Lucknow', 'Expressive', 'Semi Classical'] },
    { word: 'Tarana', category: 'Music', hints: ['Fast Syllables', 'Nom Tom', 'Energetic', 'Amir Khusrau', 'Rhythmic Vocal'] },
    { word: 'Raga Alapana', category: 'Music', hints: ['South Indian', 'Carnatic Intro', 'No Tempo', 'Raga Unveiling', 'Manodharma'] },
    { word: 'Meend', category: 'Music', hints: ['Glide', 'Note Slide', 'Continuous Bend', 'Ornament', 'Sitar Technique'] },
    { word: 'Gamak', category: 'Music', hints: ['Oscillation', 'Heavy Shake', 'Ornament', 'Note Vibration', 'Force'] },
    { word: 'Swara', category: 'Music', hints: ['Musical Note', 'Sa Re Ga', 'Seven Total', 'Pitch', 'Shuddha Vikrit'] },
    { word: 'Komal Swar', category: 'Music', hints: ['Flat Note', 'Lowered Pitch', 'Re Ga Dha Ni', 'Soft', 'Four Types'] },
    { word: 'Tivra Swar', category: 'Music', hints: ['Sharp Note', 'Raised Pitch', 'Only Ma', 'Single Type', 'Bright'] },
    { word: 'Sa Re Ga Ma', category: 'Music', hints: ['Indian Scale', 'Solfege', 'Seven Notes', 'Do Re Mi', 'Sargam'] },
    { word: 'Hindustani Classical', category: 'Music', hints: ['North Indian', 'Raga Based', 'Mughal Influence', 'Gharana System', 'Khayal Dhrupad'] },
    { word: 'Carnatic Music', category: 'Music', hints: ['South Indian', 'Tyagaraja', 'Kriti Form', 'Veena', 'Devotional Focus'] },
    { word: 'Gharana', category: 'Music', hints: ['Musical House', 'Lineage', 'Teaching Style', 'Gwalior Jaipur', 'Tradition'] },
    { word: 'Guru Shishya Parampara', category: 'Music', hints: ['Teacher Student', 'Oral Tradition', 'Learning Lineage', 'Ancient Method', 'Discipleship'] },

    // Classical artists
    { word: 'Ravi Shankar', category: 'Music', hints: ['Sitar Maestro', 'Beatles Connect', 'Norah Jones Father', 'Woodstock', 'Bharat Ratna'] },
    { word: 'Zakir Hussain', category: 'Music', hints: ['Tabla Genius', 'Alla Rakha Son', 'Shakti Band', 'Grammy Winner', 'Cross Cultural'] },
    { word: 'Bismillah Khan', category: 'Music', hints: ['Shehnai Master', 'Bharat Ratna', 'Varanasi', 'Independence Day', 'Mangal Dhwani'] },
    { word: 'Amjad Ali Khan', category: 'Music', hints: ['Sarod Master', 'Gwalior Gharana', 'Amaan Ayaan', 'Padma Vibhushan', 'Six Generations'] },
    { word: 'Hariprasad Chaurasia', category: 'Music', hints: ['Flute Master', 'Bansuri', 'Silsila Music', 'Shiv Kumar Duo', 'Vrindavan'] },
    { word: 'Bhimsen Joshi', category: 'Music', hints: ['Khayal Singer', 'Bharat Ratna', 'Mile Sur Mera', 'Kirana Gharana', 'Abhang'] },
    { word: 'MS Subbulakshmi', category: 'Music', hints: ['Carnatic Queen', 'Bharat Ratna', 'Suprabhatam', 'UN Concert', 'Meera Bhajan'] },
    { word: 'Bade Ghulam Ali Khan', category: 'Music', hints: ['Patiala Gharana', 'Khayal Master', 'Thumri King', 'Mughal Voice', 'Padma Bhushan'] },
    { word: 'Kishori Amonkar', category: 'Music', hints: ['Jaipur Gharana', 'Mharo Pranam', 'Padma Vibhushan', 'Bhairavi Queen', 'Innovator'] },
    { word: 'Shivkumar Sharma', category: 'Music', hints: ['Santoor Pioneer', 'Kashmir Strings', 'Hariprasad Duo', 'Silsila', 'Padma Vibhushan'] },

    // Instruments
    { word: 'Sitar', category: 'Music', hints: ['Strings', 'Ravi Shankar', 'Gourd Body', 'Plucked', 'Meend Technique'] },
    { word: 'Tabla', category: 'Music', hints: ['Pair Drums', 'Zakir Hussain', 'Bayan Dayan', 'Bol Patterns', 'Percussion'] },
    { word: 'Harmonium', category: 'Music', hints: ['Bellows', 'Keys Reeds', 'Pump Organ', 'Bhajan Singer', 'Portable'] },
    { word: 'Tanpura', category: 'Music', hints: ['Drone', 'Four Strings', 'Background Hum', 'No Melody', 'Sa Pa'] },
    { word: 'Sarangi', category: 'Music', hints: ['Bowed Strings', 'Crying Voice', 'Gut Strings', 'North Indian', 'Accompaniment'] },
    { word: 'Shehnai', category: 'Music', hints: ['Wedding Sound', 'Bismillah Khan', 'Reed Pipe', 'Auspicious', 'Nadaswaram Cousin'] },
    { word: 'Santoor', category: 'Music', hints: ['Struck Strings', 'Kashmir', 'Shivkumar Sharma', 'Trapezoid', 'Hammered'] },
    { word: 'Bansuri', category: 'Music', hints: ['Bamboo Flute', 'Krishna', 'Side Blown', 'Hariprasad', 'Six Holes'] },
    { word: 'Veena', category: 'Music', hints: ['Saraswati', 'South Indian', 'Fretted', 'Ancient Strings', 'Carnatic'] },
    { word: 'Mridangam', category: 'Music', hints: ['South Drum', 'Carnatic', 'Two Headed', 'Jackfruit Wood', 'Percussion'] },
    { word: 'Dholak', category: 'Music', hints: ['Two Sided Drum', 'Folk Music', 'Hand Played', 'Wedding', 'Bollywood'] },
    { word: 'Dhol', category: 'Music', hints: ['Bhangra Beat', 'Punjab', 'Large Drum', 'Stick Played', 'Wedding Dance'] },
    { word: 'Pakhawaj', category: 'Music', hints: ['Barrel Drum', 'Dhrupad', 'Ancient', 'Two Heads', 'Deep Sound'] },
    { word: 'Sarod', category: 'Music', hints: ['Fretless Strings', 'Amjad Ali Khan', 'Metal Fingerboard', 'Deep Tone', 'Plucked'] },
    { word: 'Jal Tarang', category: 'Music', hints: ['Water Bowls', 'Ceramic Cups', 'Struck Rims', 'Tuned Water', 'Unusual'] },
    { word: 'Nadaswaram', category: 'Music', hints: ['South Indian Pipe', 'Temple Music', 'Loud Reed', 'Wedding', 'Tamil Nadu'] },
    { word: 'Ghatam', category: 'Music', hints: ['Clay Pot', 'Carnatic Percussion', 'Belly Slap', 'South Indian', 'Mud Vessel'] },
    { word: 'Ektara', category: 'Music', hints: ['One String', 'Baul Singer', 'Gourd Body', 'Folk Bengal', 'Plucked'] },
    { word: 'Tumbi', category: 'Music', hints: ['Single String', 'Punjabi Folk', 'High Pitch', 'Bhangra', 'Daler Mehndi'] },
    { word: 'Manjira', category: 'Music', hints: ['Small Cymbals', 'Brass Pair', 'Bhajan', 'Clashing', 'Devotional'] },
    { word: 'Guitar', category: 'Music', hints: ['Six Strings', 'Acoustic Electric', 'Strumming', 'Frets', 'Western'] },
    { word: 'Piano', category: 'Music', hints: ['88 Keys', 'Black White', 'Grand Upright', 'Hammer Strings', 'Classical'] },
    { word: 'Drums', category: 'Music', hints: ['Kit Set', 'Sticks Beat', 'Snare Bass', 'Cymbals', 'Rhythm Section'] },
    { word: 'Violin', category: 'Music', hints: ['Bowed Four', 'Carnatic Western', 'Chinrest', 'Orchestra', 'Fiddle'] },
    { word: 'Saxophone', category: 'Music', hints: ['Brass Reed', 'Jazz Icon', 'Alto Tenor', 'Kadri Gopalnath', 'Smooth Sound'] },
    { word: 'Trumpet', category: 'Music', hints: ['Brass Horn', 'Three Valves', 'Loud Clear', 'Jazz Band', 'Fanfare'] },
    { word: 'Ukulele', category: 'Music', hints: ['Four Strings', 'Small Guitar', 'Hawaii', 'Cheerful Sound', 'Travel Size'] },
    { word: 'Bass Guitar', category: 'Music', hints: ['Low Register', 'Four Thick', 'Rhythm Groove', 'Fender', 'Band Foundation'] },
    { word: 'Keyboard', category: 'Music', hints: ['Electronic Keys', 'Synthesizer', 'Portable Piano', 'MIDI', 'Multi Sound'] },
    { word: 'Flute', category: 'Music', hints: ['Wind Blown', 'Metal Tube', 'Classical Western', 'Side Blow', 'Airy Sound'] },

    // Genres
    { word: 'Ghazal', category: 'Music', hints: ['Urdu Poetry', 'Jagjit Singh', 'Couplets', 'Mehfil', 'Romantic Sad'] },
    { word: 'Qawwali', category: 'Music', hints: ['Sufi Devotion', 'Nusrat', 'Group Clapping', 'Dargah', 'Ecstatic'] },
    { word: 'Bhajan', category: 'Music', hints: ['Devotional Song', 'Temple', 'Anup Jalota', 'Hindu Prayer', 'Meera'] },
    { word: 'Kirtan', category: 'Music', hints: ['Call Response', 'Sikh Gurdwara', 'Devotional Chant', 'ISKCON', 'Group Singing'] },
    { word: 'Sufi Music', category: 'Music', hints: ['Mystical Islam', 'Whirling', 'Divine Love', 'Bulleh Shah', 'Trance'] },
    { word: 'Folk Music', category: 'Music', hints: ['Rural Roots', 'Regional', 'Oral Tradition', 'Village Songs', 'Harvest'] },
    { word: 'Lavani', category: 'Music', hints: ['Maharashtra', 'Dance Form', 'Dholki Beat', 'Powerful Women', 'Marathi'] },
    { word: 'Bhangra', category: 'Music', hints: ['Punjab Dance', 'Dhol Beat', 'Harvest Celebration', 'Baisakhi', 'Energetic'] },
    { word: 'Garba Music', category: 'Music', hints: ['Gujarat', 'Navratri', 'Circle Dance', 'Dandiya Raas', 'Aarti'] },
    { word: 'Filmi Music', category: 'Music', hints: ['Bollywood Soundtrack', 'Playback Singer', 'Hindi Cinema', 'Item Song', 'Mainstream'] },
    { word: 'Indie Pop', category: 'Music', hints: ['Independent', 'Prateek Kuhad', 'Alternative', 'Non Film', 'YouTube'] },
    { word: 'Desi Hip Hop', category: 'Music', hints: ['Indian Rap', 'Divine Naezy', 'Gully Boy', 'Street Culture', 'Bars'] },
    { word: 'EDM', category: 'Music', hints: ['Electronic Dance', 'Drop Beat', 'DJ Set', 'Sunburn', 'Bass Heavy'] },
    { word: 'Trap Music', category: 'Music', hints: ['808 Bass', 'Hi Hats', 'Rap Subgenre', 'Atlanta Origin', 'Dark Beat'] },
    { word: 'Lo-Fi', category: 'Music', hints: ['Study Music', 'Chill Beats', 'Relaxing', 'Anime Girl', 'Low Fidelity'] },
    { word: 'Jazz', category: 'Music', hints: ['Improvisation', 'Swing', 'Blues Root', 'Saxophone', 'New Orleans'] },
    { word: 'Rock', category: 'Music', hints: ['Electric Guitar', 'Band', 'Distortion', 'Concert Arena', 'Rebellion'] },
    { word: 'Classical Fusion', category: 'Music', hints: ['East Meets West', 'Shakti Band', 'Sitar Guitar', 'Crossover', 'Experiment'] },
    { word: 'Devotional Music', category: 'Music', hints: ['Prayer Songs', 'Aarti', 'Spiritual', 'Temple Morning', 'God Worship'] },
    { word: 'Baul Music', category: 'Music', hints: ['Bengal Mystic', 'Wandering Singer', 'Ektara', 'Folk Spiritual', 'Lalon Fakir'] },
    { word: 'Rabindra Sangeet', category: 'Music', hints: ['Tagore Songs', 'Bengali', 'Nobel Laureate', 'Shantiniketan', 'Jana Gana Mana'] },
    { word: 'Reggaeton', category: 'Music', hints: ['Latin Beat', 'Despacito', 'Puerto Rico', 'Dembow Rhythm', 'Bad Bunny'] },
    { word: 'K-Pop', category: 'Music', hints: ['Korean Pop', 'BTS', 'BLACKPINK', 'Choreography', 'Fan Army'] },
    { word: 'Pop', category: 'Music', hints: ['Popular Music', 'Chart Topper', 'Catchy Hook', 'Mainstream', 'Radio Friendly'] },
    { word: 'R&B', category: 'Music', hints: ['Rhythm Blues', 'Soulful Vocals', 'Smooth Groove', 'The Weeknd', 'SZA'] },
    { word: 'Hip Hop', category: 'Music', hints: ['Rap Culture', 'MC DJ', 'Breakdance', 'Eminem Drake', 'Bars Flow'] },
    { word: 'Punk Rock', category: 'Music', hints: ['Rebellion', 'Fast Loud', 'Mohawk', 'DIY Ethos', 'Three Chords'] },
    { word: 'Metal', category: 'Music', hints: ['Heavy Riffs', 'Headbanging', 'Distortion', 'Black Sabbath', 'Loud'] },
    { word: 'Techno', category: 'Music', hints: ['Electronic Beat', 'Detroit Origin', 'Club Music', 'Repetitive', 'Synthesizer'] },
    { word: 'Country Music', category: 'Music', hints: ['Nashville', 'Twang Guitar', 'Cowboy', 'Storytelling', 'Banjo'] },

    // International artists Indians know
    { word: 'Taylor Swift', category: 'Music', hints: ['Eras Tour', 'Swifties', 'Country to Pop', 'Love Story', 'Shake It Off'] },
    { word: 'Ed Sheeran', category: 'Music', hints: ['Shape Of You', 'Ginger', 'Loop Pedal', 'Mumbai Concert', 'British'] },
    { word: 'BTS', category: 'Music', hints: ['Korean Seven', 'ARMY Fans', 'Dynamite Hit', 'Bangtan', 'K-Pop Kings'] },
    { word: 'Eminem', category: 'Music', hints: ['Slim Shady', 'Rap God', 'Eight Mile', 'Detroit', 'Lose Yourself'] },
    { word: 'Drake', category: 'Music', hints: ['Toronto', 'OVO Sound', 'Hotline Bling', 'Degrassi Actor', 'God Plan'] },
    { word: 'The Weeknd', category: 'Music', hints: ['Blinding Lights', 'Abel', 'Starboy', 'Ethiopian Origin', 'After Hours'] },
    { word: 'Rihanna', category: 'Music', hints: ['Umbrella', 'Fenty Brand', 'Barbados', 'Diamonds', 'Work'] },
    { word: 'Beyonce', category: 'Music', hints: ['Queen Bey', 'Destiny Child', 'Lemonade', 'Single Ladies', 'Halo'] },
    { word: 'Justin Bieber', category: 'Music', hints: ['Baby Song', 'Canadian', 'Purpose Tour', 'Hailey Baldwin', 'YouTube Discovery'] },
    { word: 'Coldplay', category: 'Music', hints: ['Yellow', 'Chris Martin', 'Ahmedabad Concert', 'Fix You', 'British Band'] },
    { word: 'Imagine Dragons', category: 'Music', hints: ['Believer', 'Radioactive', 'Thunder', 'Las Vegas', 'Dan Reynolds'] },
    { word: 'Billie Eilish', category: 'Music', hints: ['Bad Guy', 'Whisper Singing', 'Green Hair', 'Teen Debut', 'FINNEAS'] },
    { word: 'Dua Lipa', category: 'Music', hints: ['Levitating', 'British Albanian', 'New Rules', 'Disco Pop', 'Dont Start'] },
    { word: 'Lady Gaga', category: 'Music', hints: ['Poker Face', 'Meat Dress', 'Born This Way', 'Monster Fans', 'A Star Born'] },
    { word: 'Adele', category: 'Music', hints: ['Rolling Deep', 'British Soul', 'Hello Song', 'Powerful Voice', 'Someone Like You'] },
    { word: 'Bruno Mars', category: 'Music', hints: ['Uptown Funk', 'Grenade', 'Hawaii Born', 'Silk Sonic', 'Just The Way'] },
    { word: 'Michael Jackson', category: 'Music', hints: ['King of Pop', 'Moonwalk', 'Thriller Album', 'Glove', 'Billie Jean'] },
    { word: 'Shakira', category: 'Music', hints: ['Hips Dont Lie', 'Waka Waka', 'Colombian', 'Belly Dancing', 'World Cup'] },
    { word: 'Post Malone', category: 'Music', hints: ['Face Tattoos', 'Rockstar Song', 'Sunflower', 'Beer Pong', 'Circles'] },
    { word: 'Travis Scott', category: 'Music', hints: ['Astroworld', 'Sicko Mode', 'Cactus Jack', 'Houston Rapper', 'Fortnite'] },
    { word: 'Selena Gomez', category: 'Music', hints: ['Disney Star', 'Lose You Love', 'Rare Album', 'Wizards Show', 'Cooking Show'] },
    { word: 'Ariana Grande', category: 'Music', hints: ['High Notes', 'Ponytail', 'Thank U Next', 'Positions', 'Nickelodeon'] },
    { word: 'Kendrick Lamar', category: 'Music', hints: ['HUMBLE', 'Pulitzer Prize', 'Compton', 'DAMN Album', 'Conscious Rap'] },
    { word: 'Linkin Park', category: 'Music', hints: ['In The End', 'Numb', 'Chester Voice', 'Nu Metal', 'Hybrid Theory'] },
    { word: 'Queen', category: 'Music', hints: ['Bohemian Rhapsody', 'Freddie Mercury', 'We Will Rock', 'British Band', 'We Are Champions'] },
    { word: 'The Beatles', category: 'Music', hints: ['Fab Four', 'Liverpool', 'Let It Be', 'Rishikesh Visit', 'Yesterday'] },
    { word: 'Pink Floyd', category: 'Music', hints: ['Dark Side Moon', 'The Wall', 'Psychedelic', 'Comfortably Numb', 'British'] },
    { word: 'Led Zeppelin', category: 'Music', hints: ['Stairway Heaven', 'Hard Rock', 'Plant Page', 'Kashmir Song', 'British'] },
    { word: 'Nirvana', category: 'Music', hints: ['Smells Teen Spirit', 'Grunge', 'Kurt Cobain', 'Seattle', 'Nevermind'] },
    { word: 'Bob Marley', category: 'Music', hints: ['Reggae King', 'Jamaica', 'One Love', 'Dreadlocks', 'Buffalo Soldier'] },
    { word: 'BLACKPINK', category: 'Music', hints: ['K-Pop Girls', 'Blinks', 'DDU-DU', 'Jisoo Lisa', 'YG Label'] },
    { word: 'Doja Cat', category: 'Music', hints: ['Say So', 'Kiss Me More', 'Cat Persona', 'Rapper Singer', 'Viral TikTok'] },
    { word: 'Bad Bunny', category: 'Music', hints: ['Puerto Rico', 'Reggaeton King', 'Spotify Most', 'Wrestler', 'Latin Trap'] },
    { word: 'SZA', category: 'Music', hints: ['Kill Bill', 'SOS Album', 'TDE Label', 'New Jersey', 'Alt R&B'] },
    { word: 'Olivia Rodrigo', category: 'Music', hints: ['Drivers License', 'SOUR Album', 'Disney Star', 'Good 4 U', 'Teen Pop'] },

    // Music culture
    { word: 'Antakshari', category: 'Music', hints: ['Song Game', 'Last Letter', 'Bus Trip', 'Bollywood Songs', 'Desi Party'] },
    { word: 'Karaoke Night', category: 'Music', hints: ['Sing Along', 'Lyrics Screen', 'Microphone', 'Bar Pub', 'Off Key'] },
    { word: 'Sangeet Ceremony', category: 'Music', hints: ['Wedding Pre', 'Family Dance', 'Choreography', 'Mehndi Night', 'Bollywood Songs'] },
    { word: 'Mehfil', category: 'Music', hints: ['Gathering', 'Ghazal Evening', 'Urdu Culture', 'Seated Audience', 'Intimate'] },
    { word: 'Jugni', category: 'Music', hints: ['Punjabi Folk', 'Spirit Fire', 'Sufi', 'Wandering Soul', 'Nooran Sisters'] },
    { word: 'Bollywood Medley', category: 'Music', hints: ['Song Mix', 'Multiple Hits', 'Wedding DJ', 'Nonstop', 'Dance Floor'] },
    { word: 'Remix', category: 'Music', hints: ['New Version', 'DJ Mix', 'Bass Boosted', 'Tanishk', 'Old Song New'] },
    { word: 'Mashup', category: 'Music', hints: ['Two Songs One', 'Blend Mix', 'YouTube Trend', 'Singing Duo', 'Creative'] },
    { word: 'Unplugged', category: 'Music', hints: ['Acoustic Version', 'No Electric', 'Raw Sound', 'Stripped Down', 'Intimate'] },
    { word: 'MTV Unplugged', category: 'Music', hints: ['TV Show', 'Acoustic Sessions', 'Live Studio', 'Famous Artists', 'Stripped'] },
    { word: 'Coke Studio', category: 'Music', hints: ['Pakistan India', 'Fusion Sessions', 'Live Recording', 'Pasoori', 'Collaboration'] },
    { word: 'Indian Idol', category: 'Music', hints: ['Singing Reality', 'Auditions', 'Sony TV', 'Judges Panel', 'Neha Judge'] },
    { word: 'Sa Re Ga Ma Pa', category: 'Music', hints: ['Singing Contest', 'Zee TV', 'Oldest Show', 'Sargam Notes', 'Discovery'] },
    { word: 'T-Series', category: 'Music', hints: ['YouTube King', 'Gulshan Kumar', 'Music Label', 'Most Subscribers', 'Bollywood'] },
    { word: 'Music Video', category: 'Music', hints: ['Visual Song', 'YouTube', 'Director Shot', 'Storyline', 'Views Count'] },
    { word: 'Album Launch', category: 'Music', hints: ['Release Event', 'New Songs', 'Press Meet', 'Promotional', 'First Listen'] },
    { word: 'Concert', category: 'Music', hints: ['Live Show', 'Stadium', 'Tickets', 'Crowd Singing', 'Stage Lights'] },
    { word: 'Live Performance', category: 'Music', hints: ['Stage Show', 'Real Time', 'Audience', 'No Playback', 'Energy'] },
    { word: 'DJ Night', category: 'Music', hints: ['Club Event', 'Turntable', 'Dance Floor', 'Mixing Songs', 'Late Night'] },
    { word: 'Music Festival', category: 'Music', hints: ['Multi Stage', 'Outdoor Event', 'Camping', 'Weekend', 'Multiple Artists'] },
    { word: 'Sunburn Festival', category: 'Music', hints: ['Goa EDM', 'India Biggest', 'Electronic Dance', 'December', 'Beach Party'] },
    { word: 'NH7 Weekender', category: 'Music', hints: ['Indie Festival', 'Pune Meghalaya', 'Multi Genre', 'OML Presents', 'Happiest'] },
    { word: 'Spotify', category: 'Music', hints: ['Green App', 'Streaming', 'Wrapped Annual', 'Swedish', 'Playlists'] },
    { word: 'JioSaavn', category: 'Music', hints: ['Indian App', 'Reliance', 'Desi Streaming', 'Bollywood Focus', 'Was Saavn'] },
    { word: 'Gaana', category: 'Music', hints: ['Times Group', 'Indian Streaming', 'Hindi Songs', 'Hot Shot', 'Music App'] },
    { word: 'YouTube Music', category: 'Music', hints: ['Google App', 'Video Songs', 'Red Logo', 'Free Tier', 'Streaming'] },
    { word: 'Apple Music', category: 'Music', hints: ['iPhone Default', 'Cupertino', 'Spatial Audio', 'Lossless', 'Premium'] },
    { word: 'Vinyl Record', category: 'Music', hints: ['Turntable', 'Grooves', 'Retro', 'LP Album', 'Needle'] },
    { word: 'Cassette Tape', category: 'Music', hints: ['Rewind Pencil', 'Walkman', 'Eighties', 'Magnetic', 'T-Series Era'] },
    { word: 'Walkman', category: 'Music', hints: ['Sony Portable', 'Cassette Player', 'Headphone Jack', 'Eighties Icon', 'Personal Stereo'] },
    { word: 'Radio Mirchi', category: 'Music', hints: ['FM Station', '98.3 Frequency', 'Mirchi Sunne', 'RJ Host', 'Hot'] },
    { word: 'All India Radio', category: 'Music', hints: ['Government Station', 'AIR', 'Akashvani', 'National Broadcast', 'News Bulletin'] },
    { word: 'Vividh Bharati', category: 'Music', hints: ['AIR Station', 'Film Songs', 'Fauji Bhaiyon', 'Hindi Service', 'Commercial'] },
    { word: 'Headphones', category: 'Music', hints: ['Over Ear', 'Noise Cancel', 'Personal Audio', 'Wired Wireless', 'Padding'] },
    { word: 'Earbuds', category: 'Music', hints: ['In Ear', 'Wireless Small', 'AirPods', 'Portable', 'Bluetooth'] },
    { word: 'Playlist', category: 'Music', hints: ['Song Queue', 'Curated', 'Spotify Feature', 'Road Trip', 'Mood Based'] },
    { word: 'Encore', category: 'Music', hints: ['One More', 'Concert End', 'Audience Demand', 'Final Song', 'Comeback Stage'] },
    { word: 'Backstage Pass', category: 'Music', hints: ['VIP Access', 'Meet Artist', 'Behind Curtain', 'Exclusive', 'Lanyard'] },
    { word: 'Sound Check', category: 'Music', hints: ['Pre Show', 'Testing Levels', 'Mic One Two', 'Engineers', 'Volume Balance'] },
    { word: 'Autotune', category: 'Music', hints: ['Pitch Correction', 'T-Pain Effect', 'Robot Voice', 'Cher Believe', 'Studio Tool'] },
    { word: 'Beatboxing', category: 'Music', hints: ['Mouth Drums', 'Vocal Percussion', 'No Instrument', 'Human Jukebox', 'Hip Hop'] },
    { word: 'Freestyle Rap', category: 'Music', hints: ['Improvised Bars', 'Off Top Head', 'Cypher', 'Battle', 'No Written'] },
    { word: 'Acoustic Set', category: 'Music', hints: ['Unplugged', 'No Amplifier', 'Raw Sound', 'Intimate Stage', 'Wood Guitar'] },
    { word: 'Duet', category: 'Music', hints: ['Two Singers', 'Male Female', 'Love Song', 'Together', 'Harmony'] },
    { word: 'Chorus', category: 'Music', hints: ['Repeat Section', 'Catchy Part', 'Sing Along', 'Hook', 'Main Melody'] },
    { word: 'Hook Line', category: 'Music', hints: ['Catchy Phrase', 'Earworm', 'Memorable Bit', 'Stuck In Head', 'Song Identity'] },
    { word: 'Drop Beat', category: 'Music', hints: ['Bass Hits', 'EDM Climax', 'Buildup Release', 'Dance Floor', 'Hands Up'] },

    // Indian bands
    { word: 'Indian Ocean', category: 'Music', hints: ['Rock Band', 'Bandeh', 'Delhi', 'Fusion', 'Tandanu'] },
    { word: 'Euphoria Band', category: 'Music', hints: ['Palash Sen', 'Dhoom Pichak', 'Hindi Rock', 'Maeri', 'Delhi Band'] },
    { word: 'Parikrama', category: 'Music', hints: ['Delhi Rock', 'But It Rained', 'College Fests', 'Hindi English', 'Subir Malik'] },
    { word: 'Agnee', category: 'Music', hints: ['Sadho Re', 'Mohan Kannan', 'Aahatein', 'Rock Sufi', 'Hindi Band'] },
    { word: 'The Local Train', category: 'Music', hints: ['Indie Hindi', 'Aalas Ka Pedh', 'Chandigarh', 'Choo Lo', 'Youth Anthem'] },
    { word: 'When Chai Met Toast', category: 'Music', hints: ['Kerala Band', 'Happy Music', 'Indie Folk', 'Khoj', 'Feel Good'] },
    { word: 'Thaikkudam Bridge', category: 'Music', hints: ['Kerala Rock', 'Navarasam', 'Malayalam', 'Fish Rock', 'Govind Menon'] },
    { word: 'Raghu Dixit Project', category: 'Music', hints: ['Karnataka', 'Kannada Folk', 'Jag Changa', 'Colorful', 'Hey Bhagwan'] },
    { word: 'Pentagram', category: 'Music', hints: ['Mumbai Metal', 'Vishal Dadlani', 'Oldest Indian', 'Voice Inside', 'Rock'] },
    { word: 'Bloodywood', category: 'Music', hints: ['Folk Metal', 'Ari Ari', 'YouTube Viral', 'Indian Fusion', 'Heavy'] },

    // Iconic international songs Indians know
    { word: 'Shape of You', category: 'Music', hints: ['Ed Sheeran', 'Body Magnet', 'Billion Views', 'Marimba Beat', 'Club Love'] },
    { word: 'Despacito', category: 'Music', hints: ['Luis Fonsi', 'Latin Mega', 'Puerto Rico', 'Bieber Remix', 'Record Views'] },
    { word: 'Bohemian Rhapsody', category: 'Music', hints: ['Queen Epic', 'Mama Mia', 'Six Minutes', 'Opera Section', 'Freddie'] },
    { word: 'Stairway to Heaven', category: 'Music', hints: ['Led Zeppelin', 'Guitar Solo', 'Eight Minutes', 'Rock Classic', 'Jimmy Page'] },
    { word: 'Hotel California', category: 'Music', hints: ['Eagles', 'Check Out Never', 'Guitar Outro', 'Desert Highway', 'Classic Rock'] },
    { word: 'Thriller', category: 'Music', hints: ['Michael Jackson', 'Zombie Dance', 'Best Album', 'Halloween', 'Music Video'] },
    { word: 'Blinding Lights', category: 'Music', hints: ['Weeknd', 'Synth Pop', 'Neon City', 'Retro Beat', 'TikTok Viral'] },
    { word: 'Dynamite', category: 'Music', hints: ['BTS', 'English Single', 'Disco Pop', 'Billboard One', 'Korean Band'] },
    { word: 'Senorita', category: 'Music', hints: ['Shawn Camila', 'Latin Pop', 'Couple Song', 'Miami', 'Summer Hit'] },
    { word: 'Havana', category: 'Music', hints: ['Camila Cabello', 'Cuban City', 'Half My Heart', 'Latin Beat', 'Young Thug'] },
    { word: 'Uptown Funk', category: 'Music', hints: ['Bruno Mars', 'Mark Ronson', 'Dont Believe Me', 'Retro Funk', 'Hot Damn'] },
    { word: 'Waka Waka', category: 'Music', hints: ['Shakira', 'World Cup', 'Africa', 'This Time', 'Football Anthem'] },
    { word: 'Gangnam Style', category: 'Music', hints: ['PSY', 'Horse Dance', 'Korean Viral', 'First Billion', 'Oppa'] },
    { word: 'Baby Shark', category: 'Music', hints: ['Kids Song', 'Doo Doo', 'Pinkfong', 'Most Viewed Ever', 'Toddler Anthem'] },
    { word: 'Believer', category: 'Music', hints: ['Imagine Dragons', 'Pain', 'Thunder Band', 'Powerful Beat', 'Anthem'] },
    { word: 'Faded', category: 'Music', hints: ['Alan Walker', 'Mask DJ', 'Norwegian', 'Electronic', 'Where Are You'] },
    { word: 'Closer', category: 'Music', hints: ['Chainsmokers', 'Halsey', 'Mattress', 'EDM Pop', 'Rover Range'] },
    { word: 'Let Her Go', category: 'Music', hints: ['Passenger', 'Acoustic', 'Only Miss Sun', 'Gone', 'Folk Pop'] },
    { word: 'Perfect', category: 'Music', hints: ['Ed Sheeran', 'Wedding Song', 'Barefoot Grass', 'Ballad', 'Beyonce Duet'] },
    { word: 'Photograph', category: 'Music', hints: ['Ed Sheeran', 'Loving Can Hurt', 'Memories', 'Acoustic Pop', 'Sentimental'] },
  ],
};
