import type { WordPack } from '../game/types';

export const mythologyPack: WordPack = {
  id: 'mythology',
  name: 'Mythology',
  entries: [
    { word: 'Brahma', category: 'Mythology', hints: ['Creator', 'Four Heads', 'Vedas', 'Lotus', 'Saraswati Consort'] },
    { word: 'Vishnu', category: 'Mythology', hints: ['Preserver', 'Dashavatar', 'Shankh', 'Garuda Mount', 'Neela Varna'] },
    { word: 'Shiva', category: 'Mythology', hints: ['Destroyer', 'Kailash', 'Trishul', 'Third Eye', 'Nandi'] },
    { word: 'Lakshmi', category: 'Mythology', hints: ['Wealth', 'Diwali', 'Lotus', 'Vishnu Consort', 'Gold Coins'] },
    { word: 'Saraswati', category: 'Mythology', hints: ['Knowledge', 'Veena', 'White Swan', 'Basant Panchami', 'Learning'] },
    { word: 'Parvati', category: 'Mythology', hints: ['Mountain Daughter', 'Shiva Consort', 'Gauri', 'Himavan', 'Mother Goddess'] },
    { word: 'Ganesha', category: 'Mythology', hints: ['Elephant Head', 'Modak', 'Mushak', 'Obstacle Remover', 'Chaturthi'] },
    { word: 'Kartikeya', category: 'Mythology', hints: ['War God', 'Peacock Mount', 'Six Faces', 'Murugan', 'Skanda'] },
    { word: 'Hanuman', category: 'Mythology', hints: ['Monkey God', 'Ram Bhakt', 'Sanjeevani', 'Bajrangbali', 'Lanka Flight'] },
    { word: 'Krishna', category: 'Mythology', hints: ['Flute', 'Gopi', 'Makhan', 'Dwarka King', 'Gita Teacher'] },
    { word: 'Rama', category: 'Mythology', hints: ['Ayodhya Prince', 'Maryada Purushottam', 'Bow Breaker', 'Vanvas', 'Sita Husband'] },
    { word: 'Indra', category: 'Mythology', hints: ['Thunder King', 'Amravati', 'Airavata', 'Rain God', 'Vajra Weapon'] },
    { word: 'Agni', category: 'Mythology', hints: ['Fire God', 'Havan', 'Yajna', 'Seven Flames', 'Sacred Flames'] },
    { word: 'Vayu', category: 'Mythology', hints: ['Wind God', 'Bhima Father', 'Hanuman Father', 'Breath', 'Prana'] },
    { word: 'Varuna', category: 'Mythology', hints: ['Water God', 'Ocean Lord', 'Pasha Weapon', 'Seas', 'West Guardian'] },
    { word: 'Surya', category: 'Mythology', hints: ['Sun God', 'Chariot', 'Karna Father', 'Seven Horses', 'Chhath Puja'] },
    { word: 'Chandra', category: 'Mythology', hints: ['Moon God', 'Karva Chauth', 'Sixteen Phases', 'Soma', 'Night Light'] },
    { word: 'Yama', category: 'Mythology', hints: ['Death God', 'Buffalo Mount', 'Dharma Raja', 'South Direction', 'Nachiketa'] },
    { word: 'Kubera', category: 'Mythology', hints: ['Wealth God', 'Alakapuri', 'North Guardian', 'Pushpak Owner', 'Treasure Keeper'] },
    { word: 'Kamadeva', category: 'Mythology', hints: ['Love God', 'Sugarcane Bow', 'Flower Arrows', 'Rati Husband', 'Burned by Shiva'] },
    { word: 'Durga', category: 'Mythology', hints: ['Lion Mount', 'Navratri', 'Mahishasur Slayer', 'Ten Arms', 'Shakti'] },
    { word: 'Kali', category: 'Mythology', hints: ['Dark Goddess', 'Tongue Out', 'Skull Garland', 'Time Destroyer', 'Fierce Form'] },
    { word: 'Radha', category: 'Mythology', hints: ['Krishna Beloved', 'Barsana', 'Gopi', 'Holi', 'Divine Love'] },
    { word: 'Sita', category: 'Mythology', hints: ['Earth Daughter', 'Rama Wife', 'Janakpuri', 'Agni Pariksha', 'Ashok Vatika'] },
    { word: 'Draupadi', category: 'Mythology', hints: ['Five Husbands', 'Fire Born', 'Cheerharan', 'Panchali', 'Drupada Daughter'] },
    { word: 'Narada', category: 'Mythology', hints: ['Celestial Sage', 'Narayan Narayan', 'Veena Player', 'Gossip Rishi', 'Three Worlds Traveler'] },
    { word: 'Brihaspati', category: 'Mythology', hints: ['Guru of Gods', 'Jupiter Planet', 'Thursday', 'Deva Teacher', 'Wisdom'] },
    { word: 'Shukracharya', category: 'Mythology', hints: ['Asura Guru', 'Venus Planet', 'Friday', 'Mritsanjeevani', 'One Eyed'] },
    { word: 'Chitragupta', category: 'Mythology', hints: ['Record Keeper', 'Yama Assistant', 'Karma Ledger', 'Kayastha', 'Life Account'] },
    { word: 'Yamuna', category: 'Mythology', hints: ['Sacred River', 'Krishna', 'Mathura', 'Surya Daughter', 'Dark Waters'] },
    { word: 'Ganga', category: 'Mythology', hints: ['Holy River', 'Shiva Locks', 'Bhagirath', 'Haridwar', 'Moksha Waters'] },
    { word: 'Annapurna', category: 'Mythology', hints: ['Food Goddess', 'Kashi', 'Rice Bowl', 'Parvati Form', 'Nourishment'] },
    { word: 'Shakti', category: 'Mythology', hints: ['Divine Energy', 'Female Power', 'Devi', 'Peethas', 'Cosmic Force'] },
    { word: 'Aditi', category: 'Mythology', hints: ['Mother of Gods', 'Devamata', 'Infinite', 'Sky Goddess', 'Twelve Sons'] },
    { word: 'Savitri', category: 'Mythology', hints: ['Satyavan Wife', 'Defeated Yama', 'Devotion', 'Vat Savitri Vrat', 'Faithful Wife'] },
    { word: 'Matsya Avatar', category: 'Mythology', hints: ['Fish Form', 'Great Flood', 'Manu Saved', 'First Avatar', 'Vedas Rescue'] },
    { word: 'Kurma Avatar', category: 'Mythology', hints: ['Tortoise Form', 'Ocean Churning', 'Mount Mandara', 'Second Avatar', 'Shell Back'] },
    { word: 'Varaha Avatar', category: 'Mythology', hints: ['Boar Form', 'Earth Rescue', 'Hiranyaksha', 'Third Avatar', 'Tusks'] },
    { word: 'Narasimha', category: 'Mythology', hints: ['Half Lion', 'Pillar Burst', 'Prahlad Protector', 'Hiranyakashipu Slayer', 'Twilight Kill'] },
    { word: 'Vamana', category: 'Mythology', hints: ['Dwarf Form', 'Three Steps', 'Bali Raja', 'Fifth Avatar', 'Trivikrama'] },
    { word: 'Parashurama', category: 'Mythology', hints: ['Axe Warrior', 'Brahmin Kshatriya', 'Chiranjeevi', 'Renuka Son', 'Sixth Avatar'] },
    { word: 'Kalki Avatar', category: 'Mythology', hints: ['Future Avatar', 'White Horse', 'End Times', 'Tenth Avatar', 'Kali Yuga End'] },
    { word: 'Buddha Avatar', category: 'Mythology', hints: ['Enlightened One', 'Ninth Avatar', 'Bodh Gaya', 'Non Violence', 'Meditation'] },
    { word: 'Balarama', category: 'Mythology', hints: ['Plough Weapon', 'Krishna Brother', 'Revati Husband', 'Shesha Avatar', 'Strength'] },
    { word: 'Mohini', category: 'Mythology', hints: ['Enchantress', 'Vishnu Female Form', 'Amrit Distribution', 'Bhasmasura', 'Beauty'] },
    { word: 'Dasharatha', category: 'Mythology', hints: ['Ayodhya King', 'Rama Father', 'Three Wives', 'Putrakameshti', 'Chariot Fighter'] },
    { word: 'Kaushalya', category: 'Mythology', hints: ['Rama Mother', 'First Queen', 'Ayodhya', 'Dasharatha Wife', 'Kosala Princess'] },
    { word: 'Kaikeyi', category: 'Mythology', hints: ['Two Boons', 'Bharata Mother', 'Manthara Counsel', 'Vanvas Cause', 'Dasharatha Wife'] },
    { word: 'Sumitra', category: 'Mythology', hints: ['Twin Sons', 'Lakshmana Mother', 'Third Queen', 'Shatrughna Mother', 'Gentle Queen'] },
    { word: 'Lakshmana', category: 'Mythology', hints: ['Rama Brother', 'Loyal Shadow', 'Rekha Line', 'Meghnath Slayer', 'Shesha Avatar'] },
    { word: 'Bharata', category: 'Mythology', hints: ['Kaikeyi Son', 'Paduka Throne', 'Nandigram', 'Refused Kingship', 'Devoted Brother'] },
    { word: 'Shatrughna', category: 'Mythology', hints: ['Youngest Prince', 'Sumitra Son', 'Lavnasur Slayer', 'Mathura Conqueror', 'Twin Brother'] },
    { word: 'Ravana', category: 'Mythology', hints: ['Ten Heads', 'Lanka King', 'Sita Kidnapper', 'Veena Player', 'Shiva Devotee'] },
    { word: 'Vibhishana', category: 'Mythology', hints: ['Lanka Defector', 'Ravana Brother', 'Dharma Path', 'Ram Ally', 'New Lanka King'] },
    { word: 'Kumbhakarna', category: 'Mythology', hints: ['Giant Sleeper', 'Ravana Brother', 'Six Month Sleep', 'Huge Appetite', 'Warrior Giant'] },
    { word: 'Meghnad', category: 'Mythology', hints: ['Indrajit', 'Ravana Son', 'Lakshmana Battle', 'Brahmastra User', 'Lanka Prince'] },
    { word: 'Mandodari', category: 'Mythology', hints: ['Ravana Wife', 'Lanka Queen', 'Maya Daughter', 'Virtuous Woman', 'Panchakanya'] },
    { word: 'Surpanakha', category: 'Mythology', hints: ['Ravana Sister', 'Nose Cut', 'Panchavati', 'Lakshmana Rejected', 'Shape Shifter'] },
    { word: 'Maricha', category: 'Mythology', hints: ['Golden Deer', 'Ravana Uncle', 'Sita Lure', 'Shape Shifter', 'Tataka Son'] },
    { word: 'Jatayu', category: 'Mythology', hints: ['Brave Eagle', 'Sita Rescue Attempt', 'Ravana Fight', 'Old Vulture', 'Garuda Kin'] },
    { word: 'Sampati', category: 'Mythology', hints: ['Jatayu Brother', 'Lost Wings', 'Lanka Direction', 'Sun Too Close', 'Vulture King'] },
    { word: 'Sugriva', category: 'Mythology', hints: ['Monkey King', 'Ram Alliance', 'Vali Brother', 'Kishkindha', 'Vanara Army'] },
    { word: 'Vali', category: 'Mythology', hints: ['Mighty Monkey', 'Sugriva Brother', 'Boon of Half Strength', 'Ram Arrow', 'Kishkindha King'] },
    { word: 'Angada', category: 'Mythology', hints: ['Vali Son', 'Lanka Messenger', 'Young Warrior', 'Vanara Prince', 'Foot Challenge'] },
    { word: 'Jambavan', category: 'Mythology', hints: ['Bear King', 'Hanuman Reminder', 'Ancient Warrior', 'Samudra Manthan Witness', 'Lanka War'] },
    { word: 'Shabari', category: 'Mythology', hints: ['Tasted Berries', 'Ram Devotee', 'Forest Wait', 'Tribal Woman', 'Bhil Woman'] },
    { word: 'Ahalya', category: 'Mythology', hints: ['Stone Curse', 'Gautama Wife', 'Ram Freed', 'Indra Trick', 'Panchakanya'] },
    { word: 'Tataka', category: 'Mythology', hints: ['Demoness', 'Ram First Kill', 'Forest Terror', 'Vishwamitra Mission', 'Maricha Mother'] },
    { word: 'Manthara', category: 'Mythology', hints: ['Hunchback Maid', 'Kaikeyi Counsel', 'Vanvas Plotter', 'Palace Servant', 'Evil Advisor'] },
    { word: 'Nala', category: 'Mythology', hints: ['Vanara Engineer', 'Bridge Builder', 'Ram Setu', 'Floating Stones', 'Monkey Architect'] },
    { word: 'Neela', category: 'Mythology', hints: ['Vanara Warrior', 'Bridge Helper', 'Lanka Battle', 'Agni Son', 'Monkey General'] },
    { word: 'Swayamvar', category: 'Mythology', hints: ['Bride Choice', 'Bow Contest', 'Marriage Ceremony', 'Princess Garland', 'Royal Wedding'] },
    { word: 'Lanka Dahan', category: 'Mythology', hints: ['Burning City', 'Tail Fire', 'Hanuman Feat', 'Golden City Flames', 'Monkey Revenge'] },
    { word: 'Setu Bandhan', category: 'Mythology', hints: ['Bridge Building', 'Ocean Crossing', 'Floating Stones', 'Vanara Army', 'Ram Setu'] },
    { word: 'Agni Pariksha', category: 'Mythology', hints: ['Fire Test', 'Sita Purity', 'Trial by Fire', 'Lanka Return', 'Controversial Event'] },
    { word: 'Vanvas', category: 'Mythology', hints: ['Forest Exile', 'Fourteen Years', 'Kaikeyi Boon', 'Panchavati', 'Chitrakoot'] },
    { word: 'Ashok Vatika', category: 'Mythology', hints: ['Garden Prison', 'Sita Captivity', 'Lanka Garden', 'Hanuman Visit', 'Ashoka Trees'] },
    { word: 'Panchavati', category: 'Mythology', hints: ['Forest Home', 'Five Banyan Trees', 'Godavari Bank', 'Surpanakha Encounter', 'Exile Spot'] },
    { word: 'Ram Setu', category: 'Mythology', hints: ['Stone Bridge', 'Lanka Crossing', 'Nala Built', 'Floating Rocks', 'Adam Bridge'] },
    { word: 'Pushpak Viman', category: 'Mythology', hints: ['Flying Chariot', 'First Aircraft', 'Kubera Stolen', 'Ravana Vehicle', 'Ayodhya Return'] },
    { word: 'Dandakaranya', category: 'Mythology', hints: ['Dense Forest', 'Exile Region', 'Demon Territory', 'Central India', 'Sage Hermitages'] },
    { word: 'Kishkindha', category: 'Mythology', hints: ['Monkey Kingdom', 'Sugriva Capital', 'Vali Ruled', 'Hampi Region', 'Vanara Land'] },
    { word: 'Chitrakoot', category: 'Mythology', hints: ['Exile Station', 'Bharata Meeting', 'Holy Hill', 'Paduka Given', 'Forest Retreat'] },
    { word: 'Ayodhya', category: 'Mythology', hints: ['Ram Janmabhoomi', 'Saryu River', 'Kaushal Desh', 'Dasharatha Capital', 'Holy City'] },
    { word: 'Golden Deer', category: 'Mythology', hints: ['Maricha Disguise', 'Sita Desire', 'Ram Chase', 'Trap', 'Deception'] },
    { word: 'Lakshman Rekha', category: 'Mythology', hints: ['Protection Line', 'Safety Boundary', 'Hut Border', 'Do Not Cross', 'Famous Line'] },
    { word: 'Yudhishthira', category: 'Mythology', hints: ['Eldest Pandava', 'Dharma Raja', 'Dice Gambler', 'Truthful King', 'Kunti Son'] },
    { word: 'Bhima', category: 'Mythology', hints: ['Strongest Pandava', 'Gada Fighter', 'Duryodhana Slayer', 'Vayu Son', 'Huge Appetite'] },
    { word: 'Arjuna', category: 'Mythology', hints: ['Greatest Archer', 'Gandiva Wielder', 'Gita Student', 'Kirti Crown', 'Subhadra Husband'] },
    { word: 'Nakula', category: 'Mythology', hints: ['Twin Pandava', 'Horse Expert', 'Madri Son', 'Handsome', 'Sword Master'] },
    { word: 'Sahadeva', category: 'Mythology', hints: ['Twin Pandava', 'Astrologer', 'Madri Son', 'Youngest', 'Prophecy Knower'] },
    { word: 'Duryodhana', category: 'Mythology', hints: ['Kaurava Prince', 'Mace Fighter', 'Thigh Broken', 'Jealous Cousin', 'Gandhari Son'] },
    { word: 'Dushasana', category: 'Mythology', hints: ['Cheerharan Doer', 'Kaurava Brother', 'Draupadi Insult', 'Bhima Killed', 'Blood Oath'] },
    { word: 'Karna', category: 'Mythology', hints: ['Kavach Kundal', 'Surya Son', 'Kunti Firstborn', 'Chariot Wheel Stuck', 'Daanveer'] },
    { word: 'Bhishma', category: 'Mythology', hints: ['Arrow Bed', 'Terrible Vow', 'Ganga Son', 'Celibacy Oath', 'Ichhaamrityu'] },
    { word: 'Dronacharya', category: 'Mythology', hints: ['Archery Teacher', 'Ekalavya Thumb', 'Brahmin Warrior', 'Ashwatthama Father', 'Guru'] },
    { word: 'Kripacharya', category: 'Mythology', hints: ['Chiranjeevi', 'War Survivor', 'Teacher', 'Drona Friend', 'Immortal Guru'] },
    { word: 'Dhritarashtra', category: 'Mythology', hints: ['Blind King', 'Hundred Sons', 'Gandhari Husband', 'Hastinapur Throne', 'Pandu Brother'] },
    { word: 'Gandhari', category: 'Mythology', hints: ['Blindfolded Queen', 'Hundred Sons', 'Dhritarashtra Wife', 'Krishna Curse', 'Gandhar Princess'] },
    { word: 'Kunti', category: 'Mythology', hints: ['Pandava Mother', 'Sun Invocation', 'Karna Secret', 'Mantra Power', 'Pandu Wife'] },
    { word: 'Madri', category: 'Mythology', hints: ['Twin Mother', 'Pandu Wife', 'Sati Death', 'Nakula Sahadeva', 'Madra Princess'] },
    { word: 'Pandu', category: 'Mythology', hints: ['Pale King', 'Cursed Hunter', 'Five Sons', 'Kunti Husband', 'Forest Death'] },
    { word: 'Vidura', category: 'Mythology', hints: ['Wise Minister', 'Dharma Son', 'Pandava Supporter', 'Low Birth', 'Hastinapur Advisor'] },
    { word: 'Shakuni', category: 'Mythology', hints: ['Dice Master', 'Gandhar Prince', 'Evil Uncle', 'Loaded Dice', 'Kaurava Plotter'] },
    { word: 'Ashwatthama', category: 'Mythology', hints: ['Drona Son', 'Cursed Immortal', 'Night Massacre', 'Gem Forehead', 'Chiranjeevi'] },
    { word: 'Abhimanyu', category: 'Mythology', hints: ['Chakravyuha', 'Arjuna Son', 'Young Warrior', 'Womb Knowledge', 'Tragic Hero'] },
    { word: 'Subhadra', category: 'Mythology', hints: ['Krishna Sister', 'Arjuna Wife', 'Abhimanyu Mother', 'Elopement', 'Yadava Princess'] },
    { word: 'Ghatotkacha', category: 'Mythology', hints: ['Bhima Son', 'Hidimbi Son', 'Rakshasa Warrior', 'Night Battle', 'Karna Shakti'] },
    { word: 'Hidimbi', category: 'Mythology', hints: ['Forest Demoness', 'Bhima Wife', 'Ghatotkacha Mother', 'Love Marriage', 'Rakshasi'] },
    { word: 'Jarasandha', category: 'Mythology', hints: ['Magadha King', 'Split Body', 'Bhima Killed', 'Krishna Enemy', 'Two Halves'] },
    { word: 'Shishupala', category: 'Mythology', hints: ['Hundred Insults', 'Krishna Killed', 'Chedi King', 'Sudarshan Chakra', 'Rajasuja Yagna'] },
    { word: 'Ekalavya', category: 'Mythology', hints: ['Thumb Sacrifice', 'Self Taught Archer', 'Drona Guru Dakshina', 'Tribal Prince', 'Mud Statue'] },
    { word: 'Shikhandi', category: 'Mythology', hints: ['Gender Change', 'Bhishma Downfall', 'Amba Rebirth', 'Human Shield', 'Drupada Child'] },
    { word: 'Uttara', category: 'Mythology', hints: ['Virata Princess', 'Abhimanyu Wife', 'Parikshit Mother', 'Matsya Kingdom', 'Young Bride'] },
    { word: 'Satyaki', category: 'Mythology', hints: ['Krishna Ally', 'Yadava Warrior', 'Arjuna Student', 'Vrishni Clan', 'Chariot Fighter'] },
    { word: 'Dhrishtadyumna', category: 'Mythology', hints: ['Fire Born', 'Drona Slayer', 'Pandava Commander', 'Drupada Son', 'Draupadi Brother'] },
    { word: 'Drupada', category: 'Mythology', hints: ['Panchala King', 'Drona Enemy', 'Draupadi Father', 'Fire Sacrifice', 'Humiliated King'] },
    { word: 'Sanjaya', category: 'Mythology', hints: ['Divine Vision', 'War Narrator', 'Dhritarashtra Eyes', 'Charioteer', 'Battle Reporter'] },
    { word: 'Vyasa', category: 'Mythology', hints: ['Mahabharata Author', 'Veda Divider', 'Satyavati Son', 'Krishna Dwaipayana', 'Island Born'] },
    { word: 'Valmiki', category: 'Mythology', hints: ['Ramayana Author', 'First Poet', 'Hunter Turned Sage', 'Sita Shelter', 'Adi Kavi'] },
    { word: 'Vishwamitra', category: 'Mythology', hints: ['King Turned Sage', 'Gayatri Mantra', 'Ram Guru', 'Menaka Tempted', 'Brahmarshi'] },
    { word: 'Vasishtha', category: 'Mythology', hints: ['Seven Sage', 'Kamadhenu Owner', 'Ram Family Guru', 'Vishwamitra Rival', 'Brahmarshi'] },
    { word: 'Parasara', category: 'Mythology', hints: ['Vyasa Father', 'Satyavati Encounter', 'Shakti Son', 'Hora Shastra', 'Boat Crossing'] },
    { word: 'Agastya', category: 'Mythology', hints: ['Ocean Drinker', 'Vindhya Bowed', 'South Sage', 'Short Stature', 'Pot Born'] },
    { word: 'Durvasa', category: 'Mythology', hints: ['Angry Sage', 'Fearsome Curse', 'Shiva Avatar', 'Kunti Mantra', 'Quick Temper'] },
    { word: 'Jamadagni', category: 'Mythology', hints: ['Parashurama Father', 'Renuka Husband', 'Sacred Cow', 'Fire Sage', 'Bhrigu Clan'] },
    { word: 'Atri', category: 'Mythology', hints: ['Saptarishi', 'Dattatreya Father', 'Anasuya Husband', 'Mind Born', 'Brahma Son'] },
    { word: 'Daksha', category: 'Mythology', hints: ['Sati Father', 'Shiva Opposed', 'Prajapati', 'Goat Head', 'Yagna Destroyed'] },
    { word: 'Kashyapa', category: 'Mythology', hints: ['Father of All', 'Aditi Husband', 'Diti Husband', 'Prajapati', 'Deva Asura Father'] },
    { word: 'Sudarshana Chakra', category: 'Mythology', hints: ['Vishnu Disc', 'Spinning Weapon', 'Krishna Weapon', 'Finger Tip', 'Divine Disc'] },
    { word: 'Gandiva', category: 'Mythology', hints: ['Arjuna Bow', 'Divine Bow', 'Agni Gift', 'Mighty Twang', 'Celestial Weapon'] },
    { word: 'Trishul', category: 'Mythology', hints: ['Three Prong', 'Shiva Weapon', 'Trident', 'Destroyer Tool', 'Pinaka'] },
    { word: 'Vajra', category: 'Mythology', hints: ['Indra Weapon', 'Thunderbolt', 'Dadhichi Bones', 'Lightning Bolt', 'Unbreakable'] },
    { word: 'Brahmastra', category: 'Mythology', hints: ['Ultimate Weapon', 'Brahma Created', 'Mass Destruction', 'One Time Use', 'Cannot Recall'] },
    { word: 'Pashupatastra', category: 'Mythology', hints: ['Shiva Weapon', 'Arjuna Earned', 'Destroyer Astra', 'Tapasya Gift', 'Supreme Weapon'] },
    { word: 'Narayanastra', category: 'Mythology', hints: ['Vishnu Weapon', 'Surrender Only Defense', 'Ashwatthama Used', 'Krishna Advice', 'Thousand Missiles'] },
    { word: 'Agneyastra', category: 'Mythology', hints: ['Fire Weapon', 'Agni Astra', 'Burning Missile', 'Fire God Weapon', 'Flame Arrow'] },
    { word: 'Varunastra', category: 'Mythology', hints: ['Water Weapon', 'Varuna Astra', 'Rain Missile', 'Flood Arrow', 'Counter Fire'] },
    { word: 'Nagastra', category: 'Mythology', hints: ['Snake Weapon', 'Serpent Arrow', 'Karna Used', 'Arjuna Target', 'Venom Missile'] },
    { word: 'Garud Astra', category: 'Mythology', hints: ['Eagle Weapon', 'Counter Naga', 'Bird Missile', 'Snake Eater', 'Garuda Power'] },
    { word: 'Shakti Weapon', category: 'Mythology', hints: ['Indra Gift', 'Karna Saved', 'One Use Spear', 'Ghatotkacha Killed', 'Divine Spear'] },
    { word: 'Gada', category: 'Mythology', hints: ['War Mace', 'Bhima Weapon', 'Duryodhana Weapon', 'Heavy Club', 'Hanuman Weapon'] },
    { word: 'Vijaya Bow', category: 'Mythology', hints: ['Karna Bow', 'Parashurama Gift', 'Indra Weapon', 'Unbeatable Bow', 'String Sound'] },
    { word: 'Pinaka', category: 'Mythology', hints: ['Shiva Bow', 'Ram Broke', 'Sita Swayamvar', 'Heavy Bow', 'Janaka Challenge'] },
    { word: 'Sharanga', category: 'Mythology', hints: ['Vishnu Bow', 'Parashurama Carried', 'Celestial Bow', 'Ram Encounter', 'Divine Weapon'] },
    { word: 'Kaumodaki', category: 'Mythology', hints: ['Vishnu Mace', 'Divine Club', 'Ocean Gift', 'Krishna Weapon', 'Gold Mace'] },
    { word: 'Nandaka', category: 'Mythology', hints: ['Vishnu Sword', 'Krishna Sword', 'Divine Blade', 'Celestial Sword', 'Knowledge Cutter'] },
    { word: 'Vel', category: 'Mythology', hints: ['Murugan Spear', 'Parvati Gift', 'Shakti Lance', 'Surapadman Killed', 'Tamil Worship'] },
    { word: 'Parashu', category: 'Mythology', hints: ['Battle Axe', 'Parashurama Weapon', 'Shiva Gift', 'Kshatriya Slayer', 'Name Giver'] },
    { word: 'Anjani', category: 'Mythology', hints: ['Hanuman Mother', 'Apsara Cursed', 'Vanara Woman', 'Kesari Wife', 'Wind God Blessed'] },
    { word: 'Kesari', category: 'Mythology', hints: ['Hanuman Father', 'Vanara Chief', 'Sumeru Mountain', 'Anjani Husband', 'Monkey King'] },
    { word: 'Shatananda', category: 'Mythology', hints: ['Gautama Son', 'Ahalya Son', 'Mithila Priest', 'Janaka Court', 'Royal Sage'] },
    { word: 'Garuda', category: 'Mythology', hints: ['Vishnu Mount', 'Eagle King', 'Vinata Son', 'Amrit Theft', 'Snake Enemy'] },
    { word: 'Nandi', category: 'Mythology', hints: ['Shiva Bull', 'Temple Guardian', 'Sacred Bull', 'Kailash Dweller', 'White Bull'] },
    { word: 'Airavata', category: 'Mythology', hints: ['White Elephant', 'Indra Mount', 'Ocean Churning Born', 'Cloud Maker', 'Seven Trunks'] },
    { word: 'Uchchaihshravas', category: 'Mythology', hints: ['Seven Head Horse', 'Ocean Churning', 'White Horse', 'Indra Claimed', 'Divine Steed'] },
    { word: 'Kamadhenu', category: 'Mythology', hints: ['Wish Cow', 'Vasishtha Cow', 'Divine Bovine', 'All Desires', 'Sacred Cow'] },
    { word: 'Jambha', category: 'Mythology', hints: ['Asura', 'Indra Enemy', 'Demon King', 'War Against Devas', 'Slain by Indra'] },
    { word: 'Shesha', category: 'Mythology', hints: ['Thousand Hood Serpent', 'Vishnu Bed', 'Ananta', 'World Bearer', 'Cosmic Snake'] },
    { word: 'Vasuki', category: 'Mythology', hints: ['Serpent King', 'Churning Rope', 'Shiva Neck', 'Naga Raja', 'Kadru Son'] },
    { word: 'Takshaka', category: 'Mythology', hints: ['Venomous Naga', 'Parikshit Killed', 'Sarpa Satra', 'Indra Protected', 'Naga Chief'] },
    { word: 'Kaliya', category: 'Mythology', hints: ['Yamuna Serpent', 'Krishna Danced', 'Poisonous Hood', 'Multi Hood', 'Banished Naga'] },
    { word: 'Manasa', category: 'Mythology', hints: ['Snake Goddess', 'Bengali Worship', 'Kashyapa Daughter', 'Chand Sadagar', 'Behula Story'] },
    { word: 'Hiranyakashipu', category: 'Mythology', hints: ['Golden Throne', 'Narasimha Killed', 'Prahlad Father', 'Five Boons', 'Daitya King'] },
    { word: 'Hiranyaksha', category: 'Mythology', hints: ['Earth Stealer', 'Varaha Killed', 'Ocean Hider', 'Daitya', 'Hiranyakashipu Brother'] },
    { word: 'Prahlad', category: 'Mythology', hints: ['Devotee Child', 'Father Opposed', 'Vishnu Saved', 'Holika Fire', 'Daitya Prince'] },
    { word: 'Holika', category: 'Mythology', hints: ['Fire Immune Cloak', 'Prahlad Pyre', 'Holi Origin', 'Burned Herself', 'Hiranyakashipu Sister'] },
    { word: 'Bali Raja', category: 'Mythology', hints: ['Generous Daitya', 'Vamana Tricked', 'Patala Sent', 'Onam Festival', 'Three Steps'] },
    { word: 'Mahishasura', category: 'Mythology', hints: ['Buffalo Demon', 'Durga Killed', 'Mysore Named', 'Brahma Boon', 'Navratri Villain'] },
    { word: 'Raktabija', category: 'Mythology', hints: ['Blood Clone', 'Kali Drank', 'Drop Multiplied', 'Demon Army', 'Invincible Boon'] },
    { word: 'Shumbha', category: 'Mythology', hints: ['Asura King', 'Devi Killed', 'Nishumbha Brother', 'Devi Mahatmya', 'Arrogant Demon'] },
    { word: 'Nishumbha', category: 'Mythology', hints: ['Asura', 'Shumbha Brother', 'Devi Killed', 'Demon General', 'Pride'] },
    { word: 'Tarakasura', category: 'Mythology', hints: ['Kartikeya Killed', 'Shiva Son Only', 'Three Cities Boon', 'Powerful Asura', 'Brahma Boon'] },
    { word: 'Andhaka', category: 'Mythology', hints: ['Blind Demon', 'Shiva Killed', 'Parvati Desire', 'Blood Drops', 'Hiranyaksha Son'] },
    { word: 'Vritra', category: 'Mythology', hints: ['Drought Demon', 'Indra Killed', 'River Blocker', 'Serpent Form', 'Water Hoarder'] },
    { word: 'Bhasmasura', category: 'Mythology', hints: ['Touch to Ash', 'Shiva Boon', 'Mohini Tricked', 'Self Destruction', 'Head Touch'] },
    { word: 'Jalandhara', category: 'Mythology', hints: ['Ocean Born', 'Shiva Enemy', 'Vrinda Husband', 'Sudarshan Killed', 'Powerful Asura'] },
    { word: 'Vrinda', category: 'Mythology', hints: ['Tulsi Plant', 'Jalandhara Wife', 'Chastity Power', 'Vishnu Tricked', 'Sacred Basil'] },
    { word: 'Apsara', category: 'Mythology', hints: ['Celestial Dancer', 'Indra Court', 'Divine Beauty', 'Sage Distraction', 'Heavenly Nymph'] },
    { word: 'Menaka', category: 'Mythology', hints: ['Famous Apsara', 'Vishwamitra Tempted', 'Shakuntala Mother', 'Indra Sent', 'Celestial Beauty'] },
    { word: 'Urvashi', category: 'Mythology', hints: ['Apsara Queen', 'Pururavas Love', 'Thigh Born', 'Arjuna Cursed', 'Narayana Born'] },
    { word: 'Rambha', category: 'Mythology', hints: ['Apsara', 'Vishwamitra Cursed', 'Indra Dancer', 'Stone Curse', 'Celestial Beauty'] },
    { word: 'Tilottama', category: 'Mythology', hints: ['Perfect Beauty', 'Brahma Created', 'Sunda Upasunda', 'Sesame Seed', 'Divine Apsara'] },
    { word: 'Gandharva', category: 'Mythology', hints: ['Celestial Musician', 'Heavenly Singers', 'Apsara Partners', 'Soma Guardians', 'Cloud Dwellers'] },
    { word: 'Kinnaras', category: 'Mythology', hints: ['Half Horse Half Human', 'Celestial Musicians', 'Kubera Service', 'Heavenly Beings', 'Song Creatures'] },
    { word: 'Yaksha', category: 'Mythology', hints: ['Nature Spirit', 'Kubera Servants', 'Tree Guardians', 'Wealth Protectors', 'Forest Beings'] },
    { word: 'Rakshasa', category: 'Mythology', hints: ['Night Demon', 'Shape Shifter', 'Flesh Eater', 'Lanka Dwellers', 'Brahma Created'] },
    { word: 'Daitya', category: 'Mythology', hints: ['Diti Children', 'Anti Gods', 'Asura Type', 'Demon Race', 'Kashyapa Sons'] },
    { word: 'Danava', category: 'Mythology', hints: ['Danu Children', 'Ancient Demons', 'Asura Type', 'Sea Dwellers', 'Kashyapa Sons'] },
    { word: 'Naga', category: 'Mythology', hints: ['Serpent Race', 'Kadru Sons', 'Patala Loka', 'Hood Crown', 'Shape Shifters'] },
    { word: 'Vanadevata', category: 'Mythology', hints: ['Tree Spirit', 'Forest Deity', 'Sacred Grove', 'Nature Worship', 'Bodhi Tree'] },
    { word: 'Kubja', category: 'Mythology', hints: ['Hunchback Woman', 'Krishna Healed', 'Mathura', 'Sandalwood', 'Straightened Back'] },
    { word: 'Putana', category: 'Mythology', hints: ['Poison Breast', 'Baby Krishna', 'Demoness', 'Kamsa Sent', 'Killed by Infant'] },
    { word: 'Bakasura', category: 'Mythology', hints: ['Crane Demon', 'Krishna Killed', 'Bhima Killed', 'Village Terror', 'Food Tribute'] },
    { word: 'Aghasura', category: 'Mythology', hints: ['Snake Demon', 'Krishna Killed', 'Mouth Cave', 'Kamsa Sent', 'Cowherd Swallowed'] },
    { word: 'Trinavarta', category: 'Mythology', hints: ['Whirlwind Demon', 'Baby Krishna', 'Kamsa Sent', 'Sky Carried', 'Crushed'] },
    { word: 'Kamsa', category: 'Mythology', hints: ['Mathura Tyrant', 'Krishna Uncle', 'Devaki Brother', 'Eighth Child Fear', 'Krishna Killed'] },
    { word: 'Devaki', category: 'Mythology', hints: ['Krishna Mother', 'Prison Birth', 'Kamsa Sister', 'Eight Children', 'Vasudeva Wife'] },
    { word: 'Vasudeva', category: 'Mythology', hints: ['Krishna Father', 'Yamuna Crossing', 'Prison Escape', 'Devaki Husband', 'Gokul Delivery'] },
    { word: 'Yashoda', category: 'Mythology', hints: ['Krishna Foster Mother', 'Gokul', 'Mouth Universe', 'Butter Thief Scolding', 'Nanda Wife'] },
    { word: 'Nanda Baba', category: 'Mythology', hints: ['Krishna Foster Father', 'Gokul Chief', 'Cowherd Leader', 'Yashoda Husband', 'Vrindavan'] },
    { word: 'Rukmini', category: 'Mythology', hints: ['Krishna Wife', 'Elopement', 'Lakshmi Avatar', 'Vidarbha Princess', 'Letter to Krishna'] },
    { word: 'Satyabhama', category: 'Mythology', hints: ['Krishna Wife', 'Narakasura', 'Parijat Tree', 'Yadava Princess', 'Bold Queen'] },
    { word: 'Sudama', category: 'Mythology', hints: ['Krishna Friend', 'Poor Brahmin', 'Poha Gift', 'Childhood Friend', 'Dwarka Visit'] },
    { word: 'Akrura', category: 'Mythology', hints: ['Krishna Uncle', 'Mathura Invitation', 'Yadava Noble', 'Charioteer', 'Syamantaka'] },
    { word: 'Uddhava', category: 'Mythology', hints: ['Krishna Friend', 'Gopi Message', 'Yadava Minister', 'Bhramargeet', 'Last Teaching'] },
    { word: 'Narakasura', category: 'Mythology', hints: ['Earth Son', 'Krishna Killed', 'Sixteen Thousand', 'Diwali Origin', 'Pragjyotishpur King'] },
    { word: 'Banasura', category: 'Mythology', hints: ['Thousand Arms', 'Shiva Devotee', 'Usha Father', 'Aniruddha Captured', 'Krishna Battle'] },
    { word: 'Usha', category: 'Mythology', hints: ['Dream Lover', 'Aniruddha Wife', 'Banasura Daughter', 'Chitralekha Friend', 'Dream Portrait'] },
    { word: 'Aniruddha', category: 'Mythology', hints: ['Krishna Grandson', 'Usha Husband', 'Captive Prince', 'Pradyumna Son', 'Yadava Prince'] },
    { word: 'Pradyumna', category: 'Mythology', hints: ['Krishna Son', 'Kamadeva Reborn', 'Rukmini Son', 'Sambara Slayer', 'Love God Rebirth'] },
    { word: 'Samudra Manthan', category: 'Mythology', hints: ['Ocean Churning', 'Amrit Origin', 'Mandara Mountain', 'Deva Asura Team', 'Fourteen Treasures'] },
    { word: 'Amrit', category: 'Mythology', hints: ['Nectar Immortality', 'Ocean Churning', 'Dhanvantari Pot', 'Mohini Distributed', 'Rahu Sipped'] },
    { word: 'Halahala', category: 'Mythology', hints: ['Deadly Poison', 'Shiva Drank', 'Blue Throat', 'Ocean Churning', 'Neelkanth Origin'] },
    { word: 'Rahu', category: 'Mythology', hints: ['Shadow Planet', 'Head Only', 'Eclipse Causer', 'Mohini Tricked', 'Amrit Thief'] },
    { word: 'Ketu', category: 'Mythology', hints: ['Headless Body', 'Rahu Partner', 'Eclipse Node', 'Comet Planet', 'Shadow Graha'] },
    { word: 'Dhanvantari', category: 'Mythology', hints: ['Divine Doctor', 'Amrit Bearer', 'Ayurveda Father', 'Ocean Born', 'Medicine God'] },
    { word: 'Kaustubha', category: 'Mythology', hints: ['Vishnu Gem', 'Ocean Churning', 'Chest Jewel', 'Divine Ruby', 'Most Precious'] },
    { word: 'Parijat', category: 'Mythology', hints: ['Heavenly Tree', 'Ocean Churning', 'Night Fragrance', 'Satyabhama Demanded', 'Coral Jasmine'] },
    { word: 'Kalpavriksha', category: 'Mythology', hints: ['Wish Tree', 'Ocean Churning', 'All Desires', 'Heavenly Tree', 'Indra Garden'] },
    { word: 'Kurukshetra', category: 'Mythology', hints: ['Battle Field', 'Eighteen Day War', 'Haryana', 'Dharma Kshetra', 'Gita Spoken'] },
    { word: 'Hastinapur', category: 'Mythology', hints: ['Kuru Capital', 'Elephant City', 'Kaurava Pandava', 'Ganga Banks', 'Ancient Kingdom'] },
    { word: 'Indraprastha', category: 'Mythology', hints: ['Pandava Capital', 'Khandava Forest', 'Maya Sabha', 'Delhi Region', 'Grand Palace'] },
    { word: 'Dwarka', category: 'Mythology', hints: ['Krishna Capital', 'Golden City', 'Sea Submerged', 'Gujarat Coast', 'Yadava Kingdom'] },
    { word: 'Mathura', category: 'Mythology', hints: ['Krishna Birthplace', 'Kamsa Kingdom', 'Yamuna Bank', 'Prison Birth', 'Holy City'] },
    { word: 'Vrindavan', category: 'Mythology', hints: ['Krishna Childhood', 'Gopi Raas', 'Tulsi Forest', 'Banke Bihari', 'Holi Famous'] },
    { word: 'Gokul', category: 'Mythology', hints: ['Baby Krishna', 'Yashoda Home', 'Cowherd Village', 'Yamuna Crossing', 'Nanda Village'] },
    { word: 'Lanka', category: 'Mythology', hints: ['Golden City', 'Ravana Capital', 'Island Fortress', 'Sea Surrounded', 'Vishwakarma Built'] },
    { word: 'Kailash', category: 'Mythology', hints: ['Shiva Home', 'Sacred Mountain', 'Silver Peak', 'Tibet Border', 'Mansarovar Near'] },
    { word: 'Meru', category: 'Mythology', hints: ['Cosmic Mountain', 'Center Universe', 'Golden Peak', 'Gods Live', 'Axis Mundi'] },
    { word: 'Vaikuntha', category: 'Mythology', hints: ['Vishnu Abode', 'Supreme Heaven', 'Ocean of Milk', 'Eternal Realm', 'Moksha Destination'] },
    { word: 'Amaravati', category: 'Mythology', hints: ['Indra City', 'Heaven Capital', 'Celestial City', 'Nandana Garden', 'Deva Home'] },
    { word: 'Patala', category: 'Mythology', hints: ['Underworld', 'Naga Realm', 'Seven Layers', 'Below Earth', 'Bali Kingdom'] },
    { word: 'Swarga', category: 'Mythology', hints: ['Heaven', 'Indra Rules', 'Good Karma', 'Temporary Stay', 'Celestial Realm'] },
    { word: 'Naraka', category: 'Mythology', hints: ['Hell', 'Yama Rules', 'Sin Punishment', 'Multiple Levels', 'Temporary Suffering'] },
    { word: 'Brahmaloka', category: 'Mythology', hints: ['Creator Realm', 'Highest Heaven', 'Brahma Abode', 'Satyaloka', 'Liberation'] },
    { word: 'Ksheera Sagara', category: 'Mythology', hints: ['Milk Ocean', 'Vishnu Sleeps', 'Shesha Bed', 'Ocean Churning', 'Cosmic Sea'] },
    { word: 'Bhagavad Gita', category: 'Mythology', hints: ['Krishna Teaching', 'Arjuna Doubt', 'Kurukshetra Sermon', 'Eighteen Chapters', 'Dharma Guide'] },
    { word: 'Ramayana', category: 'Mythology', hints: ['Valmiki Epic', 'Ram Story', 'Sita Rescue', 'Twenty Four Thousand Verses', 'Seven Kandas'] },
    { word: 'Mahabharata', category: 'Mythology', hints: ['Longest Epic', 'Vyasa Written', 'Kuru War', 'Hundred Thousand Verses', 'Ganesha Scribed'] },
    { word: 'Vedas', category: 'Mythology', hints: ['Oldest Texts', 'Shruti', 'Four Books', 'Rig Yajur Sama Atharva', 'Brahma Mouth'] },
    { word: 'Upanishads', category: 'Mythology', hints: ['Vedanta', 'Philosophical Texts', 'Brahman Knowledge', 'Guru Student', 'Secret Teachings'] },
    { word: 'Puranas', category: 'Mythology', hints: ['Ancient Stories', 'Eighteen Major', 'Vyasa Compiled', 'Hindu Mythology', 'Creation Tales'] },
    { word: 'Dharma', category: 'Mythology', hints: ['Righteous Duty', 'Cosmic Order', 'Moral Law', 'Karma Linked', 'Four Goals'] },
    { word: 'Karma', category: 'Mythology', hints: ['Action Result', 'Deed Consequence', 'Rebirth Cycle', 'Good Bad', 'Universal Law'] },
    { word: 'Moksha', category: 'Mythology', hints: ['Liberation', 'Cycle End', 'Soul Freedom', 'Ultimate Goal', 'Samsara Escape'] },
    { word: 'Samsara', category: 'Mythology', hints: ['Rebirth Cycle', 'Life Death Loop', 'Karma Driven', 'Moksha End', 'Transmigration'] },
    { word: 'Maya', category: 'Mythology', hints: ['Cosmic Illusion', 'World Appearance', 'Brahman Veil', 'Vishnu Power', 'Not Real'] },
    { word: 'Tapasya', category: 'Mythology', hints: ['Penance', 'Meditation', 'Austerity', 'Boon Earning', 'Fire Practice'] },
    { word: 'Yajna', category: 'Mythology', hints: ['Fire Ritual', 'Sacred Offering', 'Havan Kund', 'Ghee Poured', 'Vedic Ceremony'] },
    { word: 'Yuga', category: 'Mythology', hints: ['World Age', 'Four Cycles', 'Satya Treta Dvapara Kali', 'Time Period', 'Declining Dharma'] },
    { word: 'Kali Yuga', category: 'Mythology', hints: ['Dark Age', 'Current Era', 'Dharma Decline', 'Kalki End', 'Iron Age'] },
    { word: 'Satya Yuga', category: 'Mythology', hints: ['Golden Age', 'Truth Era', 'First Yuga', 'Perfect Dharma', 'Longest Age'] },
    { word: 'Chakravyuha', category: 'Mythology', hints: ['Disc Formation', 'Abhimanyu Trapped', 'War Strategy', 'Spiral Array', 'No Exit Knowledge'] },
    { word: 'Dice Game', category: 'Mythology', hints: ['Shakuni Trick', 'Draupadi Staked', 'Pandava Lost', 'Loaded Dice', 'Exile Cause'] },
    { word: 'Cheerharan', category: 'Mythology', hints: ['Draupadi Disrobing', 'Krishna Saved', 'Endless Saree', 'Kaurava Court', 'Dushasana Act'] },
    { word: 'Vishwarupa', category: 'Mythology', hints: ['Universal Form', 'Krishna Showed', 'Arjuna Terrified', 'Gita Chapter Eleven', 'Cosmic Vision'] },
    { word: 'Govardhan', category: 'Mythology', hints: ['Krishna Lifted', 'Mountain Shield', 'Indra Humbled', 'Seven Days Rain', 'Little Finger'] },
    { word: 'Raas Leela', category: 'Mythology', hints: ['Krishna Dance', 'Gopi Circle', 'Vrindavan Night', 'Flute Music', 'Divine Play'] },
    { word: 'Makhan Chori', category: 'Mythology', hints: ['Butter Thief', 'Baby Krishna', 'Gopi Complaint', 'Pot Breaking', 'Childhood Mischief'] },
    { word: 'Kaliya Nartana', category: 'Mythology', hints: ['Snake Dance', 'Krishna on Hood', 'Yamuna River', 'Poison Removed', 'Serpent Subdued'] },
    { word: 'Dahi Handi', category: 'Mythology', hints: ['Pot Breaking', 'Krishna Janmashtami', 'Human Pyramid', 'Butter Pot', 'Mumbai Festival'] },
    { word: 'Shakuntala', category: 'Mythology', hints: ['Dushyanta Wife', 'Ring Lost', 'Menaka Daughter', 'Forest Raised', 'Kalidasa Play'] },
    { word: 'Dushyanta', category: 'Mythology', hints: ['Puru King', 'Shakuntala Husband', 'Ring Token', 'Forgot Curse', 'Bharata Father'] },
    { word: 'Nala Damayanti', category: 'Mythology', hints: ['Swan Messenger', 'Dice Loss', 'Forest Exile', 'Faithful Love', 'Nishadha King'] },
    { word: 'Harishchandra', category: 'Mythology', hints: ['Truth King', 'Sold Everything', 'Cremation Ground', 'Vishwamitra Test', 'Satya Vadi'] },
    { word: 'Shibi', category: 'Mythology', hints: ['Flesh Given', 'Pigeon Saved', 'Eagle Refused', 'Scale Balance', 'Generous King'] },
    { word: 'Nachiketa', category: 'Mythology', hints: ['Death Student', 'Yama Taught', 'Three Boons', 'Katha Upanishad', 'Soul Question'] },
    { word: 'Dhruva', category: 'Mythology', hints: ['Pole Star', 'Child Devotee', 'Stepmother Insult', 'Vishnu Blessed', 'Fixed Star'] },
    { word: 'Markandeya', category: 'Mythology', hints: ['Shiva Saved', 'Sixteen Years', 'Death Escaped', 'Om Namah Shivaya', 'Chiranjeevi'] },
    { word: 'Dattatreya', category: 'Mythology', hints: ['Three Headed God', 'Trimurthi Avatar', 'Atri Son', 'Anasuya Son', 'Twenty Four Gurus'] },
    { word: 'Adi Shankaracharya', category: 'Mythology', hints: ['Advaita Vedanta', 'Four Mathas', 'Young Philosopher', 'Dig Vijay', 'Kevala Brahman'] },
    { word: 'Prahlada', category: 'Mythology', hints: ['Devotee Child', 'Hiranyakashipu Son', 'Narasimha Saved', 'Pillar God', 'Om Chanted'] },
    { word: 'Trishanku', category: 'Mythology', hints: ['Hanging Heaven', 'Vishwamitra Created', 'Upside Down', 'Rejected King', 'Parallel Swarga'] },
    { word: 'Chyavana', category: 'Mythology', hints: ['Old Sage', 'Sukanya Wife', 'Ashwini Kumaras', 'Youth Restored', 'Ant Hill Meditation'] },
    { word: 'Sukanya', category: 'Mythology', hints: ['Chyavana Wife', 'Eyes Pierced', 'Old Sage Married', 'Faithful Wife', 'Sharyati Daughter'] },
    { word: 'Ashwini Kumaras', category: 'Mythology', hints: ['Divine Doctors', 'Twin Gods', 'Horse Headed', 'Dawn Sons', 'Surya Sons'] },
    { word: 'Saranyu', category: 'Mythology', hints: ['Surya Wife', 'Ashwini Mother', 'Shadow Self', 'Vishwakarma Daughter', 'Mare Form'] },
    { word: 'Vishwakarma', category: 'Mythology', hints: ['Divine Architect', 'Gods Builder', 'Lanka Built', 'Weapons Maker', 'Celestial Engineer'] },
    { word: 'Tvashta', category: 'Mythology', hints: ['Vedic Craftsman', 'Vritra Father', 'Divine Artisan', 'Tool Maker', 'Form Shaper'] },
    { word: 'Tara', category: 'Mythology', hints: ['Brihaspati Wife', 'Chandra Abducted', 'Budha Mother', 'Star Goddess', 'Divine Beauty'] },
    { word: 'Budha', category: 'Mythology', hints: ['Mercury Planet', 'Chandra Son', 'Wednesday', 'Tara Son', 'Ila Married'] },
    { word: 'Shani', category: 'Mythology', hints: ['Saturn Planet', 'Saturday', 'Slow Justice', 'Surya Son', 'Evil Eye'] },
    { word: 'Mangala', category: 'Mythology', hints: ['Mars Planet', 'Tuesday', 'Red Planet', 'War God', 'Earth Son'] },
    { word: 'Jatayu Battle', category: 'Mythology', hints: ['Eagle vs Ravana', 'Sita Protection', 'Wings Cut', 'Brave Sacrifice', 'Old Bird Fight'] },
    { word: 'Vanavasa', category: 'Mythology', hints: ['Forest Living', 'Exile Period', 'Pandava Punishment', 'Thirteen Years', 'Kamyaka Forest'] },
    { word: 'Agyatvas', category: 'Mythology', hints: ['Incognito Year', 'Thirteenth Year', 'Virata Court', 'Pandava Disguise', 'Hidden Identity'] },
    { word: 'Virata', category: 'Mythology', hints: ['Matsya King', 'Pandava Shelter', 'Incognito Year', 'Uttara Father', 'Final Year Host'] },
    { word: 'Draupadi Swayamvar', category: 'Mythology', hints: ['Fish Eye Target', 'Arjuna Won', 'Oil Reflection', 'Five Husbands Result', 'Drupada Hosted'] },
    { word: 'Maya Sabha', category: 'Mythology', hints: ['Illusion Palace', 'Mayasura Built', 'Water Floor', 'Duryodhana Fooled', 'Indraprastha'] },
    { word: 'Lac Palace', category: 'Mythology', hints: ['Wax House', 'Fire Trap', 'Purochana Built', 'Pandava Escape', 'Tunnel Exit'] },
    { word: 'Ekachakra', category: 'Mythology', hints: ['Bakasura Village', 'Bhima Killed', 'Brahmin Saved', 'Pandava Hiding', 'Demon Tribute'] },
    { word: 'Narada Muni', category: 'Mythology', hints: ['Three World Traveler', 'Narayan Chant', 'Divine Gossip', 'Veena Sage', 'Troublemaker Saint'] },
    { word: 'Charvaka', category: 'Mythology', hints: ['Materialist Sage', 'No Afterlife', 'Nastika', 'Rakshasa Disguise', 'Yudhishthira Cursed'] },
    { word: 'Matsyagandha', category: 'Mythology', hints: ['Fish Smell', 'Satyavati Name', 'Vyasa Mother', 'Parasara Encounter', 'Fragrance Given'] },
    { word: 'Satyavati', category: 'Mythology', hints: ['Fisher Princess', 'Shantanu Wife', 'Vyasa Mother', 'Two Sons Died', 'Kuru Queen'] },
    { word: 'Shantanu', category: 'Mythology', hints: ['Kuru King', 'Ganga Husband', 'Bhishma Father', 'Satyavati Husband', 'Youth Touch'] },
    { word: 'Devavrata', category: 'Mythology', hints: ['Bhishma Birth Name', 'Ganga Son', 'Terrible Vow', 'Shantanu Son', 'Crown Prince'] },
    { word: 'Amba', category: 'Mythology', hints: ['Bhishma Abducted', 'Rejected Princess', 'Shikhandi Reborn', 'Revenge Seeker', 'Kashi Princess'] },
    { word: 'Ambika', category: 'Mythology', hints: ['Dhritarashtra Mother', 'Eyes Closed', 'Kashi Princess', 'Vichitravirya Wife', 'Blind Son'] },
    { word: 'Ambalika', category: 'Mythology', hints: ['Pandu Mother', 'Pale Son', 'Kashi Princess', 'Vichitravirya Wife', 'Third Sister'] },
    { word: 'Jayadratha', category: 'Mythology', hints: ['Sindhu King', 'Chakravyuha Guard', 'Arjuna Vowed', 'Sunset Beheading', 'Duhsala Husband'] },
    { word: 'Shalya', category: 'Mythology', hints: ['Madra King', 'Karna Charioteer', 'Pandava Uncle', 'Tricked by Duryodhana', 'Final Commander'] },
    { word: 'Barbarika', category: 'Mythology', hints: ['Three Arrows', 'Krishna Tested', 'Head Witness', 'Bhima Grandson', 'Khatu Shyam'] },
    { word: 'Iravan', category: 'Mythology', hints: ['Arjuna Son', 'Naga Mother', 'Self Sacrifice', 'Kurukshetra', 'Transgender Worship'] },
    { word: 'Parikshit', category: 'Mythology', hints: ['Abhimanyu Son', 'Snake Death', 'Arjuna Grandson', 'Kali Yuga King', 'Takshaka Killed'] },
    { word: 'Janamejaya', category: 'Mythology', hints: ['Sarpa Satra', 'Parikshit Son', 'Snake Sacrifice', 'Astika Stopped', 'Revenge Yajna'] },
    { word: 'Astika', category: 'Mythology', hints: ['Naga Savior', 'Sarpa Satra Stopped', 'Manasa Son', 'Boy Sage', 'Jaratkaru Son'] },
    { word: 'Yuvanashva', category: 'Mythology', hints: ['King Who Birthed', 'Mandhata Father', 'Drank Sacred Water', 'Male Pregnancy', 'Ikshvaku Dynasty'] },
    { word: 'Mandodari Advice', category: 'Mythology', hints: ['Return Sita Plea', 'Lanka Queen Wisdom', 'Ravana Ignored', 'Peace Counsel', 'Wife Warning'] },
    { word: 'Hanuman Chalisa', category: 'Mythology', hints: ['Forty Verses', 'Tulsidas Written', 'Protection Prayer', 'Hanuman Praise', 'Popular Hymn'] },
    { word: 'Sundara Kanda', category: 'Mythology', hints: ['Ramayana Chapter', 'Hanuman Journey', 'Lanka Search', 'Beautiful Book', 'Sita Found'] },
    { word: 'Siddhartha Gautama', category: 'Mythology', hints: ['Became Buddha', 'Kapilavastu Prince', 'Bodhi Tree', 'Middle Path', 'Renunciation'] },
    { word: 'Mahavira', category: 'Mythology', hints: ['Jain Tirthankara', 'Last Prophet', 'Ahimsa', 'Kundagrama Born', 'Twenty Fourth'] },
    { word: 'Rishabhadeva', category: 'Mythology', hints: ['First Tirthankara', 'Bull Symbol', 'Adinatha', 'Jain Founder', 'Mount Kailash'] },
    { word: 'Bahubali', category: 'Mythology', hints: ['Standing Meditation', 'Shravanabelagola', 'Gommateshwara', 'Rishabha Son', 'Giant Statue'] },
    { word: 'Ashoka Chakra', category: 'Mythology', hints: ['Dharma Wheel', 'Twenty Four Spokes', 'National Flag', 'Buddhist Symbol', 'Righteousness'] },
    { word: 'Jataka Tales', category: 'Mythology', hints: ['Buddha Past Lives', 'Moral Stories', 'Animal Fables', 'Five Hundred Forty Seven', 'Birth Stories'] },
    { word: 'Bodhisattva', category: 'Mythology', hints: ['Buddha Aspirant', 'Compassion Being', 'Enlightenment Seeker', 'Mahayana', 'Helping Others'] },
    { word: 'Tara Devi', category: 'Mythology', hints: ['Buddhist Goddess', 'Compassion', 'Green White Forms', 'Avalokiteshvara Tear', 'Protector'] },
    { word: 'Avalokiteshvara', category: 'Mythology', hints: ['Compassion Buddha', 'Thousand Arms', 'Padmapani', 'Mercy Lord', 'Mahayana Buddhist'] },
    { word: 'Mara', category: 'Mythology', hints: ['Buddhist Demon', 'Tempted Buddha', 'Evil One', 'Bodhi Tree Attack', 'Desire Lord'] },
    { word: 'Muchalinda', category: 'Mythology', hints: ['Naga King', 'Buddha Sheltered', 'Rain Protection', 'Seven Hoods', 'Meditation Guard'] },
    { word: 'Nandi Flag', category: 'Mythology', hints: ['Bull Banner', 'Shiva Temple', 'Sacred Emblem', 'Joy Symbol', 'Gate Guardian'] },
    { word: 'Panchatantra', category: 'Mythology', hints: ['Animal Fables', 'Vishnu Sharma', 'Five Strategies', 'Prince Education', 'Moral Tales'] },
    { word: 'Hitopadesha', category: 'Mythology', hints: ['Good Advice', 'Narayana Written', 'Animal Stories', 'Wisdom Tales', 'Panchatantra Based'] },
    { word: 'Vikram Betaal', category: 'Mythology', hints: ['King Ghost Stories', 'Riddle Tales', 'Vampire Spirit', 'Twenty Five Stories', 'Silence Condition'] },
    { word: 'Singhasan Battisi', category: 'Mythology', hints: ['Thirty Two Tales', 'Vikramaditya Throne', 'Talking Statues', 'Wisdom Test', 'Throne Challenge'] },
    { word: 'Vikramaditya', category: 'Mythology', hints: ['Legendary King', 'Ujjain Ruler', 'Justice Famous', 'Betaal Tales', 'Nine Gems Court'] },
    { word: 'Ashtavakra', category: 'Mythology', hints: ['Eight Bends', 'Child Sage', 'Father Freed', 'Janaka Debate', 'Cursed in Womb'] },
    { word: 'Satyavan', category: 'Mythology', hints: ['Savitri Husband', 'Death Destined', 'Woodcutter Prince', 'Yama Taken', 'Revived'] },
    { word: 'Nandi Deva', category: 'Mythology', hints: ['Bull God', 'Shiva Gatekeeper', 'Dance Expert', 'Kailash Guardian', 'Devotee Lord'] },
    { word: 'Kalanemi', category: 'Mythology', hints: ['Ravana Uncle', 'Hanuman Tricked', 'Sorcerer', 'Sanjeevani Block', 'Lake Disguise'] },
    { word: 'Soorpanakha War', category: 'Mythology', hints: ['Nose Cutting Result', 'Lanka Attack Origin', 'Ravana Anger', 'Khara Dushana Killed', 'War Trigger'] },
    { word: 'Sanjeevani', category: 'Mythology', hints: ['Life Herb', 'Hanuman Carried Mountain', 'Dronagiri', 'Lakshmana Revived', 'Miracle Plant'] },
    { word: 'Dronagiri', category: 'Mythology', hints: ['Herb Mountain', 'Hanuman Lifted', 'Sanjeevani Source', 'Flying Mountain', 'Himalaya Part'] },
    { word: 'Ahilya Uddhar', category: 'Mythology', hints: ['Stone Liberation', 'Ram Foot Touch', 'Curse Broken', 'Sage Wife Freed', 'Redemption'] },
    { word: 'Navagraha', category: 'Mythology', hints: ['Nine Planets', 'Temple Worship', 'Horoscope', 'Surya Center', 'Shani Saturday'] },
    { word: 'Trimurti', category: 'Mythology', hints: ['Three Gods', 'Brahma Vishnu Shiva', 'Creator Preserver Destroyer', 'Hindu Trinity', 'Elephanta Caves'] },
    { word: 'Tridevi', category: 'Mythology', hints: ['Three Goddesses', 'Saraswati Lakshmi Parvati', 'Trimurti Consorts', 'Shakti Trinity', 'Divine Feminine'] },
    { word: 'Dashavatara', category: 'Mythology', hints: ['Ten Avatars', 'Vishnu Forms', 'Fish to Kalki', 'Evolution Theory', 'Divine Incarnations'] },
    { word: 'Ashta Lakshmi', category: 'Mythology', hints: ['Eight Forms', 'Wealth Goddess', 'Different Blessings', 'Prosperity Types', 'Lakshmi Aspects'] },
    { word: 'Navaratri', category: 'Mythology', hints: ['Nine Nights', 'Durga Worship', 'Garba Dandiya', 'Shakti Festival', 'Vijayadashami'] },
    { word: 'Vijayadashami', category: 'Mythology', hints: ['Victory Tenth', 'Ravana Effigy', 'Dussehra', 'Good Over Evil', 'Ram Victory'] },
    { word: 'Diwali', category: 'Mythology', hints: ['Light Festival', 'Ram Return', 'Lakshmi Puja', 'Narakasura Death', 'Five Days'] },
    { word: 'Holi', category: 'Mythology', hints: ['Color Festival', 'Holika Fire', 'Radha Krishna', 'Prahlad Survived', 'Spring Festival'] },
    { word: 'Janmashtami', category: 'Mythology', hints: ['Krishna Birthday', 'Midnight Birth', 'Dahi Handi', 'Prison Born', 'Fasting Night'] },
    { word: 'Ram Navami', category: 'Mythology', hints: ['Ram Birthday', 'Chaitra Month', 'Ayodhya Celebration', 'Ninth Day', 'Spring Festival'] },
    { word: 'Maha Shivaratri', category: 'Mythology', hints: ['Shiva Night', 'Night Vigil', 'Fasting', 'Lingam Worship', 'Cosmic Dance'] },
    { word: 'Ganesh Chaturthi', category: 'Mythology', hints: ['Ganesha Birthday', 'Modak Offering', 'Mumbai Famous', 'Clay Idol', 'Visarjan'] },
    { word: 'Char Dham', category: 'Mythology', hints: ['Four Abodes', 'Badrinath Kedarnath Gangotri Yamunotri', 'Pilgrimage Circuit', 'Uttarakhand', 'Salvation Journey'] },
    { word: 'Amarnath', category: 'Mythology', hints: ['Ice Lingam', 'Kashmir Cave', 'Shiva Immortality Secret', 'Pigeon Pair', 'Annual Yatra'] },
    { word: 'Tirupati', category: 'Mythology', hints: ['Balaji Temple', 'Hair Offering', 'Seven Hills', 'Richest Temple', 'Venkateshwara'] },
    { word: 'Somnath', category: 'Mythology', hints: ['First Jyotirlinga', 'Gujarat Coast', 'Moon God Built', 'Many Times Rebuilt', 'Shiva Temple'] },
    { word: 'Pralaya', category: 'Mythology', hints: ['Cosmic Dissolution', 'World End', 'Great Flood', 'New Creation', 'Vishnu Sleeps'] },
    { word: 'Shraddha', category: 'Mythology', hints: ['Ancestor Rites', 'Pitru Paksha', 'Death Ceremony', 'Food Offering', 'Soul Peace'] },
    { word: 'Pitru Loka', category: 'Mythology', hints: ['Ancestor Realm', 'Departed Souls', 'Yama Domain', 'Shraddha Linked', 'Forefathers'] },
    { word: 'Chiranjeevi', category: 'Mythology', hints: ['Immortal Beings', 'Seven Named', 'Ashwatthama Hanuman', 'Live Forever', 'Death Exempt'] },
    { word: 'Sapta Rishi', category: 'Mythology', hints: ['Seven Sages', 'Star Constellation', 'Brahma Created', 'Ursa Major', 'Vedic Seers'] },
    { word: 'Ashta Dikpala', category: 'Mythology', hints: ['Eight Direction Gods', 'Indra East', 'Yama South', 'Varuna West', 'Kubera North'] },
    { word: 'Lokapala', category: 'Mythology', hints: ['World Protectors', 'Direction Guardians', 'Indra Yama Varuna Kubera', 'Compass Gods', 'Realm Keepers'] },
    { word: 'Brahma Kamal', category: 'Mythology', hints: ['Night Bloom', 'Sacred Lotus', 'Himalayas', 'Rare Flower', 'Brahma Offering'] },
    { word: 'Soma Rasa', category: 'Mythology', hints: ['Divine Drink', 'Vedic Ritual', 'Moon Nectar', 'Immortality Juice', 'Gods Beverage'] },
    { word: 'Chintamani', category: 'Mythology', hints: ['Wish Gem', 'Thought Jewel', 'Desire Stone', 'Buddhist Hindu', 'Divine Crystal'] },
    { word: 'Syamantaka', category: 'Mythology', hints: ['Sun Gem', 'Daily Gold', 'Krishna Accused', 'Satrajit Owned', 'Jambavan Fight'] },
  ],
};
