import type { WordPack } from '../game/types';

export const placesPack: WordPack = {
  id: 'places',
  name: 'Places',
  entries: [
    { word: 'Taj Mahal', category: 'Places' },
    { word: 'India Gate', category: 'Places' },
    { word: 'Gateway of India', category: 'Places' },
    { word: 'Marine Drive', category: 'Places' },
    { word: 'Connaught Place', category: 'Places' },
    { word: 'Chandni Chowk', category: 'Places' },
    { word: 'Manali', category: 'Places' },
    { word: 'Shimla', category: 'Places' },
    { word: 'Ladakh', category: 'Places' },
    { word: 'Goa Beach', category: 'Places' },
    { word: 'Munnar', category: 'Places' },
    { word: 'Ooty', category: 'Places' },
    { word: 'Darjeeling', category: 'Places' },
    { word: 'Rishikesh', category: 'Places' },
    { word: 'Varanasi Ghats', category: 'Places' },
    { word: 'Jaipur', category: 'Places' },
    { word: 'Hawa Mahal', category: 'Places' },
    { word: 'Hampi', category: 'Places' },
    { word: 'Mysore Palace', category: 'Places' },
    { word: 'Leh Highway', category: 'Places' },
    { word: 'Howrah Bridge', category: 'Places' },
    { word: 'Charminar', category: 'Places' },
    { word: 'Meenakshi Temple', category: 'Places' },
    { word: 'Golden Temple', category: 'Places' },
    { word: 'Khajuraho', category: 'Places' },
    { word: 'Dal Lake', category: 'Places' },
    { word: 'Backwaters', category: 'Places' },
    { word: 'Nainital', category: 'Places' },
    { word: 'Coorg', category: 'Places' },
    { word: 'Rann of Kutch', category: 'Places' },
    { word: 'Pondicherry', category: 'Places' },
    { word: 'Andaman Islands', category: 'Places' },
    { word: 'Spiti Valley', category: 'Places' },
    { word: 'Rajpath', category: 'Places' },
    { word: 'MG Road', category: 'Places' },
    { word: 'Local Train', category: 'Places' },
    { word: 'Ajanta Caves', category: 'Places' },
    { word: 'Victoria Memorial', category: 'Places' },
    { word: 'Qutub Minar', category: 'Places' },
    { word: 'Red Fort', category: 'Places' },
  ],
};
