import type { WordPack } from '../game/types';

export const placesPack: WordPack = {
  id: 'places',
  name: 'Places',
  entries: [
    // Original 40
    { word: 'Taj Mahal', category: 'Places', hints: ['Agra', 'Mughal', 'Marble', 'Seven Wonders', 'Shah Jahan'] },
    { word: 'India Gate', category: 'Places', hints: ['War Memorial', 'Rajpath', 'Amar Jawan', 'Canopy', 'Lutyens'] },
    { word: 'Gateway of India', category: 'Places', hints: ['Apollo Bunder', 'British Era', 'Harbour', 'Colaba', 'Arch'] },
    { word: 'Marine Drive', category: 'Places', hints: ['Queens Necklace', 'Arabian Sea', 'Promenade', 'Art Deco', 'Sunset'] },
    { word: 'Connaught Place', category: 'Places', hints: ['CP', 'Georgian', 'Inner Circle', 'Rajiv Chowk', 'Shopping'] },
    { word: 'Chandni Chowk', category: 'Places', hints: ['Old Delhi', 'Street Food', 'Paranthe Wali', 'Mughal', 'Silver'] },
    { word: 'Manali', category: 'Places', hints: ['Solang Valley', 'Rohtang', 'Beas River', 'Honeymoon', 'Snow'] },
    { word: 'Shimla', category: 'Places', hints: ['Mall Road', 'Ridge', 'Toy Train', 'Colonial', 'Apple'] },
    { word: 'Ladakh', category: 'Places', hints: ['Pangong', 'Monastery', 'High Altitude', 'Khardung La', 'Leh'] },
    { word: 'Goa Beach', category: 'Places', hints: ['Susegad', 'Feni', 'Carnival', 'Shack', 'Konkani'] },
    { word: 'Munnar', category: 'Places', hints: ['Tea Gardens', 'Eravikulam', 'Neelakurinji', 'Western Ghats', 'Cardamom'] },
    { word: 'Ooty', category: 'Places', hints: ['Nilgiris', 'Botanical Garden', 'Toy Train', 'Lake', 'Chocolate'] },
    { word: 'Darjeeling', category: 'Places', hints: ['Tea', 'Tiger Hill', 'Kanchenjunga', 'Toy Train', 'Himalayan'] },
    { word: 'Rishikesh', category: 'Places', hints: ['Rafting', 'Yoga Capital', 'Laxman Jhula', 'Beatles', 'Ashram'] },
    { word: 'Varanasi Ghats', category: 'Places', hints: ['Dashashwamedh', 'Ganga Aarti', 'Kashi', 'Cremation', 'Boats'] },
    { word: 'Jaipur', category: 'Places', hints: ['Pink City', 'Amer Fort', 'Sawai', 'Nahargarh', 'Rajput'] },
    { word: 'Hawa Mahal', category: 'Places', hints: ['Palace of Winds', 'Pink City', 'Honeycomb', 'Windows', 'Rajput'] },
    { word: 'Hampi', category: 'Places', hints: ['Vijayanagara', 'Ruins', 'Boulders', 'Tungabhadra', 'UNESCO'] },
    { word: 'Mysore Palace', category: 'Places', hints: ['Dasara', 'Wodeyar', 'Illuminated', 'Indo-Saracenic', 'Karnataka'] },
    { word: 'Leh Highway', category: 'Places', hints: ['Srinagar Route', 'Mountain Pass', 'Zoji La', 'Army Convoy', 'Scenic'] },
    { word: 'Howrah Bridge', category: 'Places', hints: ['Rabindra Setu', 'Hooghly', 'Cantilever', 'Kolkata Icon', 'Steel'] },
    { word: 'Charminar', category: 'Places', hints: ['Hyderabad', 'Four Minarets', 'Bangles', 'Old City', 'Qutb Shahi'] },
    { word: 'Meenakshi Temple', category: 'Places', hints: ['Madurai', 'Dravidian', 'Gopuram', 'Thousand Pillars', 'Colorful'] },
    { word: 'Golden Temple', category: 'Places', hints: ['Harmandir Sahib', 'Amrit Sarovar', 'Langar', 'Sikh', 'Gold Leaf'] },
    { word: 'Khajuraho', category: 'Places', hints: ['Sculptures', 'Chandela', 'UNESCO', 'Madhya Pradesh', 'Temple'] },
    { word: 'Dal Lake', category: 'Places', hints: ['Shikara', 'Houseboat', 'Srinagar', 'Floating Market', 'Kashmir'] },
    { word: 'Backwaters', category: 'Places', hints: ['Houseboat', 'Alleppey', 'Kettuvallam', 'Coconut', 'Canals'] },
    { word: 'Nainital', category: 'Places', hints: ['Naini Lake', 'Mall Road', 'Snow View', 'Kumaon', 'Boating'] },
    { word: 'Coorg', category: 'Places', hints: ['Kodagu', 'Coffee', 'Abbey Falls', 'Misty', 'Karnataka'] },
    { word: 'Rann of Kutch', category: 'Places', hints: ['White Desert', 'Salt Flat', 'Gujarat', 'Full Moon', 'Festival'] },
    { word: 'Pondicherry', category: 'Places', hints: ['French Colony', 'Auroville', 'Promenade', 'Sri Aurobindo', 'Tamil'] },
    { word: 'Andaman Islands', category: 'Places', hints: ['Cellular Jail', 'Coral Reef', 'Havelock', 'Radhanagar', 'Bay of Bengal'] },
    { word: 'Spiti Valley', category: 'Places', hints: ['Key Monastery', 'Kaza', 'Cold Desert', 'Chandratal', 'Barren'] },
    { word: 'Rajpath', category: 'Places', hints: ['Kartavya Path', 'Republic Day', 'Parade', 'Lutyens', 'Central Vista'] },
    { word: 'MG Road', category: 'Places', hints: ['Mahatma Gandhi', 'Shopping', 'Bangalore', 'Metro', 'Main Street'] },
    { word: 'Local Train', category: 'Places', hints: ['Mumbai Lifeline', 'Compartment', 'Rush Hour', 'Western Line', 'Dabbawalas'] },
    { word: 'Ajanta Caves', category: 'Places', hints: ['Buddhist', 'Murals', 'Aurangabad', 'Rock Cut', 'UNESCO'] },
    { word: 'Victoria Memorial', category: 'Places', hints: ['Kolkata', 'White Marble', 'British', 'Museum', 'Garden'] },
    { word: 'Qutub Minar', category: 'Places', hints: ['Iron Pillar', 'Mehrauli', 'Slave Dynasty', 'Tallest Brick', 'Delhi'] },
    { word: 'Red Fort', category: 'Places', hints: ['Lal Qila', 'Independence Day', 'Mughal', 'Sandstone', 'Chandni Chowk'] },
    // Cities
    { word: 'Mumbai', category: 'Places', hints: ['Maximum City', 'Bollywood', 'Financial Capital', 'Dabbawalas', 'Western Railway'] },
    { word: 'Delhi', category: 'Places', hints: ['Capital', 'Seven Cities', 'Metro', 'Lutyens', 'Mughal Heritage'] },
    { word: 'Bangalore', category: 'Places', hints: ['Silicon Valley', 'Garden City', 'IT Hub', 'Pleasant Weather', 'Cubbon Park'] },
    { word: 'Chennai', category: 'Places', hints: ['Marina', 'Carnatic Music', 'Filter Coffee', 'Madras', 'Kollywood'] },
    { word: 'Kolkata', category: 'Places', hints: ['City of Joy', 'Rosogolla', 'Durga Puja', 'Tram', 'Victoria'] },
    { word: 'Hyderabad', category: 'Places', hints: ['City of Pearls', 'Biryani', 'HITEC City', 'Nizam', 'Twin City'] },
    { word: 'Pune', category: 'Places', hints: ['Oxford of East', 'Maratha', 'Shaniwar Wada', 'Lonavala Nearby', 'IT Park'] },
    { word: 'Ahmedabad', category: 'Places', hints: ['Sabarmati', 'Kite Festival', 'Textile', 'Gujarat', 'IIM'] },
    { word: 'Lucknow', category: 'Places', hints: ['Nawabi', 'Kebab', 'Tehzeeb', 'Bara Imambara', 'Chikankari'] },
    { word: 'Chandigarh', category: 'Places', hints: ['Le Corbusier', 'Rock Garden', 'Planned City', 'Sector', 'Rose Garden'] },
    { word: 'Bhopal', category: 'Places', hints: ['City of Lakes', 'Bhimbetka', 'MP Capital', 'Upper Lake', 'Nawab'] },
    { word: 'Indore', category: 'Places', hints: ['Cleanest City', 'Sarafa Bazaar', 'Poha Jalebi', 'Holkar', 'Street Food'] },
    { word: 'Nagpur', category: 'Places', hints: ['Orange City', 'Zero Mile', 'Central India', 'Deekshabhoomi', 'Tiger Capital'] },
    { word: 'Surat', category: 'Places', hints: ['Diamond City', 'Textile Hub', 'Locho', 'Gujarat', 'Tapi River'] },
    { word: 'Patna', category: 'Places', hints: ['Patliputra', 'Bihar Capital', 'Golghar', 'Mahavir Mandir', 'Litti Chokha'] },
    { word: 'Ranchi', category: 'Places', hints: ['Jharkhand Capital', 'Dhoni Home', 'Waterfalls', 'Plateau', 'Tribal'] },
    { word: 'Dehradun', category: 'Places', hints: ['Doon Valley', 'FRI', 'Robbers Cave', 'Mussoorie Nearby', 'Uttarakhand'] },
    { word: 'Guwahati', category: 'Places', hints: ['Kamakhya', 'Brahmaputra', 'Northeast Gateway', 'Assam', 'Umananda'] },
    { word: 'Thiruvananthapuram', category: 'Places', hints: ['Trivandrum', 'Padmanabha', 'Kerala Capital', 'Kovalam', 'Technopark'] },
    { word: 'Kochi', category: 'Places', hints: ['Chinese Nets', 'Fort Kochi', 'Backwater Gateway', 'Spice Trade', 'Biennale'] },
    { word: 'Visakhapatnam', category: 'Places', hints: ['Vizag', 'Navy Base', 'Araku Valley', 'Andhra', 'Submarine Museum'] },
    { word: 'Amritsar', category: 'Places', hints: ['Wagah Border', 'Langar', 'Jallianwala', 'Kulcha', 'Sikh Holy City'] },
    { word: 'Jodhpur', category: 'Places', hints: ['Blue City', 'Mehrangarh', 'Marwar', 'Mirchi Vada', 'Desert'] },
    { word: 'Udaipur', category: 'Places', hints: ['City of Lakes', 'Venice of East', 'Pichola', 'Mewar', 'Romantic'] },
    { word: 'Agra', category: 'Places', hints: ['Petha', 'Mughal Capital', 'Yamuna Bank', 'Leather', 'UP'] },
    { word: 'Varanasi', category: 'Places', hints: ['Kashi', 'Oldest City', 'Banarasi Paan', 'Shiva', 'Silk Saree'] },
    { word: 'Allahabad', category: 'Places', hints: ['Prayagraj', 'Triveni Sangam', 'Kumbh Mela', 'UP', 'Nehru Home'] },
    { word: 'Kanpur', category: 'Places', hints: ['Leather Industry', 'IIT', 'UP', 'Industrial', 'Nana Rao Park'] },
    { word: 'Jamshedpur', category: 'Places', hints: ['Steel City', 'Tata', 'Jharkhand', 'Jubilee Park', 'Dimna Lake'] },
    { word: 'Madurai', category: 'Places', hints: ['Temple City', 'Meenakshi', 'Tamil Nadu', 'Jigarthanda', 'Ancient'] },
    { word: 'Coimbatore', category: 'Places', hints: ['Manchester of South', 'Textile', 'Isha Foundation', 'Tamil Nadu', 'Kovai'] },
    { word: 'Mangalore', category: 'Places', hints: ['Coastal Karnataka', 'Tiles', 'Kudla', 'Bunt Cuisine', 'Surathkal'] },
    { word: 'Hubli', category: 'Places', hints: ['Dharwad Pedha', 'North Karnataka', 'Commercial Hub', 'Railway Junction', 'Vidyagiri'] },
    { word: 'Belgaum', category: 'Places', hints: ['Belagavi', 'Military', 'Karnataka Border', 'Kunda', 'Fort'] },
    { word: 'Vadodara', category: 'Places', hints: ['Baroda', 'Laxmi Vilas', 'Gaekwad', 'Gujarat', 'Sayaji Garden'] },
    { word: 'Rajkot', category: 'Places', hints: ['Saurashtra', 'Gandhi Childhood', 'Gujarat', 'Penda', 'Watch Industry'] },
    { word: 'Jalandhar', category: 'Places', hints: ['Sports Goods', 'Devi Talab', 'Punjab', 'Leather', 'NIT'] },
    { word: 'Ludhiana', category: 'Places', hints: ['Manchester of India', 'Hosiery', 'Punjab', 'Cycle Industry', 'Lodhi'] },
    { word: 'Gwalior', category: 'Places', hints: ['Fort', 'Tansen', 'MP', 'Scindia', 'Music'] },
    { word: 'Meerut', category: 'Places', hints: ['1857 Revolt', 'Sports City', 'UP', 'Scissors', 'Hastinapur Nearby'] },
    { word: 'Nashik', category: 'Places', hints: ['Wine Capital', 'Kumbh', 'Grape', 'Trimbakeshwar', 'Godavari'] },
    { word: 'Aurangabad', category: 'Places', hints: ['Ajanta Ellora', 'Bibi Ka Maqbara', 'Silk', 'Marathwada', 'Daulatabad'] },
    { word: 'Raipur', category: 'Places', hints: ['Chhattisgarh Capital', 'Steel Market', 'Naya Raipur', 'Rice Bowl', 'Marine Drive'] },
    { word: 'Jammu', category: 'Places', hints: ['Vaishno Devi Base', 'Dogra', 'Winter Capital', 'Rajma Chawal', 'Tawi River'] },
    { word: 'Srinagar', category: 'Places', hints: ['Dal Lake', 'Shikara', 'Kashmir Capital', 'Chinar', 'Mughal Gardens'] },
    { word: 'Gangtok', category: 'Places', hints: ['MG Marg', 'Kanchenjunga View', 'Sikkim Capital', 'Monastery', 'Nathula'] },
    { word: 'Shillong', category: 'Places', hints: ['Scotland of East', 'Rock Capital', 'Meghalaya', 'Ward Lake', 'Khasi'] },
    { word: 'Imphal', category: 'Places', hints: ['Kangla Fort', 'Loktak', 'Manipur', 'Ima Keithel', 'Polo Origin'] },
    { word: 'Aizawl', category: 'Places', hints: ['Mizoram Capital', 'Church', 'Hilltop City', 'Mizo', 'Northeast'] },
    { word: 'Itanagar', category: 'Places', hints: ['Arunachal Capital', 'Ita Fort', 'Ganga Lake', 'Tribal', 'Dawn Lit'] },
    { word: 'Kohima', category: 'Places', hints: ['Nagaland Capital', 'War Cemetery', 'Hornbill', 'WWII', 'Naga'] },
    { word: 'Agartala', category: 'Places', hints: ['Tripura Capital', 'Ujjayanta Palace', 'Bangladesh Border', 'Northeast', 'Neer Mahal'] },
    { word: 'Panaji', category: 'Places', hints: ['Goa Capital', 'Fontainhas', 'Mandovi', 'Portuguese', 'Latin Quarter'] },
    { word: 'Silvassa', category: 'Places', hints: ['Dadra Nagar Haveli', 'Tribal Museum', 'Garden', 'UT', 'Vanganga Lake'] },
    { word: 'Daman', category: 'Places', hints: ['UT', 'Portuguese Fort', 'Devka Beach', 'Gujarat Border', 'Jampore'] },
    { word: 'Kavaratti', category: 'Places', hints: ['Lakshadweep Capital', 'Coral Island', 'Lagoon', 'Aquarium', 'Arabian Sea'] },
    { word: 'Port Blair', category: 'Places', hints: ['Andaman Capital', 'Cellular Jail', 'Ross Island', 'Navy', 'Corbyn Cove'] },
    // Hill stations
    { word: 'Mussoorie', category: 'Places', hints: ['Queen of Hills', 'Gun Hill', 'Kempty Falls', 'Dehradun Nearby', 'Mall Road'] },
    { word: 'Kodaikanal', category: 'Places', hints: ['Princess of Hills', 'Star Lake', 'Tamil Nadu', 'Coakers Walk', 'Eucalyptus'] },
    { word: 'Kasauli', category: 'Places', hints: ['Himachal', 'Christ Church', 'Monkey Point', 'Colonial', 'Pine'] },
    { word: 'Lansdowne', category: 'Places', hints: ['Garhwal Rifles', 'Uttarakhand', 'Bhulla Lake', 'Cantonment', 'Quiet'] },
    { word: 'Mount Abu', category: 'Places', hints: ['Rajasthan Only', 'Dilwara', 'Nakki Lake', 'Aravalli', 'Cool Oasis'] },
    { word: 'Mahabaleshwar', category: 'Places', hints: ['Strawberry', 'Pratapgad', 'Maharashtra', 'Venna Lake', 'Mapro'] },
    { word: 'Lonavala', category: 'Places', hints: ['Chikki', 'Bhushi Dam', 'Mumbai Weekend', 'Karla Caves', 'Khandala Twin'] },
    { word: 'Khandala', category: 'Places', hints: ['Ghats', 'Pune Mumbai', 'Reversing Station', 'Duke Nose', 'Aamir Khan Song'] },
    { word: 'Coonoor', category: 'Places', hints: ['Nilgiris', 'Sims Park', 'Dolphin Nose', 'Tea Estate', 'Tamil Nadu'] },
    { word: 'Wayanad', category: 'Places', hints: ['Kerala', 'Edakkal Caves', 'Chembra Peak', 'Spice', 'Banasura Dam'] },
    { word: 'Almora', category: 'Places', hints: ['Kumaon', 'Bal Mithai', 'Kasar Devi', 'Uttarakhand', 'Bright End'] },
    { word: 'Ranikhet', category: 'Places', hints: ['Queens Meadow', 'Army', 'Uttarakhand', 'Golf Course', 'Chaubatia'] },
    { word: 'Dalhousie', category: 'Places', hints: ['Himachal', 'Kalatop', 'British Era', 'Pine', 'Khajjiar Nearby'] },
    { word: 'McLeod Ganj', category: 'Places', hints: ['Little Lhasa', 'Dalai Lama', 'Tibetan', 'Triund Base', 'Dharamkot'] },
    { word: 'Dharamshala', category: 'Places', hints: ['Cricket Stadium', 'Tibetan Colony', 'Himachal', 'HPCA', 'Kangra'] },
    { word: 'Bir Billing', category: 'Places', hints: ['Paragliding', 'Himachal', 'Tibetan Colony', 'Monastery', 'Adventure'] },
    { word: 'Tawang', category: 'Places', hints: ['Arunachal', 'Monastery', 'War Memorial', 'Sela Pass', 'Buddhist'] },
    { word: 'Chopta', category: 'Places', hints: ['Mini Switzerland', 'Tungnath', 'Uttarakhand', 'Chandrashila', 'Meadow'] },
    { word: 'Auli', category: 'Places', hints: ['Skiing', 'Uttarakhand', 'Ropeway', 'Nanda Devi View', 'Snow'] },
    { word: 'Gulmarg', category: 'Places', hints: ['Gondola', 'Skiing', 'Meadow of Flowers', 'Kashmir', 'Bollywood'] },
    { word: 'Pahalgam', category: 'Places', hints: ['Valley of Shepherds', 'Betaab Valley', 'Amarnath Base', 'Lidder River', 'Kashmir'] },
    { word: 'Sonmarg', category: 'Places', hints: ['Meadow of Gold', 'Thajiwas Glacier', 'Kashmir', 'Zoji La Base', 'Alpine'] },
    { word: 'Lachung', category: 'Places', hints: ['North Sikkim', 'Yumthang Valley', 'Flowers', 'Lepcha', 'Snow'] },
    { word: 'Pelling', category: 'Places', hints: ['Kanchenjunga View', 'West Sikkim', 'Rabdentse', 'Skywalk', 'Monastery'] },
    { word: 'Kasol', category: 'Places', hints: ['Mini Israel', 'Parvati Valley', 'Backpacker', 'Himachal', 'Kheerganga'] },
    { word: 'Tirthan Valley', category: 'Places', hints: ['Great Himalayan NP', 'Trout Fishing', 'Himachal', 'Offbeat', 'Jalori Pass'] },
    { word: 'Kufri', category: 'Places', hints: ['Shimla Nearby', 'Potato', 'Himalayan Wildlife', 'Snow Point', 'Horse Ride'] },
    { word: 'Chikmagalur', category: 'Places', hints: ['Coffee Land', 'Mullayanagiri', 'Karnataka', 'Baba Budangiri', 'Homestay'] },
    { word: 'Yercaud', category: 'Places', hints: ['Jewel of South', 'Salem Nearby', 'Lake', 'Tamil Nadu', 'Shevaroy'] },
    { word: 'Valparai', category: 'Places', hints: ['Tea Estate', 'Anaimalai', 'Tamil Nadu', 'Hairpin Bends', 'Sholayar Dam'] },
    { word: 'Saputara', category: 'Places', hints: ['Gujarat Only', 'Dang District', 'Tribal', 'Lake', 'Monsoon'] },
    { word: 'Pachmarhi', category: 'Places', hints: ['Satpura Queen', 'Bee Falls', 'MP', 'Pandav Caves', 'Cantonment'] },
    { word: 'Matheran', category: 'Places', hints: ['No Vehicles', 'Toy Train', 'Maharashtra', 'Echo Point', 'Red Soil'] },
    // Beaches
    { word: 'Juhu Beach', category: 'Places', hints: ['Mumbai', 'Pav Bhaji', 'Bollywood Stars', 'Chowpatty Nearby', 'Sunset'] },
    { word: 'Marina Beach', category: 'Places', hints: ['Chennai', 'Longest Urban', 'Bay of Bengal', 'Lighthouse', 'Sundal'] },
    { word: 'Baga Beach', category: 'Places', hints: ['North Goa', 'Nightlife', 'Shack', 'Water Sports', 'Titos'] },
    { word: 'Anjuna Beach', category: 'Places', hints: ['Flea Market', 'Hippie', 'Goa', 'Trance', 'Wednesday Market'] },
    { word: 'Calangute Beach', category: 'Places', hints: ['Queen of Beaches', 'North Goa', 'Crowded', 'Water Sports', 'Tourist'] },
    { word: 'Palolem Beach', category: 'Places', hints: ['South Goa', 'Crescent', 'Silent Disco', 'Canacona', 'Kayaking'] },
    { word: 'Varkala Beach', category: 'Places', hints: ['Kerala', 'Cliff', 'Papanasam', 'Healing', 'Laterite'] },
    { word: 'Kovalam Beach', category: 'Places', hints: ['Kerala', 'Lighthouse', 'Trivandrum', 'Crescent', 'Ayurveda'] },
    { word: 'Radhanagar Beach', category: 'Places', hints: ['Havelock Island', 'Asia Best', 'Andaman', 'White Sand', 'Turquoise'] },
    { word: 'Puri Beach', category: 'Places', hints: ['Odisha', 'Jagannath', 'Sand Art', 'Rath Yatra', 'Golden'] },
    { word: 'Gokarna Beach', category: 'Places', hints: ['Om Shape', 'Karnataka', 'Kudle', 'Half Moon', 'Temple Town'] },
    { word: 'Mandrem Beach', category: 'Places', hints: ['North Goa', 'Quiet', 'River Crossing', 'Yoga', 'Secluded'] },
    { word: 'Diu Beach', category: 'Places', hints: ['UT', 'Nagoa', 'Portuguese Fort', 'Gujarat Nearby', 'Island'] },
    { word: 'Mahabalipuram Beach', category: 'Places', hints: ['Shore Temple', 'Pallava', 'Tamil Nadu', 'Rock Cut', 'UNESCO'] },
    { word: 'Tarkarli Beach', category: 'Places', hints: ['Malvan', 'Scuba Diving', 'Sindhudurg', 'Maharashtra', 'Clear Water'] },
    { word: 'Alibaug Beach', category: 'Places', hints: ['Mumbai Weekend', 'Kolaba Fort', 'Konkan', 'Maharashtra', 'Ferry'] },
    { word: 'Chandipur Beach', category: 'Places', hints: ['Vanishing Sea', 'Odisha', 'Balasore', 'Tidal', 'Missile Test'] },
    { word: 'Digha Beach', category: 'Places', hints: ['West Bengal', 'Weekend Spot', 'Bay of Bengal', 'Kolkata Trip', 'Fried Fish'] },
    { word: 'Rishikonda Beach', category: 'Places', hints: ['Vizag', 'Jewel of East Coast', 'Andhra', 'Navy', 'Surfing'] },
    { word: 'Bekal Beach', category: 'Places', hints: ['Kerala', 'Bekal Fort', 'Kasaragod', 'Malabar', 'Pristine'] },
    // Monuments & landmarks
    { word: 'Jantar Mantar', category: 'Places', hints: ['Observatory', 'Jai Singh', 'Sundial', 'Astronomy', 'Delhi Jaipur'] },
    { word: 'Humayun Tomb', category: 'Places', hints: ['Mughal Garden', 'Delhi', 'Precursor Taj', 'UNESCO', 'Persian Style'] },
    { word: 'Lotus Temple', category: 'Places', hints: ['Bahai', 'Delhi', 'Flower Shape', 'Marble', 'No Idol'] },
    { word: 'Akshardham', category: 'Places', hints: ['Swaminarayan', 'Delhi', 'Light Show', 'Sandstone', 'Guinness Record'] },
    { word: 'Jama Masjid', category: 'Places', hints: ['Old Delhi', 'Shah Jahan', 'Largest Mosque', 'Red Sandstone', 'Courtyard'] },
    { word: 'Fatehpur Sikri', category: 'Places', hints: ['Akbar', 'Buland Darwaza', 'Abandoned City', 'UP', 'Salim Chishti'] },
    { word: 'Agra Fort', category: 'Places', hints: ['Red Sandstone', 'Mughal', 'Yamuna View', 'Shah Jahan Prison', 'Akbar'] },
    { word: 'Amber Fort', category: 'Places', hints: ['Jaipur', 'Elephant Ride', 'Sheesh Mahal', 'Rajput', 'Maota Lake'] },
    { word: 'Mehrangarh Fort', category: 'Places', hints: ['Jodhpur', 'Cliff Top', 'Marwar', 'Rathore', 'Museum'] },
    { word: 'Jaisalmer Fort', category: 'Places', hints: ['Golden Fort', 'Living Fort', 'Sandstone', 'Desert', 'Sonar Quila'] },
    { word: 'City Palace Jaipur', category: 'Places', hints: ['Kachwaha', 'Pink City', 'Peacock Gate', 'Mubarak Mahal', 'Royal'] },
    { word: 'City Palace Udaipur', category: 'Places', hints: ['Lake View', 'Mewar', 'Balcony', 'Museum', 'Rajput'] },
    { word: 'Lake Palace', category: 'Places', hints: ['Udaipur', 'Floating Hotel', 'Pichola', 'James Bond', 'White Marble'] },
    { word: 'Golconda Fort', category: 'Places', hints: ['Hyderabad', 'Diamond', 'Clapping Acoustics', 'Qutb Shahi', 'Sound Light'] },
    { word: 'Gol Gumbaz', category: 'Places', hints: ['Bijapur', 'Whispering Gallery', 'Dome', 'Adil Shah', 'Karnataka'] },
    { word: 'Konark Sun Temple', category: 'Places', hints: ['Chariot Wheels', 'Odisha', 'UNESCO', 'Black Pagoda', 'Stone Carving'] },
    { word: 'Jagannath Temple', category: 'Places', hints: ['Puri', 'Rath Yatra', 'Char Dham', 'Mahaprasad', 'Odisha'] },
    { word: 'Somnath Temple', category: 'Places', hints: ['Gujarat', 'Jyotirlinga', 'Destroyed Rebuilt', 'Prabhas Patan', 'Arabian Sea'] },
    { word: 'Tirupati Temple', category: 'Places', hints: ['Venkateswara', 'Laddu', 'Hair Donation', 'Richest Temple', 'Seven Hills'] },
    { word: 'Kedarnath Temple', category: 'Places', hints: ['Char Dham', 'Shiva', 'Uttarakhand', 'Trek', 'Floods 2013'] },
    { word: 'Badrinath Temple', category: 'Places', hints: ['Char Dham', 'Vishnu', 'Uttarakhand', 'Alaknanda', 'Hot Spring'] },
    { word: 'Vaishno Devi', category: 'Places', hints: ['Jammu', 'Cave Shrine', 'Trikuta Hills', 'Pindi', 'Mata'] },
    { word: 'Kashi Vishwanath', category: 'Places', hints: ['Varanasi', 'Shiva', 'Jyotirlinga', 'Corridor', 'Gold Dome'] },
    { word: 'Sanchi Stupa', category: 'Places', hints: ['Buddhist', 'Ashoka', 'MP', 'UNESCO', 'Toranas'] },
    { word: 'Ellora Caves', category: 'Places', hints: ['Kailasa Temple', 'Rock Cut', 'Aurangabad', 'Three Religions', 'UNESCO'] },
    { word: 'Elephanta Caves', category: 'Places', hints: ['Mumbai Harbour', 'Trimurti', 'Island', 'Ferry', 'Shiva'] },
    { word: 'Brihadeeswara Temple', category: 'Places', hints: ['Thanjavur', 'Chola', 'Big Temple', 'Shadow Mystery', 'UNESCO'] },
    { word: 'Ramanathaswamy Temple', category: 'Places', hints: ['Rameswaram', 'Longest Corridor', 'Char Dham', 'Tamil Nadu', 'Shiva'] },
    { word: 'Siddhivinayak Temple', category: 'Places', hints: ['Mumbai', 'Ganesh', 'Prabhadevi', 'Bollywood', 'Gold Dome'] },
    { word: 'Mahabodhi Temple', category: 'Places', hints: ['Bodh Gaya', 'Buddha', 'Enlightenment', 'Bihar', 'Bodhi Tree'] },
    { word: 'Nalanda Ruins', category: 'Places', hints: ['Ancient University', 'Bihar', 'Buddhist', 'Library', 'Ruins'] },
    { word: 'Cellular Jail', category: 'Places', hints: ['Kala Pani', 'Port Blair', 'Freedom Fighters', 'British Prison', 'Sound Light'] },
    { word: 'Sabarmati Ashram', category: 'Places', hints: ['Gandhi', 'Ahmedabad', 'Dandi March', 'Spinning Wheel', 'Riverfront'] },
    { word: 'Rashtrapati Bhavan', category: 'Places', hints: ['President House', 'Lutyens', 'Mughal Garden', 'Delhi', 'Dome'] },
    { word: 'Parliament House', category: 'Places', hints: ['Sansad Bhavan', 'Circular', 'New Building', 'Delhi', 'Democracy'] },
    { word: 'Chhatrapati Shivaji Terminus', category: 'Places', hints: ['CST', 'Victorian Gothic', 'Mumbai', 'Railway', 'UNESCO'] },
    { word: 'Haji Ali Dargah', category: 'Places', hints: ['Mumbai', 'Sea Link', 'Island Mosque', 'Causeway', 'Worli'] },
    { word: 'Jallianwala Bagh', category: 'Places', hints: ['Amritsar', 'Massacre 1919', 'General Dyer', 'Bullet Marks', 'Memorial'] },
    { word: 'Wagah Border', category: 'Places', hints: ['Flag Ceremony', 'India Pakistan', 'Retreat', 'BSF', 'Amritsar'] },
    { word: 'Statue of Unity', category: 'Places', hints: ['Tallest Statue', 'Sardar Patel', 'Gujarat', 'Narmada', 'Kevadia'] },
    { word: 'Char Minar', category: 'Places', hints: ['Hyderabad', 'Four Towers', 'Bangles', 'Old City', 'Qutb Shahi'] },
    // Rivers
    { word: 'Ganga River', category: 'Places', hints: ['Varanasi', 'Holy Dip', 'Aarti', 'Haridwar', 'Glacier'] },
    { word: 'Yamuna River', category: 'Places', hints: ['Delhi', 'Taj Mahal', 'Krishna', 'Mathura', 'Tributary'] },
    { word: 'Brahmaputra River', category: 'Places', hints: ['Assam', 'Flood', 'Mighty', 'Northeast', 'Tibet Origin'] },
    { word: 'Godavari River', category: 'Places', hints: ['Nashik', 'Dakshina Ganga', 'Maharashtra', 'Longest Peninsula', 'Kumbh'] },
    { word: 'Krishna River', category: 'Places', hints: ['Andhra', 'Mahabaleshwar', 'Dam', 'South India', 'Vijayawada'] },
    { word: 'Kaveri River', category: 'Places', hints: ['Karnataka', 'Tamil Nadu', 'Ranganathaswamy', 'Coffee Land', 'Srirangapatna'] },
    { word: 'Narmada River', category: 'Places', hints: ['Madhya Pradesh', 'Marble Rocks', 'Parikrama', 'Gujarat', 'Sardar Sarovar'] },
    { word: 'Tungabhadra River', category: 'Places', hints: ['Hampi', 'Karnataka', 'Dam', 'Vijayanagar', 'Rocky Bed'] },
    { word: 'Chenab River', category: 'Places', hints: ['Jammu', 'Five Rivers', 'Panjtnad', 'Kashmir', 'Bridge'] },
    { word: 'Sutlej River', category: 'Places', hints: ['Punjab', 'Bhakra Dam', 'Indus Tributary', 'Himachal', 'Gobind Sagar'] },
    { word: 'Beas River', category: 'Places', hints: ['Manali', 'Kullu Valley', 'Punjab', 'Alexander', 'Pong Dam'] },
    { word: 'Chambal River', category: 'Places', hints: ['Ravines', 'Rajasthan', 'Gharial', 'Dacoits', 'Clean Water'] },
    { word: 'Mahanadi River', category: 'Places', hints: ['Odisha', 'Hirakud Dam', 'Chhattisgarh', 'Great River', 'Sambalpur'] },
    { word: 'Sabarmati River', category: 'Places', hints: ['Ahmedabad', 'Riverfront', 'Gandhi Ashram', 'Gujarat', 'Dry Season'] },
    { word: 'Betwa River', category: 'Places', hints: ['Orchha', 'Bundelkhand', 'Yamuna Tributary', 'MP', 'Cenotaphs'] },
    // States & UTs
    { word: 'Rajasthan', category: 'Places', hints: ['Desert', 'Forts', 'Camels', 'Jaipur', 'Thar'] },
    { word: 'Kerala', category: 'Places', hints: ['Backwaters', 'Gods Own Country', 'Coconut', 'Ayurveda', 'Munnar'] },
    { word: 'Goa', category: 'Places', hints: ['Beaches', 'Susegad', 'Carnival', 'Portuguese', 'Cashew Feni'] },
    { word: 'Himachal Pradesh', category: 'Places', hints: ['Apple', 'Shimla', 'Mountains', 'Dev Bhoomi', 'Snow'] },
    { word: 'Uttarakhand', category: 'Places', hints: ['Char Dham', 'Rishikesh', 'Dehradun', 'Mussoorie', 'Yoga'] },
    { word: 'Sikkim', category: 'Places', hints: ['Kanchenjunga', 'Monasteries', 'Organic State', 'Gangtok', 'Cardamom'] },
    { word: 'Meghalaya', category: 'Places', hints: ['Cherrapunji', 'Living Root Bridge', 'Wettest Place', 'Shillong', 'Clouds'] },
    { word: 'Tamil Nadu', category: 'Places', hints: ['Temples', 'Chennai', 'Filter Coffee', 'Bharatnatyam', 'Silk Saree'] },
    { word: 'Karnataka', category: 'Places', hints: ['Bangalore', 'Mysore Palace', 'IT Hub', 'Coorg', 'Bisi Bele Bath'] },
    { word: 'Maharashtra', category: 'Places', hints: ['Mumbai', 'Pune', 'Vada Pav', 'Shivaji', 'Bollywood'] },
    { word: 'Gujarat', category: 'Places', hints: ['Garba', 'Dhokla', 'Rann of Kutch', 'Diamond', 'Dry State'] },
    { word: 'Punjab', category: 'Places', hints: ['Wheat Fields', 'Bhangra', 'Golden Temple', 'Lassi', 'Five Rivers'] },
    { word: 'West Bengal', category: 'Places', hints: ['Kolkata', 'Rosogolla', 'Durga Puja', 'Howrah Bridge', 'Fish'] },
    { word: 'Odisha', category: 'Places', hints: ['Jagannath', 'Konark', 'Tribal Art', 'Rath Yatra', 'Chilika'] },
    { word: 'Assam', category: 'Places', hints: ['Tea', 'Rhino', 'Bihu', 'Brahmaputra', 'Silk'] },
    { word: 'Chhattisgarh', category: 'Places', hints: ['Rice Bowl', 'Tribal', 'Chitrakote Falls', 'Bastar', 'Forests'] },
    { word: 'Jharkhand', category: 'Places', hints: ['Ranchi', 'Waterfalls', 'Mining', 'Forest Land', 'Jamshedpur'] },
    { word: 'Nagaland', category: 'Places', hints: ['Hornbill Festival', 'Kohima', 'Tribal', 'Northeast', 'Headhunters'] },
    { word: 'Mizoram', category: 'Places', hints: ['Aizawl', 'Bamboo Dance', 'Blue Mountain', 'Northeast', 'Highest Literacy'] },
    { word: 'Manipur', category: 'Places', hints: ['Imphal', 'Polo Origin', 'Loktak Lake', 'Sangai Deer', 'Northeast'] },
    // Markets & bazaars
    { word: 'Sarojini Nagar', category: 'Places', hints: ['Delhi', 'Cheap Clothes', 'Bargain', 'Export Surplus', 'Crowded'] },
    { word: 'Palika Bazaar', category: 'Places', hints: ['Underground', 'Connaught Place', 'Delhi', 'Electronics', 'Imitation'] },
    { word: 'Crawford Market', category: 'Places', hints: ['Mumbai', 'Fruits', 'British Era', 'Wholesale', 'Heritage Building'] },
    { word: 'Linking Road', category: 'Places', hints: ['Bandra', 'Mumbai', 'Street Shopping', 'Fashion', 'Bargain'] },
    { word: 'Commercial Street', category: 'Places', hints: ['Bangalore', 'Shopping', 'Narrow Lanes', 'Garments', 'Bustling'] },
    { word: 'Colaba Causeway', category: 'Places', hints: ['Mumbai', 'Gateway Nearby', 'Trinkets', 'Street Stalls', 'Tourist'] },
    { word: 'Janpath Market', category: 'Places', hints: ['Delhi', 'Handicrafts', 'Tibetan', 'Connaught Place', 'Foreigners'] },
    { word: 'Chor Bazaar', category: 'Places', hints: ['Mumbai', 'Antiques', 'Thieves Market', 'Old Furniture', 'Vintage'] },
    { word: 'Lajpat Nagar', category: 'Places', hints: ['Delhi', 'Central Market', 'Wedding Shopping', 'Mehndi', 'Chaat'] },
    { word: 'Nehru Place', category: 'Places', hints: ['Delhi', 'Computers', 'Electronics', 'Pirated Software', 'IT Market'] },
    { word: 'Karol Bagh', category: 'Places', hints: ['Delhi', 'Ajmal Khan Road', 'Sari', 'Electronics', 'Hotel Hub'] },
    { word: 'T Nagar', category: 'Places', hints: ['Chennai', 'Ranganathan Street', 'Gold Shops', 'Silk Saree', 'Pondy Bazaar'] },
    { word: 'Chickpet', category: 'Places', hints: ['Bangalore', 'Silk Market', 'Old City', 'Wholesale', 'Textiles'] },
    { word: 'Bapu Bazaar', category: 'Places', hints: ['Jaipur', 'Bangles', 'Textiles', 'Rajasthani', 'Colorful'] },
    { word: 'Laad Bazaar', category: 'Places', hints: ['Hyderabad', 'Bangles', 'Charminar', 'Lac', 'Pearl'] },
    { word: 'New Market Kolkata', category: 'Places', hints: ['Lindsay Street', 'Colonial', 'Bakery', 'Christmas', 'Red Brick'] },
    { word: 'Johari Bazaar', category: 'Places', hints: ['Jaipur', 'Jewellery', 'Kundan', 'Gemstones', 'Gold'] },
    { word: 'Zaveri Bazaar', category: 'Places', hints: ['Mumbai', 'Gold Market', 'Diamond', 'Jewellers', 'Bullion'] },
    { word: 'Meena Bazaar', category: 'Places', hints: ['Delhi', 'Jama Masjid', 'Embroidery', 'Old Delhi', 'Fabric'] },
    { word: 'Aminabad Market', category: 'Places', hints: ['Lucknow', 'Chikan Work', 'Old Market', 'Street Food', 'Nawabi'] },
    // National parks & wildlife
    { word: 'Jim Corbett', category: 'Places', hints: ['Tiger Reserve', 'Uttarakhand', 'Oldest Park', 'Safari', 'Ramganga'] },
    { word: 'Ranthambore', category: 'Places', hints: ['Tiger', 'Rajasthan', 'Fort Inside Park', 'Safari', 'Sawai Madhopur'] },
    { word: 'Kaziranga', category: 'Places', hints: ['One Horn Rhino', 'Assam', 'UNESCO', 'Flood Plains', 'Elephant Safari'] },
    { word: 'Sundarbans', category: 'Places', hints: ['Mangrove', 'Royal Bengal Tiger', 'Delta', 'West Bengal', 'Tidal Forest'] },
    { word: 'Bandhavgarh', category: 'Places', hints: ['White Tiger', 'MP', 'Fort', 'Highest Tiger Density', 'Safari'] },
    { word: 'Kanha', category: 'Places', hints: ['Jungle Book', 'MP', 'Barasingha', 'Sal Forest', 'Kipling'] },
    { word: 'Periyar', category: 'Places', hints: ['Kerala', 'Elephant', 'Thekkady', 'Lake', 'Spice Plantation'] },
    { word: 'Gir Forest', category: 'Places', hints: ['Asiatic Lion', 'Gujarat', 'Only Habitat', 'Sasan', 'Pride'] },
    { word: 'Valley of Flowers', category: 'Places', hints: ['Uttarakhand', 'UNESCO', 'Alpine Meadow', 'Monsoon Bloom', 'Hemkund'] },
    { word: 'Nanda Devi', category: 'Places', hints: ['Second Highest Peak', 'Uttarakhand', 'Biosphere', 'Goddess', 'UNESCO'] },
    { word: 'Hemis', category: 'Places', hints: ['Ladakh', 'Snow Leopard', 'Monastery', 'Largest Park', 'High Altitude'] },
    { word: 'Bandipur', category: 'Places', hints: ['Karnataka', 'Nilgiri', 'Tiger', 'Elephant Corridor', 'Night Ban'] },
    { word: 'Nagarhole', category: 'Places', hints: ['Karnataka', 'Kabini', 'Black Panther', 'Elephant', 'Rajiv Gandhi Park'] },
    { word: 'Panna', category: 'Places', hints: ['MP', 'Diamond Mines', 'Ken River', 'Tiger Reintroduction', 'Vultures'] },
    { word: 'Sariska', category: 'Places', hints: ['Rajasthan', 'Tiger', 'Alwar', 'Kankwari Fort', 'Relocated Tigers'] },
    { word: 'Pench', category: 'Places', hints: ['Jungle Book', 'MP', 'Mowgli Land', 'Tiger', 'Teak Forest'] },
    { word: 'Tadoba', category: 'Places', hints: ['Maharashtra', 'Tiger', 'Chandrapur', 'Largest in State', 'Lake'] },
    { word: 'Chilika Lake', category: 'Places', hints: ['Odisha', 'Largest Lagoon', 'Flamingo', 'Irrawaddy Dolphin', 'Migratory Birds'] },
    { word: 'Bharatpur', category: 'Places', hints: ['Keoladeo', 'Bird Sanctuary', 'Rajasthan', 'Crane', 'UNESCO'] },
    { word: 'Mudumalai', category: 'Places', hints: ['Tamil Nadu', 'Nilgiri', 'Elephant', 'Mysore Border', 'Bandipur Adjacent'] },
    // Famous streets & areas
    { word: 'Brigade Road', category: 'Places', hints: ['Bangalore', 'Shopping', 'MG Road', 'Pubs', 'Christmas Lights'] },
    { word: 'Park Street', category: 'Places', hints: ['Kolkata', 'Restaurants', 'Christmas', 'Nightlife', 'Colonial'] },
    { word: 'Carter Road', category: 'Places', hints: ['Bandra', 'Mumbai', 'Seaface', 'Jogging', 'Promenade'] },
    { word: 'Bandra Bandstand', category: 'Places', hints: ['SRK House', 'Mumbai', 'Promenade', 'Sea View', 'Fort'] },
    { word: 'Worli Sea Face', category: 'Places', hints: ['Mumbai', 'Sea Link View', 'Sunset', 'Promenade', 'Monsoon Waves'] },
    { word: 'Rajiv Chowk', category: 'Places', hints: ['Delhi', 'Metro Junction', 'Connaught Place', 'Busiest Station', 'Blue Yellow Line'] },
    { word: 'Hazratganj', category: 'Places', hints: ['Lucknow', 'British Era', 'Shopping', 'Colonial', 'Main Street'] },
    { word: 'Anna Salai', category: 'Places', hints: ['Chennai', 'Mount Road', 'LIC Building', 'Main Road', 'Long'] },
    { word: 'Koramangala', category: 'Places', hints: ['Bangalore', 'Startups', 'Cafes', 'IT Crowd', 'South Bangalore'] },
    { word: 'Indiranagar', category: 'Places', hints: ['Bangalore', '12th Main', 'Pubs', 'Hip Area', 'Toit'] },
    { word: 'Banjara Hills', category: 'Places', hints: ['Hyderabad', 'Posh Area', 'Road No 10', 'Restaurants', 'Film Stars'] },
    { word: 'Jubilee Hills', category: 'Places', hints: ['Hyderabad', 'Rich Area', 'Tollywood', 'Celebrity Homes', 'KBR Park'] },
    { word: 'Sector 17', category: 'Places', hints: ['Chandigarh', 'Plaza', 'Shopping', 'Le Corbusier', 'City Centre'] },
    { word: 'Elgin Road', category: 'Places', hints: ['Kolkata', 'South Kolkata', 'Heritage', 'Consulates', 'Tree Lined'] },
    { word: 'Salt Lake', category: 'Places', hints: ['Kolkata', 'IT Hub', 'Planned City', 'Sector V', 'Bidhannagar'] },
    { word: 'Koregaon Park', category: 'Places', hints: ['Pune', 'Osho Ashram', 'Cafes', 'Expats', 'Nightlife'] },
    { word: 'FC Road Pune', category: 'Places', hints: ['Fergusson College', 'Students', 'Eateries', 'Book Shops', 'Pune'] },
    { word: 'Hauz Khas Village', category: 'Places', hints: ['Delhi', 'Ruins', 'Cafes', 'Lake', 'Art Galleries'] },
    { word: 'Khan Market', category: 'Places', hints: ['Delhi', 'Expensive Rent', 'Books', 'Restaurants', 'Diplomatic Area'] },
    { word: 'Defence Colony', category: 'Places', hints: ['Delhi', 'South Delhi', 'Market', 'Restaurants', 'Flyover'] },
    // Spiritual & pilgrimage
    { word: 'Haridwar', category: 'Places', hints: ['Ganga Aarti', 'Har Ki Pauri', 'Kumbh', 'Gateway to Gods', 'Holy Dip'] },
    { word: 'Bodh Gaya', category: 'Places', hints: ['Buddha', 'Enlightenment', 'Bihar', 'Bodhi Tree', 'Meditation'] },
    { word: 'Amarnath Cave', category: 'Places', hints: ['Shiva Lingam', 'Ice', 'Kashmir', 'Yatra', 'Pilgrimage'] },
    { word: 'Shirdi', category: 'Places', hints: ['Sai Baba', 'Maharashtra', 'Temple', 'Prasad', 'Faith'] },
    { word: 'Dwarka', category: 'Places', hints: ['Krishna', 'Gujarat', 'Char Dham', 'Underwater City', 'Dwarkadhish'] },
    { word: 'Puri', category: 'Places', hints: ['Jagannath', 'Rath Yatra', 'Beach', 'Odisha', 'Char Dham'] },
    { word: 'Mathura', category: 'Places', hints: ['Krishna Birthplace', 'Holi', 'UP', 'Peda', 'Janmashtami'] },
    { word: 'Vrindavan', category: 'Places', hints: ['Radha Krishna', 'Temples', 'Widows', 'Holi', 'Banke Bihari'] },
    { word: 'Pushkar', category: 'Places', hints: ['Camel Fair', 'Brahma Temple', 'Lake', 'Rajasthan', 'Only One'] },
    { word: 'Ujjain', category: 'Places', hints: ['Mahakal', 'Kumbh', 'Simhastha', 'MP', 'Jyotirlinga'] },
    { word: 'Sarnath', category: 'Places', hints: ['Buddha First Sermon', 'Ashoka Pillar', 'Deer Park', 'Varanasi Near', 'Stupa'] },
    { word: 'Ajmer Sharif', category: 'Places', hints: ['Dargah', 'Sufi', 'Rajasthan', 'Khwaja', 'Urs'] },
    { word: 'Rameshwaram', category: 'Places', hints: ['Shiva', 'Tamil Nadu', 'Bridge', 'Char Dham', 'Island Temple'] },
    { word: 'Gangotri', category: 'Places', hints: ['Ganga Origin', 'Char Dham', 'Uttarakhand', 'Glacier', 'Gomukh'] },
    { word: 'Yamunotri', category: 'Places', hints: ['Yamuna Source', 'Char Dham', 'Hot Springs', 'Uttarakhand', 'Trek'] },
    // Lakes & waterfalls
    { word: 'Pangong Lake', category: 'Places', hints: ['Ladakh', 'Blue Water', '3 Idiots', 'China Border', 'Colour Change'] },
    { word: 'Tso Moriri', category: 'Places', hints: ['Ladakh', 'High Altitude', 'Salt Lake', 'Remote', 'Changthang'] },
    { word: 'Gurudongmar Lake', category: 'Places', hints: ['Sikkim', 'Sacred', 'Frozen', 'High Altitude', 'Army Border'] },
    { word: 'Loktak Lake', category: 'Places', hints: ['Manipur', 'Floating Islands', 'Phumdi', 'Sangai Deer', 'Northeast'] },
    { word: 'Vembanad Lake', category: 'Places', hints: ['Kerala', 'Houseboat', 'Backwaters', 'Longest Lake', 'Kumarakom'] },
    { word: 'Pichola Lake', category: 'Places', hints: ['Udaipur', 'Lake Palace', 'Jag Mandir', 'Rajasthan', 'Boat Ride'] },
    { word: 'Naini Lake', category: 'Places', hints: ['Nainital', 'Boat Ride', 'Crescent Shape', 'Hill Station', 'Naina Devi'] },
    { word: 'Bhimtal', category: 'Places', hints: ['Uttarakhand', 'Island', 'Kumaon', 'Nainital Near', 'Quiet Lake'] },
    { word: 'Jog Falls', category: 'Places', hints: ['Karnataka', 'Sharavathi', 'Highest Plunge', 'Monsoon', 'Four Cascades'] },
    { word: 'Dudhsagar Falls', category: 'Places', hints: ['Goa', 'Railway Track', 'Milky', 'Monsoon', 'Trek'] },
    { word: 'Athirappilly Falls', category: 'Places', hints: ['Kerala', 'Niagara of India', 'Chalakudy', 'Bahubali', 'Rainforest'] },
    { word: 'Nohkalikai Falls', category: 'Places', hints: ['Meghalaya', 'Tallest Plunge', 'Cherrapunji', 'Legend', 'Green Pool'] },
    { word: 'Kempty Falls', category: 'Places', hints: ['Mussoorie', 'British Named', 'Uttarakhand', 'Picnic Spot', 'Popular'] },
    { word: 'Hogenakkal Falls', category: 'Places', hints: ['Tamil Nadu', 'Kaveri', 'Smoke Rocks', 'Coracle Ride', 'Karnataka Border'] },
    { word: 'Chitrakote Falls', category: 'Places', hints: ['Chhattisgarh', 'Niagara of India', 'Indravati', 'Bastar', 'Horseshoe'] },
    // Passes & treks
    { word: 'Rohtang Pass', category: 'Places', hints: ['Manali Leh', 'Snow', 'Himachal', 'Tunnel Now', 'Closed Winter'] },
    { word: 'Khardung La', category: 'Places', hints: ['Ladakh', 'Highest Road', 'Nubra Valley', 'Bike Trip', 'Altitude'] },
    { word: 'Zoji La', category: 'Places', hints: ['Kashmir Ladakh', 'Dangerous Road', 'Srinagar Leh', 'Snow Blocked', 'Army'] },
    { word: 'Babusar Pass', category: 'Places', hints: ['KKH', 'Gilgit', 'Mountain', 'Naran', 'Summer Only'] },
    { word: 'Chadar Trek', category: 'Places', hints: ['Frozen River', 'Zanskar', 'Winter', 'Ladakh', 'Ice Walk'] },
    { word: 'Triund Trek', category: 'Places', hints: ['McLeodganj', 'Easy Trek', 'Dhauladhar', 'Dharamshala', 'Camping'] },
    { word: 'Hampta Pass', category: 'Places', hints: ['Manali', 'Spiti', 'Crossover Trek', 'Meadows', 'River Crossing'] },
    { word: 'Kedarkantha Trek', category: 'Places', hints: ['Uttarakhand', 'Winter Trek', 'Summit', 'Snow', 'Sankri'] },
    { word: 'Sandakphu Trek', category: 'Places', hints: ['West Bengal', 'Four Peaks View', 'Kanchenjunga', 'Everest View', 'Darjeeling'] },
    { word: 'Brahmatal Trek', category: 'Places', hints: ['Uttarakhand', 'Winter', 'Frozen Lake', 'Trishul View', 'Snow'] },
  ],
};
