import type { WordPack } from '../game/types';

export const screenPack: WordPack = {
  id: 'screen',
  name: 'Screen',
  entries: [
    { word: 'Sarabhai vs Sarabhai', category: 'Screen' },
    { word: 'Taarak Mehta', category: 'Screen' },
    { word: 'CID', category: 'Screen' },
    { word: 'Sacred Games', category: 'Screen' },
    { word: 'Mirzapur', category: 'Screen' },
    { word: 'Panchayat', category: 'Screen' },
    { word: 'Scam 1992', category: 'Screen' },
    { word: 'TVF Pitchers', category: 'Screen' },
    { word: 'Kota Factory', category: 'Screen' },
    { word: 'Family Man', category: 'Screen' },
    { word: 'Roadies', category: 'Screen' },
    { word: 'Bigg Boss', category: 'Screen' },
    { word: 'Indian Idol', category: 'Screen' },
    { word: 'Kaun Banega Crorepati', category: 'Screen' },
    { word: 'Crime Patrol', category: 'Screen' },
    { word: 'Daya Ben', category: 'Screen' },
    { word: 'Jethalal', category: 'Screen' },
    { word: 'Sasural Scene', category: 'Screen' },
    { word: 'Ekta Kapoor', category: 'Screen' },
    { word: 'Saas Bahu Drama', category: 'Screen' },
    { word: 'Shararat', category: 'Screen' },
    { word: 'Shaka Laka Boom', category: 'Screen' },
    { word: 'Malgudi Days', category: 'Screen' },
    { word: 'Munna Bhai MBBS', category: 'Screen' },
    { word: 'Aspirants', category: 'Screen' },
    { word: 'Delhi Crime', category: 'Screen' },
    { word: 'Made In Heaven', category: 'Screen' },
    { word: 'Rocket Boys', category: 'Screen' },
    { word: 'Binge Watch', category: 'Screen' },
    { word: 'OTT Platform', category: 'Screen' },
    { word: 'Weekend Release', category: 'Screen' },
    { word: 'Dance India Dance', category: 'Screen' },
    { word: 'Super Dancer', category: 'Screen' },
    { word: 'Savdhaan India', category: 'Screen' },
    { word: 'Khichdi', category: 'Screen' },
    { word: 'Office Office', category: 'Screen' },
    { word: 'Byomkesh Bakshi', category: 'Screen' },
    { word: 'Chhota Bheem', category: 'Screen' },
    { word: 'Doraemon Hindi', category: 'Screen' },
    { word: 'Shinchan Hindi', category: 'Screen' },
  ],
};
