import type { WordPack } from '../game/types';

export const screenPack: WordPack = {
  id: 'screen',
  name: 'Screen',
  entries: [
    // ── Indian TV classics ──
    { word: 'Sarabhai vs Sarabhai', category: 'Screen', hints: ['Maya', 'Monisha', 'Sahil', 'Comedy', 'Verbose'] },
    { word: 'Taarak Mehta', category: 'Screen', hints: ['Gokuldham', 'Jethalal', 'Babita', 'SAB TV', 'Sitcom'] },
    { word: 'CID', category: 'Screen', hints: ['Daya', 'ACP Pradyuman', 'Door Todo', 'Sony', 'Investigation'] },
    { word: 'Khichdi', category: 'Screen', hints: ['Praful', 'Hansa', 'Parekh Family', 'Comedy', 'Gujarati'] },
    { word: 'Office Office', category: 'Screen', hints: ['Pankaj Kapur', 'Mussadilal', 'Corruption', 'Satire', 'Babu'] },
    { word: 'Byomkesh Bakshi', category: 'Screen', hints: ['Detective', 'Rajit Kapur', 'Calcutta', 'Mystery', 'Ajit'] },
    { word: 'Shararat', category: 'Screen', hints: ['Fairy', 'Jiya', 'Magic', 'Star Plus', 'Nani'] },
    { word: 'Shaka Laka Boom', category: 'Screen', hints: ['Magic Pencil', 'Sanju', 'Drawing', 'DD National', 'Wish'] },
    { word: 'Malgudi Days', category: 'Screen', hints: ['RK Narayan', 'Swami', 'Small Town', 'DD', 'Classic'] },
    { word: 'Daya Ben', category: 'Screen', hints: ['Garba', 'Hey Maa', 'Gokuldham', 'Jethalal Wife', 'Ahmedabad'] },
    { word: 'Jethalal', category: 'Screen', hints: ['Gada Electronics', 'Babita', 'Champaklal', 'Funny Face', 'Gokuldham'] },
    { word: 'Sasural Scene', category: 'Screen', hints: ['In Laws', 'Kitchen', 'Drama', 'Bahu', 'Daily Soap'] },
    { word: 'Ekta Kapoor', category: 'Screen', hints: ['Balaji', 'Producer', 'K Serials', 'Daily Soaps', 'Star Plus'] },
    { word: 'Saas Bahu Drama', category: 'Screen', hints: ['Daily Soap', 'Kitchen Politics', 'Star Plus', 'Zoom Effect', 'Sindoor'] },
    { word: 'Crime Patrol', category: 'Screen', hints: ['Anup Soni', 'Sony', 'Savdhaan Rahein', 'Real Cases', 'Investigation'] },
    { word: 'Savdhaan India', category: 'Screen', hints: ['True Crime', 'Star Bharat', 'Warning', 'Reenactment', 'Alert'] },
    { word: 'Munna Bhai MBBS', category: 'Screen', hints: ['Sanjay Dutt', 'Jaadu Ki Jhappi', 'Circuit', 'Doctor', 'Gandhigiri'] },
    { word: 'Hum Paanch', category: 'Screen', hints: ['Five Daughters', 'Anand Mathur', 'Zee TV', 'Comedy', 'Sweety'] },
    { word: 'Dekh Bhai Dekh', category: 'Screen', hints: ['Joint Family', 'DD Metro', 'Shekhar Suman', 'Comedy', 'Diwan'] },
    { word: 'Falguni Pathak', category: 'Screen', hints: ['Navratri', 'Garba Queen', 'Maine Payal', 'Dandiya', 'Gujarat'] },
    { word: 'Flop Show', category: 'Screen', hints: ['Jaspal Bhatti', 'Satire', 'DD National', 'Comedy', 'Punjab'] },
    { word: 'Nukkad', category: 'Screen', hints: ['Street Corner', 'DD', 'Ensemble Cast', 'Common Man', 'Kundan Shah'] },
    { word: 'Buniyaad', category: 'Screen', hints: ['Partition', 'DD', 'Drama', 'Family Saga', 'Classic'] },
    { word: 'Wagle Ki Duniya', category: 'Screen', hints: ['Common Man', 'RK Laxman', 'Middle Class', 'SAB TV', 'Mumbai'] },
    { word: 'Hip Hip Hurray', category: 'Screen', hints: ['School', 'DD', 'Students', 'Teachers', 'Coming of Age'] },
    { word: 'Hum Log', category: 'Screen', hints: ['First Soap', 'DD', 'Middle Class', 'Family', 'Ashok Kumar'] },
    { word: 'Surabhi', category: 'Screen', hints: ['DD', 'Quiz', 'Culture', 'Heritage', 'Siddharth Kak'] },
    { word: 'Shaktimaan', category: 'Screen', hints: ['Superhero', 'Mukesh Khanna', 'DD', 'Gangadhar', 'Indian Powers'] },
    { word: 'Captain Vyom', category: 'Screen', hints: ['Sci Fi', 'DD', 'Space', 'Milind Soman', 'Futuristic'] },
    { word: 'Just Mohabbat', category: 'Screen', hints: ['Aman', 'Sony', 'Boarding School', 'Teen', 'Nostalgia'] },
    { word: 'Remix', category: 'Screen', hints: ['Star One', 'School', 'Band', 'Teen Drama', 'Music'] },
    { word: 'Left Right Left', category: 'Screen', hints: ['Army', 'SAB TV', 'Cadets', 'Training', 'Rajeev Khandelwal'] },
    { word: 'Jassi Jaissi Koi Nahin', category: 'Screen', hints: ['Ugly Duckling', 'Sony', 'Office', 'Makeover', 'Mona Singh'] },
    { word: 'Balika Vadhu', category: 'Screen', hints: ['Child Marriage', 'Colors', 'Rajasthan', 'Anandi', 'Social Issue'] },
    { word: 'Kumkum Bhagya', category: 'Screen', hints: ['Zee TV', 'Pragya', 'Abhi', 'Sriti Jha', 'Wedding'] },
    { word: 'Yeh Rishta Kya Kehlata Hai', category: 'Screen', hints: ['Star Plus', 'Naira', 'Kartik', 'Joint Family', 'Rajasthan'] },
    { word: 'Naagin', category: 'Screen', hints: ['Shapeshifter', 'Colors', 'Serpent', 'Revenge', 'Supernatural'] },
    { word: 'Kasautii Zindagii Kay', category: 'Screen', hints: ['Prerna', 'Anurag', 'Star Plus', 'Komolika', 'Love Story'] },
    { word: 'Kyunki Saas Bhi', category: 'Screen', hints: ['Tulsi', 'Star Plus', 'Virani Family', 'Ekta Kapoor', 'Long Running'] },
    { word: 'Pavitra Rishta', category: 'Screen', hints: ['Sushant', 'Ankita', 'Zee TV', 'Archana', 'Manav'] },

    // ── Indian web series / OTT ──
    { word: 'Sacred Games', category: 'Screen', hints: ['Nawazuddin', 'Gaitonde', 'Mumbai Underworld', 'Saif', 'Trivedi'] },
    { word: 'Mirzapur', category: 'Screen', hints: ['Guddu', 'Munna', 'Kaleen Bhaiya', 'Prime', 'UP Crime'] },
    { word: 'Panchayat', category: 'Screen', hints: ['Sachiv Ji', 'Phulera', 'Village', 'Prime', 'Jitendra Kumar'] },
    { word: 'Scam 1992', category: 'Screen', hints: ['Harshad Mehta', 'Stock Market', 'SonyLIV', 'Pratik Gandhi', 'Bull Run'] },
    { word: 'TVF Pitchers', category: 'Screen', hints: ['Startup', 'Naveen', 'Jitu', 'Funding', 'Beer'] },
    { word: 'Kota Factory', category: 'Screen', hints: ['Jeetu Bhaiya', 'IIT Coaching', 'Black White', 'TVF', 'Students'] },
    { word: 'Family Man', category: 'Screen', hints: ['Manoj Bajpayee', 'Srikant', 'Spy', 'Prime', 'TASC'] },
    { word: 'Aspirants', category: 'Screen', hints: ['UPSC', 'TVF', 'Civil Services', 'Friendship', 'Old Rajinder Nagar'] },
    { word: 'Delhi Crime', category: 'Screen', hints: ['Shefali Shah', 'DCP Vartika', 'Investigation', 'Nirbhaya', 'Police'] },
    { word: 'Made In Heaven', category: 'Screen', hints: ['Wedding Planner', 'Prime', 'Tara', 'Karan', 'Big Fat Wedding'] },
    { word: 'Rocket Boys', category: 'Screen', hints: ['Homi Bhabha', 'Vikram Sarabhai', 'SonyLIV', 'Space', 'Science'] },
    { word: 'Gullak', category: 'Screen', hints: ['Middle Class', 'SonyLIV', 'Mishra Family', 'Small Town', 'Heartwarming'] },
    { word: 'Hostel Daze', category: 'Screen', hints: ['College', 'Prime', 'Engineering', 'Roommates', 'Campus'] },
    { word: 'Tripling', category: 'Screen', hints: ['Road Trip', 'TVF', 'Siblings', 'Comedy', 'Three'] },
    { word: 'Permanent Roommates', category: 'Screen', hints: ['TVF', 'Couple', 'Live In', 'Sumeet Vyas', 'Nidhi Singh'] },
    { word: 'Paatal Lok', category: 'Screen', hints: ['Jaideep Ahlawat', 'Prime', 'Crime', 'Hathiram', 'Dark'] },
    { word: 'Breathe', category: 'Screen', hints: ['Abhishek', 'Prime', 'Thriller', 'Organ', 'Desperation'] },
    { word: 'Inside Edge', category: 'Screen', hints: ['Cricket', 'Prime', 'Match Fixing', 'Powerplay', 'IPL Style'] },
    { word: 'Aarya', category: 'Screen', hints: ['Sushmita Sen', 'Hotstar', 'Drug Mafia', 'Rajasthan', 'Mother'] },
    { word: 'Jamtara', category: 'Screen', hints: ['Phishing', 'Jharkhand', 'Scam Call', 'Young Boys', 'Bank Fraud'] },
    { word: 'Asur', category: 'Screen', hints: ['Forensic', 'Mythology', 'Voot', 'Serial Killer', 'Arshad Warsi'] },
    { word: 'Tandav', category: 'Screen', hints: ['Politics', 'Prime', 'Saif Ali Khan', 'Delhi', 'Power'] },
    { word: 'Farzi', category: 'Screen', hints: ['Shahid Kapoor', 'Counterfeiting', 'Prime', 'Money', 'Artist'] },
    { word: 'Jubilee', category: 'Screen', hints: ['Bollywood Golden Era', 'Prime', 'Film Industry', 'Period Drama', 'Vintage'] },
    { word: 'Kohrra', category: 'Screen', hints: ['Punjab', 'Murder Mystery', 'Police', 'Dark', 'Foggy'] },
    { word: 'Guns and Gulaabs', category: 'Screen', hints: ['Rajkummar Rao', 'Retro', 'Crime Comedy', 'Dulquer', 'Gulshan Devaiah'] },
    { word: 'Dahaad', category: 'Screen', hints: ['Sonakshi Sinha', 'Rajasthan Police', 'Serial Killer', 'Prime', 'Investigation'] },
    { word: 'Killer Soup', category: 'Screen', hints: ['Manoj Bajpayee', 'Konkona', 'Dark Comedy', 'Twin', 'Murder'] },
    { word: 'Heeramandi', category: 'Screen', hints: ['Sanjay Leela', 'Courtesans', 'Lahore', 'Period', 'Dance'] },
    { word: 'IC 814', category: 'Screen', hints: ['Hijack', 'Kandahar', 'Plane', 'Anubhav Sinha', 'Hostage'] },
    { word: 'Bandish Bandits', category: 'Screen', hints: ['Classical Music', 'Rajasthan', 'Prime', 'Raag', 'Pop Fusion'] },
    { word: 'Mismatched', category: 'Screen', hints: ['Prajakta Koli', 'Rohit Saraf', 'Jaipur', 'College', 'Romance'] },
    { word: 'Little Things', category: 'Screen', hints: ['Dhruv Sehgal', 'Mithila Palkar', 'Couple', 'Mumbai', 'Slice of Life'] },
    { word: 'ImMature', category: 'Screen', hints: ['TVF', 'School', 'First Love', 'Coming of Age', 'Teenager'] },
    { word: 'College Romance', category: 'Screen', hints: ['TVF', 'Campus', 'Love', 'Friends', 'DU'] },
    { word: 'Flames', category: 'Screen', hints: ['TVF', 'Tutoring', 'Teen Love', 'Rajat', 'Ishita'] },
    { word: 'Cubicles', category: 'Screen', hints: ['TVF', 'Office', 'Corporate', 'First Job', 'IT'] },
    { word: 'Laakhon Mein Ek', category: 'Screen', hints: ['Prime', 'Medical', 'Rural India', 'Biswa', 'Healthcare'] },
    { word: 'Maharani', category: 'Screen', hints: ['Huma Qureshi', 'Bihar Politics', 'SonyLIV', 'CM Wife', 'Power'] },
    { word: 'Grahan', category: 'Screen', hints: ['Hotstar', 'Riots', 'Bokaro', 'Wamiqa Gabbi', 'Past Present'] },
    { word: 'Apharan', category: 'Screen', hints: ['Kidnapping', 'Arunoday Singh', 'Voot', 'Thriller', 'Cop'] },
    { word: 'Criminal Justice', category: 'Screen', hints: ['Hotstar', 'Pankaj Tripathi', 'Lawyer', 'Court', 'Accused'] },
    { word: 'Undekhi', category: 'Screen', hints: ['SonyLIV', 'Wedding Murder', 'Witness', 'Power', 'Cover Up'] },
    { word: 'Taj Mahal 1989', category: 'Screen', hints: ['Lucknow', 'Love Stories', 'Retro', 'University', 'Multiple Couples'] },
    { word: 'Selection Day', category: 'Screen', hints: ['Cricket', 'Brothers', 'Mumbai', 'Pressure', 'Talent'] },

    // ── Reality / game shows ──
    { word: 'Roadies', category: 'Screen', hints: ['Raghu', 'MTV', 'Tasks', 'Audition Yelling', 'Adventure'] },
    { word: 'Bigg Boss', category: 'Screen', hints: ['Salman Khan', 'House', 'Nominations', 'Colors', 'Contestants'] },
    { word: 'Indian Idol', category: 'Screen', hints: ['Singing', 'Judges', 'Auditions', 'Sony', 'Talent'] },
    { word: 'Kaun Banega Crorepati', category: 'Screen', hints: ['Amitabh', 'Hot Seat', 'Lifeline', 'Sony', 'Quiz'] },
    { word: 'Dance India Dance', category: 'Screen', hints: ['Mithun', 'Zee TV', 'Choreography', 'Grand Master', 'Audition'] },
    { word: 'Super Dancer', category: 'Screen', hints: ['Kids', 'Sony', 'Shilpa Shetty', 'Geeta Maa', 'Choreography'] },
    { word: 'Khatron Ke Khiladi', category: 'Screen', hints: ['Rohit Shetty', 'Stunts', 'Colors', 'Fear', 'Cape Town'] },
    { word: 'Shark Tank India', category: 'Screen', hints: ['Startup Pitch', 'Ashneer', 'Sony', 'Funding', 'Valuation'] },
    { word: 'Splitsvilla', category: 'Screen', hints: ['MTV', 'Dating', 'Villa', 'Couples', 'Sunny Leone'] },
    { word: 'Comedy Circus', category: 'Screen', hints: ['Archana Puran', 'Sony', 'Stand Up', 'Kapil', 'Pairs'] },
    { word: 'Great Indian Laughter', category: 'Screen', hints: ['Star One', 'Stand Up', 'Raju Srivastav', 'Comedy', 'Challenge'] },
    { word: 'Nach Baliye', category: 'Screen', hints: ['Couple Dance', 'Star Plus', 'Jodi', 'Celebrity', 'Ballroom'] },
    { word: 'Sa Re Ga Ma Pa', category: 'Screen', hints: ['Zee TV', 'Singing', 'Notes', 'Musical', 'Classic Show'] },
    { word: 'The Voice India', category: 'Screen', hints: ['Blind Audition', 'Chair Turn', 'Singing', 'Coaches', 'Star Plus'] },
    { word: 'Hunarbaaz', category: 'Screen', hints: ['Colors', 'Talent', 'Variety Acts', 'Performance', 'Judges'] },
    { word: 'Jhalak Dikhhla Jaa', category: 'Screen', hints: ['Celebrity Dance', 'Colors', 'Choreographer', 'Ballroom', 'Judges Score'] },
    { word: 'Comedy Nights Kapil', category: 'Screen', hints: ['Gutthi', 'Colors', 'Dadi', 'Celebrity Guest', 'Palak'] },
    { word: 'The Kapil Sharma Show', category: 'Screen', hints: ['Chandan', 'Sony', 'Celebrity Guest', 'Archana', 'Comedy'] },

    // ── International TV / streaming ──
    { word: 'Breaking Bad', category: 'Screen', hints: ['Walter White', 'Meth', 'Heisenberg', 'Jesse', 'Chemistry'] },
    { word: 'Game of Thrones', category: 'Screen', hints: ['Iron Throne', 'Dragons', 'Westeros', 'Winter Coming', 'Stark'] },
    { word: 'Stranger Things', category: 'Screen', hints: ['Upside Down', 'Eleven', 'Hawkins', 'Demogorgon', 'Eggo Waffles'] },
    { word: 'Money Heist', category: 'Screen', hints: ['Professor', 'Bella Ciao', 'Red Suit', 'Bank Robbery', 'Dali Mask'] },
    { word: 'Squid Game', category: 'Screen', hints: ['Red Light', 'Korean', 'Survival', 'Dalgona', 'Player 456'] },
    { word: 'Wednesday', category: 'Screen', hints: ['Addams Family', 'Jenna Ortega', 'Nevermore', 'Goth', 'Dance Scene'] },
    { word: 'The Office', category: 'Screen', hints: ['Michael Scott', 'Dunder Mifflin', 'Scranton', 'Paper Company', 'Cringe Comedy'] },
    { word: 'Friends', category: 'Screen', hints: ['Central Perk', 'Ross Rachel', 'Six Friends', 'NYC Apartment', 'Sitcom'] },
    { word: 'Dark', category: 'Screen', hints: ['German', 'Time Travel', 'Winden', 'Cave', 'Parallel World'] },
    { word: 'Narcos', category: 'Screen', hints: ['Pablo Escobar', 'Colombia', 'Drug Cartel', 'DEA', 'Cocaine'] },
    { word: 'Peaky Blinders', category: 'Screen', hints: ['Tommy Shelby', 'Birmingham', 'Razor Cap', 'Gangster', 'By Order'] },
    { word: 'The Witcher', category: 'Screen', hints: ['Geralt', 'Henry Cavill', 'Monster Hunter', 'Fantasy', 'Toss a Coin'] },
    { word: 'House of the Dragon', category: 'Screen', hints: ['Targaryen', 'Prequel', 'Throne', 'Dragons', 'Civil War'] },
    { word: 'The Bear', category: 'Screen', hints: ['Restaurant', 'Chicago', 'Chef', 'Kitchen', 'Yes Chef'] },
    { word: 'Succession', category: 'Screen', hints: ['Roy Family', 'Media Empire', 'HBO', 'Billionaire', 'Power Struggle'] },
    { word: 'Ted Lasso', category: 'Screen', hints: ['Football Coach', 'Apple', 'Biscuits', 'Believe', 'Richmond'] },
    { word: 'The Boys', category: 'Screen', hints: ['Homelander', 'Corrupt Heroes', 'Vought', 'Prime', 'Butcher'] },
    { word: 'Invincible', category: 'Screen', hints: ['Animated', 'Omni Man', 'Prime', 'Superhero', 'Mark Grayson'] },
    { word: 'Loki', category: 'Screen', hints: ['Disney Plus', 'Variant', 'TVA', 'Tom Hiddleston', 'Multiverse'] },
    { word: 'WandaVision', category: 'Screen', hints: ['Disney Plus', 'Sitcom Format', 'Wanda', 'Vision', 'Westview'] },
    { word: 'Mandalorian', category: 'Screen', hints: ['Baby Yoda', 'Star Wars', 'Bounty Hunter', 'Disney Plus', 'This Is The Way'] },
    { word: 'Severance', category: 'Screen', hints: ['Apple', 'Work Life Split', 'Lumon', 'Innie Outie', 'Thriller'] },
    { word: 'Black Mirror', category: 'Screen', hints: ['Technology', 'Dystopia', 'Anthology', 'Dark Future', 'Social Rating'] },
    { word: 'Ozark', category: 'Screen', hints: ['Jason Bateman', 'Money Laundering', 'Lake', 'Cartel', 'Missouri'] },
    { word: 'Better Call Saul', category: 'Screen', hints: ['Jimmy McGill', 'Lawyer', 'Prequel', 'Albuquerque', 'Bob Odenkirk'] },
    { word: 'The Crown', category: 'Screen', hints: ['Royal Family', 'Queen Elizabeth', 'Buckingham', 'British', 'History'] },
    { word: 'Bridgerton', category: 'Screen', hints: ['Regency Era', 'Lady Whistledown', 'Romance', 'London Season', 'Duke'] },
    { word: 'Emily in Paris', category: 'Screen', hints: ['Fashion', 'American Abroad', 'Lily Collins', 'French', 'Marketing'] },
    { word: 'You', category: 'Screen', hints: ['Joe Goldberg', 'Stalker', 'Penn Badgley', 'Obsession', 'Bookshop'] },
    { word: 'Lucifer', category: 'Screen', hints: ['Devil', 'LA Detective', 'Tom Ellis', 'Desire', 'Celestial'] },
    { word: 'Suits', category: 'Screen', hints: ['Harvey Specter', 'Law Firm', 'Mike Ross', 'Fraud', 'Manhattan'] },
    { word: 'Brooklyn Nine Nine', category: 'Screen', hints: ['Jake Peralta', 'Precinct', 'Andy Samberg', 'Holt', 'NYPD'] },
    { word: 'How I Met Your Mother', category: 'Screen', hints: ['Ted Mosby', 'Yellow Umbrella', 'Legendary', 'Barney', 'NYC Bar'] },
    { word: 'Seinfeld', category: 'Screen', hints: ['About Nothing', 'Jerry', 'George', 'NYC', 'Festivus'] },
    { word: 'The Big Bang Theory', category: 'Screen', hints: ['Sheldon', 'Bazinga', 'Nerds', 'Caltech', 'Penny'] },
    { word: 'Fleabag', category: 'Screen', hints: ['Phoebe Waller', 'Fourth Wall', 'Hot Priest', 'BBC', 'London'] },
    { word: 'Chernobyl', category: 'Screen', hints: ['Nuclear Disaster', 'HBO', 'Radiation', 'Soviet', 'Reactor'] },
    { word: 'Band of Brothers', category: 'Screen', hints: ['WW2', 'HBO', 'Paratroopers', 'Normandy', 'Easy Company'] },
    { word: 'True Detective', category: 'Screen', hints: ['HBO', 'Investigation', 'Anthology', 'Louisiana', 'Dark Tone'] },
    { word: 'Mindhunter', category: 'Screen', hints: ['FBI', 'Serial Killers', 'David Fincher', 'Profiling', 'Interviews'] },
    { word: 'The Last of Us', category: 'Screen', hints: ['HBO', 'Fungal Infection', 'Joel Ellie', 'Post Apocalypse', 'Pedro Pascal'] },
    { word: 'Shogun', category: 'Screen', hints: ['Feudal Japan', 'Samurai', 'FX', 'Toranaga', 'War'] },
    { word: 'One Piece Live Action', category: 'Screen', hints: ['Luffy', 'Pirates', 'Grand Line', 'Straw Hat', 'Manga Adaptation'] },
    { word: 'Attack on Titan', category: 'Screen', hints: ['Eren', 'Titans', 'Walls', 'Mikasa', 'Survey Corps'] },
    { word: 'Death Note', category: 'Screen', hints: ['Light Yagami', 'Ryuk', 'Notebook', 'Shinigami', 'L Detective'] },
    { word: 'Demon Slayer', category: 'Screen', hints: ['Tanjiro', 'Nezuko', 'Hashira', 'Breathing', 'Sword'] },
    { word: 'Jujutsu Kaisen', category: 'Screen', hints: ['Yuji', 'Gojo', 'Cursed Energy', 'Sukuna', 'Sorcerer'] },
    { word: 'One Punch Man', category: 'Screen', hints: ['Saitama', 'Bald Hero', 'Single Blow', 'Genos', 'Overpowered'] },
    { word: 'Naruto', category: 'Screen', hints: ['Hokage', 'Ninja', 'Rasengan', 'Sasuke', 'Hidden Leaf'] },
    { word: 'Dragon Ball Z', category: 'Screen', hints: ['Goku', 'Kamehameha', 'Saiyan', 'Vegeta', 'Super Power'] },

    // ── Cartoons / anime (Indian audience) ──
    { word: 'Chhota Bheem', category: 'Screen', hints: ['Laddu', 'Dholakpur', 'Strong Boy', 'Chutki', 'POGO'] },
    { word: 'Doraemon Hindi', category: 'Screen', hints: ['Nobita', 'Gadget', 'Pocket', 'Time Machine', 'Anywhere Door'] },
    { word: 'Shinchan Hindi', category: 'Screen', hints: ['Naughty Boy', 'Kasukabe', 'Himawari', 'Buri Buri', 'Action Kamen'] },
    { word: 'Motu Patlu', category: 'Screen', hints: ['Samosa', 'Furfuri Nagar', 'John', 'Nick', 'Chingum'] },
    { word: 'Oggy and Cockroaches', category: 'Screen', hints: ['Cat', 'Three Roaches', 'Joey', 'Slapstick', 'Chase'] },
    { word: 'Tom and Jerry', category: 'Screen', hints: ['Cat Mouse', 'Chase', 'Slapstick', 'Cartoon Network', 'Silent Comedy'] },
    { word: 'Ben 10', category: 'Screen', hints: ['Omnitrix', 'Aliens', 'Grandpa Max', 'Transform', 'Hero Time'] },
    { word: 'Pokemon', category: 'Screen', hints: ['Pikachu', 'Ash Ketchum', 'Pokeball', 'Gotta Catch', 'Gym Badge'] },
    { word: 'Beyblade', category: 'Screen', hints: ['Spinning Top', 'Let It Rip', 'Tyson', 'Dragoon', 'Stadium'] },
    { word: 'Takeshi Castle', category: 'Screen', hints: ['Obstacle Course', 'Javed Jaffrey', 'Japan', 'Funny Falls', 'General'] },
    { word: 'Kochikame', category: 'Screen', hints: ['Ryotsu', 'Police', 'Tokyo', 'Money Schemes', 'Funny Cop'] },
    { word: 'Ninja Hattori', category: 'Screen', hints: ['Kenichi', 'Ninja Skills', 'Kemumaki', 'Shishimaru', 'Japanese'] },
    { word: 'Perman', category: 'Screen', hints: ['Mask', 'Copy Robot', 'Flying', 'Mitsuo', 'Birdman'] },
    { word: 'Oswald', category: 'Screen', hints: ['Blue Octopus', 'Big City', 'Weenie', 'Henry', 'Kind'] },
    { word: 'Bob the Builder', category: 'Screen', hints: ['Can We Fix It', 'Construction', 'Hard Hat', 'Scoop', 'Yes We Can'] },
    { word: 'Mr Bean Cartoon', category: 'Screen', hints: ['Teddy Bear', 'Mini Cooper', 'Silent Comedy', 'Rowan Atkinson', 'Irma'] },
    { word: 'SpongeBob', category: 'Screen', hints: ['Bikini Bottom', 'Krusty Krab', 'Patrick', 'Pineapple', 'Underwater'] },
    { word: 'Avatar Last Airbender', category: 'Screen', hints: ['Aang', 'Four Elements', 'Fire Nation', 'Bending', 'Appa'] },
    { word: 'Rick and Morty', category: 'Screen', hints: ['Portal Gun', 'Multiverse', 'Grandfather', 'Pickle', 'Wubba Lubba'] },

    // ── OTT platforms / streaming culture ──
    { word: 'Binge Watch', category: 'Screen', hints: ['Marathon', 'All Episodes', 'Weekend', 'No Sleep', 'Series'] },
    { word: 'OTT Platform', category: 'Screen', hints: ['Streaming', 'App', 'Digital', 'Subscription', 'Online'] },
    { word: 'Weekend Release', category: 'Screen', hints: ['Friday Drop', 'New Show', 'Premiere', 'Alert', 'Calendar'] },
    { word: 'Netflix', category: 'Screen', hints: ['Red Logo', 'And Chill', 'Streaming Giant', 'Originals', 'Subscription'] },
    { word: 'Hotstar', category: 'Screen', hints: ['Disney Plus', 'Cricket Live', 'Star Network', 'IPL', 'Bollywood'] },
    { word: 'Amazon Prime', category: 'Screen', hints: ['Jeff Bezos', 'Blue Logo', 'Free Delivery', 'Originals', 'Family Man'] },
    { word: 'JioCinema', category: 'Screen', hints: ['Reliance', 'Free Tier', 'IPL Rights', 'Ambani', 'Streaming'] },
    { word: 'Zee5', category: 'Screen', hints: ['Zee Network', 'Purple Logo', 'Regional', 'Originals', 'Indian'] },
    { word: 'SonyLIV', category: 'Screen', hints: ['Scam 1992', 'Sony Network', 'Sports', 'Blue Logo', 'Gullak'] },
    { word: 'MX Player', category: 'Screen', hints: ['Free Streaming', 'Aashram', 'Video Player', 'Ads', 'Originals'] },
    { word: 'YouTube Premium', category: 'Screen', hints: ['No Ads', 'Background Play', 'Music', 'Google', 'Paid Tier'] },
    { word: 'Crunchyroll', category: 'Screen', hints: ['Anime', 'Orange Logo', 'Japanese', 'Subtitles', 'Simulcast'] },
    { word: 'Apple TV Plus', category: 'Screen', hints: ['Apple', 'Ted Lasso', 'Premium', 'Originals Only', 'Severance'] },
    { word: 'Skip Intro', category: 'Screen', hints: ['Button', 'Opening Credits', 'Fast Forward', 'Theme Song', 'Shortcut'] },
    { word: 'Post Credits Scene', category: 'Screen', hints: ['Stay Seated', 'Marvel', 'Teaser', 'After End', 'Hidden'] },
    { word: 'Season Finale', category: 'Screen', hints: ['Last Episode', 'Cliffhanger', 'Twist', 'Climax', 'Wait Year'] },
    { word: 'Cliffhanger Ending', category: 'Screen', hints: ['Suspense', 'Unresolved', 'Next Season', 'Frustrating', 'Hook'] },
    { word: 'Spoiler Alert', category: 'Screen', hints: ['Warning', 'Plot Reveal', 'Ruined', 'Dont Tell', 'Major Twist'] },
    { word: 'Buffering', category: 'Screen', hints: ['Loading Circle', 'Slow Internet', 'Spinning', 'Lag', 'Frustration'] },
    { word: 'Subtitle Gang', category: 'Screen', hints: ['Reading Text', 'Foreign Language', 'Bottom Screen', 'Translation', 'Preference'] },
    { word: 'Dubbed Version', category: 'Screen', hints: ['Hindi Voice', 'Lip Sync', 'Translation', 'Local Language', 'Voice Over'] },
    { word: 'Autoplay Next', category: 'Screen', hints: ['Countdown Timer', 'Continuous', 'No Break', 'Addictive', 'Queue'] },
    { word: 'Watch Party', category: 'Screen', hints: ['Group Viewing', 'Sync', 'Friends', 'Remote', 'Together'] },
    { word: 'Continue Watching', category: 'Screen', hints: ['Resume', 'Homepage', 'Left Off', 'Progress Bar', 'Queue'] },
    { word: 'Are You Still Watching', category: 'Screen', hints: ['Popup', 'Inactivity', 'Judgement', 'Couch', 'Confirm'] },
    { word: 'Casting to TV', category: 'Screen', hints: ['Chromecast', 'Big Screen', 'Phone to TV', 'Wireless', 'Mirror'] },

    // ── YouTube / creators / internet culture ──
    { word: 'CarryMinati', category: 'Screen', hints: ['Ajey Nagar', 'Roast King', 'Gaming', 'Yalgaar', 'Faridabad'] },
    { word: 'BB Ki Vines', category: 'Screen', hints: ['Bhuvan Bam', 'Characters', 'Solo Creator', 'Comedy', 'Titu Mama'] },
    { word: 'Tanmay Bhat', category: 'Screen', hints: ['AIB', 'Comedian', 'Gaming Stream', 'Twitch', 'Comedy'] },
    { word: 'Slayy Point', category: 'Screen', hints: ['Couple', 'Commentary', 'Gautami', 'Abhyudaya', 'Roast'] },
    { word: 'Triggered Insaan', category: 'Screen', hints: ['Nischay', 'Roasting', 'Family Channel', 'Fukra', 'Comedy'] },
    { word: 'Technical Guruji', category: 'Screen', hints: ['Gaurav Chaudhary', 'Tech Review', 'Dubai', 'Gadgets', 'Hindi Tech'] },
    { word: 'Dhruv Rathee', category: 'Screen', hints: ['Explainer', 'Germany', 'Politics', 'Analysis', 'Documentary'] },
    { word: 'Beer Biceps', category: 'Screen', hints: ['Ranveer Allahbadia', 'Fitness', 'Long Form', 'Interview', 'Motivation'] },
    { word: 'Ashish Chanchlani', category: 'Screen', hints: ['Vine Star', 'Comedy', 'Mumbai', 'Sketches', 'Family'] },
    { word: 'Amit Bhadana', category: 'Screen', hints: ['Faridabad', 'Comedy', 'Desi Style', 'Hindi', 'Relatable'] },
    { word: 'Round2Hell', category: 'Screen', hints: ['Three Friends', 'Comedy', 'Sketches', 'R2H', 'Zayn Nazim Wasim'] },
    { word: 'Fukra Insaan', category: 'Screen', hints: ['Abhishek', 'Challenge', 'Experiments', 'Nischay Brother', 'Fun'] },
    { word: 'MrBeast', category: 'Screen', hints: ['Philanthropy', 'Millions', 'Challenge', 'Jimmy', 'Expensive'] },
    { word: 'PewDiePie', category: 'Screen', hints: ['Swedish', 'Most Subscribed', 'Felix', 'Meme Review', 'T Series Battle'] },
    { word: 'MKBHD', category: 'Screen', hints: ['Marques', 'Tech Review', 'Crispy', 'Premium Feel', 'Studio Quality'] },
    { word: 'Linus Tech Tips', category: 'Screen', hints: ['PC Build', 'Drop Things', 'Lab', 'Hardware', 'Segue Sponsor'] },
    { word: 'Kurzgesagt', category: 'Screen', hints: ['In a Nutshell', 'Animation', 'Science', 'German', 'Colorful'] },
    { word: 'Vsauce', category: 'Screen', hints: ['Michael', 'Or Is It', 'Science', 'Mind Blown', 'Curiosity'] },
    { word: 'Mark Rober', category: 'Screen', hints: ['NASA Engineer', 'Glitter Bomb', 'Science', 'Squirrel Course', 'Inventions'] },
    { word: 'Veritasium', category: 'Screen', hints: ['Derek Muller', 'Science', 'Experiments', 'Physics', 'Education'] },
    { word: 'Shorts', category: 'Screen', hints: ['Vertical Video', 'Sixty Seconds', 'Quick Content', 'Scroll', 'Addictive'] },
    { word: 'Reels', category: 'Screen', hints: ['Instagram', 'Short Video', 'Trending Audio', 'Vertical', 'Dance'] },
    { word: 'Subscriber Count', category: 'Screen', hints: ['Milestone', 'Silver Button', 'Gold Button', 'Followers', 'Growth'] },
    { word: 'Like and Subscribe', category: 'Screen', hints: ['Bell Icon', 'Outro', 'Call to Action', 'Support', 'Every Video'] },
    { word: 'Clickbait Thumbnail', category: 'Screen', hints: ['Shocked Face', 'Red Arrow', 'Exaggerated', 'Click Trap', 'Misleading'] },
    { word: 'Unboxing Video', category: 'Screen', hints: ['Opening Package', 'First Look', 'Review', 'New Product', 'Excitement'] },
    { word: 'Reaction Video', category: 'Screen', hints: ['Watching Content', 'Face Cam', 'Commentary', 'Response', 'Split Screen'] },
    { word: 'Vlog', category: 'Screen', hints: ['Daily Life', 'Camera', 'Personal', 'Day in Life', 'Travel'] },
    { word: 'Podcast', category: 'Screen', hints: ['Audio Show', 'Episodes', 'Interview', 'Long Form', 'Spotify'] },
    { word: 'Live Stream', category: 'Screen', hints: ['Real Time', 'Chat', 'Broadcast', 'Going Live', 'Viewers'] },
    { word: 'Superchat', category: 'Screen', hints: ['Paid Message', 'Highlighted', 'Donation', 'Live Stream', 'Color'] },
    { word: 'Collab Video', category: 'Screen', hints: ['Two Creators', 'Crossover', 'Together', 'Feature', 'Joint'] },
    { word: 'Roast Video', category: 'Screen', hints: ['Criticism', 'Comedy', 'Savage', 'Takedown', 'Funny'] },
    { word: 'Storytime Video', category: 'Screen', hints: ['Personal Story', 'Narrative', 'What Happened', 'Experience', 'Sit Down'] },

    // ── Gaming ──
    { word: 'BGMI', category: 'Screen', hints: ['Battlegrounds', 'Mobile India', 'Chicken Dinner', 'Krafton', 'Pubg'] },
    { word: 'Free Fire', category: 'Screen', hints: ['Garena', 'Battle Royale', 'Booyah', 'Mobile', 'Characters'] },
    { word: 'Valorant', category: 'Screen', hints: ['Riot Games', 'Agents', 'Tactical Shooter', 'Spike', 'Abilities'] },
    { word: 'GTA V', category: 'Screen', hints: ['Trevor', 'Los Santos', 'Rockstar', 'Open World', 'Heist'] },
    { word: 'Minecraft', category: 'Screen', hints: ['Blocks', 'Creeper', 'Survival', 'Crafting', 'Steve'] },
    { word: 'Among Us', category: 'Screen', hints: ['Impostor', 'Emergency Meeting', 'Vent', 'Crewmate', 'Suspicious'] },
    { word: 'Call of Duty Mobile', category: 'Screen', hints: ['FPS', 'Activision', 'Multiplayer', 'Warzone', 'Gunfight'] },
    { word: 'Clash Royale', category: 'Screen', hints: ['Supercell', 'Cards', 'Towers', 'Elixir', 'Arena'] },
    { word: 'Clash of Clans', category: 'Screen', hints: ['Supercell', 'Village', 'Troops', 'Clan War', 'Builder'] },
    { word: 'Subway Surfers', category: 'Screen', hints: ['Train Tracks', 'Endless Runner', 'Jake', 'Coins', 'Hoverboard'] },
    { word: 'Temple Run', category: 'Screen', hints: ['Endless Runner', 'Idol', 'Monkeys', 'Swipe', 'Obstacles'] },
    { word: 'Candy Crush', category: 'Screen', hints: ['Match Three', 'King', 'Sweet', 'Levels', 'Lives'] },
    { word: 'Ludo King', category: 'Screen', hints: ['Board Game', 'Dice', 'Four Colors', 'Online', 'Family'] },
    { word: 'Wordle', category: 'Screen', hints: ['Five Letters', 'Green Yellow', 'Daily Puzzle', 'Six Guesses', 'NYT'] },
    { word: 'Fortnite', category: 'Screen', hints: ['Epic Games', 'Building', 'Dance Emotes', 'Victory Royale', 'Storm'] },
    { word: 'Elden Ring', category: 'Screen', hints: ['FromSoftware', 'Tarnished', 'Open World', 'Difficult', 'Souls Like'] },
    { word: 'God of War', category: 'Screen', hints: ['Kratos', 'Ragnarok', 'Greek Myth', 'Boy', 'Axe'] },
    { word: 'FIFA Mobile', category: 'Screen', hints: ['Football', 'EA Sports', 'Ultimate Team', 'Cards', 'Soccer'] },
    { word: 'Mortal Kombat', category: 'Screen', hints: ['Fatality', 'Scorpion', 'Sub Zero', 'Fight', 'Finish Him'] },
    { word: 'Roblox', category: 'Screen', hints: ['User Created', 'Robux', 'Kids', 'Avatar', 'Platform'] },
    { word: 'League of Legends', category: 'Screen', hints: ['MOBA', 'Riot Games', 'Champions', 'Ranked', 'Summoner'] },
    { word: 'Apex Legends', category: 'Screen', hints: ['EA', 'Legends', 'Battle Royale', 'Respawn', 'Abilities'] },
    { word: 'Chicken Dinner', category: 'Screen', hints: ['Winner', 'PUBG', 'Victory', 'Last Standing', 'Celebration'] },
    { word: 'Noob vs Pro', category: 'Screen', hints: ['Skill Gap', 'Beginner', 'Expert', 'Gaming', 'Comparison'] },
    { word: 'Respawn', category: 'Screen', hints: ['Come Back', 'After Death', 'Reload', 'Second Chance', 'Timer'] },
    { word: 'Headshot', category: 'Screen', hints: ['One Shot Kill', 'Aim High', 'Precision', 'FPS', 'Sniper'] },
    { word: 'Battle Royale', category: 'Screen', hints: ['Last Standing', 'Shrinking Zone', 'Loot', 'Drop', 'Survival'] },
    { word: 'Aimbot', category: 'Screen', hints: ['Cheat', 'Auto Aim', 'Hacker', 'Unfair', 'Banned'] },
    { word: 'Lag Spike', category: 'Screen', hints: ['Ping', 'Delay', 'Freeze', 'Internet', 'Rubber Band'] },
    { word: 'GG WP', category: 'Screen', hints: ['Good Game', 'Well Played', 'Sportsmanship', 'End Match', 'Respect'] },

    // ── Memes / internet slang ──
    { word: 'Dank Meme', category: 'Screen', hints: ['Dark Humor', 'Reddit', 'Edgy', 'Funny Image', 'Ironic'] },
    { word: 'Viral Reel', category: 'Screen', hints: ['Millions Views', 'Trending', 'Share', 'Famous', 'Overnight'] },
    { word: 'Touch Grass', category: 'Screen', hints: ['Go Outside', 'Too Online', 'Nature', 'Digital Detox', 'Insult'] },
    { word: 'Main Character Energy', category: 'Screen', hints: ['Protagonist', 'Center Stage', 'Confident', 'Dramatic', 'Spotlight'] },
    { word: 'Caught in 4K', category: 'Screen', hints: ['Evidence', 'Exposed', 'No Denying', 'Receipt', 'Camera'] },
    { word: 'Ratio', category: 'Screen', hints: ['Twitter', 'More Replies', 'Owned', 'Clap Back', 'L Take'] },
    { word: 'NPC Energy', category: 'Screen', hints: ['Non Player', 'Script', 'Robotic', 'Bland', 'Background'] },
    { word: 'Based', category: 'Screen', hints: ['Unapologetic', 'Own Opinion', 'Bold', 'Respect', 'Authentic'] },
    { word: 'Cringe', category: 'Screen', hints: ['Awkward', 'Embarrassing', 'Second Hand', 'Uncomfortable', 'Try Hard'] },
    { word: 'Slay', category: 'Screen', hints: ['Nailed It', 'Queen', 'Impressive', 'Fashion', 'Killed It'] },
    { word: 'No Cap', category: 'Screen', hints: ['Not Lying', 'For Real', 'Truth', 'Serious', 'Honest'] },
    { word: 'Sus', category: 'Screen', hints: ['Suspicious', 'Among Us', 'Fishy', 'Doubt', 'Sketchy'] },
    { word: 'GOAT', category: 'Screen', hints: ['Greatest Ever', 'Legend', 'All Time', 'Champion', 'Best'] },
    { word: 'Rizz', category: 'Screen', hints: ['Charm', 'Flirting', 'Smooth', 'Charisma', 'Game'] },
    { word: 'Sigma Male', category: 'Screen', hints: ['Lone Wolf', 'Grindset', 'Meme', 'Patrick Bateman', 'Independent'] },
    { word: 'Bruh Moment', category: 'Screen', hints: ['Disbelief', 'Seriously', 'Facepalm', 'Exasperation', 'Really'] },
    { word: 'POV', category: 'Screen', hints: ['Point of View', 'First Person', 'Perspective', 'TikTok', 'Imagine'] },
    { word: 'It Hits Different', category: 'Screen', hints: ['Extra Special', 'Vibe', 'Feeling', 'Emotion', 'Nostalgia'] },
    { word: 'Living Rent Free', category: 'Screen', hints: ['Mind', 'Obsessed', 'Cannot Forget', 'Head', 'Stuck'] },
    { word: 'Understood Assignment', category: 'Screen', hints: ['Perfect Job', 'Exactly Right', 'Nailed', 'Slayed', 'Executed'] },
    { word: 'Red Flag', category: 'Screen', hints: ['Warning Sign', 'Danger', 'Dating', 'Avoid', 'Dealbreaker'] },
    { word: 'Green Flag', category: 'Screen', hints: ['Good Sign', 'Positive', 'Dating', 'Keep', 'Healthy'] },
    { word: 'Ick Factor', category: 'Screen', hints: ['Turn Off', 'Disgust', 'Dating', 'Sudden', 'Repulsed'] },
    { word: 'Ghosting', category: 'Screen', hints: ['Disappear', 'No Reply', 'Dating', 'Ignore', 'Vanish'] },
    { word: 'Doom Scrolling', category: 'Screen', hints: ['Bad News', 'Endless Feed', 'Cant Stop', 'Night', 'Anxiety'] },
    { word: 'Screen Time Report', category: 'Screen', hints: ['Weekly', 'Hours', 'Phone Usage', 'Guilt', 'Notification'] },

    // ── Social media / apps ──
    { word: 'Instagram', category: 'Screen', hints: ['Photo Grid', 'Stories', 'Meta', 'Filters', 'Feed'] },
    { word: 'WhatsApp', category: 'Screen', hints: ['Green Chat', 'Blue Ticks', 'Meta', 'Groups', 'Voice Note'] },
    { word: 'Snapchat', category: 'Screen', hints: ['Streak', 'Ghost Logo', 'Disappearing', 'Filters', 'Snap Score'] },
    { word: 'Twitter X', category: 'Screen', hints: ['Elon Musk', 'Tweet', 'Blue Bird', 'Rebrand', 'Hashtag'] },
    { word: 'Reddit', category: 'Screen', hints: ['Subreddit', 'Upvote', 'Front Page', 'AITA', 'Anonymous'] },
    { word: 'Discord Server', category: 'Screen', hints: ['Voice Chat', 'Gaming', 'Channels', 'Mod', 'Purple'] },
    { word: 'Telegram Group', category: 'Screen', hints: ['Blue App', 'Channels', 'Large Groups', 'Bots', 'Privacy'] },
    { word: 'LinkedIn Post', category: 'Screen', hints: ['Professional', 'Humble Brag', 'Agree Question', 'Networking', 'Corporate'] },
    { word: 'BeReal', category: 'Screen', hints: ['Daily Photo', 'Two Minutes', 'Authentic', 'No Filter', 'Notification'] },
    { word: 'Threads', category: 'Screen', hints: ['Meta', 'Text Based', 'Twitter Rival', 'Zuckerberg', 'New App'] },
    { word: 'TikTok', category: 'Screen', hints: ['Short Video', 'ByteDance', 'FYP', 'Dance Trends', 'Banned India'] },
    { word: 'Pinterest Board', category: 'Screen', hints: ['Aesthetic', 'Mood Board', 'Save Pins', 'Inspiration', 'Visual'] },
    { word: 'Story Expire', category: 'Screen', hints: ['24 Hours', 'Disappearing', 'Temporary', 'Ring', 'Tomorrow Gone'] },
    { word: 'Blue Tick', category: 'Screen', hints: ['Verified', 'Famous', 'Paid Now', 'Checkmark', 'Authentic'] },
    { word: 'DM Slide', category: 'Screen', hints: ['Direct Message', 'Flirting', 'Inbox', 'Private', 'Hey'] },
    { word: 'Going Viral', category: 'Screen', hints: ['Millions Shares', 'Famous Overnight', 'Trending', 'Blowing Up', 'Internet'] },
    { word: 'Trending Hashtag', category: 'Screen', hints: ['Pound Sign', 'Popular Topic', 'Discover', 'Explore', 'Buzzing'] },
    { word: 'Influencer', category: 'Screen', hints: ['Brand Deals', 'Followers', 'Sponsored', 'Content', 'Social Media'] },
    { word: 'Content Creator', category: 'Screen', hints: ['Full Time', 'Videos', 'Monetize', 'Niche', 'Upload'] },
    { word: 'Algorithm', category: 'Screen', hints: ['Feed', 'Recommendation', 'Hidden Logic', 'Engagement', 'Push Content'] },
    { word: 'For You Page', category: 'Screen', hints: ['FYP', 'Personalized', 'TikTok', 'Discovery', 'Recommended'] },
    { word: 'Shadow Ban', category: 'Screen', hints: ['Hidden', 'Reduced Reach', 'No Notification', 'Punishment', 'Invisible'] },
    { word: 'Double Tap', category: 'Screen', hints: ['Like', 'Heart', 'Instagram', 'Photo', 'Tap Screen'] },
    { word: 'Finsta', category: 'Screen', hints: ['Fake Account', 'Private', 'Close Friends', 'Alt Profile', 'Real Self'] },
    { word: 'Group Chat', category: 'Screen', hints: ['Multiple People', 'Messages', 'Chaos', 'Muted', 'Friends'] },
    { word: 'Mute Notifications', category: 'Screen', hints: ['Silent', 'No Alerts', 'Peace', 'Ignore', 'DND'] },

    // ── Tech / gadget culture ──
    { word: 'iPhone Launch', category: 'Screen', hints: ['Apple Event', 'September', 'Keynote', 'New Model', 'Pre Order'] },
    { word: 'Android vs iOS', category: 'Screen', hints: ['Phone War', 'Green Blue', 'Google Apple', 'Debate', 'Operating System'] },
    { word: 'Dark Mode', category: 'Screen', hints: ['Night Theme', 'Black Background', 'Eye Comfort', 'Battery Save', 'Toggle'] },
    { word: 'Incognito Tab', category: 'Screen', hints: ['Private Browse', 'No History', 'Hat Glasses', 'Secret', 'Chrome'] },
    { word: 'VPN', category: 'Screen', hints: ['Virtual Network', 'Location Change', 'Privacy', 'Tunnel', 'Geo Block'] },
    { word: 'AI Chatbot', category: 'Screen', hints: ['Artificial', 'Conversation', 'Generated', 'Prompt', 'Language Model'] },
    { word: 'ChatGPT', category: 'Screen', hints: ['OpenAI', 'Prompt', 'Language Model', 'Conversation', 'Generative'] },
    { word: 'Crypto Bro', category: 'Screen', hints: ['Bitcoin', 'To the Moon', 'Blockchain', 'HODL', 'Digital Currency'] },
    { word: 'NFT', category: 'Screen', hints: ['Digital Art', 'Blockchain', 'Ape', 'Token', 'Worthless Now'] },
    { word: 'Deepfake', category: 'Screen', hints: ['Fake Video', 'AI Generated', 'Face Swap', 'Manipulation', 'Realistic'] },
    { word: 'QR Code', category: 'Screen', hints: ['Square Pattern', 'Scan', 'Camera', 'Black White', 'Link'] },
    { word: 'UPI Payment', category: 'Screen', hints: ['Scan Pay', 'India', 'Digital', 'Instant', 'Phone Number'] },
    { word: 'PhonePe', category: 'Screen', hints: ['Purple App', 'Payment', 'Recharge', 'Scan', 'Wallet'] },
    { word: 'GPay', category: 'Screen', hints: ['Google', 'Payment', 'Blue App', 'Scratch Card', 'Transfer'] },
    { word: 'Bluetooth Earbuds', category: 'Screen', hints: ['Wireless', 'TWS', 'Charging Case', 'Music', 'No Wire'] },
    { word: 'Smart Watch', category: 'Screen', hints: ['Wrist', 'Fitness Track', 'Notifications', 'Heart Rate', 'Apple Samsung'] },
    { word: 'Ring Light', category: 'Screen', hints: ['Circular', 'Selfie', 'Creator', 'Lighting', 'Bright Face'] },
    { word: 'Green Screen', category: 'Screen', hints: ['Chroma Key', 'Background', 'VFX', 'Studio', 'Replace'] },
    { word: 'Two Factor Auth', category: 'Screen', hints: ['OTP', 'Security', 'Login', 'Extra Step', 'Verification'] },
    { word: 'Password Manager', category: 'Screen', hints: ['Vault', 'Security', 'Auto Fill', 'Master Key', 'Stored'] },
    { word: 'Cloud Storage', category: 'Screen', hints: ['Google Drive', 'Online', 'Backup', 'Sync', 'Remote'] },
    { word: 'Low Battery Anxiety', category: 'Screen', hints: ['Red Icon', 'Charger Hunt', 'One Percent', 'Panic', 'Power Bank'] },
    { word: 'Wireless Charger', category: 'Screen', hints: ['Pad', 'No Cable', 'Place Phone', 'Qi', 'Charging'] },
    { word: 'Screen Protector', category: 'Screen', hints: ['Tempered Glass', 'Bubble', 'Scratch Guard', 'Film', 'Phone Shield'] },
  ],
};
